### ISSUE TITLE
Add cache to rollup

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1054]
Would be really nice to have the cache feature inside rollup plugin.

When using Fable.Elmish.Bulma the project take a long time to compile because there is some large records and a lot of files who never changed (they belongs to the libs not the user code).

I notice a gain of **40** seconds when using webpack with the cache. (60sec -> 20sec)

**Comment by alfonsogarciacaro** [comment]
Yeah, I saw the same, I should profile and see why compiling BulmaClasses.fs takes so long. I'm a bit afraid of the cache feature because it's not well tested and I've seen some situations where it doesn't update files correctly, although I couldn't find the specific reason. I'd like to add a "clear cache" option, but I'm not sure how to do it because the cache depends entirely on fable-loader so it doesn't make sense to clear the cache with the dotnet Fable CLI.

In any case, could you try porting the cache to the rollup plugin. It shouldn't be very difficult, just [take the Wepack loader as reference](https://github.com/fable-compiler/Fable/blob/9508c1359363292691f39b0de08e5a7a2d04ac2b/src/js/fable-loader/index.js#L55-L94). Or maybe we could port the cache to fable-utils so it can be easily be shared by the two modules.

**Comment by MangelMaxime** [comment]
For BulmaClasses, I suppose the problem is coming from all the nested records.

I think adding it to fable-utils would make more sense. Last time I looked at the code, I didn't really understand what was going on.

**Comment by alfonsogarciacaro** [comment]
rollup-plugin-fable 1.0.7 has been published with the cache feature, please give it a try 😊

**Comment by MangelMaxime** [comment]
Awesome :)
I will give it a try during the weekend. Keep you inform :)

**Comment by alfonsogarciacaro** [comment]
Closing for now, please feel free to reopen if it's not working.

**Comment by MangelMaxime** [comment]
I think it's working :)

Without cache: 128 secondes
With cache: 28 secondes

It's coming back to "usable". Thanks for the feature
