### ISSUE TITLE
reraise doesn't work correctly in JS

### ISSUE THREAD

**Issue by i-p** [fable-compiler/Fable#1057]
### Description

When a "reraise" statment is compiled to JS, a new exception is created instead of throwing the current one.

### Repro code

```
exception Ex of int
try
    try
        raise (Ex(1))
    with   
    | _ -> reraise()
with
| e -> if e <> Ex(1) then failwithf "Unexpected exception" else ()
```

Compiled JS code shows the problem:

```
try {
  try {
    throw new Ex(1);
  } catch (matchValue) {
    throw new Error();
  }
} catch (e) {
  if (!equals(e, new Ex(1))) {
    throw new Error("Unexpected exception");
  }
}

```

Instead of ``throw new Error()`` there should be ``throw matchValue``.

### Expected and actual results

Expected result: no exception is thrown.
Actual result: "Unexpected exception" is thrown.

### Related information

* Fable version: 1.1.8
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Nice catch, thank you! Hmm, this is tricky. `reraise` was indeed wrongly implemented, but in order to fix it we need to implement the possibility to crawl the AST upwards which is not currently feasible in the Replacements module. I've been thinking to do it for other tasks (like optimizing `printfn`) but it's not trivial. There are also other solutions so I've to think about it. For now, would it be ok, to just throw an error saying `reraise` is not supported and `raise + exception` should be used instead?

**Comment by i-p** [comment]
Sure, that's a good idea.

**Comment by alfonsogarciacaro** [comment]
As agreed, fixed temporarily just by disallowing `reraise`
