### ISSUE TITLE
Wrap clickHandler in System.Func<>

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1067]
### Description

![image](https://user-images.githubusercontent.com/2621499/28214609-3cff1368-68ab-11e7-828f-d99a9d426a0e.png)

This is probably more an F# question than a fable one but why did I need to wrap my F# function in a `System.Func`?

### Related information

* Fable version (`dotnet fable --version`): 1.1.9
* Operating system: Windows 7

**Comment by alfonsogarciacaro** [comment]
This is because previous Fable versions made a distinction between delegates (`System.Func`) and F# lambdas. The main difference being the latter can be curried. Fable used to compile curried F# lambdas as nested JS functions (e.g. `fun x y -> x + y` became `x => y => x + y`) so they were not compatible with native JS code. To avoid problems, you had to convert the F# lambdas into delegates before sending them to native JS code.

Fable 1.x fixed that and now F# lambdas are compiled as _normal_ JS functions (e.g. `fun x y -> x + y` became `(x, y) => x + y`) so in principle it's not necessary any more to do the conversion. However, most of the bindings haven't been updated yet so you may still need to type `System.Func` from time to time (other times the conversion is done implicitly).

> Tip: You can omit the generics most of the times: `Func<_,_>(openAlert)`.

**Comment by nojaf** [comment]
I see, thanks for the very quick response!

**Comment by nojaf** [comment]
Circling back to this, say if I would want to correct the binding for the latest Fable (1.3.x).
What would 
```fsharp
[<Emit("$0.addEventListener('load',$1...)")>] abstract addEventListener_load: listener: Func<Event, obj> * ?useCapture: bool -> unit
```
become?

```fsharp
[<AbstractClass>]
type Element() =
    [<Emit("$0.addEventListener('load',$1...)")>] 
    abstract addEventListener_load: listener:(Event -> unit) * ?option: (Choice<bool, AddEventListenerOptions>) -> unit
```

Taking the [spec](https://dom.spec.whatwg.org/#callbackdef-eventlistener) into account. See [mdn](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

**Comment by alfonsogarciacaro** [comment]
There's a PR to the Browser bindings that goes in a similar direction: https://github.com/fable-compiler/fable-import/pull/40/files#diff-434cfab899cfc40a17547bc9ef6ae86cR2226

```fsharp
[<Emit("$0.addEventListener('load',$1...)")>] abstract addEventListener_load: listener: (Event -> 'Out) * ?useCapture: bool -> unit
```

I used a generic for the output so you can use `unit` or another object if necessary, but `unit` should also work for most situation. `Choice` cannot be used because it's a type from fable-core that JS won't understand, but you can use an [erased type](http://fable.io/docs/interacting.html#erase-attribute): `?option: (U2<bool, AddEventListenerOptions>)`
