### ISSUE TITLE
Fable module not found following Getting Started manual

### ISSUE THREAD

**Issue by halcwb** [fable-compiler/Fable#1079]
### Description

Perform a fresh install following the requirements and Getting started manual from the fable website.

### Repro code

Create a new project following the manual
Restore dependencies

### Expected and actual results

Open the App.fs file in Atom or Visual Studio Code with the Ionide package installed.
This results in:

<img width="1294" alt="fable-module-notfound" src="https://user-images.githubusercontent.com/683631/28262815-c1339a2e-6ae4-11e7-85d5-9a744a038e30.png">

### Related information

* Fable version 1.1.9
* Operating system: El Capitan

**Comment by alfonsogarciacaro** [comment]
Hi @halcwb! Are you using the latest template? Please make sure to also check the README of the template because sometimes the steps may change a bit (for example, recently .fsproj has been moved to the src folder, so you've to run `dotnet restore` from that folder).

Also, please note that dotnet SKD 2.0 preview seems to give problems. You may need to run `mono .paket/paket.exe install` to fix them. If that doesn't work, it's recommended you use the stable dotnet SDK 1.0.4.

**Comment by halcwb** [comment]
@alfonsogarciacaro Thanks. But I run the stable 1.0.4 dotnet version and I did do the `dotnet restore` from the src folder. As you can see all the Fable packages are there.

**Comment by halcwb** [comment]
I think it might be a paket issue? My .proj file doesn't contain any references to installed packages:

```
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by halcwb** [comment]
Ok, after running paket manually and doing a `mono .paket/paket.exe restore`. I got this working. But still don't know what the initial problem was.

**Comment by alfonsogarciacaro** [comment]
Glad you got it working! Not sure here either, but yes sometimes it may help running `paket install` or just restarting VS Code with `Reload window`.
