### ISSUE TITLE
Convert.ToBase64String fails with react native

### ISSUE THREAD

**Issue by talbottmike** [fable-compiler/Fable#1112]
I'm trying to convert a string to base64 for a react native app, but am getting a warning from the Fable compiler and an error at runtime. There is an existing test that I think covers this code in fable-compiler tests.
 
https://github.com/fable-compiler/Fable/blob/119b557e3d2672cecea33bf0141ffbab255c05cf/src/tests/Main/ConvertTests.fs

I tried the follwing based on the example found in the Fable tests.
```
let bytes = [| 2uy; 4uy; 6uy; 8uy; 10uy; 12uy; 14uy; 16uy; 18uy; 20uy |]
let foo = Convert.ToBase64String(bytes)
```
This code produces a warning at compile time "warning FABLE: Convert.toBase64String only accepts one single argument". 
At runtime it produces an error "Can't find variable: Buffer"

* Fable version (`dotnet fable --version`): 1.1.19
* Operating system: Windows 10

The following is from a gitter post made by @alfonsogarciacaro, and is working for me. 

```
[<Import("Buffer","buffer")>]
let Buffer = obj()

let inline encode (text: string, encoding:string) : string =
        Buffer?from(text)?toString(encoding) |> unbox
```

If there is a bug and there is anything I can do to help, I'd be happy to. However, it might also just be a case of me doing this wrong.

**Comment by talbottmike** [comment]
I pulled the current repo and ran build.cmd to run the tests. The Convert.ToBase64String test succeeeds. I don't understand why I was running into issues when attempting to use it.

**Comment by MangelMaxime** [comment]
I believe 1.1.19 is not the latest version of fable.  Perhaps you need to upgrade your version.

**Comment by inosik** [comment]
I assume the warning is there to indicate that only the overload taking a `byte []` is supported, because [the `Convert.ToBase64String` method has other overloads][msdn] too. I think we should change that, so that Fable doesn't emit this warning for this overload and fails for the others.

  [msdn]: https://msdn.microsoft.com/en-us/library/system.convert.tobase64string(v=vs.110).aspx

As for the runtime error, there seems to be no `btoa` function in React Native, so the code falls back to Nodes `Buffer` module, which doesn't exist in RN either. The code is in the [`String` module][impl] of Fable.Core.

  [impl]: https://github.com/fable-compiler/Fable/blob/6f08ff88e95d8bf49050a23545823bb43c02580b/src/js/fable-core/String.ts#L313-L315

This seems to be a known problem with RN when people try to use some Node packages (search for "react-native buffer"), and some workarounds exist for it, but the snippet you added above seems to be the easiest one. However, you could [create a plugin][plugin] for Fable to provide a replacement for `Convert.ToBase64String`, if you want to use the .NET API. The tutorial already existed for quite a time now, but I tried it with Fable 1.x once, and I was able to create a plugin without any problems.

  [plugin]: http://fable.io/docs/plugins.html

**Comment by alfonsogarciacaro** [comment]
Converting toBase64String in JS is a bit tricky because it's one of the few things that depends on the environment. I recently changed the function in fable-core to [detect if the code is being run in the browser or on node](https://github.com/fable-compiler/Fable/blob/6f08ff88e95d8bf49050a23545823bb43c02580b/src/js/fable-core/String.ts#L313-L314). Unfortunately this still doesn't work on react-native because it has neither access to the browser `btoa` function nor global `Buffer` variable, as @inosik points out.

The solution is what you did, importing a `buffer` polyfill for react-native and invoking it. Actually, [this is already included in the `fable-react-native` helpers](https://github.com/fable-compiler/fable-react-native/blob/ca8349feda346819e6205e9de19808eb7972720a/src/Fable.Helpers.ReactNative.fs#L1737-L1742), so you can use it directly (but don't forget to add the [buffer module](https://www.npmjs.com/package/buffer) to your package.json).

BTW, the warning is wrong and caused by a mistake from my side when making the change mentioned above. I'll fix it, sorry! 😅

**Comment by talbottmike** [comment]
Thanks all. I'll use the version in the fable-react-native helpers.
