### ISSUE TITLE
Fable imports fable-core from NuGet cache directory

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#1124]
### Description

When using fable-splitter with the latest 1.2.0 beta, Fable imports fable-core from the NuGet cache directory.

### Repro code

1. Download the [repro sample][repro]
1. Restore packages
   1. `$ paket restore && dotnet restore`
   1. `$ yarn install`
1. `$ dotnet fable yarn-run compile`

  [repro]: https://gist.github.com/inosik/edfc6dda1f6fd1b18bfca2c43389f472

### Expected and actual results

The code compiles properly, but the import path for `fable-core/String` points to the NuGet cache directory on my machine:

``` js
"use strict";

var _String = require("C:/Users/nosikil/.nuget/packages/fable.core/1.2.0-beta-003/fable-core/String");

({
  formatFn: (0, _String.fsFormat)("Fable rocks!"),
  input: "Fable rocks!"
}).formatFn(function (x) {
  console.log(x);
});
//# sourceMappingURL=Program.js.map
```

### Related information

* Fable version (`dotnet fable --version`): 1.2.0-beta-005
* Operating system: Windows 7 x64

**Comment by inosik** [comment]
Apparently we can set the `fable.fableCore` option to a directory where fable-core is located or a module name.

**Comment by alfonsogarciacaro** [comment]
Yeah, this is tricky, because fable-core files are distributed with the Fable.Core Nuget package (to avoid version discrepancies) and now Fable will look for this in the .Nuget cache.

Anyway, what JS client are you using? The bundlers (Webpack, Rollup) should inject fable-core code in the final bundle, and fable-splitter should copy the files to the output folder. Maybe you're setting fable-core as a external dependency in Webpack? In that case, the best solution is probably to copy the `fable-core` folder in the Nuget package to a local folder and set `fableCore` in the fable-loader settings.

I've been also wondering if it's a good idea to distribute fable-core also through npm again. This could make it easier for your case, but it may cause problems if Fable.Core and fable-core versions go out of sync.

**Comment by ncave** [comment]
@alfonsogarciacaro Using explicit fableCore location scenario still requires you to provide a reference to Fable.Core in your project, which is fine as long as the fableCore option location is what is used at the end.

**Comment by inosik** [comment]
I wanted to build a small Node app, without using a bundler. But I think if somebody wanted to build a JS library with Fable, they would run into the same problem. I'm fine if we don't find a solution for this yet, I just thought that's a scenario worth considering.

Setting `fable.fableCore` only changed the module name/path where fable-core was imported from. So `fableCore: './fable-core'` translated to `var _String = require('./fable-core/String')` and so on.

> distribute fable-core also through npm again.

We'd need multiple versions of it, for the different module systems 🤔

> may cause problems if Fable.Core and fable-core versions go out of sync

Yes, that's the same problem we had with Fable.Core and dotnet-fable, but now spread over two different package systems 😄

**Comment by alfonsogarciacaro** [comment]
Creating a library with Fable and leaving fable-core as a external dependency was explored in the past but has not been discussed any more since fable-core is not distributed through npm. With tree shaking you shouldn't have to worry too much about the overhead and you'll avoid versioning issues.

However, if you want to have Node libraries written with Fable for your personal use without bundling fable-core, you can set the `fableCore` option to "fable-core" (as if it were an npm package, without a dot in front), compile it with fable-splitter and let the client resolve the "fable-core" dependency (for example, in Webpack config). We could distribute fable-core through npm again to make this easier and prevent versioning conflicts, but as you say this brings other issues like which module system should be used, etc.
