### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/Fable#1137]
This looks very tasty to me: 
https://reasonml.github.io/community/blog/#way-way-waaaay-nicer-error-messages

It is a new implementation of error messages for OCaml/Reason and Bucklescript.

**Comment by MangelMaxime** [comment]
I don't think fable can do something about it. It's more a feature that need to be implemented into F# compiler IMO.

I think you should open your issue here: https://github.com/fsharp/FSharp.Compiler.Service

**Comment by ShalokShalom** [comment]
These error messages in OCaml get activated by a Bucklescript flag, which is why I assumed its the same here. :smile:

**Comment by alfonsogarciacaro** [comment]
There's already ongoing effort to improve F# error messages (not only for Fable): https://github.com/Microsoft/visualfsharp/issues/1103

BTW, for what I've seen in the discussions, the F# compiler contributors are more in favor of having shorter texts as IDE tooltips rather than long texts in the compiler command line output.

**Comment by ShalokShalom** [comment]
An option is possible for sure.
