### ISSUE TITLE
REPL should say "loading" instead of "compiling" for first run

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1146]
The very first compile in the REPL is a bit slow since stuff is loaded or things like that.
We should change the status message to reflect that so that people don't assume it's always that slow.

/cc @ncave

**Comment by alfonsogarciacaro** [comment]
Could be an idea though there're several things happening (downloading and parsing JS bundle, downloading and decoding assemblies, etc) and I'm not sure if there's a hook to when _actual_ compilation starts.

We could also add a mention about that in the new README. I hope that users would notice by themselves that compilation after the first one are faster too.

**Comment by ncave** [comment]
@alfonsogarciacaro We're already timing only the actual compilation, any difference between times is due to javascript jitting. What I think @forki is referring to is the long wait on initial load and very first compile.

As there is nothing we can do about that (those things still need to happen), we can either:
- set expectations by explaining all about it (but nobody likes excuses, or reading, i.e. tl:dr),
- or just pre-compile all samples on load (in the worker) but not show anything on the right (just enable the Compile button when ready). If we move the loading of the Fable bundle in the worker as well, the page would load very fast. We can just have some welcome text on the right, or nothing.

**Comment by alfonsogarciacaro** [comment]
Now REPL says "Loading" on firs compilation :)

**Comment by forki** [comment]
💋
