### ISSUE TITLE
Calling and applying to a function returned by a member doesn't work

### ISSUE THREAD

**Issue by durkiewicz** [fable-compiler/Fable#1154]
First of all, thank you for this great tool! I would like to submit an issue I've recently found in it.

### Repro code

```
let foo a b c d = a , b + c d
let bar a = foo 1 a
let baz = bar 2 (fun _ -> 3) ()
```

### Expected and actual results

Expected: the `baz` should be equal to `(1, 5)`
Actual: Runtime error "Uncaught TypeError: bar(...)(...) is not a function" when computing `baz`

### Related information

* Fable version (`dotnet fable --version`): 1.2.0-beta-004
* Operating system: Ubuntu 16.04
* The bug is also reproducible in the REPL (http://fable.io/repl)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the kind words, for the report and for the code to reproduce the issue :smile: It seems this problem comes from the F# compiler as it gives me wrong types for the function returned by a member, so the uncurrying optimization doesn't work. I should check with FCS maintainers but for now I'm using the dynamic `CurriedLambda` which is acting as a catch-all for the cases where partial application cannot be resolved.
