### ISSUE TITLE
Partially applied functions with side effects

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#1156]
### Description

Side effects saga continues. It seems that partially applied functions evaluate already applied arguments on every execution.

### Repro code

```
let mutable counter = 0
let next () = 
  let result = counter
  counter <- counter + 1
  result

let adder () = 
  let add a b = a + b
  add (next())

let add = adder ()
add 1 + add 2 + add 3 |> printfn "%d"
```

The problem is that result of `adder` is `return $var1 => add(next(), $var1);` which executes `next()` on each call. Proper code would be `next_frozen = next(); return $var1 => add(next_frozen, $var1);` (or equivalent iife).

### Expected results

`6`

### Actual results

`9`

### Related information

* Fable version (`dotnet fable --version`): 1.2.3
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
This is tricky. I applied your sensible suggestion and it works. But unfortunately it doesn't in a local function (I added the failing test in the commit but it's commented out):

```fsharp
let ``Partially applied functions don't duplicate side effects locally``() =
    let mutable counter = 0
    let next () =
      let result = counter
      counter <- counter + 1
      result
    let adder () =
      let add a b = a + b
      add (next())
    let add = adder ()
    add 1 + add 2 + add 3 |> equal 6
```

This translates too:

```js
  ...
  const adder = CurriedLambda(function () {
    const add = function (a, b) {
      return a + b | 0;
    };
    const $var1 = next() | 0;
    return $var2 => add($var1, $var2);
  });
  let add_1 = $var4 => adder(null, $var4);
  ...
```

The problem is adder is also wrapped so `next` is going to be called every time even if the expression was frozen within adders' body. I'm not sure if there's an easy way to fix this. Apparently the solution is to do `adder(null)($var4)` but the compiler may not know where that function comes from and it would also defeat the purpose of the uncurrying optimization 😕

**Comment by alfonsogarciacaro** [comment]
Can you please check with Fable 1.2.4? I'm using now more JS runtime dynamic magic and less compile-time Fable tricks ;)
