### ISSUE TITLE
fable-loader reads files from outside of my project

### ISSUE THREAD

**Issue by haf** [fable-compiler/Fable#1158]
### Description

Fable loads things from outside of my project, e.g. as seen with the linter that runs as part of my webpack build pipeline:

```
/Users/h/.nuget/packages/fable.core/1.2.3/fable-core/ListClass.js
  7:27  error  'List' was used before it was defined  no-use-before-define
  9:19  error  'List' was used before it was defined  no-use-before-define
```

### Repro code

Any of the samples + linter in `webpack.config.js`:

```
        { test: /\.js$/, exclude: /node_modules/, loader: 'eslint-loader', enforce: 'pre', },
```

### Expected and actual results

Source code from `packages/` so I can use `.eslintignore` to ignore it for anyone building the project.

### Related information

Latest fable, macOS, following fable-suave-scaffold sample.

**Comment by MangelMaxime** [comment]
It seems to happen even if we don't use `storage:none` option.

**Comment by alfonsogarciacaro** [comment]
Yes, this is intended. `fable-core` JS files live now in the `Fable.Core` Nuget package. This is to avoid the common version mismatch that happened when both packages lived separately. So Fable will look for fable-core JS files where `Fable.Core` package is, usually in the Nuget cache.

You can avoid conflicts with the linter by adding excluding files in `.nuget` folder, for example: 

```js
 { test: /\.js$/, exclude: /node_modules|\.nuget/, loader: 'eslint-loader', enforce: 'pre', },
```

@MangelMaxime This is because Paket actually doesn't reference the .dlls in the local `packages` folder for dotnet SDK projects. Before Fable was doing a manual resolution of the references looking for the `paket.dependencies` file among other things, but this was prone to failure. Now Fable invokes MSBuild (through Dotnet.ProjInfo) to resolve the .fsproj file and its dependencies. An package references are always (at least as far I've seen) in Nuget cache.

**Comment by haf** [comment]
Wouldn't it be better to ship Fable.Core in a npm package as well, in the case when it's invoked through webpack?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro  Ah yes, you are right :)
