### ISSUE TITLE
Suggestion: fable-loader should output type information

### ISSUE THREAD

**Issue by haf** [fable-compiler/Fable#1159]
Similar to how CoffeeScript 2 outputs flow type information: https://github.com/jashkenas/coffeescript/issues/4706

As far as I understand @GeoffreyBooth has done a lot of the heavy lifting to output these block comments for CoffeeScript; it would be great to have them in Fable as well! Perhaps he can give some pointers on where to start?

Right now, this is what it looks like from the vscode flow plugin's viewpoint:

<img width="595" alt="screen shot 2017-09-20 at 15 51 50" src="https://user-images.githubusercontent.com/193115/30647821-c321b512-9e1c-11e7-8ef7-e21e76f30988.png">

It would have to export the module structure as well as the types. Is this how the coffee script webpack/babel loader works?

Another side-effect I'd like is to be able to navigate to the file through the IDE, like I can with JS files; F12/CMD+D should take me to the F# in question.

**Comment by alfonsogarciacaro** [comment]
Something similar has been discussed in the past (see #805, #270). In fact there's some code in the source to output declaration info but it's not working at the moment because it relied on a plugin that's not maintained any longer IIRC.

It's difficult to invest time in such a feature because there's no standard at the moment and trying to do this would probably force us to support all the competing tools: basically Flow and TypeScript. In fact the old implementation was intended to output TS declaration files but relied on the signatures to be the same as Flow's as this is what Babel support, I'm not sure what's the situation right now.

[Here](https://github.com/fable-compiler/Fable/issues/805#issuecomment-299507708) the possibility of outputting JsDocs is explored. This could be interesting as it shouldn't be too difficult, practical enough for most purposes, and the TS checker and I guess other tools can use them.

As a side note, Fable's goal is to comply with JS standards as much as possible, but not with 3rd party specs of other compile-to-JS languages. That's far out of my reach ;)

**Comment by haf** [comment]
It should probably be a plugin of some sort, not core Fable. It wouldn't force you to support both tools though (doesn't follow logically). Doing it for flow would mean you support flow annotations. Doing it for typescript would mean you support ts annotations.

The upside with the comments of Flow is that you DO output standard JS, just with added comments. Those comments would also help a human reason about the types.

If "the same as Flow's as this is what Babel support" is true, then isn't that a great reason to support it, as Babel is the de-facto standard for compiling ECMAScript vX to browser-food?

JSDoc isn't expressive enough; Flow is on par with the F# type system, so it's almost no mapping necessary.

**Comment by haf** [comment]
Do you have any "your first contribution tutorial" for Fable; I can see if I can do the basics in an evening so we get that WIP PR.

**Comment by alfonsogarciacaro** [comment]
You can play by passing `declaration: true` to Fable options in any of Fable clients (Webpack loader, Rollup plugin, fable-splitter). It should generate some (albeit incomplete) annotations in the Babel AST (look for `if com.Options.declaration then` in Fable2Babel.fs) and then you can use a Babel plugin to generate the comments.

I gave [babel-plugin-transform-flow-comments](https://www.npmjs.com/package/babel-plugin-transform-flow-comments) a quick try, but it didn't seem to work:

```fsharp
let foo x y = x + y
```

Using following splitter.config.js:

```js
const fableUtils = require("fable-utils");

var babelOptions = fableUtils.resolveBabelOptions({
  plugins: [
    "transform-es2015-modules-commonjs",
    "babel-plugin-transform-flow-comments"
  ],
})

module.exports = {
  entry: "QuickTest.fsproj",
  outDir: "temp",
  babel: babelOptions,
  fable: { declaration: true }
};
```

I get:

```js
function foo /*:: */(x /*:: */, y /*:: */) /*:: */ {
  return x + y | 0;
}
```

Which seems to work but not quite right (it doesn't output the `number` type annotation). I'm not sure what's wrong because if I print the JSON received from Fable daemon to fable-splitter it seems to be right:

```json
            "declaration": {
                "id": {
                    "name": "foo",
                    "type": "Identifier"
                },
                "params": [
                    {
                        "name": "x",
                        "typeAnnotation": {
                            "type": "TypeAnnotation",
                            "typeAnnotation": {
                                "type": "NumberTypeAnnotation"
                            }
                        },
                        "type": "Identifier"
                    },
                    {
                        "name": "y",
                        "typeAnnotation": {
                            "type": "TypeAnnotation",
                            "typeAnnotation": {
                                "type": "NumberTypeAnnotation"
                            }
                        },
                        "type": "Identifier"
                    }
                ],
                "body": {
                     ...
```

At least when comparing a similar JS code in [AST Explorer](http://astexplorer.net/) (using babylon6 parser and hiding location data).

```js
export function foo(x: number, y: number) {
  return x + y;
}
```
