### ISSUE TITLE
Watch mode crashes with StackOverflow on "let rec inline"

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1161]
![so](https://user-images.githubusercontent.com/57396/30649737-5ebde758-9e21-11e7-90b1-e737d0f7fe3f.gif)

It's probably a stupid thing to do, but it should result in compile error not StackOverflow

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on the latest Visual F# Tools, which uses `ParseAndCheckProject` in one place. No SO for sure. May it be the case that Fable uses an outdated FCS?

**Comment by alfonsogarciacaro** [comment]
I'm not sure how the F# compiler resolves inline functions in IL, but Fable just replaces the call to a inline function with the function body, so I guess when a inline function calls itself recursively Fable naively tries to insert the function body ad infinitum, and thus causing the SO.

The easiest solution would be not to inline recursive function (and maybe adding a warning) but the problem is I cannot find an easy way to detect if `FSharpMemberOrFunctionOrValue` is recursive. Do you know how to do that @vasily-kirichenko? Latest Fable also uses latest FCS (14.0.2).

**Comment by forki** [comment]
@dsyme close the corresponding VF# issue (https://github.com/Microsoft/visualfsharp/issues/3634) as "Won't fix" ;-(

**Comment by alfonsogarciacaro** [comment]
Don't mention him, @forki. I promised Don at FableConf I wouldn't be bothering him with SO exceptions at least for the rest of the year ;)

**Comment by alfonsogarciacaro** [comment]
I also promised him I wouldn't be asking again what's `LoadTime` for in the FSharpProjectOptions ;)

**Comment by forki** [comment]
what I don't really understand: why is fable inlining it? shouldn't that be already done in TAST of compiler? I mean don't you run optimizeExpr on it?

**Comment by alfonsogarciacaro** [comment]
Nope, the TAST doesn't contain any optimization (you should see what I need to do to clean the `|>` chains). What's `optimizeExpr`? I've never used it 🤔

**Comment by forki** [comment]
@vasily-kirichenko do you know if FCS exposes the optimizer?

**Comment by vasily-kirichenko** [comment]
I don't know :( @dsyme

**Comment by forki** [comment]
@alfonsogarciacaro I'm talking about https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/Optimizer.fs#L1672 - it should replace `|>` and other inlining automatically. and I think it would throw on the original error here.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/31019466-0dd22cf8-a530-11e7-938b-40c88e0814bc.png)

also this ^^

If we run it through optimizer it would reduce g to 6.

**Comment by alfonsogarciacaro** [comment]
Inlining is discussed in #1197 and #1266
