### ISSUE TITLE
String.split / Regex.split

### ISSUE THREAD

**Issue by evilz** [fable-compiler/Fable#1167]
### Description

Compile `Regex.Split` to `"mystring".split` when possible ?

### Repro code

```fsharp
  let nonword input =
    Regex.Split(input,"/\W+/")
```
Will not work since the pattern is not correct it must be "\W+"

and compile to 

```
import { split } from "fable-core/RegExp";
const nonword = __exports.nonword = function (input) {
    return split(input, "\\W+");
  };
```

### Expected and actual results

Can be cool to be 

```
return input.split(/\W+/)
```

### Related information

REPL =>   ES2015 Compile  Run Fable v1.2.0, FCS v14.0.2, Babel v6.26.0

**Comment by alfonsogarciacaro** [comment]
The `split` function in fable-core is more general and covers more cases to follow .NET semantics more closely, but it would be possible to detect this special case and perform the optimization. This should be done [somewhere in here](https://github.com/fable-compiler/Fable/blob/28295febd79592968545a0b74dd3a9dad22e6892/src/dotnet/Fable.Compiler/Replacements.fs#L1201-L1240), you can give it a try 💪  I'll have a look later too, though as this is only a minor optimization it's not a high priority at the moment. 

Fable is not outputting JS literal Regex at the moment because of the flags, but we could also try do it when no `RegexOption` is being passed.

**Comment by alfonsogarciacaro** [comment]
We're currently aiming for correctness so we can close this as it's a small optimization that it's not benchmarked. But it'd be great if you could send a PR (with tests, please) for it!
