### ISSUE TITLE
Documentation on F# Records

### ISSUE THREAD

**Issue by isaacabraham** [fable-compiler/Fable#1175]
It's not entirely clear from the getting started guides that you can acutually use F# records *without* the `[<Pojo>]` attribute. Taken from the docs:

> It is also possible to instantiate a plain JS object in a type-safe manner by declaring an F# record with the Pojo attribute

From reading this, it's entirely possible to think that you *must* use the attribute on records to allow them to be used in Fable.

In the compatibility guide it also says:

> The following F# semantic and syntactic features are also available:    Records and Unions

However, it's not clear what the difference is between a record and a record with `[<Pojo>]`. What do I gain by using the attribute? When and why should I use it?

**Comment by alfonsogarciacaro** [comment]
With the documentation, I always try to be informative without writing too much, this makes it easier to maintain the docs, but I've also noticed that many people don't read documentation if it's too long. That said if something is clearly missing and cannot be understood by the current text, I'm always open to PRs to improve the docs :)

The [Plain Old Javascript Objects](http://fable.io/docs/interacting.html#plain-old-javascript-objects) section is about POJOs, that is, literal JS objects (no class instances). These are especially important because some JS libraries, like React, require plain JS objects for configuration and don't accept a class instance. The section in the docs mention the different ways to create Pojos with Fable (`createObj`, `createEmpty<'T>` or records with `[<Pojo>]`). The end of the section mentions answers partially your questions but it may not be enough:

> This is mainly useful to interact with JS libraries that expect a plain object (e.g., for configuration) instead of a class instance. But do not abuse this solution because records with Pojo attribute will miss features like members or reflection.

The compatibility guide is more about writing standard F# for Fable without special tricks to interact with JS libraries. It says the F# semantic features are kept for records, because they will be compiled to classes with metadata so you can static/prototype members, type checking, reflection, etc. This can be quickly tested in the REPL.

It can happen that if someone checks the interacting document before anything gets this wrong impression. Please feel free to send a PR to expand the current wording or maybe a link to a sample in the REPL showing F# records with and without `Pojo` attribute so users can see the difference :+1:

**Comment by isaacabraham** [comment]
Perhaps it's more useful to elaborate on the "literal JS object" that you mentioned above, or simply to add a caveat in that section that clearly explains that this is *only* for them, and that F# Records compile to classes just fine.

The main worry I have - especially because the order of the docs means that you might read this one *before* the other one - is that someone reads this and comes away thinking that they always need to use Pojo for an F# record.

**Comment by alfonsogarciacaro** [comment]
I'll close this for now on, please feel free to send a PR to the docs (`docs` folder in this repo) to improve the wording :+1:
