### ISSUE TITLE
Generate documents for core library

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/Fable#1177]

**Comment by alfonsogarciacaro** [comment]
Sorry, could you please expand a bit on your request? What kind of documentation do you want to see? If it's for `Fable.Core` most of the documentation can be found in the [Interacting with JS document](http://fable.io/docs/interacting.html). If it's about calling fable-core directly from JS, I'm a bit reluctant to do that, because the way it works in some case depends on some internal operations made by the compiler and exposing a public JS API where we need to be careful of breaking changes can pose a burden to maintenance.

**Comment by zaaack** [comment]
Actually I'm saying just a generated API reference for Fable.Core and even others like Fable.Import.JS, like this 
 http://fsprojects.github.io/ProjectScaffold/writing-docs.html#API-docs. I notice there many useful API I can only find in source code and tests, e.g. jsOptions,  operators like :?. It would be convenient if Fable have a full generated API reference to exploring.

**Comment by alfonsogarciacaro** [comment]
That could be helpful indeed, would you be open to send a PR for this?

**Comment by zaaack** [comment]
@alfonsogarciacaro Sure, I'm willing to send a PR! But it might take some time... I'm busy doing some more high level work recently because here is a small side project coming from my friend and I'm going to using SAFE-Stack. But I'll working on this whenever I got time.

**Comment by alfonsogarciacaro** [comment]
Great, thank you! Don't worry, there's no rush :+1:
