### ISSUE TITLE
gRPC Web PoC

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1183]
### Description

gRPC web is a project and a spec for doing doing web communication using gRPC. You are able to create and consume gRPC services. The project has a good example that create a TypeScript client. I'd like to get that client working from Fable as a proof-of-concept. I could use some assistance with:

- [ ] Module not found errors when running `dotnet fable webpack`

see details in https://github.com/ctaggart/grpc-web/pull/1

### Repro code

```
git clone https://github.com/ctaggart/grpc-web.git
cd grpc-web
git checkout fable
cd example\FableApp\src
dotnet build
dotnet fable webpack
```

cc @panesofglass

**Comment by alfonsogarciacaro** [comment]
Errors like `Module not found: Error: Can't resolve 'grpc'` come from Webpack, maybe you need to run `npm install` or `yarn install`? The messages like ` warning FABLE: jsNative is being compiled without replacement, this will fail at runtime` are probably caused by the bindings, I'll have a look :+1:

**Comment by ctaggart** [comment]
Thanks @alfonsogarciacaro, I decided to have a better look at Fable interop and ts2fable. I'll come back to this after that. I imagine, this will not be as difficult, once I understand how that all works.
https://twitter.com/cmr0n/status/919919033234935808

**Comment by alfonsogarciacaro** [comment]
Closing as I think you got it figured out :wink: Please reopen if you still need help.
