### ISSUE TITLE
Enum.GetName or similar

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1217]
It would be nice to be able to print the enum name somehow.

``` fs
printfn "unknown kind in ModuleDeclaration: %A %A" nd.kind (Enum.GetName(typeof<SyntaxKind>, nd.kind))
```

I'm not sure if there is something Fable can do on the standard APIs or a custom Fable API, but the generated code would essentially just be a `match` that returned the name for each enum case.

currently with Fable 1.2.4:
``` 
error FABLE: Cannot find replacement for System.Enum::GetName
```

**Comment by alfonsogarciacaro** [comment]
Hmm, right now enums are completely erased (they're just literal ints in JS code) so this is tricky as you cannot resolve the enum case until runtime. I'll try to have a look but I guess we'll need to inject the enum info somewhere for this... or we could just do it in the type declaration and trust the JS minifiers will delete that piece of code if it's not finally used.

**Comment by alfonsogarciacaro** [comment]
This is proving to be a bit complicated. [I'm trying to output the Enum cases in the compiled JS](https://github.com/fable-compiler/Fable/commit/657f3b9996ef0bf74c825ad59afed46532154beb) so you get something like this:

```fsharp
type Foo =
    | Ja = 5
    | HOHOHO = 8
    | Mooo = 9

let test() =
    Enum.GetName(typeof<Foo>, Foo.Mooo) |> equal "Mooo"
    let typRef = typeof<Foo>
    Enum.GetName(typRef, 8) |> equal "HOHOHO"
    Enum.GetName(typRef, 7) |> equal null
```

```js
const Foo = {
    ["5"]: "Ja",
    ["8"]: "HOHOHO",
    ["9"]: "Mooo"
};
function test() {
    equal("Mooo", Foo[9]);
    const typRef = Foo;
    equal("HOHOHO", typRef[8]);
    equal(null, typRef[7]);
}
```

However, for some reason I'm getting Stack Overflow exceptions when testing the code. Probably because the Fable AST was designed [so Enum would be erased](https://github.com/fable-compiler/Fable/blob/b0646e7fbbf0619713addc2c433566ff7a7bfc4a/src/dotnet/Fable.Core/AST/AST.Fable.fs#L27) and thus it doesn't hold much info. Changing that may have caused some issues when traversing the AST.

This solution is not ideal either because it requires the Enum info to be in the JS, which is not the case for .dll bindings. I can think of some alternatives:

- Resolve the name at compile time: so `(Enum.GetName(typeof<SyntaxKind>, nd.Foo))` just becomes `"Foo"` in the compiled JS. This would be the easiest option for me, but the problem is this won't work if the enum value can only be resolved in runtime (as in your sample above).
- Inline all the enum options in the call site. This shouldn't be too difficult to implement either, but it could bloat the code too much if `Enum.GetName` is used multiple times or the enum has too many cases.
- Add an additional file to compilation to inject extra code (like the enum cases), so you only need to do it once. I'm not sure how difficult this would be, though I tried something similar in the past.

What do you think?

**Comment by ctaggart** [comment]
I wouldn't prioritize this super high right now. I'd rather get help trying to figure how to deal with imports/exports and multiple files with ts2fable https://github.com/fable-compiler/ts2fable/issues/29 https://github.com/fable-compiler/ts2fable/issues/21.  :-)

This is pretty easy to work-a-round manually or by code gen in ts2fable with a custom function. In this case:

``` fs
type Foo
static member GetEnumName (v: Foo) =
  match v with
  | Ja -> "Ja"
  | HOHOHO -> "HOHOHO"
  | Mooo -> "Mooo" 
```

**Comment by alfonsogarciacaro** [comment]
Ok, I'll close the issue for now. Feel free to reopen it if you still need the method :+1:

**Comment by theimowski** [comment]
I just encountered same issue in my project. Nothing critical, the workaround works fine, just a heads up as it's a bit annoying as I have an enum with more than 20 cases. 
Would be great to have that working OOTB in fable. 
Also had to modify the workaround a bit to make it work by using fully qualified case names:

```fsharp
match v with
| Foo.Ja -> "Ja"
...
```

**Comment by alfonsogarciacaro** [comment]
Reflection for enum types is finally supported by Fable :) Please check https://github.com/fable-compiler/Fable/commit/e2c1bef8366ab4f0ff40b4a209252485fb40c0f7#diff-32f2dda6a86cff59fc9073965d7eee93
