### ISSUE TITLE
Multiple namespace declarations does not work.

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#1218]
### Description

This was an old request but it would it be possible to support multiple namespaces?

https://fable.io/repl/#?code=namespace%20Test.A.B%0Atype%20Test%20%3D%20%7B%0A%20%20Int%3A%20int%0A%7D%0Anamespace%20Test.A.C%0Atype%20Test%20%3D%20%7B%0A%20%20String%3A%20string%0A%7D%0A%0Amodule%20Test1%20%3D%0A%20%20printfn%20%22%25A%22%20%7B%20Test.A.B.Test.Int%20%3D%200%20%7D&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2

As you can see here from the generated code, it seems like it bails out as soon as `Test.A.C` is defined. Normally it used to generate a compile error so when 1.2 came it I erroneously thought it was fixed but upon closer inspection, I realized it isn't.

I'm reopening this issue, hoping you guys can take a look at it again. My workaround is really not pretty and supporting multiple namespace declarations in a file would help me greatly.

### Repro code

The fable repl code

### Expected and actual results

To work

### Related information

* Fable version (`dotnet fable --version`): 1.2.0
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
Hmm, it's still better if you use a single top module per file when compiling to Fable, as you'll get the benefits of tree shaking. I don't remember exactly if there was an specific reason why multiple spaces were not supported but it may be possible converting them to nested modules if you really need them. I'll try to have a look :+1:

**Comment by alfonsogarciacaro** [comment]
I tested this with dotnet-fable CLI and it was actually working. The only problem was Fable wasn't flattening the common part of the two namespaces (Test.A) so it failed when trying to create two JS objects (to represent the namespace) with the same name on the same level (Test).

I have added the code to [flatten the common namespace](https://github.com/fable-compiler/Fable/blob/89856e134dfbc58f2b4b11efca4e810266943ea1/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1208-L1220). [Some F# patterns will still be forbidden](https://github.com/fable-compiler/Fable/blob/89856e134dfbc58f2b4b11efca4e810266943ea1/tests/Main/Util/Util3.fs#L3-L8) but hopefully this is enough for your use case :)

I will publish a new 1.3 beta version with the change right away.

**Comment by FrankBro** [comment]
Unfortunately this will not fix my issue. I do have duplicate namespace definitions as well as different namespace.

My example has parts looking like this

https://fable.io/repl/#?code=namespace%20Test.A.B%0Atype%20Test%20%3D%20%7B%0A%20%20Int%3A%20int%0A%7D%0Anamespace%20AnotherTest.D.E%0Atype%20Test%20%3D%20%7B%0A%20%20Test%3A%20Test.A.B.Test%0A%7D%0Anamespace%20Test.A.B%0Atype%20Test2%20%3D%20%7B%0A%20%20String%3A%20string%0A%7D&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2

**Comment by alfonsogarciacaro** [comment]
Hmm, I guess we could merge the duplicated namespaces... Out of curiosity, why do you need such a structure?

**Comment by FrankBro** [comment]
We have a very large F# code base that defines a lot of types. We made a protocol extractor that extracts all of our types, mostly because a lot of types have members or overrides that are not accepted by Fable. This goes thru all of our code and extract tagged types. We found a workaround to this issue by creating a file per new namespace, which ends up being 100 F# files. I'd rather have a single "model" file with all our types if possible.

**Comment by alfonsogarciacaro** [comment]
Thanks for the explanation! I understand your use case much better now 😄 I've been [trying to support duplicated namespaces in different parts of the file](https://github.com/fable-compiler/Fable/commit/b480d464c5b24beec14acb0152362a873a85f2ef). Unfortunately this is revealing to be a non-trivial task, in my quick tests I've found several corner cases (especially in the way types reference to each other) that are not easy to solve the way Fable works right now.

I've been thinking to group the namespaces, but I guess it doesn't make much sense, because the user may want to put a namespace in between to overcome F# compilation order restriction (although this is not so necessary since we can apply `rec` to modules and namespaces). Is it not possible for your protocol extractor to do the grouping by itself?

I'm not sure I'll be able to dedicate much time to this. If you wish, please give it a try to the `multiple-namespaces` branch to see if you can find a solution to the problem. I can provide you with guidance for that.
