### ISSUE TITLE
dotnet core only 

### ISSUE THREAD

**Issue by evilz** [fable-compiler/Fable#1235]
### Description

Should avoid dependencie to mono for tooling or remove usage of them.
I'm trying to create a dev fable docker image.

The image contains node image and dotnet 2.0.3 sdk.
I want to only use dotnet cli to compile my fable projet.

### Repro code

- create simple netcoreapp2.0 project
- Remove paket stuff like target
- add one by one nuget package using cli including `dotnet-fable`
- execute
  - dotnet restore
  - cd src
  - yarn  install
  - dotnet fable webpack --port free -- -p

> this is an exemple ..

### Expected and actual results

do the job without error \o/

### Related information

Actual error
```
Module build failed: Error: MSBuild failed with exitCode 1 Working Directory: 'D:\Repos\boost-support\src' Exe Path: 'dotnet' Args: 'msbuild D:\Repos\boost-support\src\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\vbourdon\AppData\Local\Temp\tmpFB4A.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\vbourdon\AppData\Local\Temp\tmpFB4B.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\vbourdon\AppData\Local\Temp\tmpFB4C.tmp.GetProperties.txt /nologo /verbosity:quiet'
    at Loader.fableUtils.client.send.then.r (D:\Repos\boost-support\node_modules\fable-loader\index.js:67:22)
```

**Comment by alfonsogarciacaro** [comment]
Hmm, looks like this is an MSBuild error. That's weird because MSBuild should be installed as part of dotnet SDK 🤔 

In any case, it's going to be difficult to remove the Mono dependency as of now for non-trivial projects because Fable relies on Paket to resolve the dependency order of Nuget references. We have to wait until @forki and @matthid migrate Paket to netcore ;)

**Comment by forki** [comment]
@enricosada promised to have version until Xmas. :hugs:

Am 17.11.2017 16:15 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by evilz** [comment]
@alfonsogarciacaro What do you mean by 
>Fable relies on Paket to resolve the dependency order of Nuget references
 not sure to understand

🎄 🎁 <= a xmas paket  @forki are you Santa ?

**Comment by forki** [comment]
Paket is creating a file which lists the dependency tree in topological
order. Fable needs that info so that it can order file imports for you.

Regarding Santa. Yes I really hope we can pull that stunt

Am 17.11.2017 16:34 schrieb "Vincent B." <notifications@github.com>:

@alfonsogarciacaro <https://github.com/alfonsogarciacaro> What do you mean
by

Fable relies on Paket to resolve the dependency order of Nuget references
not sure to understand

🎄 🎁 <= a xmas paket @forki <https://github.com/forki> are you Santa ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/Fable/issues/1235#issuecomment-345276348>,
or mute the thread

**Comment by alfonsogarciacaro** [comment]
Ionide has a netcore-only option now. When Paket follows suit we'll be able to remove `Mono` from the list of Fable requirements :smile: I'll close the issue for now as we can't do anything from here at the moment.
