### ISSUE TITLE
Generic functions works weirdly 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/Fable#1245]
This code fails at runtime:

```fsharp
let get<'a> (host: Host) (path: string) : JS.Promise<'a> =
        promise {
            let url = sprintf "http://%s:65002/%s" host path
            let! resp = fetch url [ RequestProperties.Method HttpMethod.GET; requestHeaders [ContentType "application/json"]]
            let! text = resp.text()
            ofJson<'a> text
        }
...
get<ARecord> ".." ".."
```
![image](https://user-images.githubusercontent.com/873919/33162052-8f1ec144-d038-11e7-8f7a-a0a796d5dea9.png)

![image](https://user-images.githubusercontent.com/873919/33162123-d4a98d8e-d038-11e7-9442-a5b1adca377b.png)

![image](https://user-images.githubusercontent.com/873919/33162129-dd78786c-d038-11e7-97c6-50835b9ca5fd.png)

Making `get` function `inline` solves the problem.

**Comment by alfonsogarciacaro** [comment]
Yes, generic information is erased in runtime. This is intended to make it easier to expose F# functions to JS code and also to avoid generating specific functions for each generic instantiation as Funscript did. `ofJson` needs the generic information and that's why it fails. However, it is still possible to [access generic information with inline functions (as you did) or with the `PassGenerics` attribute](http://fable.io/docs/compatibility.html#generics). BTW, didn't you get a compiler warning asking you to add `PassGenerics` to the `get` method?

**Comment by alfonsogarciacaro** [comment]
I'm going to close this, as this is per design. But please feel free to reopen if you've any other related issue or suggestion.
