### ISSUE TITLE
Repl regression

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1269]
Repl is currently broken, most probably by #1265.

**Comment by alfonsogarciacaro** [comment]
Damn, I really need to add the REPL to CI 😬

**Comment by alfonsogarciacaro** [comment]
I'm about to merge #1271 an it seems the JS version is able to compile the Sudoku sample with the actual code, how can we test this regression?

**Comment by ncave** [comment]
@alfonsogarciacaro Did you change something from #1265? It was definitely not working before.

**Comment by alfonsogarciacaro** [comment]
Nothing in particular I can recall, during the tests for #1271 at one point I commented out [the suspect lines](https://github.com/fable-compiler/Fable/blob/efaff4739d42a7e90b140cc2429d1cf84e7cc5fd/src/dotnet/Fable.Compiler/Fable2Babel.fs#L719-L722) but I brought them again after confirming they weren't causing any problem.

One noticeable change though is I converted the `test_script.fsx` into the module `test_script.fs` because I was getting an "unexpected behavior" error. Is that what you were seeing? What was broken exactly? The FCS/Fable compilation itself, or compiling F# code to JS with the REPL?

**Comment by ncave** [comment]
@alfonsogarciacaro Idk, it works now, I guess you fixed it :)

**Comment by alfonsogarciacaro** [comment]
Ok, let's call it a fix then! 😄 Hopefully now that the REPL is being built by CI I won't be breaking your work as many times as before :wink:

**Comment by alfonsogarciacaro** [comment]
This is not surprising but you were right :wing: For some reason, the test I added to CI passed fine, but when trying to do autocompletion in the repl there were errors, commenting out [the Assignments active patter](https://github.com/fable-compiler/Fable/blob/efaff4739d42a7e90b140cc2429d1cf84e7cc5fd/src/dotnet/Fable.Compiler/Fable2Babel.fs#L719-L722) does prevent the error.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, I can confirm that commenting that Assignments active pattern (above) fixes it.
I would say just take it out temporarily until it can be fixed, and close this issue.

**Comment by alfonsogarciacaro** [comment]
Ok, #1284 should fix it. I was interested in having this optimization as it removes a lot of the generated closures to put assignments in expression position. Hopefully this also helps improve the performance of the REPL.

> Note to self: don't expose mutable fields, you can't control them ;)

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, that fixes it.
