### ISSUE TITLE
Klipse - Another way to evaluate Fable in the Browser

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/Fable#1309]
See this: http://blog.klipse.tech/ocaml/2017/10/05/blog-ocaml.html

**Comment by alfonsogarciacaro** [comment]
Thanks! Yes, there's a related old issue #727 We haven't completed support for Klipse yet because we're focusing on the new [Fable REPL](https://github.com/fable-compiler/fable-repl) which offers IDE-like capabilities. After this is finished, we're planning to componentize it so it can be used as a library by Klipse :+1:
