### ISSUE TITLE
How to include Fable.Fable2Babel in a plugin ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1326]
I have this `paket.references`:

```
Fable.Core
Fable.Compiler
```

But I can't open `Fable.Fable2Babel`. @alfonsogarciacaro Any idea why I can't access this module ?

**Comment by MangelMaxime** [comment]
For info, I pushed a "working" plugin [here](https://github.com/MangelMaxime/Fulma/tree/feature/try_plugin/docs/Plugins).

This is just, printing the `info.ownerFullName` of everything that's pass by `TryReplace`.

You can run it by doing:
1. `cd docs/Plugins`
2. `dotnet build -c Release`

And build the docs site via: `build.sh QuickBuildDocs`

**Comment by alfonsogarciacaro** [comment]
Apparently it was because there was a [`>= netcoreapp2.0` restriction for Fable.Compiler in paket.lock](https://github.com/MangelMaxime/Fulma/commit/6d0f48994bbcb4dd89ea287542eeddbf56cda774#diff-2bfb11ab4230093400363f8d70eab088L12) and this made Paket not install the package even if was in paket.references. Any idea why the restriction was generated (it went away by deleting paket.lock and running `paket install` again) and why Paket skipped package installation silently @forki?
