### ISSUE TITLE
Clashing member names cause runtime exception

### ISSUE THREAD

**Issue by tpetricek** [fable-compiler/Fable#1343]
### Repro code

In normal F#, the following is allowed - you can have a type with a member name that clashes with a member name of an interface it implements:

```
type I = 
  abstract Trick : string
type A = 
  { Trick : string }
  interface I with
    member x.Trick = x.Trick + "!"
let a = { Trick = "Hi" }    
a.Trick // Should return "Hi"
(a :> I).Trick // Should return "Hi!"
```

### Expected and actual results

You get an error message at runtime:

> Uncaught TypeError: Cannot set property Trick of #<A> which has only a getter

This should either emit a warning (because you probably don't need to do this in any sensible code) or Fable should somehow mangle interface member names to make it work. I'd be quite happy with the former though.

**Comment by alfonsogarciacaro** [comment]
It would be problematic to mangle interface names as they are used to define types coming from JS in the bindings, but own methods and properties are mangled in the case of conflict #1301 The case of record fields is a bit trickier because they are implemented as direct fields in the object. Probably the warning is the way to go.

Anyway, this is changing in Fable 2, where a new object with the interface methods will be defined every time a value is coerced to an interface. This should resolve the clashes, the only limitation remaining would be that interface methods cannot be overloaded.

**Comment by Alxandr** [comment]
This is also a huge problem with computational expresions. I used most of today to figure out that my JS was calling the wrong implementation for `myBuilder.For`, and that's even though it was inlined.

Basically, I had this:

```fsharp
type Builder () =
  member inline __.For (x: seq<_>, f) = foreach f x
  member inline __.For (x: IOSeq<_>, f) = foreachM f x
```

And the js called `foreach` (the `.For` calls isn't in the JS at all, cause of the inlining).

**Comment by Alxandr** [comment]
Quick tests in the Fable repl does not reproduce. The issue is that my project is stupidly complex, so figuring out what's causing this is probably not going to be easy (at least not at 2AM :P). I'm currently splitting the project up, and cleaning up (it's working now, so time to fix all the mess I made to get to this point), so if it shows up again I'll to to figure out why.

If you would like to have a look yourself, you can see the code here:

https://github.com/YoloDev/GitVersion/blob/master/src/core/YoloDev.GitVersion.Core.Abstractions/builders.fs#L361
https://github.com/YoloDev/GitVersion/blob/master/src/core/YoloDev.GitVersion.Core.Abstractions/builders.fs#L345

As you can see, I remove one of the `For` functions when building for fable, then I add a `coerce` function that turns a `seq<_>` into an `IOSeq<_>` (so I can make due with one overload).

**Comment by BillHally** [comment]
I can confirm that the issue of clashing member names causing runtime exceptions also affects Fable 3.

Duplicating the code from the original issue report here for convenience:
```fsharp
type I =
  abstract Trick : string
type A =
  { Trick : string }
  interface I with
    member x.Trick = x.Trick + "!"
```
When passed to Fable 3 this generates:

```javascript
import { Record } from "./.fable/fable-library.3.1.2/Types.js";
import { record_type, string_type } from "./.fable/fable-library.3.1.2/Reflection.js";

export class A extends Record {
    constructor(Trick) {
        super();
        this.Trick = Trick;
    }
    get Trick() {
        const x = this;
        return x.Trick + "!";
    }
}

export function A$reflection() {
    return record_type("App.A", [], A, () => [["Trick", string_type]]);
}
```
Any attempt to create an instance fails in the constructor when the attempt is made to assign a value to the property, with the same error as originally reported.

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @BillHally! Unfortunately, it's not easy to "fix" this automatically without breaking other code. The best thing we can do is raise a Fable compilation error when this happens. It's still possible to avoid the interface name clashing if you've access to the interface and decorate it with the `Mangle` attribute.
