### ISSUE TITLE
Old version of paket.exe in the dotnet project template?

### ISSUE THREAD

**Issue by ssmock** [fable-compiler/Fable#1353]
After I create a new Fable project via dotnet template, I am unable to `dotnet restore`, and get a TLS/SSL error:

> The request was aborted: Could not create SSL/TLS secure channel. (Github - cached (temporarily ignore updates))

I tried uninstalling/reinstalling the fable template with no success. I managed to work around the problem by replacing the project's paket.exe with a newer version ([5.148.0](https://github.com/fsprojects/Paket/releases/tag/5.148.0)). After doing that, I could restore without an issue.

This might be related to a recent problem noted here: [Paket.bootstrapper.exe unable to communicate with GitHub (5.138.5)](https://github.com/fsprojects/Paket/issues/3065).

**Comment by alfonsogarciacaro** [comment]
Thanks @ssmock. Yes, we haven't updated the templates since the githubgate so Paket.bootstrapper.exe is the old version and doesn't update automatically. I'll release a new version with the latest one. Thanks again for the reminder!

**Comment by bilkusg** [comment]
While you're at it, it is probably worth doing something about the other fable templates on nuget. The default template suggests looking on nuget for others, but they all seem very old, based on much older versions of fable and .net, and without a health warning. It would be useful to know for example if there is a new 'recommended' way of creating a javascript library using fable.

**Comment by alfonsogarciacaro** [comment]
The fragmentation of the templates is indeed an issue and there are some discussions about how to solve it (as in https://github.com/fable-compiler/fable-react/issues/59#issuecomment-367323202) but I'm not sure yet what's the best way. For Fable 2 I'll try to align with recent developments in Webpack and other tools and try to reduce the configuration as much as possible. I'm also waiting to see how dotnet CLI tools will evolve, as it seems it'll be possible to install them globally soon.

About creating a JS library with Fable, it's not a common case so we don't have a recommended solution at the moment. But there is a template for that: https://github.com/slogsdon/Fable.Template.JavaScriptLibrary

**Comment by bilkusg** [comment]
Thanks. I've managed to get that template to work, but only after:
changing the 'cp' command in package.json to copy ( since I'm on Windows ) and slashes to backslashes
a) updating paket.exe etc in .paket
b) deleting paket.lock
c) Updating the version of netstandard to 2.0 in the project file
d) running paket install
Following the other instructions.

But it's not then immediately obvious what one should actually be deploying to the javascript application. All of the stuff in dist I assume....but what else? 

I have a lot of sympathy with the difficulties in keeping lots of older stuff up to date. People coming to fable for the first time are likely to hit on it at random through a search, and there's no guarantee that the stuff they read first will be current.

However, in that case, I do think that it's a priority to ensure that your website has a clear section which allows one to see what's currently considered 'up to date'. Just a comment like:
"  fable is currently at version 1.3 ( or whatever ) and uses dotnet standard 2.0
Projects and templates based on earlier versions should be considered out of date and only used if you are confident you know what you are doing "

might go some way to avoiding putting potential new users off.

BTW, you're not alone. I've also done some looking at WebSharper ( I prefer Fable... ) and their situation is just as bad if not worse...

Hope this helps.

**Comment by MangelMaxime** [comment]
Thank you for your feedback.

About this part:

> " fable is currently at version 1.3 ( or whatever ) and uses dotnet standard 2.0
> Projects and templates based on earlier versions should be considered out of date and only used if you are confident you know what you are doing "

The part about considering earlier versions out of date is kind of dragstic. For example, the [Elmish templates](https://github.com/fable-elmish/templates) have not been updated since a long time for the deps part and should still work directly using dotnet standard 1.6 or 2.0.

About the problem of `cp` command, this a reason why we should avoid system CLI or use either FAKE or Node package to do the job in templates.

Perhaps, we could have a way to update some of the templates via a CI server. At least the officials like Fable.Simple, Fable.Electron, Elmish templates, ...

**Comment by bilkusg** [comment]
I accept that you might not wish to consider the older versions obsolete, but they are out of date! 

I'm trying to think from the perspective of a new user, and what I expect is that if I find a template ( by following existing readme files and their suggestions ) and try to use that template, and subsequently discover that it's bringing in a rather old version of the compiler and the tools ( because of paket.lock ), and that's why my attempts to follow some example code is failing, then I'm likely to get pissed off, and may just give up.

If instead, I was warned up front that the older templates should be treated with caution, and how reliably to realise they are older, then I'm much less likely to have a problem.

If nothing else, every template which freezes a version of fable, should document that fact in its readme.

**Comment by MangelMaxime** [comment]
Locking version of dependencies is important to make sure project will build. What would happen if there is a breaking change introduce by one dependencies and you don't lock the version ? Then the user will use the latest version of the deps and have a compilation error.

By locking the version, we make sure if the project build on our system then it will build on any other machine too. 

I am sorry that you had problems when using a Fable template and from what you said your problem was not about using an old version of Fable but the template build system being broken. It's not the same thing.

I will try to take time and send a PR to the template :) :)

**Comment by bilkusg** [comment]
Thanks. I do understand that the initial issue I mentioned related to the template being broken, and indeed to the paket issue that this thread is about. 

But my later point is that if you are coming to fable for the first time, and are pointed, by fable's own readme files, towards a template which installs quite old versions of the software, then you are going to have a less-than-ideal introduction to the system, and may well be discouraged.

I'm not saying remove paket.lock from your templates. I'm saying, document in the readme file the version of fable that that template was built for, and on the fable website the version of fable which is considered 'current', and warn people that if those two are different, you may be better off not using that template for a new project.

Obviously it's possible to work this out for oneself once one realises the issue, but only after wasting a lot of time.

All I'm suggesting is a couple of lines of text in readmes and the website!

**Comment by alfonsogarciacaro** [comment]
The fable-templates repo has been archived and from now we will recommend people to start from examples or check the SAFE template. Unfortunately other templates maintained/published by other people are outside of our control :/
