### ISSUE TITLE
Parcel support?

### ISSUE THREAD

**Issue by baronfel** [fable-compiler/Fable#1364]
### Description

Should Fable support the Parcel bundler?

I was looking at Parcel (a hopefully zero-conf bundler for JS) and noticed that they advertise out-of-the-box compatibility with various transpilers including Reason/Bucklescript. I looked at the PR and it didn't look too nuts.

Is this something that might be of interest?

https://github.com/parcel-bundler/parcel/pull/342/files

**Comment by MangelMaxime** [comment]
There this plugin: https://github.com/slogsdon/parcel-plugin-fable

But i never used Parcel, I am not sure the zero-conf bundler could work. When I look at my different project I always have some special case to handle. But could be worth investigating for new users

**Comment by alfonsogarciacaro** [comment]
Yes, the plugin linked above is working, at least for simple cases. It's interesting because you can reference your .fsproj directly from HTML and Parcel can load the Fable plugin directly from package.json. However, there are a few things needed for a good dev experience in watch compilations that fable-loader (Webpack) does: like setting which files depend on others or making errored files non-cacheable. I couldn't find any documentation about writing plugins for Parcel so I don't know how to solve those /shrug

**Comment by baronfel** [comment]
I should have known you all would already know about it :D Thanks for the status update.

**Comment by alfonsogarciacaro** [comment]
Perfect, I'll close the issue for now. Please feel free to reopen should you have any other question :+1:
