### ISSUE TITLE
Use the WarningsAsErrors-Property of MSBuild

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#1398]
### Description

The `WarningsAsErrors`-Property is currently ignored by Fable. @nojaf asked about that on Gitter yesterday. He wanted to make the compilation fail on incomplete pattern matches.

### Repro code

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--
    Warning FS0025: Incomplete pattern matches on this expression.
    -->
    <WarningsAsErrors>FS0025</WarningsAsErrors>
  </PropertyGroup>
</Project>
```

### Expected and actual results

Fable should fail on a project with this setting, just as `dotnet build` does. But we currently generate a warning instead of an error.

### Related information

* Fable version (`dotnet fable --version`): 1.3.16

**Comment by alfonsogarciacaro** [comment]
Thanks for the detailed report @inosik. It shouldn't be difficult to do this. I'd prefer to do it in `dev2.0` branch because it has already diverged a lot with master and probably I will have to merge the changes manually checking the commits one by one.

Maybe you or someone else could send a PR. I think the necessary steps are:

1 - Read `WarningsAsErrors` [from MSBuild properties](https://github.com/fable-compiler/Fable/blob/467c56dafee68df47c35f63bddfcb773c4a04dfc/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs#L188-L189) and add it as an option to FableCompiler object.
2 - When adding a warning and the tag is `FSHARP` (not `FABLE`), [replace it with an error](https://github.com/fable-compiler/Fable/blob/467c56dafee68df47c35f63bddfcb773c4a04dfc/src/dotnet/Fable.Compiler/Transforms/State.fs#L104-L109) if the option is set.

**Comment by inosik** [comment]
> I'd prefer to do it in dev2.0 branch

Sure.

> Maybe you or someone else could send a PR?

I can look into that 👍 

1. We should already get all the properties from Dotnet.ProjInfo, but most of them seem to get lost somewhere. I'll look closer at the Project Cracker.

2. We don't have to do anything special. If we pass the `--warnaserror:FS0025` option to the FCS, it will turn the warning to an error and Fable will report it correctly. I already tried that yesterday real quick by simply appending the option to the `OtherOptions` array here:

    https://github.com/fable-compiler/Fable/blob/69dc66a1c62e4a02b7a85a2d933f0ddb5ed45f7f/src/dotnet/dotnet-fable/StateUtil.fs#L101

**Comment by inosik** [comment]
[The `ProjectCracker.fullCrack` function](https://github.com/fable-compiler/Fable/blob/2b3d7823699e41a4c523a956ddfb3cbf4d51200e/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs#L184) filters most of the options.

**Comment by alfonsogarciacaro** [comment]
Ah, yeah. That's why I linked in my first comment the line where you can get the options :)

**Comment by inosik** [comment]
See #1402.

**Comment by inosik** [comment]
We should finally add some docs about this and close this issue 😄

**Comment by alfonsogarciacaro** [comment]
You're right! Would it be OK for you to send a quick PR? I guess an entry [in the FAQ](https://github.com/fable-compiler/Fable/blob/master/docs/FAQ.md) should work for now.

**Comment by inosik** [comment]
See #1591.
