### ISSUE TITLE
dev2.0 cannot implement ToString for records and unions

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1425]
- ~~error FABLE: Current version cannot implement ToString for records and unions~~ Fixed
- ~~error FABLE: Cannot type test: interfaces, records or unions~~ Very rare

Opening a discussion to brainstorm about it.

**Comment by ncave** [comment]
@alfonsogarciacaro I'm probably not getting something, but what's wrong with just treating override members (on records and unions) as regular members (that just generate static module functions)?

**Comment by alfonsogarciacaro** [comment]
Thanks for opening the issue @ncave. I've been also thinking about it the last days, so it's good to open a thread for discussion before starting to implement anything.

#### About overrides being implemented in the prototype

There are two reasons for this: first overrides are implemented in a child classes but may be called from the parent class, this makes it impossible to locate the implementation at compile time. For example:

```fsharp
[<AbstractClass>]
type Parent() =
    abstract Add: int * int -> int

type Child() =
    inherit Parent()
    override __.Add(x, y) = x + y

let test(x: Parent) =
    x.Add(2,2)

test(Child() :> Parent) 
```

I have no way to know `x.Add(2,2)` corresponds to the implementation in `Child` class when traversing the AST. In fact, the entity given in `.ToString` calls is System.Object, not the implementing type. It also happens this behavior still allows inheriting JS classes from F# (like React components).

The second reason is `.ToString` as well as `.Equals` and `.Compare` are called by fable-core at runtime and attaching the methods to the prototype makes it easier to locate them (I'm doing something similar with `IEnumerable` implementation).

A **possible solution** would be to detect at compile time which records and unions implementing `.ToString` or have custom equality/comparison and in those cases compile them as JS classes as in Fable 1. This should be possible because in Fable 2 we're minimizing the assumptions about the implementation at runtime (although there're still some): by using F# in fable-core, moving JSON serialization to a external library, etc. In fact, we could have different representations depending on the compilation mode (e.g. in development union cases could include the case name while in production they may only need the tag number).

#### About type testing with interfaces, records or unions

This is more difficult. For interfaces we could attach the name directly to the object (I'm doing it for [F# custom exceptions](https://github.com/fable-compiler/Fable/blob/f377905265857d7c47ff4f557093f1211fd2ba8a/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L831-L835), but I wouldn't do it for records and unions if they don't have a prototype. Because this is agains the purpose of making the bundle size smaller.

BTW, have you seen the problem with type testing in FCS? I think I made a quick check some time ago, and all the type tests seemed to belong to full-fledge classes.

**Comment by alfonsogarciacaro** [comment]
After sleeping on this, maybe we don't need to marry the lightweight types. Now that we have some test projects [like fulma-demo](https://github.com/MangelMaxime/fulma-demo/pull/5) we can try outputting classes like before and see how much the bundle size changes. By removing the reflection and maybe putting the common methods (`Equals`, `CompareTo`) in a parent type we don't need to output so much extra code (we also save the field names every time we instantiate a record). And it's possible that using types gives the JS engine more opportunities to optimize the code.

**Comment by ncave** [comment]
@alfonsogarciacaro I added ToString for light-weight records/unions , see #1427.
Obviously it's not going to cover everything, but should work in most cases, and is better than nothing.
Something similar can probably be done for Equals, GetHashCode and CompareTo, to cover the common case of CustomEquality and/or CustomComparizon.

**Comment by ncave** [comment]
Already implemented, closing.
