### ISSUE TITLE
(dev2.0) Cannot type test any exception

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1428]
```
module App

let length xs =
    try xs |> Array.length
    with :? System.NullReferenceException -> 0

[<EntryPoint>]
let main argv =
    length [| 1; 2; 3 |]
```
error FABLE: Cannot type test: System.NullReferenceException

**Comment by alfonsogarciacaro** [comment]
This is in the `Replacements.tryReplaceEntity` method, which just replaces any [class ending with "Exception"](https://github.com/fable-compiler/Fable/blob/2cd894d09a796a0ca805fe9326b9d7c28a210242/src/dotnet/Fable.Compiler/Replacements.fs#L2631-L2632) with a JS Error reference. I don't remember exactly the route now, but we're reaching there when [calling `makeNonGenTypeRef` from `makeTypeTest`](https://github.com/fable-compiler/Fable/blob/b1659e2c809522fd73538c7e098039b49938028f/src/dotnet/Fable.Core/AST/AST.Fable.Util.fs#L348).

In Fable2, the implementation of type testing has been moved to Fable2Babel (`transformTypeTest`). We should add a `tryReplaceEntity` method to Replacements, but unfortunately we cannot call it from `FSharp2Fable.Util.tryEntityRef` because Replacements.fs comes after FSharp2Fable.fs and the method is receiving `ICompiler` not `IFableCompiler`. So probably in `Fable2Babel.transformTypeTest` we need to call `Replacements.tryReplaceEntity` if [`tryEntityRefMaybeImported` returns None](https://github.com/fable-compiler/Fable/blob/dev2.0/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L842).

**Comment by alfonsogarciacaro** [comment]
I already [did it in the `dev2.0-types` branch](https://github.com/fable-compiler/Fable/blob/ad08f8d97d5c39d63ffe9e6fd179670b17ce13a9/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L835-L840) :)

BTW, atm in Fable 2 it's not possible to check the original type of an object casted to an interface (because this operation creates a new object/façade with the interface methods), nor it's possible to cast an interface back to the original type. However, the interface objects are keeping a reference to the original object, so it shouldn't be difficult to add these features (testing for original type after interface casting and casting back). Do you think you're going to need them?

Another thing we need to discuss for the REPL is about deflating (this has also been removed in Fable 2) when sending the generated Babel AST with F#/Fable types to JS Babel. But we probably need another thread for that :)

**Comment by ncave** [comment]
@alfonsogarciacaro No, I don't see any errors related to interface casting in the repl, I'll open an issue with the outstanding errors (not that many).

**Comment by ncave** [comment]
Closing as fixed.

**Comment by alfonsogarciacaro** [comment]
I've been thinking about this, and it's probably not very sound to type test any exception in the same way, so in the latest I'm adding a warning (not an error) and evaluating to false if you type test against an unknown exception type. This should fall through to the last branch dealing with general exceptions, what do you think?

Example:

```fsharp
let test() =
    try
       ...
    with
    | :? FileNotFoundException as ex -> ...  // This evals to false
    | ex -> printfn "%s" ex.Message          // This will be true
```
