### ISSUE TITLE
(dev2.0) Inherited type constructor issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1436]
This is compiling just fine with the master branch, but not in dev2.0:
```
open System.Collections.Generic

type ConcurrentDictionary<'TKey, 'TValue when 'TKey: equality> =
    inherit Dictionary<'TKey, 'TValue>
    new () = { inherit Dictionary<'TKey, 'TValue>() }
    new (comparer: IEqualityComparer<'TKey>) = { inherit Dictionary<'TKey, 'TValue>(comparer) }
    member x.TryAdd (key:'TKey, value:'TValue) = x.[key] <- value; true
```
Here is the result, the constructors are messed up, the return is not in the right place:
```
import { tryGetValue, comparerFromEqualityComparer } from "./fable-core.2.0.0-alpha-020/Util";
import { createMutable } from "./fable-core.2.0.0-alpha-020/Map";
export function ConcurrentDictionary$00602$$$$002Ector() {
  new Map([]);
  return new ConcurrentDictionary$00602();
}
export function ConcurrentDictionary$00602$$$$002Ector$$1(comparer) {
  createMutable([], comparerFromEqualityComparer(comparer));
  return new ConcurrentDictionary$00602();
}
export function ConcurrentDictionary$00602$$TryAdd(x, key, value) {
  x.set(key, value);
  return true;
}
```

**Comment by alfonsogarciacaro** [comment]
You're rising the bar too high here @ncave. I didn't even know this syntax was possible in F# ;)

There're two tricky things here:

- Classes without implicit constructor. I thought all classes needed an implicit constructor in F#. However, I've been checking the AST of your example and it should be possible to accept it. Some code refactoring is needed though because I wasn't expecting this case. [I already started it but it make take a bit longer](https://github.com/fable-compiler/Fable/commit/93b692f7f03b52dc90658b25829960593e041766).

- Inheriting from a JS type (`Map` in this case). [Extending JS types has complications.](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work) And so far I was only covering the case for Exceptions (JS Errors). In the commit linked below I've extended this other types. However `Dictionary` has an extra complication because right now we're compiling it in two different ways: a) if the key type has equality compatible with JS (string, number) we use the native `Map`, b) if not, [we disguise a F# Map as a mutable dictionary]() to keep the full semantics.

Out of curiosity, is this code part now of FCS? I guess it wasn't before because I don't think Fable 1 can compile this correctly either.

**Comment by ncave** [comment]
@alfonsogarciacaro Not raising the bar higher than what the almighty Fable 1.3.7 already can do :)
Yes, this code has been part of FCS Fable for more than a year, and it works just fine.
We don't really need to add support for that right now, I can obviously rewrite it with composition instead of inheritance, it's just an example of a difference between Fable 1 and 2.

**Comment by alfonsogarciacaro** [comment]
Hmm, the REPL gives me something like this:

```js
export class ConcurrentDictionary extends Map {
  static [".ctor_0"]() {
    new Map();
    return new ConcurrentDictionary();
  }

  static [".ctor_1"](comparer) {
    create(null, fromEqualityComparer(comparer));
    return new ConcurrentDictionary();
  }

  TryAdd(key, value) {
    this.set(key, value);
    return true;
  }
}
```

Probably this is working due to a happy coincidence of not compiling to ES5, using a JS engine that accepts inheritance from native types with classes, and the autogeneration of the class constructor. But the secondary constructors look faulty, and this will definitely not work with a custom comparer :/

**Comment by alfonsogarciacaro** [comment]
Ok, I've enabled classes without primary constructors and also inheriting from `Dictionary`. However, generating the auto constructor clashes with the mechanism designed to allow inheritance from different constructors (not possible with JS classes nor in Fable 1), so for now I'm throwing an error if you try to inherit a class without a primary constructor.

I've also had problems to call base constructor in non-primary constructors, and because this seems to be very rare in F# I've just disabled it too. Which basically means the syntax above is not yet supported but, hey, at least now you have an error at compile time ;)

I can offer you this which should be working with latest `dev2.0`:

```fsharp
type ConcurrentDictionary<'TKey, 'TValue when 'TKey: equality>(comparer: IEqualityComparer<'TKey>) =
    inherit Dictionary<'TKey, 'TValue>(comparer)
    new () =
        ConcurrentDictionary
            { new IEqualityComparer<'TKey> with
                member __.GetHashCode(x) = x.GetHashCode()
                member __.Equals(x, y) = x.Equals(y) }
    member x.TryAdd (key:'TKey, value:'TValue) = x.[key] <- value; true
```

Would it be possible to use this code for now?

**Comment by Alxandr** [comment]
@alfonsogarciacaro Yous a suggestion, but could you not rewrite constructors (maybe only when there are more) to something like this:

```fs
// Note in the output that there is nothing special about implicit constructors
type Person(name: string, age: int) =
  new (name: string) = Person (name, -1)
  ...
```

```js
// cheating with ?? syntax for brievety. Should be an actual undefined check.
function Person(__ctor_id, ...args) {
  switch (__ctor_id) {
    case 1: return Person$$ctor_1.apply(this, args) ?? this;
    case 2: return Person$$ctor_2.apply(this, args) ?? this;
    default: throw new Error("invalid ctor id");
  }
}

function Person$$ctor_1(name, age) {
  this.name = name;
  this.age = age;
}

function Person$$ctor_2(name) {
  return Person$$ctor_1(name, -1);
  // or, if it's simpler this could even be
  return Person.apply(this, [1, name, -1])
}
```

**Comment by alfonsogarciacaro** [comment]
Thanks for the suggestion @Alxandr. Not sure, I'd have to check. Unfortunately your sample is missing the edge cases the current implementation doesn't cover, so we don't know if it's a good replacement. If you can write JS that fulfills the following conditions we can consider the proposal:

- Three layers of type inheritance: A > B > C
- Type B doesn't have implicit constructor in F#
- Type B has two or more constructors that call different parent constructors (A) or the same constructor with different arguments
- Type C can inherit from any constructor in B
- Any instantiation successfully passes type tests (e.g. in `let c = C()` c is of type C, B and A) no matter which constructor has been used.

**Comment by Alxandr** [comment]
@alfonsogarciacaro before I tackle that list let me get one thing clear: The resulting constructor should be callable from JS? In that case, which one? Take the following example for instance:

```fsharp
type Person =
  val name: string option
  val age: int option

  new (name: string option, age: int option) = { name = name; age = age }
  new (name: string) = { name = Some name; age = None }
  new () = { name = None; age = None }
```

Now, I call in js:

```js
const p = new Person('name');
```

How on earth is this supposed to work? None of these constructors have any indication that they are "primary". They are all equally valid. IMHO, if you want a construcor callable by JS, it would have to be explicit somehow. Though, I think the better solution is haveing factory functions for JS, like this:

```fsharp
[<Export>]
let empty = Person ()

[<Export>]
let withName n = Person n

[<Export>]
let withNameAndAge n a = Person n a
```

**Comment by alfonsogarciacaro** [comment]
Your code above will generate this JS:

```js
function Person(arg1, arg2) {
  this.name = arg1;
  this.age = arg2;
}

function Person$$$$002Ector(name, age) {
  return new Person(name, age);
}

function Person$$$$002Ector$$1(name$$1) {
  return new Person(name$$1, null);
}

function Person$$$$002Ector$$2() {
  return new Person(null, null);
}

const p = exports.p = Person$$$$002Ector$$2();
```

In this case, Fable has generated the implicit constructor because there was none. The other constructors will call it. This works but causes problems when inheriting `Person` so for now I'm raising an error message if you try to do it. In the more general case where the class has an implicit constructor, the generated code looks like:

```fsharp
type Person private (name: string option, age: int option) =
    new (name: string) = Person(Some name, None)
    new (age: int) = Person(None, Some age)
    new () = Person(None, None)
    member __.Name = name
    member __.Age = age

type Child() =
    inherit Person(5) 

let c = new Child() |> box
printfn "Is Person: %b. Is Child: %b" (c :? Person) (c :? Child)
```

```js
function Person(name, age) {
  this.name = name;
  this.age = age;
}

function Person$$$$002Ector(name, age) {
  return this != null ? Person.call(this, name, age) : new Person(name, age);
}

function Person$$$$002Ector$$1(name$$1) {
  return Person$$$$002Ector.call(this, name$$1, null);
}

function Person$$$$002Ector$$2(age$$1) {
  return Person$$$$002Ector.call(this, null, age$$1);
}

function Person$$$$002Ector$$3() {
  return Person$$$$002Ector.call(this, null, null);
}

function Person$$get_Name(__) {
  return __.name;
}

function Person$$get_Age(__$$1) {
  return __$$1.age;
}

function Child() {
  Person$$$$002Ector$$2.call(this, 5);
}

(0, _Types.inherits)(Child, Person);

function Child$$$$002Ector() {
  return this != null ? Child.call(this) : new Child();
}

const c = exports.c = Child$$$$002Ector();
(0, _String.toConsole)((0, _String.printf)("Is Person: %b. Is Child: %b"))(c instanceof Person)(c instanceof Child);
```

Note:

- Fable doesn't actually use `new` when instantiating the Child. But it's still important to have a JS function constructor for type testing.
- Secondary and inheriting constructors always call the sibling/base constructor using `.call.(this, args)`.
- Fable has generated actually two functions for the Person implicit constructor: the actual JS function constructor `Person` and the exposed constructor whose body is `return this != null ? Person.call(this, name, age) : new Person(name, age);`. This means that when the constructor is called directly or from a sibling constructor a new object is created, but when it's called from a derived class, it just initializes `this`.

**Comment by Alxandr** [comment]
You just broke your previous requirements though. You explicitly required that `B` should not have a implicit constructor in F#, yet now you're saying that all types need implicit constructors (whether or not they are auto-generated by Fable has little impact on that).

**Comment by Alxandr** [comment]
@alfonsogarciacaro there is still the limitation on having to call the right base constructor, no? Or can you do this in Fable 2?

```fsharp
type Person (name: string, age: int option) =
  new (name: string) = Person (name, None)
  
  member __.Name = name
  member __.Age = age

type Ninja (name: string) =
  inherit Person (name) // nobody knows the age of ninjas!
```

**Comment by ncave** [comment]
Closing as the suggested alternative seems to work.
