### ISSUE TITLE
Include files from all projects in output from fsproj

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1439]
### Description

*Note: this issue was renamed/modified due to feedback. Original description bellow.*

Currently, when adding dependencies to a Fable project, if you don't explicitly use anything from that project, it does not get compiled. I suggest that we modify fable such that the last file from all fsproj files (not just the last one) get's imported from the "entry-point" file you get when asking fable to compile a fsproj file. For instance, currently if I have 3 projects; `ProjA`, `ProjB` and `ProjC`, where `ProjA` is my app and it has dependency on `ProjB` and `ProjC`, when I compile `ProjA.fsproj` I get the following:

```js
export * from 'path/to/last/file/in/ProjA.fs';
```

My suggestion is that this is change to either emit includes for all files (shouldn't really matter cause tree shaking, order should likewise not matter) like this:

```js
import 'ProjA/file1.fs';
import 'ProjA/file2.fs';
import 'ProjB/file1.fs';
import 'ProjB/file2.fs';
import 'ProjC/file1.fs';
import 'ProjC/file2.fs';
export * from 'ProjA/file2.fs';
```

Either that, or we just import the last files from each project like this:

```js
import 'ProjB/file2.fs';
import 'ProjC/file2.fs';
export * from 'ProjA/file2.fs';
```

I think the first one is actually the one that maps best to how F# compilation works. And as long as Fable 2 does no longer have a global variable where all the types are put into, tree shaking should remove any file that doesn't do anything. This is likely to lead to less surprices in the long run I would think. As for only including the last file, that would also solve the technical issue I'm having nicely, but it would be something users would need to know about how works.

### Old Description

I'm building up a system of abstractions I use to write CLI applications in F# that run on both `dotnet` and `node` (node version being built by fable). One of the issues I've encountered during this is that I have a "plugin" model for adding new "system services" (like a service that is able to read environment variables or whatever, which is different on both platforms). So currently I have something like this for fable (simplified to show the issue):

```f#
// registry.fs - core project
module Registry

let private registered = Dictionary<string, obj> ()

let register name service =
  registered.Add (name, service)

let get name =
  unbox registered.[name]

// env.fs - env project
module Env =

type EnvService () =
  interface IEnv =
    member __.Get name = jsNative

do Registry.register "env" (EnvService ())

// cli.fs - client project (should be downstream, consumer of my libraries)
let env: IEnv = Registry.get "env"
```

This currently does not work. The issue is that when this get's compiled, Fable does not import the file `env.fs` at all, so in the JS the content is not there. It's not just that it's tree-shaked, rollup never get's told to load the file. The solution I'm using currently is this:

```f#
// cli.fs

do importSideEffects "../../../src/fable/YoloDev.ISystem.Env.Fable/env.fs"
let env: IEnv = Registry.get "env"
```

This is not only ugly, but it also means that I can't use this downstream. If `YoloDev.ISystem.Env.Fable` was installed form Paket, the path would be somewhere on my system, and providing a import to it manually is just not a viable solution.

### Proposed solution

I propose an attribute, something like this:

```fsharp
// env.fs

module Env =

type EnvService () =
  interface IEnv =
    member __.Get name = jsNative

[<ModuleSideEffects>]
let register () =
  Registry.register "env" (EnvService ())
```

where the attribute can be applied to `unit -> unit` functions. Then, the output from "compiling" the fsproj would change to this:

```js
import { register } from 'env.fs';
// import other ModuleSideEffects

register();
// call other side-effects

export * from 'lastFileInCompilation.fs';
```

Some important and should-be documented constraits with this attribute:

1. The module side effect functions cannot depend on other side effects to be run, as they should be considered arbitrary in order (either that, or they are ordered by the order of files included in the compilation).
2. Module side effect functions cannot be defined in the last file of the compilation. Either that, or the `export * from` should be changed to `export { all of the things except side-effect functions} from` (which IMHO might be a good idea regardless).

And if anyone has any better suggestion to how to solve this problem, I'm all ear.

**Comment by alfonsogarciacaro** [comment]
I acknowledge this is a problem in Fable as the behaviour is different from standard F#. The solution is complicated because there's no information in the AST about which modules are open and we're actually relying on this for tree shaking of big libraries. So I usually respond this is a feature of the JS target that we need to understand and live with.

Your proposal is interesting, but I'm not sure if it can bring many benefits:

- Instead of fixing the divergence with .NET F# it introduces a new Fable-only attribute, something I'm trying to avoid for Fable 2 (I'm deprecating attributes like PassGenerics, Pojo...).
- Apart from the work of implementing the feature in Fable, it also imposes cognitive overload on the user: they have to remember to use it (the compiler won't tell anything if they forget) and know about the constraints you listed.
- If you want to make this work both in .NET and Node, why don't use the already-available cross-platform solution? Just call the registers from the `main` function of your application. This is more deterministic and doesn't require introducing any new feature in the compiler.

**Comment by alfonsogarciacaro** [comment]
That makes sense. If you want to open an issue about this we can discuss the feature then. There're some other things needed for Fable 2 release so this cannot be a priority at the moment, but I can guide you if you want to try to send a PR.

**Comment by Alxandr** [comment]
@alfonsogarciacaro I update the issue with new title and description as it was basically morphed into it. If option 1 is acceptable (it should definitely be the simplest to implement; just loop through all included files and spew out an import) I can probably look at doing a PR for it. I'm guessing the selective one is a bit more involved, but if you think it's fairly straightforward I'm willing to help, I just have limited time (as we all do 😞) 🙂

**Comment by alfonsogarciacaro** [comment]
Ah, sorry! We're talking in several issues and didn't notice this was your own one 😅 Unfortunately, there are very few straightforward things when building a compiler (that is actually used). I wouldn't go for option 1, as it will impose an increase in compile time for many users who don't need this feature. I have to think of option 2 and collect some feedback. Some people could argue our aim shouldn't be to make side effects easier but rather the contrary.

I'm still wondering if [there's really no easier solution to this](https://en.wikipedia.org/wiki/Occam%27s_razor). Users of your library will have to reference something from your code at some point (say `Register` could be a static class with a static constructor), and you can use that opportunity to make the appropriate initializations.

**Comment by Alxandr** [comment]
@alfonsogarciacaro No they actually don't. My users only calls an interface, defined in another project. The registry is basically a really simple DI container. A user has to go explicitly out of his way to call anything from the library with the type to be registered (which is what I currently do as a workaround).

My main issue with moving the registration call to the users is the following scenario:

1. You're making an app, that depends on YoloDev.ISystem.ColordConsole
2. YoloDev.ISystem.ColordConsole depends on YoloDev.ISystem.Env
3. You now have to manually register the EnvService.

Also, with regards to just importing all of the referenced files, I don't really think it will be all that hard. As far as I can see, it's one place, where you have the array of files available: https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/Fable2Babel.fs#L1265

I still think this is the better solution. Yes, it will increase build time, but not when using file watching. And it causes fewer surprises because this is more like how normal .NET compilation works.

**Comment by alfonsogarciacaro** [comment]
Well, other users may have different opinions about increasing the build time ;) But now that I think about it, actually we already have a similar option (`allFiles`) for [fable-splitter](https://www.npmjs.com/package/fable-splitter) that was included to compile unit tests. So it may make sense to include it in the fable-loader too. It is just [a single file](https://github.com/fable-compiler/Fable/blob/bbe343f007a317c5b92a1c98b2f14c00cf870493/src/js/fable-loader/index.js) and it's easy to create a custom version (just reference it from webpack.config.js instead of the fable-loader).

In the JSON returned for [the .fsproj, Fable will include the list of files in a `.sourceFiles` field](https://github.com/fable-compiler/Fable/blob/bbe343f007a317c5b92a1c98b2f14c00cf870493/src/js/fable-splitter/src/index.ts#L182-L184). It shouldn't be too difficult to generate the JS code you suggest instead of [interpreting the Babel AST](https://github.com/fable-compiler/Fable/blob/bbe343f007a317c5b92a1c98b2f14c00cf870493/src/js/fable-loader/index.js#L96-L98),

**Comment by Alxandr** [comment]
I've already added it to the compiler (v1 mind you) as a flag (similar to the ones for using typed numeric arrays). Not tested it yet, but I've not broken any unit tests at least. I'm not sure how I'm supposed to test it though :-/.

**Comment by Alxandr** [comment]
@alfonsogarciacaro please take a look at this: https://github.com/Alxandr/Fable/commit/5bfa4587ea8d740bc903db953a3a34a838eb40c1

I've not cared about code style or any such things (I used the `seq` builder cause it was easy and quick for instance), but it should illustrate the functionality nonetheless. It's a small code change that's opt-in. Would something like this be acceptable?

**Comment by alfonsogarciacaro** [comment]
Hmm, I still think this probably should be handled on the JS client (same way as it's for fable-splitter). Also, at this point I'd rather not add new features to Fable 1 as most of the development is being done in `dev2.0` branch.

**Comment by Alxandr** [comment]
I don't think it's right to handle this in the JS client, that would require modifying the JS from fable after it's compiled (to insert the needed `include` statements). I want rollup and webpack (and any other bundler that somebody might want to make a fable plugin for) to support this, not to mention that doing it in JS is likely to be way more complicated, because it would likely require changes to the fable server regardless. There is no good way in JS (as far as I know) to ask for "all sources involved in compilation". That information is computed by fable (using msbuild), and having to recreate that in JS seems to be a really inefficient way of going about things given that all the information you need is readily available in Fable already. Just look at the commit I made in my previous post, illustrating how small of a change this would really be to add to fable itself, and in likelyhood getting "only the last file in each project" would only require a bit more code.

And wrt. dev2.0, I can probably make the same change against that branch.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing this as we want to prioritize tree shaking in Fable even at the expense of some confusion like this. I understand it's annoying and unexpected from dotnet point of view, but I still prefer manual registration of services because this way users are more conscious of what they're paying for when using a Fable library.
