### ISSUE TITLE
.fable folder doesn't keep up to date with local packages

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#1514]
### Description

I might be pushing the expectations, but working with a local package dependency (for example, testing unpublished Fable.Elmish.Debugger changes in a sample app) the new `.fable` (documented somewhere?) folder does not keep up with the package changes. To emphasize, the package is unpublished and is the same version between the runs, but has updated content.

### Repro code

* build a dependency package, reference the package location for paket in the sample app.
   sidetrack: added a local directory as a source
* build the sample app.
* update the dependency and build a new package.
* remove the existing version from `~/.nuget/packages`
* run restore in the sample,
  confirm that the new version is now in `~/.nuget/packages`
* run fable compiler on the sample

### Expected and actual results

Expected: `.fable` files to update to the latest package content.
Actual: previous dependency code is used.
Workaround: delete `.fable` folder, run the build again

### Related information
* Fable version (`dotnet fable --version`): 2.0.0-beta-001
* Operating system: OSX

**Comment by alfonsogarciacaro** [comment]
Fable 2 is copying files from nuget packages in a local `.fable` folder to avoid the problem we had before that some dependencies couldn't be resolved unless users were very careful in their webpack configuration. But you're right, I also had frequently the issue of dependencies not updating during development. There are two solutions for this at the moment:

- Remove the .fable folder: Yes, very imaginative, and you already noticed that.
- Use `--replace-files` argument: This is not documented either but I also added it to quickly test changes in external packages. For example, in the case of the debugger I was doing something like:

```bash
dotnet fable webpack-dev-server --verbose --replace-files \
RemoteDev.fs:../debugger/Fable.Import.RemoteDev.fs,\
debugger.fs:../debugger/debugger.fs
```

As the `.fable` folder uses the version number to detect changes, I cannot think at the moment of an easy way to detect if the package content has been updated even if the version is the same. But I agree we need an opt-in solution to ease development. `--replace-files` is useful but it has some problems (it's verbose and it has issues with JS dependencies too if the files are in a different folder). Maybe we can add a `--replace-package` argument that uses the specified directory for the source files instead of those in the nuget package, and always copy the latest files to the .fable folder (although this means changes won't trigger watch compilations), what do you think?

**Comment by alfonsogarciacaro** [comment]
I added the `--force-pgks` compiler option to force a new copy of package sources when restarting the compiler.

**Comment by et1975** [comment]
thank you!
