### ISSUE TITLE
Strange behaviour with unit -> unit members

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/Fable#1516]
### Description

Ran into some strange behaviour with `unit -> unit` members.
There is a third party lib, and one function - that does return an object - had the type definition of `unit -> unit`. Fable "decided" that if the type definition is right, the return value should be `null`, and passed literal `null` to other calls instead of passing the actual value. But only if this is in a function (discovered this when tried to reproduce in the REPL).

Sidenote: the root cause for me was an error in the type definition, so not really likely that someone runs into this, because you would not assign `unit` to a value...

```fsharp
// types ommited
let boringHello = boringObj.hello()
printfn "In function printf: %A" boringHello
JS.console.log("In function console.log:", boringHello)
// this is just for demonstration for other calls
let json = toJson (123, boringHello)
```

Compiles to this, if this is in a function

```javascript
const boringHello = boringObj.hello();
toConsole(printf("In function printf: %A"))();
console.log("In function console.log:", null);
const json = toJson([123, null]);
```

And this is what you get, if this is not in a function (this, or an error is what I would expect):

```javascript
export const boringHello = boringObj.hello();
toConsole(printf("Direct printf: %A"))(boringHello);
console.log("Direct console.log:", boringHello);
export const directJson = toJson([123, boringHello]);
```

### Repro code
In the [REPL](http://fable.io/repl/#?code=open%20Fable.Core%0D%0Aopen%20Fable.Core.JsInterop%0D%0Aopen%20Fable.Import%0D%0A%0D%0A%0D%0Atype%20BoringType%20%3D%20%0D%0A%20%20%20%20abstract%20hello%3A%20unit%20-%3E%20unit%0D%0A%0D%0Alet%20%5B%3CGlobal(%22boringObj%22)%3E%5D%20boringObj%20%3A%20BoringType%20%3D%20jsNative%0D%0A%0D%0A%2F%2F%20this%20fails%3A%0D%0Alet%20doStuff%20%3D%20fun%20(x%3A%20BoringType)%20-%3E%0D%0A%20%20%20%20let%20boringHello%20%3D%20boringObj.hello()%0D%0A%20%20%20%20printfn%20%22In%20function%20printf%3A%20%25A%22%20boringHello%0D%0A%20%20%20%20JS.console.log(%22In%20function%20console.log%3A%22%2C%20boringHello)%0D%0A%20%20%20%20let%20json%20%3D%20toJson%20(123%2C%20boringHello)%0D%0A%20%20%20%20()%0D%0A%0D%0AdoStuff(boringObj)%0D%0A%0D%0A%2F%2F%20direct%20call%20works%3A%0D%0Alet%20boringHello%20%3D%20boringObj.hello()%0D%0A%2F%2F%20printfn%20%22boring%20hello%3A%20%25A%22%20boringHello%0D%0Aprintfn%20%22Direct%20printf%3A%20%25A%22%20boringHello%0D%0AJS.console.log(%22Direct%20console.log%3A%22%2C%20boringHello)%0D%0Alet%20directJson%20%3D%20toJson%20(123%2C%20boringHello)&html=%3Chtml%3E%3Cbody%3E%0D%0A%3Cscript%3E%0D%0A%20%20%20%20var%20boringObj%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20hello%3A%20function()%7B%20return%20%22I%20return%20something!%22%20%7D%0D%0A%20%20%20%20%7D%0D%0A%3C%2Fscript%3E%0D%0A%3C%2Fbody%3E%3C%2Fhtml%3E), [Repl2](http://fable.io/repl2/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQoksiKG2aAUgM4CSEALmFqAUdPMmrQLYjYMCQ-AwCe4KACFsASwgBzACriwUALxQCUbVETUGWOAGMGUABZgkSYAC4oAVwgzTAWgB8Dp4PwEUpgNoAPADi1ghwSAAUAEQIsgoA8ggAVtEAlG4AulBxWHLySclQdtJ5CsoSGsnUAHJwDDIAbng++AD0bVAMZjLUUABmcDJI1Da+YKYAJsAAygz2-f3qA45QkQAeJfFKKmlQ7lo6fjnbABKW1su5+YWoFlbAkWmH2iBlDP3Q0fQrECYywGgbzkHzsAFIAILRE5leTnB4vKCUGaoIyA6jAMjWeQxH79Rz-QFQNEQDFY4DyGzRAA0MPy8Osz3wOigHS6PT6vSgyXs+gG2CgkzAPHRBnqAOg-QFwG6zGJERGiOO1SJGgYwBoRMiAEYAEwAZlp1wUDOATJZT2E0zmC36kWNBRSTIIbMmMhwJnlVigAHdsABrUbjUwO01Xba3e7WS3tTrAxifKCxbbmC62KCQ6GhtMEeMfL4AEXdYE9ef64KhdJNOfwyNR6MxaGxMSLHtMJLJTYpVKNZzTTOObrbmugao1GOgOoNvdhprSQA&html=DwCwLgtgNgfMBGB7AJgTxgWAFDAM4GMAnASwAcxMsACGqgNwENCqkSA7AcwHl4ArKgLxUA3tlriqIAKZQoiAFxUAZgFc2+MMURsAFAEphVQlLArCbKgCIAkkZNmLuRBBMhinAIRePlqgF8xWgCcAHoCEnJKYBCkNDgQ8GgYIA)
### Expected and actual results

IMO either should work in both cases, or should throw / send a warning, since you are assigning `unit` to a value.

Fun addition: `printf` behaves differently in Fable 1 and 2! (does get called in repl1 "direct" case, but does not get called in repl2)

**Comment by alfonsogarciacaro** [comment]
I'm turning local unit values into `null` because sometimes these are references to the unit argument (in functions like `fun () -> ...`) which gets erased in the JS code. But you're right that it's confusing in cases like the one you describe. A possible solution would be to check if the value is an argument or not, but probably for now the easiest solution is to add a warning when a unit value is replaced as you suggest. I'll do it for the next beta release :+1:

**Comment by alfonsogarciacaro** [comment]
Fable 2.0.0-beta-002 includes the warning but I'm considering to make it only visible in verbose mode for the next release as it's generating some warnings that can be more confusing than helpful. Also, this is tricky to fix even if we didn't do the null replacement, because the compiler is making some assumptions when you use `unit`. For example in this case:

```fsharp
let boringHello (): unit = jsNative

let test() =
    let x = boringHello()
    x // Fable replaces x with null here

let y = test()
```

Even if we didn't replace `x`, Fable won't generate a return statement at that point because `test()` is inferred to be a void function. `y` would become `undefined` in JS anyways. So in general, we need to be careful with the signature of external functions (this is true for other types as well, not only unit) :)
