### ISSUE TITLE
[REPL2] printf doesn't compile with optimizations enabled

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1573]
__EDIT:__ it does compile, this seems to only be an issue in the editor?

--------------------
![grafik](https://user-images.githubusercontent.com/4236651/46004590-8e11a480-c0b3-11e8-9484-e257d5105227.png)

![grafik](https://user-images.githubusercontent.com/4236651/46004615-9b2e9380-c0b3-11e8-8bf4-b480bbad6e84.png)

![grafik](https://user-images.githubusercontent.com/4236651/46004629-a386ce80-c0b3-11e8-8399-8e3362ed5f20.png)

**Comment by 0x53A** [comment]
moved to https://github.com/fable-compiler/repl2/issues/31, sorry for the spam

**Comment by alfonsogarciacaro** [comment]
Yeah, that's why the "Optimize" function is experimental, it's still missing some replacements ;) I'm not sure if we will follow this path or just disable the option. It seems that many of the FCS optimizations are very focused on .NET and others (like inlining properties) don't have a big performance impact in the generated JS.

At this point it may be better to focus on Fable optimizations, what do you think @ncave?

**Comment by ncave** [comment]
@alfonsogarciacaro You can make the FCS optimization harder to find, if you think too many people are tripping over it. It would be nice to still be able to access it in some form, at least as a compiler option.

**Comment by MangelMaxime** [comment]
Yes let’s implement the Konami code 😜

**Comment by ncave** [comment]
@alfonsogarciacaro Let's keep it for now, I'll look into adding this replacement.

**Comment by ncave** [comment]
Fixed in #1574
