### ISSUE TITLE
Can't type tests interfaces in Fable 2

### ISSUE THREAD

**Issue by ed-ilyin** [fable-compiler/Fable#1580]
### Description

Can't match erased types in Fable 2.0.0 (worked in Fable 1).

### Repro code

repl2: https://goo.gl/owWjw5
```fsharp
open Fable.Import
open Fable.Core

type [<AllowNullLiteral>] TokenResponse =
    abstract tokenType: string with get, set
    abstract accessToken: string with get, set
type [<AllowNullLiteral>] ErrorResponse =
    abstract error: string with get, set
    abstract errorDescription: string with get, set
type AcquireTokenCallback =
    (JS.Error -> U2<TokenResponse, ErrorResponse> ->
        Result<TokenResponse,string>
    )

[<Import("AuthenticationContext", "adal-node")>]
let acquireToken: (AcquireTokenCallback -> unit) = jsNative

acquireToken <| fun err response ->
    match err, response with
        | null, U2.Case1 tr -> Ok tr
        | e, U2.Case2 er ->
            sprintf "AD token: %s: %s. %s: %s." e.name
                e.message er.error er.errorDescription
                |> Error
        | e, u ->
            sprintf "AD token: %s: %s. %A" e.name
                e.message
                u
                |> Error
```

### Expected and actual results

Expecting compilation without error (like in Fable 1).
Actually Fable 2 compiler gives error:
`error FABLE: Cannot type test: interface "Fable.Import.Adal.ErrorResponse"`

### Related information

* Fable version (`dotnet fable --version`): 2.0.0
* Operating system: 64bit Mac OS X 10.14 18A391

**Comment by alfonsogarciacaro** [comment]
Actually the problem here is not erased types, something like this is still compilable:

```fsharp
let foo (x: U2<int,string>) =
    match x with
    | U2.Case1 x -> printfn "Int %i" x
    | U2.Case2 x -> printfn "Str %s" x
```

The problem is the interface type `ErrorResponse`. Fable 2 is a bit more strict with type testing to prevent surprises at runtime. In Fable 1 was possible to test interfaces **but only for types declared in F#**, as Fable was adding the interface names in the reflection info. However, as interfaces are also used for types coming from JS (as in your case) this didn't work in all the cases, so type testing against interfaces is disallowed in Fable 2.

In your case, I'm afraid you'll have to use some unsafe casting to deal with the JS response:

```fsharp
acquireToken <| fun err response ->
    if isNull err then
        let tr: TokenResponse = unbox response
        Ok tr
    else
        let er: ErrorResponse = unbox response
        sprintf "AD token: %s: %s. %s: %s." err.name
            err.message er.error er.errorDescription
            |> Error
```

**Comment by ed-ilyin** [comment]
Thank you for clarification.

**Comment by whitetigle** [comment]
Same problem here with:

`error FABLE: Cannot type test: interface "JsonWebToken.JsonWebTokenError"`

```f#
type VerifyErrors =
    U3<JsonWebTokenError, NotBeforeError, TokenExpiredError>

module VerifyErrors =
   let isJsonWebTokenError (v: VerifyErrors) = match v with U3.Case1 _ -> true | _ -> false
```

or 

` error FABLE: Cannot type test: interface "Fable.Import.Node.Buffer.Buffer"`

```f#
type Secret =
    U4<string, Buffer, obj, obj>

module Secret =
    let isBuffer (v: Secret) = match v with U4.Case2 _ -> true | _ -> false
```

What would replace the `match`?

**Comment by MangelMaxime** [comment]
IMHO ts2fable should not generate the `Helpers` when it encounter `U2, U3, U4, etc.` because it can lead to subtle bugs and this is the reason why Fable 2 do not allow type check against interface. I think in the past we had the impression that the test were working were in fact it was checking nothing :)

I prefer to let the developper type it's API where needed. For example:

```fs
// This is just pseudo code so it's probably incorrect for the bindings
let buffer : Node.Buffer = Node.file.readSync("filePath") |> unbox
// The developer, decided to use the `Buffer` object and from here he can use it
// I think he should be able to remove the `unbox` by using `!^` so the compiler still got is back
```

The reason being, if the method return `U3<string, Node.Buffer, Node.Stream>` then at runtime all three cases are valid and depends on the usage you want to do.

------------------

And for JavaScript library that have an API to check the error type either by using [`instanceOf`](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json/Decode.fs#L30-L31) or another mechanism then it's the developer job to write the code (can be in an Fable.Helpers.MyLib or in the project directly).

In the case of `VerifyErrors` based on [the documentation](https://www.npmjs.com/package/jsonwebtoken#errors--codes), we can probably write something like that:

```fs
open Fable.Core
open Fable.Core.JsInterop

// Fake type to mimic the JsonWebToken API
type JsonWebTokenError = obj
type NotBeforeError = obj
type TokenExpiredError = obj

type VerifyErrors =
    U3<JsonWebTokenError, NotBeforeError, TokenExpiredError>

let (|JsonWebTokenError|NotBeforeError|TokenExpiredError|) (obj : VerifyErrors) : Choice<JsonWebTokenError, NotBeforeError, TokenExpiredError> = 
    match obj?name with
    | "JsonWebTokenError" -> JsonWebTokenError (unbox obj)
    | "NotBeforeError" -> NotBeforeError (unbox obj)
    | "TokenExpiredError" -> TokenExpiredError (unbox obj)
    | unkown -> failwithf "Unkown error type: `%s`" unkown

// Just create an error value for getting type intellisense
// Should be a real error instance
let error : VerifyErrors = unbox null

match error with
| JsonWebTokenError jsonWebTokenError -> printfn "jsonWebTokenError"
| NotBeforeError notBeforeError -> printfn "notBeforeError"
| TokenExpiredError tokenExpiredError -> printfn "tokenExpiredError"
```

**Comment by humhei** [comment]
```fsharp
open Fable.Import
open Fable.Core

type [<AllowNullLiteral>] TokenResponse =
    abstract tokenType: string with get, set
    abstract accessToken: string with get, set
type [<AllowNullLiteral>] ErrorResponse =
    abstract error: string with get, set
    abstract errorDescription: string with get, set
type AcquireTokenCallback =
    (JS.Error -> U2<TokenResponse, ErrorResponse> ->
        Result<TokenResponse,string>
    )

[<Import("AuthenticationContext", "adal-node")>]
let acquireToken: (AcquireTokenCallback -> unit) = jsNative

acquireToken <| fun err response ->
    match err, response with
        | null, U2.Case1 tr -> Ok tr
        | e, U2.Case2 er ->
            sprintf "AD token: %s: %s. %s: %s." e.name
                e.message er.error er.errorDescription
                |> Error
        | e, u ->
            sprintf "AD token: %s: %s. %A" e.name
                e.message
                u
                |> Error
```


I didn't test the codes, But i think it actually worked in Fable1


https://github.com/fable-compiler/ts2fable/blob/master/src/read.fs#L15
https://github.com/fable-compiler/ts2fable/blob/master/src/read.fs#L434


I am sorry but I think people more like the typed way 
But not the dynamic way 
As the solutions provided by @alfonsogarciacaro  @MangelMaxime 


> The problem is with ts2fable bindings we usually don't know if the type comes from a JS class or whether it's a plain JS object, so Fable doesn't know how to do the type testing. Is it possible to have a different strategy in your case to get the type of the error?


All all codes (Whether it from npm package or F#) they are finally compiled to js codes

So maybe a better typed solution exists?
