### ISSUE TITLE
Int64 regression: parsing negative numbers as positive ones 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1586]
### Description
Detected this while running integration tests on remoting against Fable 2.0.2 and confirmed in the REPL
the function `int64` parses negative numbers as without the negative sign 

### Repro code and current result

```fs
let a = int64 "5"
let b = int64 "-5"
printfn "%A" (a = 5L)   // true 
printfn "%A" (a = b)    // true 
printfn "%A" (b = -5L)  // false
```
### Expected 
```fs
let a = int64 "5"
let b = int64 "-5"
printfn "%A" (a = 5L)   // true
printfn "%A" (a = b)    // false
printfn "%A" (b = -5L)  // true
```
Please provide the expected and actual results.

### Related information

* Fable version (`dotnet fable --version`): 2.0.2 and Current REPL (2.0.0-beta-005)
* Operating system: Win 10

**Comment by alfonsogarciacaro** [comment]
Thanks for checking this @Zaid-Ajaj! @ncave while debugging it seems the problem comes [from this line](https://github.com/fable-compiler/Fable/blob/0afdad2f5e6b1a3f12bf2749aab8a608ac5c8314/src/js/fable-core/Long.js#L238) which takes the third group of the regex match returned by `isValid`. However this group removes the negative sign. The line comes [from this commit](https://github.com/fable-compiler/Fable/commit/fce0adeb4e9833de30d0a68e50ca9e91d3c24861), is it intended? Can we fix it somehow? Thanks!

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Confirmed that it is working now, thanks for the  fix! 

Quick question though, why was it sufficient to just update `dotnet-fable` to 2.0.3 and not `Fable.Core` too? Since there were changes made to the sources of `Long.ts` I expected that I would need to update Fable.Core but that wasn't needed and my library still depends on Fable.Core 2.0 does that meansif someone used `dotnet-fable` 2.0.2 to parse int64 with negative sign, their code would still fail or am I missing something obvious here?

**Comment by ncave** [comment]
@Zaid-Ajaj Confusing, right? Fable.Core.dll is just the main ("core" if you will) bindings package, separate and different than "fable-core" (which is the javascript BCL implementation, bundled with Fable 2.0.x).

**Comment by Zaid-Ajaj** [comment]
@ncave Thanks for the clarification! So if I understand correctly Fable.Core became *just* the binding and `dotnet-fable` now embeds the BCL implementation. I was still thinking in the Fable 0.7.x era (and I guess 1.3.x too) when Fable.Core was *the* BCL implementation and `dotnet-fable` applied the replacements, mappings etc.

However, this introduces the very small problem that libraries cannot pin a specifc `dotnet-fable` that they rely one. for example Fable.Remoting.Client depends on Fable.Core 2.0 but would fail parsing negative int64 if the user decides to use `dotnet-fable` v2.0.2 or an earlier version. am I correct?

**Comment by ncave** [comment]
@Zaid-Ajaj As far as I can remember (which is not *too* far), `fable-core` (the BCL) has always been separate and different from Fable.Core (the bindings), it's just that before it was distributed through `npm`, and now it's embedded in `dotnet-fable`.

So yes, because of that embedding, every time you compile your library with a different version of `dotnet-fable`, you will be bundling it with a (potentially) different version of the `fable-core` BCL. That's actually a feature, not a bug, in the sense that this way they're guaranteed to work together well (since `dotnet-fable` and `fable-core` are the same version and have been unit tested together).

**Comment by Zaid-Ajaj** [comment]
> in the sense that this way they're guaranteed to work together well (since dotnet-fable and fable-core are the same version and have been unit tested together).

@ncave That part I understood but the problem was more that a library author cannot *ensure* that the library is compiled against matching versions of `Fable.Core` and `dotnet-core`.  I can only pin the version of Fable.Core and *hope* that the user is using a matching version 

@alfonsogarciacaro I think I get it, it has been a while since I've looked into the internals of Fable. 

I don't think it is a big problem as the compiler isn't likely to update as often as libraries do, it is just a nice-to-jh As for the solution, I personally prefere not to pollute library code with compiler attributes, it is possible to add it in the `.fsproj` file a xml property?
```xml
<MinimumFableVersion>2.0.3</MinimumFableVersion>
``` 
Since Fable already has access to the sources of project files, it can read these and verify the versions

**Comment by ncave** [comment]
IMO `dotnet-fable` should know what is the minimum `Fable.Core` version it can compile against, and tell you if your project is referencing one that is too old, with a compile error or a warning. That would be even less friction or internal knowledge needed for library developers (unless I'm wrong on that).

**Comment by MangelMaxime** [comment]
I do agree with @ncave 

It can be really hard for developpers to know which version of Fable.Core they should set as minimal. Personally, I don't really understand those version things and in general I use lastest whenever possible because I consider then the most stable.

**Comment by alfonsogarciacaro** [comment]
@ncave [dotnet-fable already does this](https://github.com/fable-compiler/Fable/blob/fc89c870e8054399637f4df205ed47d02bad28f4/src/dotnet/Fable.Compiler/CLI/Agent.fs#L35-L41), but @Zaid-Ajaj's problem is the bug wasn't in Fable.Core but in the compiler itself, and he has no way to set a minimum compiler version from the library.

In Fable 1, Fable.Core and dotnet-fable packages were more or less in sync (mainly because the `fable-core` JS files were in the Fable.Core package) so setting a minimum Fable.Core version was a way to set a minimum version for the compiler. But this is not the case in Fable 2, and Fable.Core is expected to change much less often.

Just to be clear, my intention is to keep Fable.Core and dotnet-fable major and minor versions in sync. But this time it's trickier because the fix to make Fable.Remoting work is in a patch release (dotnet-fable 2.0.3). So it looks like we have two options:

- Add a mechanism so libraries can specify a minimum compiler version the user must run. For that we can use a property in the .fsproj as @Zaid-Ajaj suggests.
- Do nothing. If users encounter a problem, they should first try updating the compiler. This is not only for specific library problems but it may also affect their code, so it's always a sensible thing to do.

**Comment by MangelMaxime** [comment]
The second solution is more or less what we are already doing. 

And people seems ok with that, every time someone as an issue my first is to make sure they use thé latest version
