### ISSUE TITLE
(fable-compiler, REPL) Incremental building for projects with multiple files

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1648]
As we now have a use case for potentially editing multiple files in a future version of the REPL, it would be nice if we can do incremental builds so we don't have to recompile all files every time there is a change.

Continuing the discussion from [here](https://github.com/fsharp/FSharp.Compiler.Service/pull/810#issuecomment-436670203).
>  Add `ParseAndCheckFileInProject` in Fable REPL.

**Comment by ncave** [comment]
A good first step towards that would be adding parse and typecheck caches (with [hashed keys](https://github.com/Microsoft/visualfsharp/pull/5944) to reduce GC).

**Comment by alfonsogarciacaro** [comment]
If we manage to get this the next (or parallel step) would be to add support for libraries and the question would be how to resolve the package references without resorting to MSBuild (or could we communicate with it?). I mention it because Fable 2.1 will be distributed through npm so it'd be interesting to add an option to fable-loader to switch the dotnet or js compiler. However, the libraries will still be distributed through Nuget. We already tried distributing F# libraries with npm in Fable 0.7 but it didn't play very well with F# tooling. Though we could entertain again the idea if it helps fable-compiler(-js), what do you think?

> Maybe we could detect Fable packages in `node_modules` and automatically inject .dll references to the .fsproj if needed. This would also remove the need of having to move F# sources from the Nuget cache to .fable folder to prevent Webpack module resolution issues.

**Comment by alfonsogarciacaro** [comment]
Thanks! Yes, probably renaming it's a good idea :+1: The mention about packages distributed through npm was not about precompiled libraries, sorry I was not clear, just the same way as we do now (sources + .dll). I'm reluctant to distribute precompiled libraries outside because there may be issues when using a different compiler version. Actually, it already happened in the repl https://github.com/fable-compiler/repl/issues/80

I was thinking that it could be easier to resolve package dependencies if they're in npm. But you're right, we can just get the information from projects.asset.json if necessary. Forget what I said 😸

**Comment by ncave** [comment]
@alfonsogarciacaro
[Added](https://github.com/ncave/FSharp.Compiler.Service/commit/dc3c88b214ef3509144c3702b89f3802ffbfbd4d) parsing and type check caching to FCS-Fable's `ParseAndCheckProject_simple` (only).
I opted for simplicity and not changing the current interface. Functionality is the same, just recompile the whole project every time, if something can be reused, it will be. If you hold on to the checker, and If no source changes, or only a few at the end, it will be much much faster. There is also an explicit cache clean method, if memory pressure becomes an issue.

**Comment by ncave** [comment]
@alfonsogarciacaro The next step will be to try the `fable-compiler-js` with hot reload :)

**Comment by alfonsogarciacaro** [comment]
I edited my comment above, but you were faster to reply ;) I'll implement this in `fable-compiler-js` :+1: Probably the easiest way to implement hot reload is to integrate it with fable-loader. I'll try to do it so we can start uniforming the dotnet and JS versions :)

**Comment by ncave** [comment]
@alfonsogarciacaro I'm not sure what you mean by uniforming, currently `fable-compiler-js` is also doing the `fable-splitter` role (albeit the output folder structure is different (not flat), it's preserving the original folder structure, so IMO it's better :). What's still missing from `fable-compiler-js` apart from hot reloading is copying the javascript dependencies (if any) to output folder. Technically this is not part of compiling, can be done after.

**Comment by alfonsogarciacaro** [comment]
We're starting to have many flavors of Fable & friends, sometimes with duplicated behavior (as you just mentioned for fable-compiler-js and fable-splitter) which complicates maintenance. I was thinking that maybe we could forget about the dotnet/js division (becoming blurrier) and just have components with common protocols so it's easy to combine them. We could have these main categories:

- Compiler: FCS/Fable (dotnet and js versions)
- Libraries: Fable.Core, fable-library, fable-metadata, fable-repl-library?
- Clients: fable-loader, fable-splitter, fable-repl... Get/watch the code and send it to the compiler, interact with Babel for the JS generation...
- IDE: Monaco integration, React component

So in this view, `fable-loader` for example would interact with `fable-compiler` (dotnet) by default but users would have the option to use fable-compiler-js instead. Much like, the [sass-loader](https://github.com/webpack-contrib/sass-loader) can either use node-sass (c++) or (dart-)sass (js) (see [the `implementation` option](https://github.com/webpack-contrib/sass-loader)).

It's work but it may save us from trouble in the future. What do you think?

**Comment by alfonsogarciacaro** [comment]
BTW, I remember the flattened structure in fable-splitter was done to avoid problems with files coming from outside the project folder. Has this been solved now?

**Comment by alfonsogarciacaro** [comment]
Published as [fable-compiler-js 1.0.0-alpha-001](https://www.npmjs.com/package/fable-compiler-js). We probably need a test project so people can quickly give it a go.

**Comment by ncave** [comment]
@alfonsogarciacaro Any F#-only Fable-oriented project should do.
