### ISSUE TITLE
Cannot use Seq.map on ResizeArray of tupples

### ISSUE THREAD

**Issue by thmxv** [fable-compiler/Fable#1671]
### Description
Using Seq.map on a ResizeArray of tupple compile and execute but does not behave as expected. It behaves as if the ResizeArray was empty

### Repro code
```
open Fable.Import.Browser
let offsets = ResizeArray<(float*float)> [ 
                ( 1.0, 0.0 );
                ( -1.0, 0.0 );
                ( 0.0, 1.0 );
                ( 0.0, -1.0 )]
offsets |> Seq.map (fun o -> o.ToString) |> console.log
```

### Expected and actual results

I expect the object printed to the console to have a length of 4 like the "offsets" array. Instead it has a zero length and the lambda is never call

### Related information

* Fable version: 1.2.0
* Operating system: Windows 10, FableREPL

**Comment by 0x53A** [comment]
A sequence is lazy. The lambda will ony be called upon iteration (printing doesn't iterate).

-----------------

If you add a ``Seq.ToArray`` before the log, then you get an array with 4 functions.

```f#
offsets |> Seq.map (fun o -> o.ToString) |> Seq.toArray |> console.log
```

![grafik](https://user-images.githubusercontent.com/4236651/49838523-5c9f9f80-fdab-11e8-9627-53cfe5cc5ccf.png)


That is because you give back the function ``ToString`` itself, the lambda is missing ``()``.

------------

With them added, it looks ok:

```f#
offsets |> Seq.map (fun o -> o.ToString()) |> Seq.toArray |> console.log
```

![grafik](https://user-images.githubusercontent.com/4236651/49838590-a5575880-fdab-11e8-97f7-1c81e9f274a6.png)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the explanation @0x53A! The behavior is intended, so we can close this. Please feel free to reopen @thmxv if you've further questions :+1:
