### ISSUE TITLE
New Documentation for Fable and all core libraries

### ISSUE THREAD

**Issue by fergusmeiklejohn** [fable-compiler/Fable#1690]
Have we already looked at this: https://docusaurus.io/en/
It's a super easy to use docs website builder. Basically all we need to do is write the markdown and wire it up. It's a docs site builder with side bar and nav, and it offers free Algolia search, free translation, a blog.. It's batteries included.

Just a thought, as it seems so easy to use: quick to get the site up and running, and simple for many people to contribute while keeping the structure and style consistent

**Comment by alfonsogarciacaro** [comment]
I did have a look at docusaurus and considered it, though I was a bit pulled back when I saw the [scripts to generate the documentation for Reason website](https://github.com/reasonml/reasonml.github.io/tree/source/generate-docs) were not trivial. Also, this would probably make Fable's website look like Reason's and other Facebook-related projects, which I'm not sure it's a good or a bad thing :)

Building docs from markdown is not complicated as there several parsers available for that. Algolia search would be interesting though, but I don't know if we could find enough volunteers to have translations and keep them up to date.

Right now I'm thinking in evolving the static HTML (with some live capabilities) generation with Fable.React itself like [Fable's website](https://github.com/fable-compiler/fable-compiler.github.io/blob/c046419f9ef68f7b018a454e96b00081eca020eb/src/Main.fs) or [Thoth](https://github.com/MangelMaxime/Thoth/blob/d10e60b8b7997149cd0556c1917ced6df5c65013/docs/src/Main.fs) already do. This should provide some dogfooding and more flexibility for changes and additional features (as in https://github.com/fable-compiler/fable-compiler.github.io/issues/32). But if we see it's too much work to implement everything ourselves, we can look back at docusaurus or similar tools.

**Comment by thitemple** [comment]
Hi @alfonsogarciacaro, do you have a plan for improving the site and docs? From the more recent blog posts, I'm understanding that Fable and Elmish are growing together now. Is that really so? If that's the case it would be nice to have more centralized documentation, much like the one for the safe-stack. Not just to document the APIs but also as a learning place with examples. 

What do you think about that? 

Also for the platform, I have played with docusaurus and found it pretty simple (it would have my vote) unless of course, you don't want any resemblance with Facebook stuff. But I understand if you want to dogfood, it just that it doesn't seem to me that this is the focus of the project.

LMK, what are your thoughts on it, I'd be glad to help with some documentation.

**Comment by MangelMaxime** [comment]
Hello @thitemple ,

Fable and Elmish are still 2 separates projects. Indeed, Elmish is one of the main selling point for introducing Fable but some project is made without Elmish behind. 

Work about Fable documentation is done in [this repo](https://github.com/fable-compiler/fable-doc). 

[View the current state of the documentation](https://fable.io/fable-doc/communicate/js-from-fable.html) design is still subject to change because we are working with a designer for it. The goal was just to have a repo set up so people can contribute to the `*.md` files.

We are using Nacara which is a documentation generator (created by me) which will include a plugin system made to support Fable, Elmish, etc. project needs in term of documentation.

For the quick history, I started Nacara in order to use one tool for all my project documentation. I looked at existing tools and they didn't fit the need I had. For example:

- How to generate documentation by running Tests code as Fulma does
    - Preview of the result 
    - Source code for obtaining this result
- How to generate a page by parsing F# source files without hacking too much the tool
- Having really good syntax colouration by using VSCode grammar files

*Please note that not everything is yet supported in Nacara because it is a young project*

**Comment by thitemple** [comment]
I understand that they are both 2 separate projects, but much like in the SAFE stack, a starting point could be an opinionated point of view. SAFE already starts with proposing Fable and Elmish together, and it seems that the goal is to lower the barrier of entrance, I mean, if as part of the main docs there was a tutorial of sorts of how to use both together in a well-presented way, that would help lower even more the barrier of entrance, don't you agree? 

The new documentation is looking really great, and I think it is a step forward, the point that I was trying to make (and probably didn't) is that information is all spread out. Before coming to Fable I was doing Elm, in Elm, that's all you need it's all in there and it makes things simpler to learn. 

Now, I have been trying to assemble a project with Fable and Elmish lately and already I'm facing some tuff choices, do I use `Fable.Promise` + `Fable.Fetch`? I saw in a comment somewhere that `Fable.SimpleHttp` is the more F# way of doing things and more recommended. But why? Then do I use `Thoth.Json` or `Fable.SimpleJson` or something else? What about routing? The Elmish Templates has a way of doing it, but it's not complete. 

And these are all basic things for a web client app. And again I understand that Fable is not just about web apps, it's about node as well, but those could be different parts of docs.

**Please** understand that I'm not trying to be critical, I'm making suggestions and offering to help, but I want to align with you and see if my way of thinking is the same as yours. 

PS: As for the used tool, if Nacara is the way to go, is the way to go. From the previous response from Jan 10th, I understood that you were considering options.

**Comment by MangelMaxime** [comment]
>  I mean, if as part of the main docs there was a tutorial of sorts of how to use both together in a well-presented way, that would help lower even more the barrier of entrance, don't you agree?

I think at some point someone said we should indeed have documentation for that. But I do think Fable doc should simply redirect to the documentation of the said project. And if it doesn't exist we should contribute to the said project documentation to provide it. Something like Fable-doc being a way to centralize the "how to find the info I am looking for" (even if it doesn't mean anything I hope you get the idea)

The thing is in Elm there is kind of a one way only to do things which is good and bad as some people discover with Elm 0.19.

To be honest, in most of the case I don't like telling people to use X or Y exclusively people because it really depends on how people think their apps. Like do they think Fable should make you write idiomatic F# web apps or stay as close as possible to the native API.

I think when there is 2-3 popular libraries for doing a thing the Fable doc could try to explain the pros and cons between one or another. But this is hard to do in general in an objective way :)

For example, you can think about the `hook` support in React I know some people are really enthusiastic about it while I am not because people are already abusing them and stop having a single state in their app. But that's indeed some questions we need to ask ourself and try to provide an answer or at least guidance if possible.

> Please understand that I'm not trying to be critical, I'm making suggestions and offering to help, but I want to align with you and see if my way of thinking is the same as yours.

Sure, and I really appreciate your help :)

> PS: As for the used tool, if Nacara is the way to go, is the way to go. From the previous response from Jan 10th, I understood that you were considering options.

Sure no worry :) we just decided it kind of recently :)

I really encourage you proposing you POV on what should be added next to fable-doc in the fable-doc repo. You can see the initial Table of content [here](https://github.com/fable-compiler/fable-doc/issues/1)

**Comment by thitemple** [comment]
That's all very reasonable, just a few points:

> To be honest, in most of the case I don't like telling people to use X or Y exclusively people because it really depends on how people think their apps. Like do they think Fable should make you write idiomatic F# web apps or stay as close as possible to the native API.

It's not that people should be told what to do (at least not in a definitive way), it's that making it the default or recommended way would make it simpler. Still, the things that could be replaced could be documented as such.

But I understand the line of thought you are proposing, the idea would be to point people to other projects that have that more opinionated view from the Fable site. Fair enough.

Wow! Just looking at that TOC you shared, there's way more stuff than what's available today. How are approaching writing all that?

**Comment by MangelMaxime** [comment]
> It's not that people should be told what to do (at least not in a definitive way), it's that making it the default or recommended way would make it simpler. Still, the things that could be replaced could be documented as such.

If we make clear enough that there is a replacement/equivalent tool I guess yes it is fine. I also think I have a hard time writing black on white the default is the library X when I am the author of the library 😅 because of course, I am biased ^^

@thitemple I think you can say you are writing about topic X in an issue.

And then send a PR with the new page added.

**Comment by alfonsogarciacaro** [comment]
Closing this as we already moved the docs to Nacara... although now I have to update things for Fable 3 😅 About the discussion to have a "recommended way" of doing things, I know this is something good for beginners but it's difficult to do because we don't control the whole ecosystem and more a more great tools are created outside the `fable-compiler` org (which I'm very happy about). However, there are already efforts for a more comprehensive like the [SAFE Stack](https://safe-stack.github.io/) or [The Elmish Book](https://zaid-ajaj.github.io/the-elmish-book/#/), we should try to give them more visibility.
