### ISSUE TITLE
Add README for src folder

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1736]
Could someone make a little readme file under the [src](https://github.com/fable-compiler/Fable/tree/master/src) folder? It is somewhat confusing what folder contains what code.
A simple oneliner per folder would suffice.
Thx!

**Comment by alfonsogarciacaro** [comment]
I tried to do that in the past, but I don't like it now because every time a change in the structure is made you need to remember to update the README links as well. But I wouldn't oppose if "someone" writes such a document for the src folder 😸 

Most of the subfolders corresponding now to npm packages. I've just added a README to those that were missing it :)
