### ISSUE TITLE
Regex Dotnet vs JS : a path to Regex Type Provider

### ISSUE THREAD

**Issue by evilz** [fable-compiler/Fable#1820]
### Description

Attempt to make better Regex implementation. 
In Fable 2 two version of Regex was available Dotnet one and Js one.

Since Fable Core 3 only dotnet Regex is available. 

This can be a problem since but don't actually work exactly the same.
- JS : 
   * no group name
   * no backtraking
  ...

By the way some of those features have been implemented in V8 or Babel.
=> https://github.com/DmitrySoshnikov/babel-plugin-transform-modern-regexp#named-capturing-groups

Can/should we use these plugin to make a better implementation of Regex in `fable-library` ?

At the end we can use group name in same way as dotnet and create the Regexp Type provider \o/

**Comment by MangelMaxime** [comment]
For reference, the discussion started on Gitter.

And my point of view, is we could avoid making `babel-plugin-transform-modern-regexp` a dependency of `fable-compiler` but mark it as a requirement for using the `Regexp Type provider library`.

The same way, it's required to install `@babel/plugin-proposal-class-properties` in order to use [Fable.ReactGoogleMaps](https://github.com/fable-compiler/Fable.ReactGoogleMaps).

Because the more we include dependencies the harder it get to keep tracks of everything.

**Comment by evilz** [comment]
I understand your point. But in this case things are differents : it's core and in BCL. 
Then I use a regex with group name or kind of syntax that run well on dotnet I also hope this will run on Fable.

**Comment by evilz** [comment]
this code : https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoAqYAeT0BKYA5gK4A2AhgE4CiOI1YCCAlsBAgFBflhJQmxKAF4oEMAHcoRYrgAUAInkB+ADwAzVtWQRKqMAD4AOsckBqAJSmEqtVV36jpi5cWWA3D178oqUYIk6ACylEgAxgAWSgBqrBDhkAIAQsCk1AAmHO5cjPFIGtCKAKQAgop+6ADi1GkgCOgA2opaOkh6BooAuugxlOSkYLnU+YVQJeWVNXUNzQ7tTt29-YNAA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q

Should work like this one : https://repl.it/@vbshift/Regex

**Comment by alfonsogarciacaro** [comment]
As commented in #1819, there are no regex types in Fable, everything is compiled to native JS RegExp. That's why I unified the types in Fable.Core 3, to prevent confusion.

From the very beginning, Fable's goal was to compile to JS as standard as possible, not to keep exactly the same behaviour as .NET/BCL. There're are many other places where Fable runtime behaviour is not exactly the same as .NET, so this is not a strong reason for adding complexity to Fable setup. I'm reluctant to add the need for plugins that are not included in Babel preset-env. We already tried to do that with `plugin-proposal-class-properties` and got some conflicts with fable-splitter. There are other solutions to port the full BCL to the browser, like Blazor.

So, as Maxime says, I would ask users to add the plugin by themselves or wait until the plugin is included in preset-env. Also, since you're building a type provider, it wouldn't be very difficult to detect the name groups and transform them to numbered groups by yourself as the plugin does.

**Comment by evilz** [comment]
Ok ok. I pointed the babel plugin but in fact this is already in JS.  
This code work already in browser (chrome) and node 
```js
let reg = /(?<firstname>\w+)\s(?<lastname>\w+)/

let m = reg.exec("Vincent Bourdon")
console.log(m.groups["firstname"])
console.log(m.groups["lastname"])
```
https://repl.it/repls/PointlessWoozyRadius

@alfonsogarciacaro Do you think Emit is possible inside a Type Provider ?

**Comment by alfonsogarciacaro** [comment]
Yes, [it's possible](https://github.com/fable-compiler/Fable.JsonProvider/blob/da0bc9dc76896047e7736f1da7a19f5144b80d33/src/Fable.JsonProvider.fs#L17-L21). Although you need to be careful about providing something that only works in one browser :)

**Comment by alfonsogarciacaro** [comment]
Group names are already supported by Fable thanks to @Booksbaum 👍
