### ISSUE TITLE
SRTP does not work with Replacement Methods and byref magic

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1830]
```f#
let inline private tryParse (s:string) : Option< ^T > =
    let mutable out = Unchecked.defaultof< ^T >
    let f =  (^T : (static member TryParse : string * byref< ^T > -> bool) (s, &out))
    match f, out with
    | true, x -> Some x
    | _ -> None

let i : int option = tryParse "1"
let b : byte option = tryParse "1"
```

this fails with ``FABLE: Cannot resolve trait call TryParse - Inline call from .(14,21)``

[repl](https://fable.io/repl/#?code=LYewJgrgNgpgBABQE4gOZIIbALACg8gAOMAdnAGIYBGsBxZlNMAdAMIhIx2kXWzMBJYIQ4AXPHlii4ASxJQ58QkhkA3DKPiikATwQYkAZ3gAKQwC5D2uagCUcc3ADyhUTJAkAPHAB6AFTgAPjgAXjw4CLgpOGAIUT54EDjQuABVEgBjAAsYDIBrGDBmMBgAMwxoURBS738g8Mjo0pS4EzrHM3i3DJiYYCoYJDg-XX0jeEcrFRJUOAAqOCodThrfAOCAWmCqEBAoezMAGjgAMiTRW1sGiOANbLhS4-O4AHcZUSzruAAfOG0IGDHAAecC2cAAyiBgPAgV9fgB9UHBAByHi4+Fw0RkDlkJGkRDcHhS2j0BmMcAARABGCmSGDSKg4paaOAE9xkEJ-UZk+DU2m4IA&html=DwCwLgtgNgfAsAKEaApgQwCbwQAjz4CFMNHcMABwFoUBHAVwEsA3AXgHIBhAewDswU-KgBUAnhRTscAYz4D+HAQA8wAenDQA3DJBoATgGdiremABmVABzts+Agel7GFMDgN7prAEQB9HwAkAeQBlYT9VKEYAIwNVPXRpMAA6Cj1uDHpExj4kiEZeJIArAy8YYFUHJxdbfGBK51d3T18AkLCfCOjY+LREqgxuCBS0jKycvILi0vL66uR1dCxEZCj00RkoNAMDbzQKall+NHyUPVLEO2AMFhxGDG8UKDyDECo9ii8NrZ2vR+fX97TVTXZjYcqrDCibDzDSwRBAA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA)

**Comment by alfonsogarciacaro** [comment]
Well this is not exactly about static members (STRP works for static members in user-defined types) but due to the fact `TryParse` is a replacement method which also involves magic from both the F# compiler and Fable. The F# compiler converts the byref argument into a return tuple type, and Fable eliminates the byref arg because this is not supported in JS .

Not sure if it's possible to fix this, but if it is, it will probably involve a lot of work (there's already [specialized code to identify the `TryParse` pattern](https://github.com/fable-compiler/Fable/blob/7365d1749463aef9ba120ce7750d1a076e0076d6/src/Fable.Transforms/FSharp2Fable.Util.fs#L371-L414)) just to support this corner case :/

**Comment by 0x53A** [comment]
yeah that seems to be a corner case of a corner case. I mostly created the issue because I was so proud of myself for even managing to write that SRTP, it always feels like alchemy.

Thanks :D
