### ISSUE TITLE
Missing Option map2/3 implementations

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#1842]
### Description

When trying to use `Option.map2` or `Option.map3` fable provides the following error

```
error FABLE: Cannot resolve Microsoft.FSharp.Core.OptionModule.Map2
error FABLE: Cannot resolve Microsoft.FSharp.Core.OptionModule.Map3
```

### Repro code

Using `Option.map2` or `Option.map3`

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`

```
$ npm show fable-compiler version
2.3.10
```

* Operating system

OSX

**Comment by TheAngryByrd** [comment]
I would love to contribute this.  What do I need to know about implementing these?

**Comment by alfonsogarciacaro** [comment]
Great to hear you want to contribute @TheAngryByrd! To compile calls to FSharp.Core/BCL we have the so-called [Replacements](https://github.com/fable-compiler/Fable/blob/296194e75e18747d6d43cfe4ebc259eb6aab371c/src/Fable.Transforms/Replacements.fs#L2842). Basically we detect the call in the F# code and replace it with an equivalent call to the embedded fable-library. In fact, apparently there's already [a placeholder for `Option.map2/map3`](https://github.com/fable-compiler/Fable/blob/296194e75e18747d6d43cfe4ebc259eb6aab371c/src/Fable.Transforms/Replacements.fs#L1859).

Maybe it's better not to take [Option.Map](https://github.com/fable-compiler/Fable/blob/296194e75e18747d6d43cfe4ebc259eb6aab371c/src/Fable.Transforms/Replacements.fs#L1835-L1841) into account because it's generating some code and it's more complicated. You can take a look at `Filter` right below which just diverts the call. Then you can add the `map2/map3` JS equivalents [here](https://github.com/fable-compiler/Fable/blob/296194e75e18747d6d43cfe4ebc259eb6aab371c/src/fable-library/Option.js#L73).

For testing, you can use the `Quicktest.fs` file. Please read [the instructions here](https://github.com/fable-compiler/Fable/blob/15fc91d46a2ba5794893adfb21a7882148f01dcb/src/quicktest/QuickTest.fs#L3-L7). And when finished, please move the tests [here](https://github.com/fable-compiler/Fable/blob/15fc91d46a2ba5794893adfb21a7882148f01dcb/tests/Main/OptionTests.fs#L93).

Thanks a lot for your help!
