### ISSUE TITLE
"export 'allPairs' was not found in './.fable/fable-library.2.3.10/Array.js'

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#1845]
### Description
When F# code using `Array.allPairs` is compiled, a warning is issued:

"export 'allPairs' was not found in './.fable/fable-library.2.3.10/Array.js'

### Related information

* Fable version: 2.3.10
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
What does that function do? I cannot find any documentation for it

**Comment by Zaid-Ajaj** [comment]
Looks like `allPairs` creates the Cartesian product of two arrays

![pairs](https://user-images.githubusercontent.com/13316248/59098941-11adb180-8922-11e9-9f31-5293f602bcbb.png)

Example implementation 

```fsharp
module Array = 
  let allPairs (xs: 't []) (ys: 'u []) : ('t * 'u) [] = 
    [| for x in xs do for y in ys do yield (x, y) |] 
         
```

**Comment by alfonsogarciacaro** [comment]
Thanks @Zaid-Ajaj! At the end, because the method is implemented for the 3 collections I'm defaulting to [the `Seq` implementation](https://github.com/fable-compiler/Fable/commit/26b042132e98e95fc9104afef98218ad92feba3a#diff-e30c62fac6f2268f671973334d5ec910) (which is a bit more complicated, as there's some caching involved. It's probably enough for now, but if it's better to add specific methods for each collection we could do it.
