### ISSUE TITLE
What's the recommended way to construct JS classes?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1849]
I'm working on creating bindings for Electron. I've used ts2fable to start with, and notice that it creates constructors along with other static functions like this:

```f#
type [<AllowNullLiteral>] BrowserViewStatic =
  [<Emit "new $0($1...)">] abstract Create: ?options: BrowserViewConstructorOptions -> BrowserView
  (* other static functions *)
```

Another option is to use the `Fable.Core.JsInterop.createNew`.

It seems to me like the first option is preferable, since `createNew` isn't strongly typed.

Is there a recommended way to create bindings for JS constructors?

**Comment by alfonsogarciacaro** [comment]
`createNew` is to interact with JS code dynamically. Actually, you can use any function as long as you decorate it with `Emit("new $0($1...)")` (or the new `EmitConstructor`) but the convention for the bindings is to put the static members of a JS type (including the constructor) in another interface with the same name and suffixed with -Static or -Type, so that's what I would recommend

**Comment by cmeeren** [comment]
Thanks! But why not place static stuff as static members of the actual type, or as functions in a module? I recall a Fable blog post recommending less auto-generated and more hand-crafted, F# idiomatic bindings, and both of those alternatives are more F# idiomatic than having a separate -Static or -Type type.

**Comment by alfonsogarciacaro** [comment]
Interfaces cannot have static member but anyways the problem here is how Fable can locate the class definition where the static members are attached. Fable 1 tried to define classes the same way as in JS so it was somehow possible to use a class type for JS bindings but this created other problems (overload resolution didn't work all the time, couldn't inherit from secondary constructors, the code was not very optimized for tree shaking, etc...), so we changed it in Fable 2 and the way F# classes are implemented in the generated code is very different now from actual JS classes.

If you decorate the module with the appropriate `Import` attribute you can use it for the static members. But F# module functions don't accept optional arguments, and this is usually a big limitation when writing JS bindings.

It's true two separate interfaces don't look idiomatic (this is actually what Typescript declarations [do sometimes](https://github.com/microsoft/TypeScript/blob/36aa1014f80beee0baa8af74eb76d4459da96816/lib/lib.es5.d.ts#L972-L982)) but most of the times users don't notice this:

```fsharp
// Binding
type MyClass =
    abstract AMethod: int -> int

type MyClassStatic =
    abstract Create: unit->MyClass
    abstract AStaticMethod: string -> unit

// Expose the static part
[<ImportAll("./util.js")>]
module Util =
    let MyClass: MyClassStatic = jsNative


// Usage
// Note the user "doesn't see" MyClassStatic
 
let myClass = Util.MyClass.Create()
let x = myClass.AMethod(5)
myClass.AStaticMethod("foo")
```

**Comment by cmeeren** [comment]
Thanks! That clears up a lot for me. :) The only question I have left then is how to surface the static stuff. You mention that you can decorate a module with `Import`. What ts2fable does is generate an `IExports` interface that contains members with all the static stuff. Isn't it simpler then to just import a value of type `IExports` and be done with it? Or does that have negative impacts for tree-shaking?

**Comment by alfonsogarciacaro** [comment]
For a while I was thinking that tree shaking didn't work if you did `import * from ...` but it seems bundlers are clever enough to detect which imports you're actually using (at least Rollup but I think Webpack can do it now too). It should be fine to just expose the `IExports` object as a value that users can easily access.

**Comment by cmeeren** [comment]
Thanks for all the help! :)
