### ISSUE TITLE
Fable Splitter not compiling every project file

### ISSUE THREAD

**Issue by jbotto94** [fable-compiler/Fable#1906]
### Description
I'm trying to compile F#+ with Fable. I know F#+ is fully not compatible with Fable, but the purpose of this is to see which error messages are thrown to start enabling at least parts of F#+ to be compiled with Fable.

### Repro code
[My repo of F#+](https://github.com/jbotto94/FSharpPlus/tree/FableBuild/src) with a simple Fable build script.
I use the following to build F#+
- `npm install`

- `npm run-script build`

### Expected and actual results
The compilation succeeds very quickly, but only `parsing.fs` gets compiled inside the `build` folder generated at compile time. 
Compilation should theoretically result in all files getting compiled or some sort of compilation error being returned.

### Related information
This is more likely something I'm doing wrong, rather than this actually being a bug.
*  Fable version: 2.3.25
*  Operating system: MacOS 10.14.6

**Comment by alfonsogarciacaro** [comment]
Looks like [you're passing an `--allfiles` flag](https://github.com/jbotto94/FSharpPlus/blob/bda058505145c4035906b430290ef67f4e3d5c35/src/package.json#L4) (all lower case) but the actual option uses Pascal case ([allFiles](https://www.npmjs.com/package/fable-splitter)). I guess fable-splitter is not recognizing the option because of this, can you try with `--allFiles`? We could also make fable-splitter recognize both `--allfiles` and `--allFiles` to avoid confusion.

**Comment by jbotto94** [comment]
That solved it! Thank you so much!
