### ISSUE TITLE
Suppress Warnings

### ISSUE THREAD

**Issue by krauthaufen** [fable-compiler/Fable#1917]
Fable currently reports lots of warnings when implementing generic types with a custom `Equals` override. 

```fsharp
override x.Equals(o) =
    match o with
    | :? HashSet<'T> as o -> // ...
    | _ -> false
```
In most scenarios the type-test for the generic arguments is not really required here anyway but checking the *container-type* (e.g. HashSet<_>) would be important and can (to my knowledge) currenty not be done without the warning being reported.

Wouldn't it be nice to have some mechanism for suppressing Fable warnings?
maybe we could just create new warning codes and parse the `#nowarn` directives from F# files?

Cheers

**Comment by alfonsogarciacaro** [comment]
I like the idea but it may be a bit difficult to implement because there are two ways to silent warnings in F#, one is to pass a compiler option and the other is to use `#nowarn` directive as you said. We could intercept the first one, but there's no information about the preprocessor directives in the F# AST, so Fable would be unaware of it.

I already added a `silent` flag (in addition to `verbose`) for #1862. Probably we should unify them in a `verbosity` option with different levels, including one to silence warnings (although this is something I'm always a bit reluctant to do).

**Comment by krauthaufen** [comment]
the problem with suppressing warnings globally it cant't be controlled per file.
However I'll just live with the warnings for now...

**Comment by alfonsogarciacaro** [comment]
In other similar situations other users have created helpers with conditional compilation to change the code for Fable and avoid the warning. Maybe something like this?

```fsharp
let inline customEquals (this: 'T) (other: obj) (equals: 'T -> 'T -> bool) =
#if FABLE_COMPILER
    equals this (other :?> 'T)
#else
    match other with
    | :? 'T as other -> equals this other
    | _ -> false
#endif

type MyWrapper<'T when 'T : equality>(value: 'T) =
    member __.Value = value
    override this.Equals(other: obj) =
        customEquals this other (fun x y -> x.Value = y.Value)
```

**Comment by alfonsogarciacaro** [comment]
Warnings are finally suppressed in Fable 3 :)
