### ISSUE TITLE
Function copies are not uncurried

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1922]
```
let add x y z = x + y + z
let add_ = add
```
resutls in:
```
export function add(x, y, z) {
  return x + y + z;
}
export function add_(x$$1) {
  return function (y$$1) {
    return function (z$$1) {
      return add(x$$1, y$$1, z$$1);
    };
  };
}
```
@alfonsogarciacaro From the top of your head, any idea which Fable optimization step this needs to be added to? The AST for `add_` is a nested Lambda (without Let):
```
Lambda (val x,
    Lambda (val y,
        Lambda (val z,
            Call (None,val add,[],[],[Value val x; Value val y; Value val z]))))
```

**Comment by alfonsogarciacaro** [comment]
Hmmm, this code should actually propagate uncurrying through let bindings, but for some reason it's not working in this case (maybe because of the nested lambda). I'll check:

https://github.com/fable-compiler/Fable/blob/b0e003ba97659cad69d7970597ba42fa0489b56d/src/Fable.Transforms/FableTransforms.fs#L416-L431

**Comment by ncave** [comment]
@alfonsogarciacaro I don't think it's wrapped in a let in the AST.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry! Read your sample too quickly. Those `let`s are exposed directly as module values, but I was thinking in local (within a function body) bindings. Makes sense, we'll have to add a extra transformation for this case.

**Comment by alfonsogarciacaro** [comment]
I'm tempted to leave it as is. It doesn't seem to cause any problem, and F#/Fable recognize the function copy is curried when calling it. And if you want to send the copy as argument to another function, it's properly curried in the runtime (it would fail though if you call directly the copy from JS in an uncurried way).

I think this has more to do with the point-free style rather than copying the function. And dealing with point-free functions has always been tricky. If there are no actual errors, I'd prefer not to touch as I'm afraid that if we try to uncurry the function declaration this will cause issues in the call sites.

The following code works:

```fsharp
let log (o: obj) =
    printfn "%O" o

let add x y z = x + y + z
let add1 = add
let add2 x = add x
let add3 x y = add x y

let test2 f =
    f 4 5 |> log

let test() =
    add 3 4 5 |> log
    add1 3 4 5 |> log
    add2 3 4 5 |> log
    add3 3 4 5 |> log

    let add4 = add1 3 4
    add4 5 |> log
    test2 (add1 3)
    test2 (add2 3)
    test2 (add3 3)

test()
```

Translated to:

```js
function add(x, y, z) {
  return x + y + z;
}

function add1(x$$1) {
  return function (y$$1) {
    return function (z$$1) {
      return add(x$$1, y$$1, z$$1);
    };
  };
}

function add2(x$$2) {
  return function (y$$2) {
    return function (z$$2) {
      return add(x$$2, y$$2, z$$2);
    };
  };
}

function add3(x$$3, y$$3) {
  return function (z$$3) {
    return add(x$$3, y$$3, z$$3);
  };
}

function test2(f$$3) {
  const o$$1 = f$$3(4, 5);
  log(o$$1);
}

function test() {
  const o$$2 = add(3, 4, 5) | 0;
  log(o$$2);
  const o$$3 = add1(3)(4)(5) | 0;
  log(o$$3);
  const o$$4 = add2(3)(4)(5) | 0;
  log(o$$4);
  const o$$5 = add3(3, 4)(5) | 0;
  log(o$$5);
  const add4 = add1(3)(4);
  const o$$6 = add4(5) | 0;
  log(o$$6);
  test2((0, _Util.uncurry)(2, add1(3)));
  test2((0, _Util.uncurry)(2, add2(3)));
  test2((0, _Util.uncurry)(2, function (y$$4) {
    return add3(3, y$$4);
  }));
}

test();
```

**Comment by ncave** [comment]
That's fine, I was just looking for possible optimizations at compile time. Thanks!
