### ISSUE TITLE
Option.map ignore creates undefined underlying type

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#1923]
### Description

Over in https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/58, we're getting test errors when comparing two `Some ()` types. 

```
 2 failing
  1) All Tests
       Result Option Tests
         ResultOption.ignore Tests
           ignore with Ok(Some x)
             ignore with Ok(Some x):
     Error: Expected Ok(null), was Ok(undefined).
  2) All Tests
       AsyncResultOptionTests
         AsyncResultOption.ignore tests
           ignore with Async(Ok Some(x)):
     Error: Expected Ok(null), was Ok(undefined).
```

It seems that `Some ()` gets converted to `null` while if you do `Some 42 |> Option.map ignore` it gets converted to `undefined`. 

### Repro code

https://fable.io/repl/#?code=PTAEHUCcEsBcFNQGMD2ATRLKgDYoIZqj6gDO+AtgA46IBmkKFZ0GARvpAFBcXoCutUADEUKUAF4uoXPFigKATwDKTRBNCqKiABQBKabPlKA8rAAW8SFvUKVa0AB8AfKBNVY0FADsAdBXwqUB1oAHNvLHgDQyoYb1g6b1AAIiUbAC5QAFIAQWS7Gxi4hKTUxTNLazVM3PzTCytCriA&html=Q&css=Q

### Expected and actual results

I would expect the `Option.map ignore` call to return the same as `Some ()`.  Which is most likely both being null.

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`
* Operating system

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! `Some ()` prints as null, but it's actually a null wrapped by a [Some object](https://github.com/fable-compiler/Fable/blob/4bfed5201e1c1e17490b46063d3d0a3edd595cf6/src/fable-library/Option.ts#L4). This is necessary to tell `Some ()` and `None` (which also compiles as null) apart. But I forgot to do the wrapping in `Option.map`. It will be fixed in the next fable-compiler release :+1:

**Comment by TheAngryByrd** [comment]
Ty!
