### ISSUE TITLE
fable-splitter for browser output

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#1929]
### Description

When I tried fable splitter, and when it generates modules, it doesn't add .js to the module paths.
When I tried with babel for es2015, I still couldn't make it working for browsers. Is fable-splitter not supported for browser?

**Comment by alfonsogarciacaro** [comment]
I think fable-splitter is mostly used for node applications or just to read the generated JS code more easily. For the browser, usually fable-loader with Webpack is used because you get other benefits like tree shaking. But it's still possible to use files generated by fable-splitter in the browser (the Fable REPL does this with the fable-library files). I think there was a problem when adding the ".js" extension but I don't remember what it was exactly. I didn't look much into it because [it's not difficult to make an extra pass to attach the extension anyways](https://github.com/fable-compiler/repl/blob/2dd3ce76962c4204adab0bd1b3c5509ae33c6113/build.fsx#L193-L202).

**Comment by alfonsogarciacaro** [comment]
Closing as fable-splitter is not used in Fable 3 and it's currently out-of-support.
