### ISSUE TITLE
Subsring should throw exception instead of returning an empty string when start index is > than input length 

### ISSUE THREAD

**Issue by saidziani** [fable-compiler/Fable#1955]
### Description

Subsring should throw exception instead of returning an empty string when start index is > than input length
### Repro code

```fs
open System

let input = "Hello Fable"

let output = input.Substring(200)
printf "Output = '%s'" output // Output = ''
```

### Expected and actual results

* Expected: `Substring` to throw an exception just like the [.NET implementation](https://dotnetfiddle.net/Ol82d7) does when start index is > than input length

* Actual behaviour: `Substring` returns an empty string when start index is > than input length (JS implementation)
### Related information

* Fable version: `2.4.9`
* Operating system GNU/Linux Ubuntu 18.04

**Comment by alfonsogarciacaro** [comment]
The original idea was to use native JS methods whenever possible, that's why for example there's no array bound checking when accessing its index. But it's true that we've added checks in other places to be closer to .NET behavior and the situation is a bit messy right now.

It'd be great to get a PR to change this. For that, you need to remove "Substring" [from this map](https://github.com/fable-compiler/Fable/blob/47516906d9c47256fc2e96f08fc397435f722503/src/Fable.Transforms/Replacements.fs#L1527) (which converts it directly to the JS method), [add it here instead](https://github.com/fable-compiler/Fable/blob/47516906d9c47256fc2e96f08fc397435f722503/src/Fable.Transforms/Replacements.fs#L1477) and the include the `substring` function with the desired behavior [in this file](https://github.com/fable-compiler/Fable/blob/master/src/fable-library/String.ts). Bonus also when adding a test :smile_cat:
