### ISSUE TITLE
CompiledName works on Union Cases, while in .NET in doesn't

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#2041]
### Description

While looking at #2040, I discovered that `CompiledName` attribute does work on Union Cases in Fable, while in .NET it doesn't. 

### Repro code

``` fsharp
type T = X | [<CompiledName("Z")>] Y

typeof<T>
|> FSharp.Reflection.FSharpType.GetUnionCases
|> Array.iter (fun ci -> printfn "%s" ci.Name)
```

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAYgygCwIYCcQDoBKYBmAbMAYwBcBLYCAKEuIE9woAVKAXigA0oAfKAbQB4AwsAC2IUgQAmAOSQiwACgBEALSUBKAHwBdKAE1q8ZGkb0w6AOJhiAVQjkIgpAGcwzqHXDAc-RpspcmlAAgigoSLTopMRgKFAKOACu0ISkUAC0QSAopBDEONBKAKTOSlCp6LLy6kA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

### Expected and actual results

The REPL prints X and Z, while in F# interactive we get X and Y.

### Related information

* Fable version: 2.8.0

**Comment by MangelMaxime** [comment]
Having `CompiledName` working for Union type then is a feature of Fable and I don't think we will drop it because that's how bindings in Fable.React style works.

For example, Fulma code is entirely dependant on that too now.

Fable doesn't aims to reproduce 100% of .Net behaviour and sometimes it can do thing differently in order to provide a better experience or better interop with JavaScript.

**Comment by inosik** [comment]
> Fable doesn't aims to reproduce 100% of .Net behaviour and sometimes it can do thing differently in order to provide a better experience or better interop with JavaScript.

One could argue that this is not about .NET vs. JS, but rather F# vs. Fable. However, I don't have a strong opinion on this, so I guess I'm fine with leaving it as it is. It's just something I discovered yesterday and I was a bit surprised that `CompiledName` doesn't work in this case.

One thing I'm a bit worried is serialization. Will a type as defined in the sample code work correctly with Thoth.Json, for example?

**Comment by MangelMaxime** [comment]
@inosik You are right about the distinction of F# vs Fable instead of .NET vs JS.

Ah well it will work if you use Thoth.Json:

```fs
open Fable.Core
open Thoth.Json

type MyType = 
    | X 
    | [<CompiledName("Z")>] Y

let json = Encode.Auto.toString(4, MyType.Y)

let value : MyType = Decode.Auto.unsafeFromString(json)

printfn "%A" MyType.Y
JS.console.log(json)
printfn "%A" value
printfn "%A" (MyType.Y = value)

// Result:
// Z
// "Z"
// Z
// true
```

After checking Thoth.Json(.Net) code yes the libraries supported `CompiledName` and `StringEnum` when using .NetCore as the runtime.

[Implementation source](https://github.com/thoth-org/Thoth.Json.Net/blob/26e0d883538c930002541a585d879dd909911218/src/Encode.fs#L370-L403)

[Tests source](https://github.com/thoth-org/Thoth.Json/blob/master/tests/Encoders.fs#L579-L599)

I think it should be possible to support `CompiledName` also on .NET framework too because that's not something coming from Fable.Core library.

**Comment by alfonsogarciacaro** [comment]
This is tricky: the behavior of `CompiledName` attribute is already messy in F#/.NET (it seems to be only honored in runtime for module and class members) and it's even messier in Fable :) I don't remember exactly, but probably I started to use the CompiledName attribute on union cases when building the React API and after that I realized it's not working on .NET. I wouldn't touch it because as @MangelMaxime says it would break lot of code. Also as already pointed, in shared libraries we make CompiledName work in .NET also when necessary by manually inspecting the custom attributes.

**Comment by inosik** [comment]
As I've written above, I'm okay with leaving it as it is.

I'm aware that we use this for JS interop (React props, `StringEnum`) and special casing these scenarios would be too difficult and we'd probably end up enabling `CompiledName` anyways.
