### ISSUE TITLE
Unexpected end of JSON input at JSON.parse in dist/index.js

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2043]
### Description

On our CI system we see strange flaky compile errors when building our electron app:

    C:\WORK\fdgC2beP\0\products\msu.projectmanagement\electron\node_modules\fable-compiler\dist\index.js:80
                    resolve(JSON.parse(data.substr(pattern[0].length)));
                                ^
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Interface.linereader.on (C:\WORK\fdgC2beP\0\products\msu.projectmanagement\electron\node_modules\fable-compiler\dist\index.js:80:30)
        at Interface.emit (events.js:198:13)
        at Socket.onend (readline.js:171:12)
        at Socket.emit (events.js:203:15)
        at endReadableNT (_stream_readable.js:1129:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Running build failed.
    Error:
    System.Exception: Error while running 'C:\Program Files (x86)\Yarn\bin\yarn.cmd' with args: run compile

This points to https://github.com/fable-compiler/Fable/blob/fe87afbc3673840f8f5c83808f23f13958f2a0b0/src/fable-compiler/src/index.ts#L92

### Related information

* Fable version:  2.8.3
* Operating system: Windows

cc @atheck @MangelMaxime @ncave @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Usually I see this error when I put a `printfn` by mistake somewhere and it interrupts the JSON writing in stdout. However in the current code there are only two places writing to stdout [json](https://github.com/fable-compiler/Fable/blob/35225105910eb5626bb09a00ddb5903c0d545b3d/src/Fable.Cli/Stdin.fs#L11-L15) and [logs](https://github.com/fable-compiler/Fable/blob/35225105910eb5626bb09a00ddb5903c0d545b3d/src/Fable.Cli/Util.fs#L129-L131) and they are both protected by the same lock.

It may happen that in your CI server sometimes the lock is not honored for some reason, or that I'm not using the lock properly (maybe we should use another mailbox for writing to stdout). You can try using the [silent option](https://github.com/fable-compiler/webpack-config-template/blob/5bcb4fc7ed2d4db17057f16d8cc5efc606691c4e/webpack.config.js#L133) of the fable-loader in your CI server to see if it helps.

**Comment by forki** [comment]
@atheck  can you please try that on monday? thanks

**Comment by atheck** [comment]
@alfonsogarciacaro I tried setting the silent option to true but it's still not working. Is there something else I can try?

**Comment by atheck** [comment]
Ok, I reverted some changes in the build script, now it's working again. I will watch this.

**Comment by atheck** [comment]
Now, after some successful builds the error reappeared.

**Comment by forki** [comment]
@alfonsogarciacaro any chance to get https://github.com/fable-compiler/Fable/pull/2044 in? Maybe that helps to find the cause.

**Comment by ncave** [comment]
@forki Would installing Fable as [local npm package](https://docs.npmjs.com/cli/link) help in your troubleshooting, as you can test #2044 without waiting for it to be merged? Just a suggestion if you need it immediately.

**Comment by forki** [comment]
@ncave that's rather difficult to set up for CI, right?

I tried 

![image](https://user-images.githubusercontent.com/57396/81213738-1f0e6880-8fd7-11ea-8be1-d76e9cf8fdd6.png)

but that way doesn't seem to work

**Comment by ncave** [comment]
@forki We're using local packages in the Fable CI, e.g. here: [link](https://github.com/fable-compiler/Fable/blob/master/build.fsx#L156-L157)/[unlink](https://github.com/fable-compiler/Fable/blob/master/build.fsx#L167-L168).

**Comment by ncave** [comment]
@forki: Of course, using local packages is only if you don't want to change your `package.json`.
Otherwise, per your screenshot, you might just need to add the `file:` prefix to make it work with your local copy of Fable (see using [local paths](https://docs.npmjs.com/files/package.json#local-paths)).

**Comment by MangelMaxime** [comment]
Version `2.9.0` of fable-compiler include a better error reporting for this issue perhaps you can try it.

**Comment by forki** [comment]
C:\WORK\psBdKN2R\0\products\msu.projectmanagement\electron\node_modules\fable-compiler\dist\index.js:82
                         const parsed = JSON.parse(json);
                                             ^
     SyntaxError: Unexpected end of JSON input
         at JSON.parse (<anonymous>)
         at Interface.linereader.on (C:\WORK\psBdKN2R\0\products\msu.projectmanagement\electron\node_modules\fable-compiler\dist\index.js:82:41)
         at Interface.emit (events.js:198:13)
         at Socket.onend (readline.js:171:12)
         at Socket.emit (events.js:203:15)
         at endReadableNT (_stream_readable.js:1145:12)
         at process._tickCallback (internal/process/next_tick.js:63:19)
     error Command failed with exit code 1.
     info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     Running build failed.
     Error:
     System.Exception: Error while running 'C:\Program Files (x86)\Yarn\bin\yarn.cmd' with args: run compile
        bei FSI_0005.Build.run'@50-3.Invoke(String message) in C:\WORK\psBdKN2R\0\products\msu.projectmanagement\build.fsx:Zeile 50.
        bei FSI_0005.Build.run'(TimeSpan timeout, Lazy`1 cmd, String args, String dir) in C:\WORK\psBdKN2R\0\products\msu.projectmanagement\build.fsx:Zeile 50.
        bei FSI_0005.Build.run@52.Invoke(Lazy`1 cmd, String args, String dir) in C:\WORK\psBdKN2R\0\products\msu.projectmanagement\build.fsx:Zeile 52.
        bei Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:Zeile 626.


Looks like the exception wasn't catched

**Comment by MangelMaxime** [comment]
@forki 

Are you sure you are running `fable-compiler` 2.9.0 ?

Because, if I am on purpose making the JSON serialization failed I do pass in the try-catch.

```
fable-compiler 2.9.0
JSON parsing failed on {"sourceType":"module","body":[{"source":{"value":
C:\Users\Maxime\Documents\Workspaces\Github\Fable\Fable\src\fable-compiler\dist\index.js:87
                    throw (error);
                    ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Interface.<anonymous> (C:\Users\Maxime\Documents\Workspaces\Github\Fable\Fable\src\fable-compiler\dist\index.js:82:41)
    at Interface.emit (events.js:321:20)
    at Interface._onLine (readline.js:327:10)
    at Interface._normalWrite (readline.js:472:12)
    at Socket.ondata (readline.js:184:10)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

In order to troubleshoot, the problem on your machine you can do the following:

1. Run `npm run build compiler` <-- It will make sure you have the `fable-compiler` and all the stuff compiled correctly on your machine
1. Run `npx tsc --project src/fable-compiler -w` <-- Start compiling `fable-compiler` sources only in watch mode.
1. In another terminal and in your failing project, run `npm link relative/path/to/Fable/src/fable-compiler` near the package.json used to introduce `fable-compiler` dependency <-- This will tell `npm` to use the files from your computer as the source.

Run `npm unlink` in order to remove the link.

**Comment by forki** [comment]
Yes we're running 2.9 - the reported code place looks updated

**Comment by forki** [comment]
ok with the help of applying #2053 locally we found:

![image](https://user-images.githubusercontent.com/57396/82046987-45589600-96b2-11ea-965a-72eda70e3eca.png)

it's a big wall of text. I put it into a gist at https://gist.github.com/forki/8623d5fd0d9906fedd28cfda04bfe226.

the last bit is: ```"property":{"name":"isArray"``` 

so it looks like the text is not complete. 294871 chars

**Comment by alfonsogarciacaro** [comment]
Hmm, so it doesn't look as if another message is interrupting the JSON. I don't know what other problem may be happening. I'm using the [line reader API in node.js](https://nodejs.org/api/readline.html), maybe the JSON is hitting some limit on your CI server? (Although we do compile big files in Fable CI when converting the F# compiler to JS)

**Comment by inosik** [comment]
I'd check if the line (the `data` argument) contains a complete, valid JSON document here:

https://github.com/fable-compiler/Fable/blob/96f056834ffdef4db6c64be3c547aaf38a57af9e/src/fable-compiler/src/index.ts#L86

**Comment by alfonsogarciacaro** [comment]
I assume Fable 3 should help with this as we're not exchanging jsons anymore. Would it be possible to test your project with latest beta?

**Comment by atheck** [comment]
Hi, I tested with Fable 3 beta 005. Because it is an electron app, I have a Main and a Renderer project. So I have to call fable twice like this:

```sh
fable ../src/electron/Main/ --outDir dist/main/ --define 'ELECTRON' --run fable ../src/electron/Renderer/ --outDir dist/renderer/ --define 'ELECTRON' --run electron-webpack dev
```

But after compiling and before running electron-webpack, all compiled js files in dist/main are deleted, which results in an error:

Error: Cannot find entry file electron/dist/main/index.ts (or main.ts, or app.ts, or index.js, or main.js, or app.js)

Any hints?

**Comment by ncave** [comment]
@atheck Is that one big command? Perhaps try compiling the projects separately, to see what's going on.

**Comment by alfonsogarciacaro** [comment]
Thanks @atheck! Yes, I would try to run the commands in sequence (later we can try compiling the two Fable projects in parallel) to spot the issue more easily:

```
dotnet fable ../src/electron/Main/ --outDir dist/main/ --define 'ELECTRON'
dotnet fable ../src/electron/Renderer/ --outDir dist/renderer/ --define 'ELECTRON'
npx electron-webpack dev
```

In any case, Fable shouldn't delete files so I don't understand what's happening with `dist/main`. Is there something in your build pipeline that cleans the `dist` dir before running fable. Maybe you used to clean everything before, but because now it's two commands the second one may be deleting the result of the first. If those are npm scripts, can you share the "scripts" section of your package.json?

**Comment by atheck** [comment]
Thanks for the answers. The problem was that electron-webpack puts its output to the dist folder and deletes its contents first. So I changed the output folder of fable to "out". Now it's working with one command.

Now there is a compile error in the output of Fable. The F# code:

```fsharp
let defaultTheme themeID = Styles.createMuiTheme([
    theme.palette.type'.light
    theme.palette.primary'.main (getColor themeID ColorID.Button)
    theme.palette.secondary'.main (getColor themeID ColorID.InputBackground)
    theme.palette.text.primary (getColor themeID ColorID.Text)
    theme.palette.text.secondary (getColor themeID ColorID.SectionHeader)
    theme.palette.text.disabled (getColor themeID ColorID.DisabledText)
])
```

is transpiled to:

```js
export function defaultTheme(themeID) {
    let color, color_1, color_2, color_3, color_4;
    const props = ofArray([["palette.type", "light"], (color = getColor(themeID, new ColorID(8)), ["palette.primary.main", color]), (color_1 = getColor(themeID, new ColorID(12)), ["palette.secondary.main", color_1]), (color_2 = getColor(themeID, new ColorID(6)), ["palette.text.primary", color_2]), (color_3 = getColor(themeID, new ColorID(10)), ["palette.text.secondary", color_3]), (color_4 = getColor(themeID, new ColorID(9)), ["palette.text.disabled", color_4])]);
    const merge = [];
    let theme;
    theme = (function setProperty(target, key, value) {
    const sepIdx = key.indexOf('.')
    if (sepIdx === -1) {
    target[key] = value
    } else {
    const topKey = key.substring(0, sepIdx)
    const nestedKey = key.substring(sepIdx + 1)
    if (target[topKey] === undefined) {
    target[topKey] = {}
    }
    setProperty(target[topKey], nestedKey, value)
    }
    }
    const target = {}
    for (let kv of props) {
    setProperty(target, kv[0], kv[1])
    }
    return target
    );
    return StyleImports_createMuiTheme_argsArray(theme, ...merge);
}
```

ERROR in ./out/renderer/App.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  SyntaxError: /home/heck/Dokumente/Arbeit/Projekte/msu.projectmanagement/electron/out/renderer/App.js: Unexpected token, expected "," (222:4)

Line 222: const target = {}

Do you need more information?

**Comment by inosik** [comment]
@atheck Please raise an issue with [cmeeren/Feliz.MaterialUI](https://github.com/cmeeren/Feliz.MaterialUI). There's [an inner function](https://github.com/cmeeren/Feliz.MaterialUI/blob/f7c30c91d875770f1ade8a47c8a2273c0c0555d6/src/Feliz.MaterialUI/Flatten.fs#L32) which isn't quite right. In short, the emitted code should either be an IIFE or a proper function.

**Comment by forki** [comment]
summoning @cmeeren

**Comment by cmeeren** [comment]
> summoning @cmeeren

Here, what's up? If this is a bug with Feliz.MaterialUI, please raise an issue there (and if it requires a change to some pure JS code in `[<Emit>]`, a PR is welcome, since JS is not my strong suit). If this is not an issue with Feliz.MaterialUI, I don't think I can help much here, but feel free to ask a specific question.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the pointer @inosik! Indeed that function looks suspicious. Not sure if for some reason it worked in Fable 2 but in any case it's better to change. You can change it to an IIFE as @inosik suggests or wait for the incoming [emitJsStatement helper](https://github.com/fable-compiler/Fable/blob/0ec0e7eca6ddb3595046b2f2d704e7b7b524017c/src/quicktest/QuickTest.fs#L56-L63), but the following (not-so-nice) F# code should work anyways:

```fsharp
open Fable.Core.JsInterop

let fromFlatEntries (kvs: seq<string * obj>): obj =
    let rec setProperty target (key: string) value =
        match key.IndexOf(".") with
        | -1 -> target?(key) <- value
        | sepIdx ->
            let topKey = key.Substring(0, sepIdx)
            let nestedKey = key.Substring(sepIdx + 1)
            if isNull(target?(topKey)) then
                target?(topKey) <- obj()
            setProperty target?(topKey) nestedKey value
    let target = obj()
    for k, v in kvs do
        setProperty target k v
    target
```

**Comment by cartermp** [comment]
Should this issue be closed since it's an external library problem? (that got resolved)

**Comment by alfonsogarciacaro** [comment]
IIRC it was not exactly a library but the json sent from the Fable 2 server to Babel getting corrupted somehow. Luckily this is not an issue anymore with Fable 3 :+1:
