### ISSUE TITLE
Duplicate methods in prototype

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#2068]
> there are two cases where members are still attached to the prototype: overloads and interface implementations.

I've run again into one of the fundamental difference between dotnet and javascript, in that JS does not support method overloading, so methods from two different interfaces (or inherited methods with different signatures) are clashing names and one will overwrite the other.
Currently the way Fable is [dealing with that](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Transforms/Global/Prelude.fs#L140-L143) is to discard one of the implementations, which is not ideal, as they may not be the same.

Not sure what is the best way to overcome this impedance, perhaps coming up with some way of making methods unique instead of deleting one of them.

**Comment by alfonsogarciacaro** [comment]
Yes, before releasing Fable 2 I tried to fix this by wrapping the object when casting to an interface (although it didn't solve the issue with overloads) but this solution was discarded because of several issues ([like this one](https://github.com/fable-compiler/Fable/issues/1452)) including [a drop in performance](https://github.com/fable-compiler/Fable/issues/1452).

Without reinventing the wheel I guess the way to fix this is to add a virtual table including the name of the interface, the method and the overload hash. So whenever we're calling an abstract member (either from interface or abstract class):

- Check if the object implements the virtual table (it may be coming from JS)
- If it doesn't, call the method by its display name. If it does, get the method from the virtual table with the fully qualified name (type + method + overload hash).

> These steps will be done at runtime. I guess this will prevent some optimizations from JS engines, not sure if it will have a bigger or smaller impact than the wrapping in Fable 2 beta. We should try to do some benchmarking.

When implementing the abstract methods, we will still have to add the method by its display name to the prototype in case we want to send it to JS (unless we want to make this a breaking change in Fable 3, not sure how many users rely on this feature). In that case, still only one method can win.

**Comment by ncave** [comment]
@alfonsogarciacaro Perhaps a trivial question, but why are we attaching all interface methods to the prototype, shouldn't it be only for overrides?

**Comment by alfonsogarciacaro** [comment]
Two main reasons:

- Because we don't know the concrete type at compile time, the method has to be attached to the object (or more efficiently in JS, to its prototype) so we can locate and call it in runtime. For abstract methods in abstract classes, this is also the only way I found to emulate the behavior of the method being overriden even when we upcast the object. For example:

```fsharp
type A() =
    abstract Greet: unit -> string
    default _.Greet() = "Hello"
    member _.Greet2() = "Hello"
    
type B() =
    inherit A()
    override _.Greet() = "Bye"
    member _.Greet2() = "Bye"
    
let a = B() :> A
a.Greet() |> printfn "%s" // Bye
a.Greet2() |> printfn "%s" // Hello
```

- Interop with JS: Interfaces are used to type objects coming from JS. And you can also define interfaces to send F# objects to JS (that's why we don't use overload hashes). Abstract classes are also used for JS interaction sometimes, as with React class components.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, virtual methods (including from abstract classes) can be mapped well to the prototype chain, my question was more about interface methods specifically, do they all have to be attached to the prototype even if they're not inherited, or can they be more like regular methods.

**Comment by alfonsogarciacaro** [comment]
I'm thinking that we could implement the following changes (probably for Fable 3 as it could break some existing code):

- **Calling an abstract method:** Retrieve the method by using the full type name + method + overload hash from a virtual table, with an exception (see below). Also during a transition period we could include some defensive code as follows (we could also add a compiler option to remove the check):

```js
x.$vtable ? x.$vtable.["FullInterfaceName.methoName$overloadHash"] : x.methodName
```

 > Exception: If the interface (or the module containing it) is decorated with a special attribute, like `ExternalNoMangle`, don't try to access the virtual table.

- **Implementing an abstract method:** Implement it within the virtual table unless the interface is decorated with the special attribute. In that case, implementations are attached directly to the prototype with the method display name (we could try to add warnings if there are name conflicts, although I think I tried to implement these warnings already and they're not working well).

What do you think?

**Comment by ncave** [comment]
@alfonsogarciacaro I'm not sure on the performance of a runtime solution, but I guess it might work. I sometimes wish we could just limit the scope of the OOP support, so we could optimize the generated code much better without matching every feature. But that's just me QQ'ing, please ignore :)

But before that, what do you think about this more limited in scope interim solution:

Since my immediate issue is mainly with overloads introduced by explicit interfaces (e.g. `IEqualityComparer.Equals/GetHashCode` clashing with `Object.Equals/GetHashCode`, etc.), can we just prepend the explicit interface name to the method name, and still attach it to the prototype?
Something like `MyType.prototype.IEqualityComparer_Equals = ...`, would that work?

**Comment by alfonsogarciacaro** [comment]
Actually, I'm designing an API for interacting with databases in Node and the OOP features come in handy, but it's true it would be much easier to compile to and interop with JS if we didn't have to support all OOP in F#.

Well, that solution may work but if we don't add the overload hash we would still have issues with overloads. And I'm afraid it would still be a breaking change if we're using an interface to type an object from JS (and we cannot apply prepend the interface name only to classes implementing more than one interface because in the call site we're unaware of this fact).

We'd probably still need to add defensive code like:

```js
(myObject.IEqualityComparer_Equals ? myObject.IEqualityComparer_Equals : myObject.Equals)(x)
```

**Comment by ncave** [comment]
> if we're using an interface to type an object from JS 
- Can we handle those differently (i.e. not prepend interface name), if they have an "import" attribute attached to them?
- Alternatively, even simpler, but much more restricted, we can just white-list which interfaces we want to handle with prepend, and only do those.

**Comment by alfonsogarciacaro** [comment]
Yes, this is what I had in mind with a new attribute like `ExternalNoMangle`. Import won't work unfortunately because it's intended for actual values, not type declarations.

I would be a bit reluctant to the white-list as it feels a bit like a path and at some point we would probably need to extend the behavior anyways.

**Comment by alfonsogarciacaro** [comment]
So we could:

- Add a `mangleAbstractMembers` flag to compiler options. When activated, all abstract members will be mangled except for interfaces with `NoMangle` attribute (or interfaces contained in a module with `NoMangle` attribute).

- During a transition period this flag is set to false. But we can still mangle interfaces we're sure won't be used for objects coming from JS, either using a white-list or just all interfaces in the `System` namespace (although we may want to keep `GetHashCode` and `Equals` non-mangled).

- After the transition period the flag is set to true by default (and later we may just remove it). We may warn users for examples when they import a JS object using an interface that's not mangled.

**Comment by ncave** [comment]
@alfonsogarciacaro That's a very sensible approach, I like that.

**Comment by alfonsogarciacaro** [comment]
Fixed in Fable 3 with the (opt-int) Mangle attribute
