### ISSUE TITLE
Slow Compilation Results

### ISSUE THREAD

**Issue by aspnetde** [fable-compiler/Fable#2079]
I am playing with Fable for the first time, using @Zaid-Ajaj's fantastic [Elmish Book](https://zaid-ajaj.github.io/the-elmish-book/) and its samples. What I immediately noticed is the slow compilation performance on my MacBook Pro Late 2016, which is not the fastest but has been good enough until now to compile large Xamarin apps for iOS and Android from time to time:

To give you some examples:

1. [Elmish Counter, macOS](https://twitter.com/asp_net/status/1270404170470830085?s=20)
2. [Elmish counter, Windows 10 (Dell XPS13, latest model, maxed config)](https://twitter.com/asp_net/status/1270444589850247170?s=20)
3. [SAFE Conf Planner, macOS](https://twitter.com/asp_net/status/1270410964916207616?s=20)

As much as I love F# – if I cannot improve those build times, this would be a real show-stopper.

Has anyone an idea what could be "wrong"?

Cheers

Thomas

PS: My dependencies look like this right now:

```json
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "fable-compiler": "^2.10.1",
    "fable-loader": "^2.1.9",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  }
```

**Comment by aspnetde** [comment]
Update 1: Using `Fable.Template` works as expacted, performance-wise: https://twitter.com/asp_net/status/1270469431341318146

**Comment by aspnetde** [comment]
I found it. In `webpack.config.js`, `mode` must be set to `development`. Otherwise a full compilation seems to take place.

**Comment by aspnetde** [comment]
Hey everyone,

After looking into Elmish et al. for a couple of days now, I am on one hand pretty much amazed by the whole stack, on the other hand I am left with a couple of concerns. One of the bigger ones is scalability in terms of compiler performance.

Hot Module Reloading works amazingly fast. However, even for the smallest possible hello world sample compiled by Fable, the initial/complete/full compile cycle appears to be very slow. No matter if executed on macOS (my main system) or Windows. See the recordings in the Tweets linked in the original post above.

To quote @rommsen:

> Hmm. Just tried https://github.com/SAFE-Stack/SAFE-ConfPlanner Initial start (in watchmode) with webpack mumbo jumbo: 30sec Changing a couple of files when its running: almost not measurable, at most 0,5 sec Surfacebook 2, Windows 10, Netcore 3.1

30s for an application of that size is remarkable.

And this one [statement](https://twitter.com/jbeeko/status/1271276368022523904):

> [...] The tool chain normally used is very slow. About 7 or more seconds for a trivial project, vs ms for ReasonML via BuckleScript. But... http://TryFSharp.com, Fable in the browser,  will compile the same code at least twice as fast.

Why is that?

I am not here to complain, but to understand. I also wonder if there is some known bottle necks, some low hanging fruits, something that is on the roadmap (to be investigated or improved)? 

If I make the decision for my business to bet on Fable, I would not want to find ourselves regularily buying new hardware in order to keep compile time at a reasonable level – that's where I am coming from (building Xamarin apps for the last years).

Thomas

**Comment by alfonsogarciacaro** [comment]
Yes, the first compilation of Fable is slow. Most of the effort we did went into improving the watch compilations which is what happens more often during development. But I understand it's a bit painful when you start the compiler to quickly check something.

Why is it so slow? _Grosso modo_:

- Neither the F# compiler nor Fable are very fast ;) Although improvements in the F# compiler also improve Fable compilation times too.
- Fable needs to compile **all the source files**, including those from packages, unlike in .NET where the packages are already compiled in the form of .dll. Fable needs the sources because it's the only way of accessing the TypedTree of inline functions, which is important for SRTP resolution and other stuff.

When you see the message `Parsing MyProject.fsproj...` this is the F# compiler parsing the sources to provide the TypedTree. As far as I know, this doesn't use multithreading. When you start to see messages like `fable: Compiled Myfile.fs` this is Fable already kicking in and responding to requests from the JS client (fable-loader or fable-splitter). The files are compiled in parallel, so in theory with more cores it could be a bit faster.

What things could be done to improve performance? I can think of the following for example:

- Profile the compiler and see which functions are taking too long. In the past we managed to find a couple of bottlenecks this way, but it's been a while since we haven't done it. If we want to give it a try, you need to start Fable.Cli independently of the JS client as it's explained here: https://github.com/fable-compiler/Fable/issues/1787#issuecomment-493984321

- Replace Json.net with the new Json serializer in netcore: https://github.com/fable-compiler/Fable/blob/7d02d3e690a9b15cb7ca823b90c20f46f13f2a37/src/Fable.Cli/Agent.fs#L277-L279

- Fable runs `dotnet restore` before compilation because devs (including myself) usually forget to do it and the error messages in that case were misleading. This takes a few seconds at the beginning, we could enable a `--no-restore` option to kip that.

- As the sources from the packages won't change unless you update the dependencies it'd be great if we could cache the TypedTree for them somehow. I think we've talked a few times in the past about that but don't think we can serialize the classes from FCS with BinaryFormatter or similar. Maybe @ncave has some ideas?

**Comment by aspnetde** [comment]
Thanks @alfonsogarciacaro for the detailed feedback, really appreciate it. I might look into it and profile myself at some point – however, right no I am overwhelmed with learning about all the new stuff :-).

> Replace Json.net with the new Json serializer in netcore

I didn't follow the development closely, is it supposed to be faster?

3 years ago I had the glorious idea to implement a [Redux store in a Xamarin application](https://thomasbandt.com/fsharp-redux-store-for-xamarin-apps). The whole thing relies on a big central tree (the state) that needs to be serialized in order to be persisted. Turns out: Serializing F# stuff is surprisingly slow and also not that well supported along .NET-based serialization libraries. While most have trouble to work with things like discriminated unions and cannot be used at all, we eventually fell back on Newtonsoft.Json, as the performance gains were not that big with those we could consider to be an alternative. But the netcore serializer wasn't released at the time.

> Fable runs dotnet restore before compilation because devs (including myself) usually forget to do it and the error messages in that case were misleading.

Maybe there is a way to check if a restore has been taken place at least once, and in case of a build failure provide a hint like (like "Did you make sure you ran `dotnet restore`?")?

> As the sources from the packages won't change unless you update the dependencies it'd be great if we could cache the TypedTree for them somehow.

I think that's similar to `dotnet restore` and would definitely make sense.

However, it is all addressing the symptoms rather than the cause. Would be cool to know what that is exactly (besides thet F# compiler itself, which should become a bit faster with .NET 5 as far as I know).

Also: What's the main difference to ReasonML/BuckleScript with regard to Fable? The "core library" which needs to be processed by Fable, but isn't available through the former?

**Comment by ncave** [comment]
@alfonsogarciacaro Serializing the typechecker cache to files and rehydrating it on start will obviously speed things up, but the question is what format to use, and do we use single file, multiple files or some db format to store multiple entries.

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm thinking now it could be easier to cache directly the generated JS and manage it from the client (like fable-loader). I'll give it a try.

**Comment by Shmew** [comment]
Not much to add here, but the fastest json library afaik is [Utf8Json](https://github.com/neuecc/Utf8Json).

**Comment by alfonsogarciacaro** [comment]
Closing as compilation is becoming faster in Fable 3. For Fable 3.1 we will try to implement #2200 so we don't need to recompile the dependencies every time.
