### ISSUE TITLE
Async.Sequential does not exist

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#2093]
In the repl:

![image](https://user-images.githubusercontent.com/4236651/84596048-a31c0180-ae5b-11ea-8132-d7498696120d.png)

**Comment by TerenceHinrichsen** [comment]
I have the same - project compiles, but warning:
"export 'sequential' was not found in '../xxxxxxxx/.fable/fable-library.2.13.0/Async.js'

**Comment by MangelMaxime** [comment]
Hum, I think that `Async.sequential` is not implemeted in fable-library because when searching for `sequential` in [Async.ts](https://github.com/fable-compiler/Fable/blob/master/src/fable-library/Async.ts) it yield zero results.

I guess we miss either implementing it or adding the standard Fable message: `Fable can't find replacements for ....`
