### ISSUE TITLE
Support Tasks

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#2095]
Currently Fable can't resolve a `Task`, I think a lot of libraries would be Fable compatible ootb or with significantly less work. I've been working on bringing [FSharp.Control.AsyncSeq to Fable](https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/114), and dealing with Tasks is the biggest hurdle I have left.

**Comment by alfonsogarciacaro** [comment]
Well, if Fable supported the whole BCL most libraries would be Fable compatible out of the box :)

My reply is usually the same. Fable's goal is more about compiling F# to JS rather than running .NET on the browser (there are other projects for that). We're open to contributions to extend the BCL support if it's done in a way that doesn't make the bundle size explode, but I see little benefit in supporting `Task` as, due to the single-thread nature of JS, it would just become another way to wrap callbacks and many features would have to be faked or remain unsupported (as it already happens with `Async`).

About `AsyncSeq` the old fable-powerpack [had support for `PromiseSeq`](https://github.com/fable-compiler/fable-powerpack/tree/master/src/extra/PromiseSeq) (which was just an adaptation of `AsyncSeq`), maybe it helps?

**Comment by Shmew** [comment]
Yeah I assumed that would be the answer, but worth a shot 😅 

Thanks for the quick reply!
