### ISSUE TITLE
Async.StartImmediate swallows exceptions

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#2115]
### Description

Unlike CLR implementation, Fable's `Async.StartImmediate` swallows the exceptions thrown in the async body.

### Repro code
```fsharp
try
  async {
    failwith "expected"
  } |> Async.StartImmediate
with
  ex -> printf "cought: %A" ex
```

### Expected and actual results

Should raise the exception thrown, but doesn't.

### Related information

* Fable version: reproducible in fable.io/repl
* Operating system: N/A

**Comment by alfonsogarciacaro** [comment]
I think we had this discussion before, but I don't remember the issue. If I recall correctly, the problem is we cannot propagate an exception from a promise or a callback (which is how async is translated). Not sure if there's a solution to this 🤔

**Comment by reinux** [comment]
Unless I'm missing something, it should seem to make sense that an async exception wouldn't get caught.

On the other hand, it would be good if it could report the exception to the console the way exceptions ocurring elsewhere do, since otherwise it's just a silent failure, and it's time consuming to hunt down exactly where it went wrong.

For my own purposes, I've wrapped `Cmd.OfAsyncImmediate` calls with something that'll `console.log` the exception.

**Comment by alfonsogarciacaro** [comment]
It's one of the nuances in semantic differences between .NET and JS runtimes. `Async.StartImmediate` does return to the thread that started it, but just because JS is single-threaded. However, it's not possible to throw uncaught exceptions in the thread if we've used an external API like fetch.

Logging the exception looks like a good compromise though 👍

**Comment by et1975** [comment]
I'm kinda torn on this one:
1. From runtime perspective your code is not allowed to throw when running on the thread pool.
2. `Async`, even if scheduled with `StartImmediate` may schedule some continuation it awaits on to be run on the thread pool thread, which leads to the 1. consideration.
3.  Awaiting on an `Async` always surfaces the exception if it happens in the computation being awaited on. 
4. `StartImmediate` most empathically does not await on the result, it just co-opts current thread to start the async on it.

So, FSharp.Core implementation handles the exception in this case, but I'm not sure why. It might be specific to the computation body itself, which means shouldn't care about such an implementation detail and just keep in mind the points above.
Feel free to close it, @alfonsogarciacaro.

**Comment by et1975** [comment]
Btw, I just tried:
```fsharp
try
  async {
      do! Async.Sleep 1000 
      failwith "expected"
  } |> Async.StartImmediate
with
  ex -> printf "cought: %A" ex
```
and it crashed my FSI, as expected. So it depends on what the computation itself does, which confirms to me that we can ignore it as an implementation detail. Closing.

**Comment by reinux** [comment]
Should I start a feature suggestion issue in regards to logging to the console? Silent failures are really hard to debug, so it would be nice to have.
