### ISSUE TITLE
Better support for reflection on erased unions

### ISSUE THREAD

**Issue by rmunn** [fable-compiler/Fable#2131]
### Description

A discriminated union with the `[<Erase>]` attribute is apparently treated as `System.Object` by the Fable reflection API, which caused me some trouble when trying to serialize & deserialize an erased union to & from JSON. Originally reported at https://github.com/thoth-org/Thoth.Json/issues/49 but after much discussion, [the conclusion was](https://github.com/thoth-org/Thoth.Json/issues/49#issuecomment-653677219) that Fable isn't providing the reflection info that Thoth.Json needs to deserialize the type correctly and so this needs to be reported as a Fable issue.

### Repro code

https://github.com/rmunn/repro-json-parsing-failure has a reproduction. As is, that repro will produce a console error "TypeError: Cannot read property 'tag' of undefined" when you click on the "Get Packages" button. To make it *succeed* instead of failing, apply the following patch:

```diff
diff --git a/src/Client/Client.fs b/src/Client/Client.fs
index e688b4a..0462bdb 100644
--- a/src/Client/Client.fs
+++ b/src/Client/Client.fs
@@ -26,10 +26,10 @@ type Msg =
     | Decrement
     | InitialCountLoaded of Counter
     | LoadPackages
-    | PackagesLoaded of JsonResult<Packages>
+    | PackagesLoaded of Packages
 
 let initialCounter () = Fetch.fetchAs<Counter> "/api/init"
-let loadPackages () = Fetch.fetchAs<JsonResult<Packages>> "/api/json"
+let loadPackages () = Fetch.fetchAs<Packages> "/api/json"
 
 // defines the initial state and initial command (= side-effect) of the application
 let init () : Model * Cmd<Msg> =
@@ -56,12 +56,11 @@ let update (msg : Msg) (currentModel : Model) : Model * Cmd<Msg> =
         let loadCmd =
             Cmd.OfPromise.perform loadPackages () PackagesLoaded
         currentModel, loadCmd
-    | _, PackagesLoaded jsonResult ->
-        unpackJsonResult currentModel jsonResult (fun packages ->
+    | _, PackagesLoaded packages ->
             console.log("Loaded packages: ", packages, " successfully")
             for pkg, ver in packages.devDependencies |> Map.toSeq do
                 console.log("Version of ", pkg, " is: ", ver)
-            currentModel, Cmd.none)
+            currentModel, Cmd.none
     | _ -> currentModel, Cmd.none
 
 
diff --git a/src/Server/Server.fs b/src/Server/Server.fs
index 51c1d01..7b5c9c6 100644
--- a/src/Server/Server.fs
+++ b/src/Server/Server.fs
@@ -38,7 +38,7 @@ let webApp = router {
                     "fable-compiler", "^2.4.6"
                     "fable-loader", "^2.1.8"
                 ]}
-            return! jsonSuccess packages next ctx
+            return! json packages next ctx
         })
 }
```

As you can see, the only difference between success and failure is that instead of sending a `Packages` data type via the API, I'm sending a `JsonResult<Packages>` data type. The JsonResult type looks like this:

```fsharp
// ***** Shared code in Shared.fs, imported by both client and server
type JsonSuccess<'a> = {
    ok : bool
    data : 'a
}

type JsonError = {
    ok : bool
    message : string
}

// ***** Client-side code in JsonHelpers.fs, loaded in Client.fs by "open JsonHelpers"
[<Erase>]
type JsonResult<'a> =
    | Success of JsonSuccess<'a>
    | Failure of JsonError
```

### Expected and actual results

Expected: two package versions print to the Javascript console.
Actual: Console error "TypeError: Cannot read property 'tag' of undefined".

### Related information

* Fable version: 2.4.6 (have not yet been able to test on later versions of Fable)
* Operating system: Linux (Ubuntu 18.04)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed reported @rmunn. I understand the type info for the erased type would be useful in this case, but as Bartleby would say, "I would prefer not to":

- Conceptually erased types are, precisely, erased. The type is removed in the generated code and type information shouldn't be available either.
- Even if we decide to implement it, it's going to be complicated and prone to failure. In Thoth auto coders, type info is used to generate a encoder/decoder for each type. But for erased unions we would have to generate two or more encoders **plus** a type test (which has weak support in Fable) to decide what's the actual type of the runtime object. And the decoders would have to be combined with something like `Decode.oneOf` but this can easily conflict too (in your example, imagine `JsonError`  has also shape `{ok, data}`.

Erased union types were added to Fable just to represent Typescript union types when translating .d.ts files, and I'd like to avoid having them as "first-citizens" of Fable type system, because they introduce complexity and diverge from standard F#.

Not sure why you need the erased union here, but I'd recommend to just use a normal union. If that's not possible, you can still use a custom coder in Thoth. Right now, that would likely be tricky too because you won't have access to the type name either but _maybe_ we could just emit the type name as a common point of agreement.

**Comment by rmunn** [comment]
It's been six months since I worked on that project, but I believe I wanted to produce JSON where the "ok" property would always be present, but the "data" property would only be there if "ok" was true; if "ok" was false, I wanted the "message" property instead. And with normal (non-erased) unions, the case name was getting serialized. So as you say, a custom Thoth coder would have been a better solution to my issue. (I eventually went with a design where the JSON returned by the API would always have a data property and a message property, and abandoned my attempt to use an erased union there).

**Comment by alfonsogarciacaro** [comment]
If I'm not mistaken, Thoth won't include optional arguments set to None in the json, so something like this should work (of course, it's not as nice because it makes it possible to have both message and data at the same time):

```fsharp
type JsonResult<'a> = {
    ok : bool
    message: string option
    data : 'a option
}
```

**Comment by MangelMaxime** [comment]
The behaviour @alfonsogarciacaro is speaking of is only for the `Auto` modules when setting `skipNullField = true`. Of course, when using manual encoder/decoder you can generate whatever you want.

**Comment by rmunn** [comment]
As I mentioned in my earlier comment, I'm fine with this not being implemented if it would be too difficult. I'll leave the issue open in case you want to consider adding the necessary type information later on, but feel free to close it if your "I would prefer not to" gels into a firm "won't fix" decision.

**Comment by alfonsogarciacaro** [comment]
I'll close this so we can focus on other issues but please feel free to reopen if you have any other suggestion/comment.
