### ISSUE TITLE
Model AST.Babel with unions

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2158]
When I wrote the Babel AST implementation I chose classes over unions because the structure was not purely hierarchical as some nodes could appear in different places. But after the AST simplification I think it should be possible to turn the classes into unions. Is it worth it? Would it improve the code? What do you think @ncave?

**Comment by ncave** [comment]
@alfonsogarciacaro I guess there are pros and cons. I don't know, it works now, and if changing it will be a departure from a well-documented Babel AST representation for JS, that may be detrimental. I guess it depends on your definition of "improving".

**Comment by alfonsogarciacaro** [comment]
I do totally agree there's value in keeping the JS AST conforming to Babel-spec. I was hoping that modeling with union types wouldn't cause any deviation (I've already deviated slightly in a few cases). I guess the main advantage would be using pattern matching if we have to operate on the JS AST. So far we didn't have to do it as we sent the AST straight to Babel, but now the printers do inspect the AST sometimes. It's possible to use type testing for this although we have to be careful when self-compiling Fable because we cannot type test interfaces: https://github.com/fable-compiler/Fable/commit/bacc5e26196b8ad29cc8b5e25129e6fb76bcc832#diff-30eb58b256eb39dbc630650ff978e105R166

Operating on the JS AST may become more common if we allow plugins to do it to solve specific needs as in these requests: https://github.com/fable-compiler/Fable/issues/1974 https://github.com/fable-compiler/Fable/pull/2066#issuecomment-668600721

One potential drawback is we wouldn't be able to use optional arguments any more, so constructors may look "less clean".

**Comment by dbrattli** [comment]
@alfonsogarciacaro I think it works well with the Babel AST even if pattern matching is a lot of `:?`. Could I perhaps use active patterns for cleaning it up? You can have a look at my latest effort at https://github.com/dbrattli/Fable/pull/1 It's a step backward in what can be translated, but it looks much more promising IMO.

**Comment by dbrattli** [comment]
@alfonsogarciacaro  I btw decided to rewrite the Python AST (initially modeled as the Babel AST) into records and unions. With composition the "inheritance" is sort of turned on it's head. But it's nice to look at e.g Expression and see the list of "sub-expressions".  I also added a static `Create` method to each type that takes optional parameters and upcasts, so e.g `Emit` is upcasted to `Expression` when created. 

```fs
static member Create(value, ?args): Expression =
    {
        Value = value
        Args = defaultArg args []
    }  // Emit
    |> Emit // Expression
```

Each type also impl an `IPrint` i.e

```fs
type IPrint =
    abstract Print: Printer -> unit
```

- Before (inheritance): https://github.com/dbrattli/Fable/blob/3863ca8d506d96ab7a935724eb286b29f784b15b/src/Fable.Transforms/Python/Python.fs#L226
- After (du/record): https://github.com/dbrattli/Fable/blob/python/src/Fable.Transforms/Python/Python.fs#L230

I mostly use records instead of tuples since it's nice to pattern match on the keys even for single case types. And it's easier to extend the types when they are records (with e.g SourceLocation etc). 

So if you like the change there I, then I could do a similar rewrite for the Babel AST. It would make it much easier for me to pattern match over  e.g a sub-tree of expressions.
