### ISSUE TITLE
getEnumerator missing on regex match.Groups

### ISSUE THREAD

**Issue by chillitom** [fable-compiler/Fable#2167]
Using RegEx groups and getting the following warning `export 'getEnumerator' was not found in '../Proj/.fable/fable-library.2.13.0/RegExp.js'`

`match.Groups` is not iterable.

Fable version 2.13

Repo:

```fsharp
    open System.Text.RegularExpressions

    let (|Regex|_|) pattern input =
        let m = Regex.Match(input, pattern)
        if m.Success then Some(List.tail [ for g in m.Groups -> g.Value ])
        else None
```

Workaround:

```fsharp
let (|Regex|_|) pattern input =
    let m = Regex.Match(input, pattern)
    if m.Success then
        Some [ for x in 1 .. m.Groups.Count - 1 -> m.Groups.[x].Value ]
    else 
        None
```

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @chillitom! Hmm, `match.Groups` iteration [should work](https://github.com/fable-compiler/Fable/blob/ab186a4dd4096e2ea78f30fdc4e1ac095153fc9e/tests/Main/RegexTests.fs#L102), but it's true the Regex API is a bit particular because it's old and doesn't implement the generic `IEnumerable<Group>` so maybe we need to do something for the sequence expressions. I'll have a look.

**Comment by alfonsogarciacaro** [comment]
Will be fixed in Nagareyama (Fable 3).
