### ISSUE TITLE
byte[] in Fable 3 is no longer UInt8Array?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2197]
Hi @alfonsogarciacaro, I was hitting a wall when trying to send binary data to the server and it turns out Fable 3 (currently 008-alpha) doesn't treat byte[] as a typed `UInt8Array` during runtime but instead as a normal array of numbers. Is this intentional?
```fs
let input = [| byte 1; byte 2; byte 3|]
``` 
The `input` from the line above would compile to `UInt8Array` in Fable 2.x but it compiles to an array of numbers in Fable 3. 

This is workable, however it is a bit inconvenient and would cause a bunch of breaking changes to existing code that assumes the typed array representation (when uploading, downloading etc.)

**Comment by alfonsogarciacaro** [comment]
Sorry for that @Zaid-Ajaj. This was changed in #2090, although the behavior was untouched, only the default value for the `--typedArrays` option changed. This was because there were bugs coming from time because of issues with JS interaction due to the typed arrays and I thought nobody was using them. I'm happy to see they were useful for you 😄 

I think we can avoid the breaking change in two ways:

- Go back to `typedArrays=true` by default. Besides JS interaction, a problem can arise when a library relies on this but a user set it to default.
- Let libraries define their own Fable compiler options properties (currently the options set by the user are used for all the sources), probably through properties in the .fsproj as Femto does.

**Comment by Zaid-Ajaj** [comment]
Thanks for the follow up @alfonsogarciacaro, I don't think that libraries should provide compiler options, this goes against the idea of compiler options in the first place: imagine two libraries defining different Boolean values for a compiler option, that would be quickly ambiguous. Instead, I like option 1 more to retain backward-compat from Fable 2,x

If possible however, somehow exposing the compiler options and compiler versions to client libraries would be great, so that infra libraries can provide compatible behaviour.

**Comment by alfonsogarciacaro** [comment]
3.0.0-nagareyama-alpha-009 is release with typedArrays as default again :+1: (Use `--noTypedArrays` option to disable the behaviour)
