### ISSUE TITLE
Remove redundant else block from unit-returning functions in Fable 3

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2216]
### Description

Remove redundant else block from unit-returning functions in Fable 3

(I would like to have a look and give this one a try to fix :smile:) 

### Repro code

Given the snippet:
```fs
let stuff(n) =
    if n = 1
    then printfn "Hello"
```
It generates:
```js
export function stuff(n) {
    if (n === 1) {
        String_toConsole(String_printf("Hello"));
    }
    else {
    }
}
```
Ideally, the `else` branch should be emitted:
```js
export function stuff(n) {
    if (n === 1) {
        String_toConsole(String_printf("Hello"));
    }
}
```

### Related information

* Fable version: 3.0.0-nagareyama-alpha-015
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Yes, there's a note about this: https://github.com/fable-compiler/Fable/blob/f37a97e61bb67d0c921a1d3780cb361ff975d9fb/src/Fable.AST/Babel.fs#L497-L502

I guess we need to make this function return the productive statements instead of printing them directly and skip the `else` block if the array is empty: https://github.com/fable-compiler/Fable/blob/f37a97e61bb67d0c921a1d3780cb361ff975d9fb/src/Fable.AST/Babel.fs#L40
