### ISSUE TITLE
Compiler exception `Method not found` when compiling a Feliz app with Nagareyama beta 4

### ISSUE THREAD

**Issue by gaku-sei** [fable-compiler/Fable#2244]
### Description

I get this error with the latest Fable version `3.0.0-nagareyama-beta-004`:

```
error EXCEPTION: Method not found: 'Void Fable.AST.Fable.MemberDecl..ctor(System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1<Fable.AST.Fable.Ident>, Fable.AST.Fable.Expr, Fable.AST.Fable.MemberInfo, Microsoft.FSharp.Collections.FSharpSet`1<System.String>)'.
```

### Repro code

To reproduce you can clone https://github.com/gaku-sei/fable-next-starter and set the `version` to `3.0.0-nagareyama-beta-004` in the `.config/dotnet-tools.json` file. Notice that version `3.0.0-nagareyama-beta-004` works as expected 😕 
(I wanted to try beta 4 to have the non prefixed React hooks 😄 )

### Related information

Mac OS 10.15.7

**Comment by Zaid-Ajaj** [comment]
Hi @gaku-sei can you please upgrade to Feliz v1.16.1 it should solve this issue

> Also this version of Feliz is still [WIP](https://github.com/Zaid-Ajaj/Feliz/pull/266) because I am testing out the plugin implementation and it might change (giving you errors such as the one above) I would wait until the PR is merged and an announcement is made :smile:

**Comment by gaku-sei** [comment]
Wouah! Thank you very much @Zaid-Ajaj for your super quick reply and your advices.

I confirm that updating to Feliz 1.16.1 and changing the attribute to `[<ReactComponent(exportDefault=true)>]` works perfectly 😄

**Comment by alfonsogarciacaro** [comment]
@gaku-sei I just realized you see `Feliz_React__React_useElmish_Static_17DC4F1D` not because the import member is prefixed but because this is the actual mangled name of the `useElmish` helper in Feliz: https://github.com/Zaid-Ajaj/Feliz/blob/ef1ccc7302fe4ad475fcd308b8a2e70b1fffab0a/Feliz.UseElmish/UseElmish.fs#L59

@Zaid-Ajaj To avoid this (without using plugins or other compiler magic) you would have to inline and ultimately call a function in the root module of the file named `useElmish` or similar. You can also avoid a similar issue with `useState` helpers and friends by inlining the [intermediate functions](https://github.com/Zaid-Ajaj/Feliz/blob/ef1ccc7302fe4ad475fcd308b8a2e70b1fffab0a/Feliz/React.fs#L72) (some of them already are).
