### ISSUE TITLE
Regression in Fable 3 when emitting functions via Emit attribute

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#2249]
### Description

There's a regression in Fable 3, when the `Emit` attribute is used to emit a function. This was [reported](https://github.com/fable-compiler/Fable/issues/2043#issuecomment-721567953) by @atheck. I reduced the repro sample.

The [original code](https://github.com/cmeeren/Feliz.MaterialUI/blob/f7c30c91d875770f1ade8a47c8a2273c0c0555d6/src/Feliz.MaterialUI/Flatten.fs#L32) emits a non-trivial function with the `Emit` attribute, which might be a "happens to work, but never actually supported" thing, so feel free to close this.

### Repro code

``` fsharp
open Fable.Core

[<Emit "return $0">]
let id (x : 'a) : 'a = jsNative

let x = id 42
```

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDaAPAKIC2AlgC5QBEOVArltACQAMtAfALq4o0KAEygAKAB5QAXFADkcAJTS5cKAF4oAKwDOAOThUKANzz8wNSRuFQALACZcQA&html=Q&css=Q)

### Expected and actual results

This is what we get in the REPL:

``` js
export const x = function () {
  return 42;
}();
```

And this is what we get with Fable 3:

``` js
export const x = return 42;
```

In Fable 2, Babel might have recognized this and wrapped it in an IIFE by itself. In Fable 3 however, we don't use Babel anymore, so that's probably why this regressed.

In _Fable.Core_ 4, the `Emit` attribute has an additional parameter `isStatement`, added in #2138. When it's set to `true`, Fable turns the code in an IIFE, instead of printing it as-is. @alfonsogarciacaro maybe you noticed this back then already and added the new parameter for that reason.

### Related information

* Fable version: 3.0.0-nagareyama-beta-005
* Operating system: N/A

**Comment by Zaid-Ajaj** [comment]
That's probably not the best way to use Emit when you have such a multi-line functions. Instead, you can export the function from a JS file and use import to bring it locally from the F# file and call it (remember to include the JS file in the nuget package)

**Comment by alfonsogarciacaro** [comment]
Your intuitions are correct @inosik. So far, `Emit` was considered to always emit a JS expression (vs a JS statement like `return`, `throw` or `debugger`), so in this case Fable was automatically adding the `return` statement. Not entirely sure why this worked in Fable 2, but maybe it's because we were using [babel-template](https://babeljs.io/docs/en/babel-template) for building the Babel AST from a string, and this was fixing the issue.

In Fable 3, because we have our own printer and the code string is printed directly without any analysis (besides argument substitution) we need to make the distinction between JS expressions and statements explicitly or you'll get double `return` (the one inserted by Fable plus the one in the code string), that's why now you can mark explicitly that `Emit` contains a JS statement.

I doubt we can "fix" this to get the same behavior as in Fable 2, as checking whether a code string is a JS expression or statement is not trivial. We will have to spot the issues and fix them. The recommended way when you have complicated JS code has always been to put in a separate JS file and import it as @Zaid-Ajaj says, so I'd prefer to consider this as "happened to work, but never actually supported", as you say 😊

**Comment by inosik** [comment]
Thanks @alfonsogarciacaro, your explanation confirms what I was thinking 👍
