### ISSUE TITLE
Fable 3 - Cannot resolve member extension

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2250]
Hello,

first of all, great job on this new iteration of Fable 3. I am just toying with it but really like the new direction in term of UX and also the performance improvement :)

### Description

When using member extension on a type coming from `System` Fable 3 doesn't resolve the member extension.

### Repro code

```fs
    type System.Math with
        static member Clamp (value, (min: float), (max: float)) =
            let mutable res = value
            if value < min then
                res <- min
            if value > max then
                res <- max
            res

    printfn "%A" (System.Math.Clamp(14, 0, 12))

    let v = System.Math.Clamp(14, 0, 12)

    printfn "%A" v
```

```js
import { printf, toConsole } from "../.fable/fable-library.3.0.0-nagareyama-beta-005/String.js";

export function System_Math__Math_Clamp_Static_Z7AD9E565(value, min, max) {
    toConsole(printf("User implemented clamp function"));
    let res = value;
    if (value < min) {
        res = min;
    }
    if (value > max) {
        res = max;
    }
    return res;
}

(function () {
    const arg10 = null;
    const clo1 = toConsole(printf("%A"));
    clo1(arg10);
})();

export const v = null;

(function () {
    const arg10 = v | 0;
    const clo1 = toConsole(printf("%A"));
    clo1(arg10);
})();
```
### Expected and actual results

It should use the defined `Clamp` method.

### Related information

* Fable version: `3.0.0-nagareyama-beta-005`
* Operating system: `Windows 10`

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! I'm glad you like Fable 3 😄 

I've tested your sample with latest Fable build and also .NET. It seems it's expected that F# gives precedence to the type member than an extension. In you example, the arguments of the extension are floats and the call uses ints, but even if I change them, the native method is still called. You can test this by returning `5` for example from the extension method but you will still get `12` when running `dotnet run`. If you want to call the extension method you need to use a different name or an overload that is not existing in `System.Math`.

The problem here is actually we don't have a replacement for `System.Math.Clamp`, we probably should implement it.

**Comment by MangelMaxime** [comment]
Hum, ok I see.

In the past, using method extensions was enough to get around the missing replacement that's probably why it break my code. 

Adding the replacement to `System.Math.Clamp` makes sense as this is not a huge function I think.

Here is an implementation of  `Clamp` which doesn't really on a mutable variable if we prefer.

```fs
Math.Max(Math.Min(value, Math.Max(min, max)), Math.Min(min, max))

clamp (4., 5., 15.)|> printfn "%A" // Should return 5
clamp (5., 5., 15.)|> printfn "%A" // Should return 5
clamp (10., 5., 15.)|> printfn "%A" // Should return 10
clamp (15., 5., 15.)|> printfn "%A" // Should return 15
clamp (16., 5., 15.)|> printfn "%A" // Should return 15
```

or

```fs
    if value < min then
        min
    else if value > max then
        max
    else
        value
```

I am not sure which one is better. I guess the second one is easier to read.
