### ISSUE TITLE
Specifying --optimize prevents constant folding of strings

### ISSUE THREAD

**Issue by bklop** [fable-compiler/Fable#2254]
### Description
I know that the FCS option --optimize is probably still considered experimental, but it does a bunch of handy optimizations in some cases. One issue I found is that it prevents constant folding of strings (string concatenation) by the Fable optimizer.

### Repro code
```
let a = "foo" + "bar"
```

### Expected and actual results
The code above (correctly) compiles to:

```
export const a = "foobar";
```

When specifying --optimize it compiles to:
```
import { concat } from "./.fable/fable-library.3.0.0-nagareyama-rc-002/String.js";
export const a = concat("foo", ..."bar");
```

### Related information
* Fable version: 3.0.0-nagareyama-rc-002
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Well, it's experimental because we're not running the tests with this option (and in fact they don't pass) 😅 It's tricky because `--optimize` activates F# optimization which is more oriented to IL, while Fable optimizations are tested with Fable AST. TBH, Fable "optimizations" are scattered in different steps of the compilation (F# to Fable, Fable transforms, Fable to Babel and Babe printing) and the one to concatenate strings in particular was an attempt still incomplete to resolve operations at compile time: https://github.com/fable-compiler/Fable/blob/111a0b2175bf605594817f849109fedef04eb6f3/src/Fable.Transforms/FableTransforms.fs#L240-L242

Anyways, if we can identify these divergences, it should be possible to fix them one by one. In this case, [when replacing the `String.Concat` call](https://github.com/fable-compiler/Fable/blob/111a0b2175bf605594817f849109fedef04eb6f3/src/Fable.Transforms/Replacements.fs#L1626-L1631) we could check if the arguments are string literals and concat them at compile time (or just use the plus operator so the constant folding is applied later after the binding beta reduction).

BTW, I myself haven't played with `--optimize` very much. What are the examples you've found where better JS code is generated?

**Comment by bklop** [comment]
I see, thanks for the clarification! :). 

I'm not sure if there is a reference somewhere listing all the optimizations performed by the F# compiler?

I did have a look at the effect that --optimize had on my codebase. Two examples of cases where I found the generated JS code was "better" (mostly reduction of code leading to a smaller bundle size, I didn't actually check runtime performance):

**Constant folding**
```F#
let foo x = if x = 1 then 40 else 1

let bar = (foo 1) + 2
```

Output:
```js
export function foo(x) {
    if (x === 1) {
        return 40;
    }
    else {
        return 1;
    }
}

export const bar = foo(1) + 2;
```

Output with --optimize:
```js
export function foo(x) {
    if (x === 1) {
        return 40;
    }
    else {
        return 1;
    }
}

export const bar = 42;
```

The foo function will be removed via tree shaking when bundling, if not used anywhere else.

**Tuple optimization**
```F#
type MyType = MyType of int * int

let add (MyType(a, b)) = a + b

let f x = (1, x) |> MyType |> add
```
Output:
```js
/* ... MyType definition ... */

export function add(_arg1) {
    return _arg1.fields[0] + _arg1.fields[1];
}

export function f(x) {
    let arg00$0040;
    const tupledArg = [1, x];
    arg00$0040 = (new MyType(0, tupledArg[0], tupledArg[1]));
    return add(arg00$0040) | 0;
}
```

Output with --optimize:
```js
/* ... MyType definition ... */

export function add(_arg1) {
    return _arg1.fields[0] + _arg1.fields[1];
}

export function f(x) {
    return 1 + x;
}
```

The code no longer references MyType so it will be removed via tree shaking when bundling, if not used anywhere else.

**Other optimizations**
I noticed some other optimizations, for example List.iter and Array.iter are rewritten as a while loop and a for loop, respectively. I assume this is done for .NET to enable bounds-checking elimination? I'm not sure that this improves the JS code in anyway.

Anyway, if Fable tests aren't being run (or don't pass) with --optimize then it probably shouldn't be used for production code anyway. Feel free to close this issue!

**Comment by Zaid-Ajaj** [comment]
@bklop I think using `inline` for these functions will erase them when --optimize is enabled

**Comment by alfonsogarciacaro** [comment]
Thanks @bklop! Yes, function evaluation at compile time is tricky. I didn't try to go too wild on the optimizations because it's easy to break code (the main optimization made by Fable is the uncurrying and there are still several failing corner cases) and also because terser (the minifier used by Webpack) already does many things for us (although it seems it only does function evaluation in very simple cases). You can test how the code is transformed here (you need a side-effect like `console.log` so the code is not totally erased): https://xem.github.io/terser-online/

There's also [Prepack](https://prepack.io/) but it seems development has been abandoned and it will never be "production-ready".

**Comment by alfonsogarciacaro** [comment]
Closing as the `--optimize` option was experimental and we're not working on it atm.
