### ISSUE TITLE
Elmish messages look weird in nagareyama

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2262]
Elmish messages look weird in nagareyama:

![image](https://user-images.githubusercontent.com/57396/98802778-111d2280-2414-11eb-9a41-318788cede62.png)

compared to fable 2:

![image](https://user-images.githubusercontent.com/57396/98803027-7709aa00-2414-11eb-9cda-400593b5e498.png)

Basically with nagareyama we are left with counting the DU case.

/cc @atheck

**Comment by alfonsogarciacaro** [comment]
The name is actually there, but now is a getter instead of a field so the dev console only evaluates it on demand. In your screenshot you can see `name: (...)` on the bottom if you click on it you should see the name of the DU.

If this is still not good maybe we could the Emish tools to some preprocessing of the message before printing it to the console

**Comment by alfonsogarciacaro** [comment]
In the Redux dev tools for example, we made it so you get the "full message name" by appending the names of the nested DUs in reverse order

**Comment by alfonsogarciacaro** [comment]
@forki Was the solution ok with you? Can we close this?

**Comment by forki** [comment]
Yes redux Tools do work. Thank you
