### ISSUE TITLE
Inlined imports don't work anymore: parameters are ignored on call-site

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2280]
### Description

Inlining an import now ignores the parameters on call-site. 

### Repro code

This works:
```fs
open Fable.Core
open Fable.Core.JsInterop

module Interop = 
    let create (x: obj) (y: obj) : obj = import "createElement" "react"

let element = Interop.create "div" (obj())
```
compiles to
```js
import { createElement } from "react";

export const Interop_create = createElement;

export const element = Interop_create("div", {});
```
However, when the `create` function is inlined, it no longer applies the parameters:
```fs
open Fable.Core
open Fable.Core.JsInterop

module Interop = 
    let inline create (x: obj) (y: obj) : obj = import "createElement" "react"

let element = Interop.create "div" (obj())
```
Compiles to the following incorrect code:
```js
import { createElement } from "react";

export const element = (() => {
    const y = {};
    return createElement;
})();
```

### Expected and actual results

Expected the code to use the imported function right away when the import is inlined:
```js
import { createElement } from "react";
export const element = createElement("div", { });
```
### Related information

* Fable version: Fable 3 rc7
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Actually it seems this didn't work in Fable 2 (at least it doesn't in repl 2) but hopefully it will be fixed in next release 👍

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Can we get a quick release with this one please? :pray: 

I've seen that importing uncurried functions (x, y) in JS with curried F# ones always causes confusion, isn't it an idea to expose call args from user code like this 🤔 
```fs
let inline createElement (x: obj) (y: obj) = importMemberCall "createElement" "react" [x; y]

let inline toString (x: obj) : string = emitJs "$0.toString()" [x]
```
What do you think?

**Comment by alfonsogarciacaro** [comment]
Ok, I'll try to push a release tonight after kids are sleeping and I can review the latest commits :) Sorry, I don't understand exactly your proposal. The whole issue with currying/uncurrying is super confusing because while in the F# language module functions and local lambdas look the same, in the AST they're different things. Maybe I shouldn't have introduced the `import` functions because, unlike the attributes, they allow you to import at the module or at the local level and the AST generated may be different in each case. Actually when fixing this issue, I tried to [tackle a common mistake](https://github.com/fable-compiler/Fable/commit/6258ded078b5421925dc158e4caced6a9c8d74bd#diff-ea3bc6b45d9295f9c8bf3f1acdaf7b8d94fb1bc7eb60fcedc3027710b4abf2e2R432) but I broke another test so I had to undo it.

So even if the behaviour of the import functions is a bit weird, if people have got used to the Fable 2 way [as documented](https://fable.io/docs/communicate/js-from-fable.html#Miscellaneous-import-helpers) I'd prefer not to touch it.

**Comment by Zaid-Ajaj** [comment]
> I'll try to push a release tonight after kids are sleeping and I can review the latest commits

Awesome ❤️ 

> So even if the behaviour of the import functions is a bit weird, if people have got used to the Fable 2 way as documented I'd prefer not to touch it.

That's fair enough :smile:
