### ISSUE TITLE
Does Fable run on .NET 5?

### ISSUE THREAD

**Issue by psfinaki** [fable-compiler/Fable#2294]
### Description

I am trying to update my app to use .NET 5 and F# 5, to benefit from string interpolation and other things. Fable app is currently on .NET Core 3.1.

I know switching target framework is always a traumatizing experience but I am running out of ideas what else to do. I retargeted the app to `net5.0`, updated all the Fable packages, updated `fable-loader` and `fable-compiler`... 

I found [this app](https://github.com/NatElkins/NHS) successfully working on .NET 5 but it's already working via Nagareyama stuff. Is it supposed to be possible to run things without Nagareyama? I read the Fable blog but this stuff is still kind of magic for me.

**Comment by alfonsogarciacaro** [comment]
Actually, for Fable apps the .net target framework should not be relevant, but I guess you're interested in F# 5 features. Fable 2 supports some of them but not string interpolation. We are very close to publish an official release of Fable 3 so I'd recommend upgrading to get latest features and fixes. Here's a guide for upgrading apps using Webpack: https://github.com/MangelMaxime/fulma-demo/pull/43

In order for latest features to work both with Fable and your IDE you need two things:

- Reference FSharp.Core 5.0
- Add `<LangVersion>5.0</LangVersion>` property to your .fsproj (or `preview` instead of `5.0`) 

I think these are automatic when using dotnet sdk 5 regardless of the target framework.

**Comment by psfinaki** [comment]
@alfonsogarciacaro, alright, thanks for the response. I guess this PR should be somehow more visible, that would help a lot :)

**Comment by alfonsogarciacaro** [comment]
Yes, visibility is always and issue :/ It's mentioned in the recent blog posts but I haven't updated the landing page yet because Fable 3 is not officially released. That will happen soon.

**Comment by psfinaki** [comment]
Alright. I got my response, and I checked things are working with the latest Fable RC. You can close the issue, or close it once Fable is officially released - it's on you :)

**Comment by alfonsogarciacaro** [comment]
Thanks for confirming @psfinaki! Ok, let's close it as we are not working on Fable 2 branch, so new issues are only filled for Fable 3 👍
