### ISSUE TITLE
Implementing System.Drawing.Color

### ISSUE THREAD

**Issue by EverybodyKurts** [fable-compiler/Fable#2307]
### Description

`System.Drawing.Color` can't currently be used with Fable. 

### Repro code

```fsharp
module Color =
    let rgbaString (color: System.Drawing.Color) =
        let alpha = float color.A / 255.0
        String.Format("rgba({0}, {1}, {2}, {3})", color.R, color.G, color.B, alpha)
```
The Fable compiler throws errors like: `error FABLE: Cannot resolve System.Drawing.Color.get_R`

### Expected and actual results

This seems like it'd be a good first pull request for somebody such as myself who's new to F# and .net but has some experience with javascript. However, per the readme, I'm opening up this issue to discuss its viability.

**Comment by alfonsogarciacaro** [comment]
Thanks @EverybodyKurts! Yes, it could be an interesting addition, I [did try this with Funscript](https://github.com/alfonsogarciacaro/FunScript.HTML/blob/master/src/main/Drawing.fs). However, I'm usually a bit wary when increasing support for BCL classes because then users always ask for more 😅 and also because it's one of those this that "better not done if not done right". BCL APIs have lots of overloads and semantic nuances that are difficult to port many times.

Usually the reason to support something is because it's frequently used in F#, it opens new possibilities or it helps with sharing code(between client and server). In the case of `System.Drawing` I have the feeling it's not used a lot in F# project nowadays (though I may be wrong). Could it be an idea to just create a Drawing interface easier to user and with different implementations? (Canvas or SVG for HTML, and System.Drawing for Windows forms, etc).

**Comment by alfonsogarciacaro** [comment]
Sorry, I just realized the issue was just about `System.Drawing.Color` specifically 😅 In that case it could make sense and we could adapt the code in link above, although I'm sure users will expect more classes from System.Drawing namespace to be supported. And we may have an issue with Fable 3, because the System.Drawing.dll assembly is not loaded by default.

**Comment by alfonsogarciacaro** [comment]
Closing as there are no currently plans to increase support for the BCL, please use the link above to add `System.Drawing.Color` members to your project source as an alternative.
