### ISSUE TITLE
Inline function with callback compiles but produces invalid JS

### ISSUE THREAD

**Issue by theprash** [fable-compiler/Fable#2311]
### Description

Using a particular pattern of an inline function/method with a callback that takes an anonymous record can produce invalid JS code. I found this

### Repro code

```fsharp
let inline myFun callback =
    fun () -> {| A = 1 |} |> callback

let x = myFun (fun x -> x.A)
```

### Actual:

```js
export const x = () => {
    A: 1,
}.A;
```

JS error: `Uncaught SyntaxError: Unexpected token '}'`

### Expected:

```js
export const x = () => ({
    A: 1,
}).A;
```

Note the extra parens that make this valid.

### Related information

Fable 3.0.0 on https://fable.io/repl/

**Comment by delneg** [comment]
After doing some experimentation the issue seems to be with how returned objects are accessed (.A)
Some f#:
`let inline myFun2() = {| A = 1|} |> fun x -> x.A

let inline myFun callback =
    fun () -> {| A = 1 |} |> callback

let inline myFun3 callback =
    fun () -> callback {| A = 1 |}

let inline myFun4 callback (b: unit)=  {| A = 1 |} |> callback

let myFun5 callback =
    fun () -> callback {| A = 1 |}
let x = myFun (fun x -> x.A)
let y = myFun2()
let z = myFun3 (fun x -> x.A)
let c = myFun4 (fun x -> x.A)
let d = myFun5 (fun x -> x.A)`

Corresponding js:
`export function myFun5(callback, unitVar0) {
    return callback({
        A: 1,
    });
}

export const x = () => {
    A: 1,
}.A;

export const y = {
    A: 1,
}.A;

export const z = () => {
    A: 1,
}.A;

export const c = () => {
    A: 1,
}.A;`

Maybe the workaround could be to always add parens around the returned object in that case ?

Invalid js:
`export const x = () => {
    A: 1,
}`

Valid js:
`export const x = () => ({
    A: 1,
})`

**Comment by alfonsogarciacaro** [comment]
Thanks @theprash for reporting and @delneg for investigating! It was indeed an issue about wrapping JS literal objects with parens within an arrow function. Fable was actually doing this already but this case skipped the check because it was a MemberExpression `anObject.A` instead. I added a check for this, hopefully there are no other conflicting cases :)
