### ISSUE TITLE
Support System.IO.Path

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2369]
### Description

It might be nice to have a replacement implementation of System.IO.Path in Fable. I've written a pretty robust one over at [Fable.System.IO](https://github.com/jwosty/Fable.System.IO/blob/f55a65e075869757a9a3d03fbeb4f15c651265c9/src/Fable.System.IO.fs). Perhaps a merger of this into core Fable would be a net good?

I thought I've already asked this somewhere, but I can't find it anymore. The reason it's already its own library is because I figured @alfonsogarciacaro would take the viewpoint that it's better in general to keep BCL API implementations out of Fable itself and in separate libraries to reduce maintainer overhead of Fable itself -- at which point, the question becomes whether or not this is worth that cost. Might be, might not be, but I figured I'd bring it up!

The one thing that would make this tricky is the fact that Fable.System.IO uses a platform detector (currently [platform-detect](https://www.npmjs.com/search?q=platform-detect) from npm; but in the process of switching over to Shmew's F#-only [Fable.Extras](https://github.com/Shmew/Fable.Extras)). So if Fable were to properly absorb this code, it would have to either similarly take some kind of dependency (or inline) on a platform detector, or it would just choose which environment's behavior to emulate (Windows vs Unix paths).

FWIW, I have complete unit test coverage [here](https://github.com/jwosty/Fable.System.IO/blob/f55a65e075869757a9a3d03fbeb4f15c651265c9/tests/Fable.System.IO.Tests.fs).

**Comment by alfonsogarciacaro** [comment]
Hi @jwosty! This is a great work you've done with Fable.System.IO 👏👏👏 I understand your desire to see this integrated into Fable, but I'm still very careful in trying to shim more .NET APIs. Path is useful, but I assume when adding any support for System.IO people will try to use File as well. Javascript can run in multiple environments: browser, nodejs, mobile... and trying to support File I/O in all of these is too big an undertake (for me). We already have trouble with binary serialization because btoa is not supported in Node :/

Also, fable-library doesn't have dependencies, so we would have to include platform-detect in our codebase. We've already done something like that for decimals and longs, but besides this causing trouble with bundle sizes (as in  which took me a long time to realize)

**Comment by alfonsogarciacaro** [comment]
Closing as we've Fable.System.IO as a great alternative to trying to add more (imperfect) BCL replacements. Thanks again for this @jwosty!

**Comment by jwosty** [comment]
Sure thing; I can definitely understand this reasoning!
