### ISSUE TITLE
Can we re-add options allFiles to Fable 3?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2382]
Hello,

in Fable 2 it was possible to use `allFiles` options to make Fable/Fable splitter compiles all the files in a project.

Can we add this option back to Fable 3?

This is especially useful when you are mixing F# code with other language like Haxe, JavaScript. --> Allows you to write some part of the application in F# and consume them from the other languages.

Another plus is when writting tests using `mocha` otherwise you kind of have to be imaginative in your namespace/module naming.

**Comment by alfonsogarciacaro** [comment]
Actually this is always the behavior now :) Fable 3 just compiles files from first to last because there are no tools like fable-loader or fable-splitter anymore to analyze the JS imports of the generated files. Were some files not being compiled in your case?

Note that another disadvantage of not being able to analize the JS import is we cannot move linked JS files to the output folder. Maybe this is what happened in your case? Or was it because the "cache" function? (In debug mode Fable 3 skips compilation for files if there's already a generated js file with more recent timestamp)

**Comment by MangelMaxime** [comment]
Hum, I need to recheck.

I though that when commenting a reference/call `Express.router.test()` to a file `mocha` didn't report the expected number of tests. But now, that I think of it perhaps the problem was because I told it to execute `tests/Main.js` and not `tests/`.

I will check and close this issue if that was a wrong configuration from my part. Thank you for the explanations

**Comment by MangelMaxime** [comment]
You were right @alfonsogarciacaro all the files are compiled by default. 

It was me not using correctly mocha.

I had to invoke it using `mocha -r esm -r tests/env.js --recursive tests/` (note that I give it a folder and not a file).

Only strange thing it that I needs to put all the tests in the files under behind a `let tests =` declaration because it was complaining about not finding an exported variable named `tests` in the different files. Perhaps this is due to the module usage instead of standard `require`.
