### ISSUE TITLE
Fable REPL does not work in Firefox Ubunutu

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2387]
### Description

I hope this is the right place for the issue. 

Fable REPL (https://fable.io/repl/) is currently broken in Firefox for me. Old versions worked well. It works in Chromium. 

### Repro code

N/A

### Expected and actual results

Visit https://fable.io/repl/

No UI elements appear. 

Some warnings are in the console:

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

> Loading failed for the <script> with source “https://fable.io/repl/app.2e87a0d750e00dfae456.js”.

### Related information

From "About Firefox":

> Firefox 85.0.1 (64-bit)
> Mozilla Firefox for Ubuntu canonical  - 1.0

```bash
$ lsb_release -a                                            
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by MangelMaxime** [comment]
Hello @njlr for me it is working.

It seems like your browser is request and old version of the project:
- Your URL: https://fable.io/repl/app.2e87a0d750e00dfae456.js
- The URL of the file should currently be: https://fable.io/repl/app.8faab45124666f11eeb2.js

Can you please try to force clearing the cache?

@alfonsogarciacaro We really need to find a way to fix the REPL cache issue... People often encounter it. I tough that we removed the worker doing "custom" caching. Am I wrong? Is there something else we need to do?

**Comment by njlr** [comment]
> Hello @njlr for me it is working.
> 
> It seems like your browser is request and old version of the project:
> 
>     * Your URL: https://fable.io/repl/app.2e87a0d750e00dfae456.js
> 
>     * The URL of the file should currently be: https://fable.io/repl/app.8faab45124666f11eeb2.js
> 
> 
> Can you please try to force clearing the cache?
> 
> @alfonsogarciacaro We really need to find a way to fix the REPL cache issue... People often encounter it. I tough that we removed the worker doing "custom" caching. Am I wrong? Is there something else we need to do?

Yes clearing the cache fixed the issue for me. Thanks @MangelMaxime

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! I removed the service worker completely from the repl since v3 but it seems it's still active and loading old code if it was registered in the browser by a previous version. I didn't manage to unregister it, maybe we have to do it directly in the HTML before the service worker has an opportunity to load the old cache.

**Comment by MangelMaxime** [comment]
> I didn't manage to unregister it, maybe we have to do it directly in the HTML before the service worker has an opportunity to load the old cache.

Perhaps yes, just hoping that `index.html` isn't cached too. 

Another workaround, would be to have a way to detect if the REPL hasn't loaded in X second and pint a message asking the user to refresh the page with clearing the cache. It is not ideal because it depends on the connexion of the person etc. but as it least after X seconds it would have an idea to try fixing the problem by himself.

That workaround should also be done in the `index.html` file as it seems to be the only file not cached or at least not having problem with it.
