### ISSUE TITLE
Formatting `TimeSpan` with `%A` prints TotalMilliseconds instead of formatted TimeSpan

### ISSUE THREAD

**Issue by Booksbaum** [fable-compiler/Fable#2409]
### Description
`printfn "%A" myTimeSpan` prints `TotalMilliseconds` of `myTimeSpan` and not a readable TimeSpan format.

### Repro code

```fsharp
let ts = TimeSpan(11, 57, 37)
printfn "%A" ts
printfn "%s" (ts.ToString())
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWA2YlRIJQC8UAKgJapgwgCGEAFAIwsA0UArAOycDMPAJRYQAJ0oQkAM2gAiAKQBBOYQSiJU2VEUJVTIgDpywGEk0BzJkKFA&html=Q&css=Q))

### Expected and actual results

Actual Output:
> 43057000  
> 11:57:37

Expected Output:
> 11:57:37  
> 11:57:37

During runtime `TimeSpan` becomes just milliseconds -- which is printed without any additional formatting.   
It's probably not even possible to format: Type information isn't available at runtime and it's just a number (the milliseconds). So it might not be possible to distinguish `TimeSpan` from just `number`. But it still bites me every time I want to print a TimeSpan for debugging...

Workaround: manually call `ToString()` on TimeSpan. But that's only possible when it's known to be a TimeSpan.

### Related information

* Versions:
  * Fable: `3.1.5`
  * Repl: `3.1.5`

**Comment by alfonsogarciacaro** [comment]
As commented in several other issues, unfortunately print formatting is not the same as .NET and particularly `%A` doesn't really do anything atm. To be fix this I guess we'd have to use a proper type for `TimeSpan` instead of just erasing it into a number, which would require some work. For now, let's close this issue and consolidate it with #2408
