### ISSUE TITLE
VS Code Chrome debugging issues

### ISSUE THREAD

**Issue by kittipatv** [fable-compiler/Fable#2428]
### Description

I'm trying to use the [VS Code Chrome debugging](https://safe-stack.github.io/docs/recipes/developing-and-testing/debug-safe-app/#im-using-vs-code). I got the breakpoint working but there are a few issues

1. Out-of-scope variables are visible: `todos` & `value` are obviously out-of-scope, but they are visible. `todo` (which is `todo$$1` for a reason I don't know) from `AddedTodo todo` case is also visible. 
2. Variable names are arbitrarily mangled:
   1) Why `model` is mangled to `model$$1` but `msg` is not mangled?
   2) `AddedTodo todo` (`todo$$1`) and `let todo = ...` (`todo`) are mangled by the order they appear in the code. If I tried to match `AddedTodo` before `AddTodo`. The mangled variable names are swapped. But, ideally, only one should be visible, as the other would be out-of-scope.
3. Stepping doesn't work. Stepping over the statement took me to the bottom of the file, not the next statement (`let cmd = ...`). Stepping again took me to the function definition (`let update`)

<img width="962" alt="Screen Shot 2021-04-05 at 10 32 59 AM" src="https://user-images.githubusercontent.com/6920665/113605135-1402f480-95fb-11eb-8f97-e588c12500d4.png">

### Repro code

https://safe-stack.github.io/docs/quickstart/

### Expected and actual results

See the description

### Related information

* Fable version: `npm show fable-compiler version` 2.13.0
* Operating system: MacOS 11.2.1

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @kittipatv! Not sure if the safe-stack template already includes Fable 3. We made [some improvements in name mangling](https://fable.io/blog/Announcing-Nagareyama-2.html#better-name-mangling) with respect to Fable 2. Although due to the transformations done when compiling to js, unfortunately debugging with sourcemaps won't be a 1:1 experience.

- **Name mangling**: as mentioned in the blog post linked, Fable 2 just generated a unique name for all values in one file, so `model` would be mangled if it was used in another function. 

- **Out-of-scope variables visible in the debugger**: this happens because Fable moves the declaration of some variables to the top of the function to avoid creating many closures. In F# everything is an expression, so you can declare a value anywhere. However JS syntax rules forbid statements in positions reserved to expressions (e.g. `return foo(var x = 5, x + 3)`). To avoid this we can use an iife: `return foo((() => { var x = 5; return x + 3; })())`. But this is not always ideal, so we move the declaration instead: `var x; return foo(x =5, x + 3)`.

- **Stepping**: For a similar reason that F# is expression-based, while the JS debugger moves from statement to statement, sometimes stepping won't work as expected, particularly in code that goes through more transformations like pattern matching or computation expressions. This problem also happens when debugging F# in .NET.

**Comment by kittipatv** [comment]
Hi @alfonsogarciacaro, thank you for clarifications! Cleaner generated code definitely helps. Feel free to close the issue.
