### ISSUE TITLE
Watcher/ HMR question

### ISSUE THREAD

**Issue by PawelStadnicki** [fable-compiler/Fable#2429]
This is just a question. 
I went through the code to some extend but I do not have enough knowledge how watcher/HMR works in general.

I'm using Fable with .NET Interactive via custom extension.
It works but I want to improve the performance.

For the time being I'm compiling the code via "fable src --run webpack"
so every little change I have the full process in place.

Combination of running Fable with watcher could potentially and significantly speed up it
but it is hard to combine it further in the loop.

Currently the dist output of webpack is used as <script src="dist.js"></script>
and consumed by HTML .NET Interactive Kernel.

can you see feasibility for HMR here ?
If I run fable with --watch hot to make webpack also rerun on each change?
And if I have the webpack running on each change it is possible to have HMR if I just update the ultimate HTML file with new dist URL or some another actions are required?

Thanks in advance

**Comment by alfonsogarciacaro** [comment]
Hi @PawelStadnicki! With Fable 3, the watchers of Fable and Webpack are different things. `--run` only runs once after the first compilation and then Webpack watcher (with HMR) is active after that. It usually works like this:

1. User runs `dotnet fable watch src --run webpack serve`
2. First compilation of Fable happens and then first Webpack compilation. After that both Fable and Webpack watchers keep running (independently) in parallel
3. When an .fs file changes, Fable watcher detects it and recompiles to .js
4. When the .js file changes, Webpack watcher detects and recompiles the bundle triggering HMR

Not sure how your workflow is, but if possible I would suggest that instead of running `dotnet fable` for every change, you do it only once at the beginning in watch mode (both for Fable and Webpack, like `dotnet fable watch src --run webpack serve`). Does .NET interactive saves files on disk or just keeps them in memory? I assume they must be saved on disk or Fable wouldn't be able to read the source code.

**Comment by PawelStadnicki** [comment]
Thanks @alfonsogarciacaro for explanations.
Correct, I save the files on disk.

The problem with fable --watch is that after running the command I do not have exact information that the command has finished as it is always in progress, so I cannot notify .NET Interactive to follow up.

I run the fable tool using CliWrap nuget package :

`    CliWrap.Cli.Wrap("fable.exe").WithArguments(sprintf " src --watch --cwd %s --run webpack --config webpack.config.js" target).ExecuteAsync().Task.Wait()`

If I can handle the "end event" somehow then I'm at home.

Regarding HMR: after some considerations I don't think there is a space for it with .NET Interactive.
In .NET Interactive you "accept" every change by running the cell so it is de facto full reload.
It still could have been possible with implementing keyboard shortcut or similar but this requires some effort (updating .NET Interactive, not my program) that may not be justified with the .NET Interactive nature that is all about running small pieces of code/UI when the HMR doesn't provide value

**Comment by alfonsogarciacaro** [comment]
Would it be possible to scan the console logs of Fable? Fable emits a "Fable compilation finished in XXXms" message after each compilation. A similar mechanism (scan console logs) is used in VS Code to highlight errors reported by Webpack in the IDE.

If this is not possible we could add an option to run something after each watch compilation (`--runScript` already runs after each compilation but atm it only works with the generated JS script). In the last case we could bring back the server so Fable compiles F# on demand although that would take some work.

**Comment by PawelStadnicki** [comment]
yes, it looks like we can scan the logs (actually we have several option with CliWrap including the Observable) and it should work ( I quickly tested) but requires some additional research from my side how to setup solid communication between the logs events and the .NET Interactive cell (especially regarding threading).
Will play with it this week and let you know

**Comment by alfonsogarciacaro** [comment]
Cool! Just in case, I realized we already have an option to run an arbitrary command after each watch compilation, `--runWatch` 😅
