### ISSUE TITLE
Questionable code generated for pattern match

### ISSUE THREAD

**Issue by chkn** [fable-compiler/Fable#2437]
### Description

I have some code that looks like this:

```fsharp
type DomViewHandler() =
    inherit Handler<BuiltInView,Node>()
    override _.CanHandle(view) = view :? BuiltInView
    override _.Handle(prev, view) =
        match view with
        | BuiltInView.Button(_, action) ->
            let btn =
                match prev with
                | Some(:? HTMLButtonElement as elem) -> elem
                | _ -> document.createElement("button") :?> HTMLButtonElement
            btn.onclick <- fun _ -> action()
            // ...
            btn :> _
        // ...
```

And the output generated by Fable 3.1.15:

```js
export class DomViewHandler extends Handler$2 {
    constructor() {
        super();
    }
    ["Flimsy.Handler.CanHandle4E60E31B"](view) {
        return view instanceof BuiltInView;
    }
    ["Flimsy.Handler`2.HandleZ7250BFAC"](prev, view) {
        let elem;
        if (view.tag === 0) {
            const btn = (prev != null) ? (document.createElement("button")) : document.createElement("button");
            btn.onclick = ((_arg1) => {
                view.fields[1]();
            });
            return btn;
        }
        else {
            throw (new Error("Match failure"));
        }
    }
}
```

### Repro code

Reduced repro: [REPL](https://fable.io/repl/#?code=PYBwpgdgBAQgTsA7gZzHAUKSsErQOgBUBPcZddAF1LFgFcBLAG0oEkIA1BsRKAXnRQhUAD71KlYNGAAzKAEEAxpQZSAXFAAUdCA0pQAtAD4oOvQEoK1cFAAiwALZceACQCGEACZM0m8-0FhBzAHACM0KAB9fABhD3cvH00AN25EDWBQgCt-PihUnig1AH56ZjZONMChYLCI6ITvME0QODBkjQA5YE9aUBUpABp8tPMuntoBYWmoBzdKRQALEcLEPUXqmbEYRhZ2Z0R8HYkpTTdlVQh-Y02Z4R99UMpoKbu3mvmlqFb2qDXKDbvd5iADKjmaJSgLkIAFkADLHSQQACiPmCEH0bmQUDAaOuJlxIVuQKEYkihhMnmAijo6Mo+EUbXmYFRIUglE0ACJQnQThBOf4SiZofDEVJWXTiXcnhB8FJFEwGIoANZQAA8BigMh0UQpUHOAwgfilMxlRRMkSAA&html=Q&css=Q)

### Expected and actual results

There are a couple things here:

1. The first type test in `CanHandle` works, but the one in the match doesn't (there is a warning about interfaces, but `document.createElement("button") instanceof HTMLButtonElement` __does__ work in JS)
2. Rather than simply erasing the cast, the `document.createElement("button")` expression is repeated on both branches.
3. Not an issue but still a curiosity: `view.fields[1]` is extracted inside the JS lambda, while the corresponding `action` value is extracted outside the lambda in the F# code.

### Related information

* Fable version: `dotnet fable --version`: 3.1.15
* Operating system: macOS 10.15.7

**Comment by alfonsogarciacaro** [comment]
It seems Fable gets indeed confused here because of the interface type testing `:? HTMLButtonElement`, if you check the warning and remove it the correct code is generated:

```fsharp
match prev with
| Some(elem) -> elem :?> HTMLButtonElement
| _ -> document.createElement("button") :?> _
```

But you're probably still interested to check whether `elem` is an actual button or not. You're right `elem instanceof HTMLButtonElement` works in JS but this is an issue of the bindings, not the Fable compiler itself. Fable cannot test against interfaces because they're erased, so there's no (good) way to know if an object implements the interface at runtime. This is discussed in other issues but usually Fable JS bindings use interfaces because they're more flexible than (empty) class declarations.

Moreover, in the Browser API bindings, the "static" and the "instance" parts of a type are defined with separated interfaces (it's a long topic, but one of the reasons is because the Typescript definition was originally like this). So the JS constructor of HTMLButtonElement interface is actually of HTMLButtonElementType.

I know it's confusing, sorry for that. But we had to use some workarounds when creating the bindings. It's a bit of boilerplate, but you can add some kind of "type testing" using an extension like this:

```fsharp
open Fable.Core.JsInterop

type HTMLButtonElementType with
    member this.Try(x: Node) =
        if jsInstanceof x this then Some(x :?> HTMLButtonElement)
        else None
```

Then use it like this:

```fsharp
let btn =
    prev
    |> Option.bind HTMLButtonElement.Try
    |> Option.defaultWith (fun _ -> document.createElement("button") :?> _)
```

About `view.fields[1]` this is because of the Fable binding beta reduction optimization. In this case `view` and case fields are immutable values, so it's considered safe to remove the binding and access the value directly from the closure. If the value were mutable (e.g. `let mutable view = view) then the action would be extracted outside of the closure.

I know this optimization is not always desirable. For example when debugging you may expect to see the `action` value in that scope. But optimizations are tricky so I try to avoid having multiple compilation flags because it becomes harder to maintain and make sure everything works in all situations.

**Comment by chkn** [comment]
Thanks for the quick and detailed response!

Your workaround using `jsInstanceof` works, thanks! But it's a bummer that the normal F# type test doesn't work. I wonder if we could have an attribute on `HTMLButtonElement`, something like `[<JsConstructor(typeof<HTMLButtonElementType>)>]` that would allow the Fable compiler to emit the proper type test in this case?

**Comment by alfonsogarciacaro** [comment]
That's a good idea! Although that specific implementation could be problematic because it's not easy for the compiler to know what _value_ represents the `HTMLButtonElementType` _type_. Maybe we could a specific version of `Emit` that would be effective for type tests, like `[<EmitTypeTest("$0 instanceof HTMLButtonElement")>]`. If feels more like a "cheap trick" but it can give us more flexibility for doing type testing without the `instanceof` operator.

And we can even make it trickier by admitting an `instanceofImport` operator when the constructor is in another module: `[<EmitTypeTest("$0 instanceofImport default from './my-module.js'")>]` :)

**Comment by alfonsogarciacaro** [comment]
Closing for now, please reopen if someone is willing to work on `EmitTypeTest` or an alternative solution.

**Comment by chkn** [comment]
I'm revisiting this - sorry for letting it languish. It sounds like there have been recent discussions against having something like `EmitTypeTest` (e.g. https://github.com/fable-compiler/Fable/issues/2492#issuecomment-890718964), in favor of just using classes for bindings (https://github.com/fable-compiler/fable-browser/issues/77)

While using classes for the bindings would rectify the original case I had with `HTMLButtonElement`, I still think there are cases where it's genuinely necessary to do interface type tests. For instance, there appear to be some hardcoded into Fable already: https://github.com/fable-compiler/Fable/blob/f250d781b8322bd93f0aff3bf547282164172500/src/fable-library/Util.ts#L58-L76

With something like `EmitTypeTest`, libraries could prescribe similar type tests for their own interfaces.

@alfonsogarciacaro What do you think? I may be able to make some time to work on this.

**Comment by alfonsogarciacaro** [comment]
Yes, those "interface type tests" are a necessary evil because the F# compiler inserts tests for IDisposable and we also need to test for custom equality. But they are not ideal, they just check if the function is present in the object but don't check the signature. They basically rely on the fact that functions in JS usually starts with lower case so the possibility of conflict is minimal. But it's kind of hacky so it's not a pattern we should likely extend.

I regretted a bit the comment about `EmitTypeTests` later because I'm already introducing too many artifacts in the compiler 😅 We should probably try to solve the problem with the resources we already have. I'm thinking now that we could just check if the interfaces are decorated with Global (and also Import for consistency) and use `instanceof` in that case. This would be more in line how Fable works and would only require publishing a new Fable.Browser.Dom package with the interfaces decorated with Global`

**Comment by MangelMaxime** [comment]
I think the closer we can go to native F# the better it is in general because it feels less magic and is less error prone.

This discussion made me think of a discussion we had in #2492 so it could be nice to check if the proposed solution would also solve this problem too.

**Comment by chkn** [comment]
> I'm thinking now that we could just check if the interfaces are decorated with Global (and also Import for consistency) and use instanceof in that case.

I think that's a decent solution to the original issue. But I also think there are other cases where you can't use `instanceof` but you still need to support interface type tests.

> But they are not ideal, they just check if the function is present in the object

For some cases I think this is fine, and it's a pattern I've seen in JS land too. Whether it's `EmitTypeTest` or something else, I think it would be nice to give interface authors a way to opt in to the function checks. I could open a separate issue to discuss this if people prefer.

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm less convinced now of a solution like `EmitTypeTest` or similar because it would introduce more obscure behavior in Fable with the only benefit of being able to do pattern matching. However you can already do that with active patterns:

```fsharp
type Foo =
    abstract doFoo: unit -> unit

[<Emit("typeof $0.doFoo === 'function' ? $0 : null")>]
let (|IsFoo|_|) (o: obj): Foo option = jsNative

let test = function
    | IsFoo foo -> foo.doFoo()
    | _ -> ()

{ new Foo with member _.doFoo() = printfn "Foo" }
|> test
```

I'm still open to allowing type testing with interfaces decorated with `Global/Import` because the implementation is minimal, the behavior is in line with current use of the attributes, and it will allow us to enable type testing in Fable.Browser.XXX packages without breaking changes. I still find the interfaces nicer to declare the bindings than classes, so being able to easily type test them would be a nice addition.

**Comment by chkn** [comment]
Fair enough. That sounds reasonable for now

**Comment by chkn** [comment]
> This would be more in line how Fable works and would only require publishing a new Fable.Browser.Dom package with the interfaces decorated with Global.

PR here: https://github.com/fable-compiler/fable-browser/pull/93
