### ISSUE TITLE
Error in command while handling: UserMsg (UserMsg (MenuMsg Customers)) TypeError: Failed to construct 'CustomEvent': 1 argument required, but only 0 present.

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2463]
Since upgrading to Fable 3.2.2 from Fable 3.1 I see following errors in the browser:

VM115 react_devtools_backend.js:2560 Error in command while handling: UserMsg (UserMsg (MenuMsg Customers)) TypeError: Failed to construct 'CustomEvent': 1 argument required, but only 0 present.
    at navigation.fs.js:31
    at cmd.fs.js:23
    at cmd.fs.js:23
    at cmd.fs.js:9
    at List.js:482
    at fold (List.js:405)
    at iterate (List.js:481)
    at Cmd_exec (cmd.fs.js:7)
    at _loop (program.fs.js:136)
    at dispatch (program.fs.js:129)

**Comment by forki** [comment]
Seems to be thrown whenever the inner message DU is without payload

**Comment by forki** [comment]
@alfonsogarciacaro  @et1975 @MangelMaxime is this a fable or elmish issue?

**Comment by alfonsogarciacaro** [comment]
Events were touched in #2454 which was included in latest release. @chkn does this ring a bell?

**Comment by MangelMaxime** [comment]
Because, I see `CustomEvent` in the error I have an opened PR https://github.com/thoth-org/Thoth.Elmish.Toast/pull/31 when using which latest version of `Browser.Event` which made the `CustomEvent` generic.

The error in the PR is not the same as the one @forki has. In the PR case, it is because of invalid JavaScript generated by Fable.

But perhaps, both are linked.

I didn't have the time yet to make some test.

@forki Can you please show us what is at the line 31 of `navigation.fs.js` and a bit around it so we can see the generated JavaScript?

**Comment by forki** [comment]
```
import { Union } from "../fable-library.3.2.2/Types.js";
import { union_type, class_type } from "../fable-library.3.2.2/Reflection.js";
import { ofArray, singleton } from "../fable-library.3.2.2/List.js";
import { Cmd_batch, Cmd_map } from "../Fable.Elmish.3.1.0/cmd.fs.js";
import { ProgramModule_map } from "../Fable.Elmish.3.1.0/program.fs.js";

export class Navigable$1 extends Union {
    constructor(tag, ...fields) {
        super();
        this.tag = (tag | 0);
        this.fields = fields;
    }
    cases() {
        return ["Change", "UserMsg"];
    }
}

export function Navigable$1$reflection(gen0) {
    return union_type("Elmish.Navigation.Navigable`1", [gen0], Navigable$1, () => [[["Item", class_type("Browser.Types.Location")]], [["Item", gen0]]]);
}

export function Navigation_modifyUrl(newUrl) {
    return singleton((_arg1) => {
        history.replaceState(void 0, "", newUrl);
    });
}

export function Navigation_newUrl(newUrl) {
    return singleton((_arg1) => {
        history.pushState(void 0, "", newUrl);
        const ev = new CustomEvent()("NavigatedEvent");
        void window.dispatchEvent(ev);
    });
}

export function Navigation_jump(n) {
    return singleton((_arg1) => {
        history.go(n);
    });
}

let ProgramModule_Internal_onChangeRef = (_arg1) => {
    throw (new Error("`onChangeRef` has not been initialized.\nPlease make sure you used Elmish.Navigation.Program.Internal.subscribe"));
};

export function ProgramModule_Internal_subscribe(dispatch) {
    let clo1, clo1_1, clo1_2;
    let lastLocation = void 0;
    const onChange = (_arg1) => {
        let href;
        let value;
        let pattern_matching_result;
        if (lastLocation != null) {
            if (href = lastLocation, href === window.location.href) {
                pattern_matching_result = 0;
            }
            else {
                pattern_matching_result = 1;
            }
        }
        else {
            pattern_matching_result = 1;
        }
        switch (pattern_matching_result) {
            case 0: {
                value = (void 0);
                break;
            }
            case 1: {
                lastLocation = window.location.href;
                value = dispatch(new Navigable$1(0, window.location));
                break;
            }
        }
        return void 0;
    };
    ProgramModule_Internal_onChangeRef = onChange;
    window.addEventListener("popstate", (clo1 = ProgramModule_Internal_onChangeRef, (arg10) => {
        clo1(arg10);
    }));
    window.addEventListener("hashchange", (clo1_1 = ProgramModule_Internal_onChangeRef, (arg10_1) => {
        clo1_1(arg10_1);
    }));
    window.addEventListener("NavigatedEvent", (clo1_2 = ProgramModule_Internal_onChangeRef, (arg10_2) => {
        clo1_2(arg10_2);
    }));
}

export function ProgramModule_Internal_unsubscribe() {
    let clo1, clo1_1, clo1_2;
    window.removeEventListener("popstate", (clo1 = ProgramModule_Internal_onChangeRef, (arg10) => {
        clo1(arg10);
    }));
    window.removeEventListener("hashchange", (clo1_1 = ProgramModule_Internal_onChangeRef, (arg10_1) => {
        clo1_1(arg10_1);
    }));
    window.removeEventListener("NavigatedEvent", (clo1_2 = ProgramModule_Internal_onChangeRef, (arg10_2) => {
        clo1_2(arg10_2);
    }));
}

export function ProgramModule_Internal_toNavigableWith(parser, urlUpdate, program, onLocationChange) {
    const map = (tupledArg) => {
        const model = tupledArg[0];
        const cmd = tupledArg[1];
        return [model, Cmd_map((arg0) => (new Navigable$1(1, arg0)), cmd)];
    };
    const update = (userUpdate, msg, model_1) => {
        let userMsg, location;
        return map((msg.tag === 1) ? (userMsg = msg.fields[0], userUpdate(userMsg, model_1)) : (location = msg.fields[0], urlUpdate(parser(location), model_1)));
    };
    const subs = (userSubscribe, model_2) => Cmd_batch(ofArray([singleton(onLocationChange), Cmd_map((arg0_1) => (new Navigable$1(1, arg0_1)), userSubscribe(model_2))]));
    const init = (userInit, unitVar1) => map(userInit(parser(window.location)));
    const setState = (userSetState, model_3, dispatch) => userSetState(model_3, (arg) => dispatch(new Navigable$1(1, arg)));
    const view = (userView, model_4, dispatch_1) => userView(model_4, (arg_1) => dispatch_1(new Navigable$1(1, arg_1)));
    return ProgramModule_map(init, update, view, setState, subs, program);
}

export function ProgramModule_toNavigable(parser, urlUpdate, program) {
    return ProgramModule_Internal_toNavigableWith(parser, urlUpdate, program, (dispatch) => {
        ProgramModule_Internal_subscribe(dispatch);
    });
}

```

**Comment by forki** [comment]
```
export function Navigation_newUrl(newUrl) {
    return singleton((_arg1) => {
        history.pushState(void 0, "", newUrl);
        const ev = new CustomEvent()("NavigatedEvent");  // line 31
        void window.dispatchEvent(ev);
    });
}
```

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro 

The error @forki see is the same error as I have in the PR I linked.

Fable is generated invalid JavaScript:

![image](https://user-images.githubusercontent.com/4760796/121532054-48ca6800-c9ff-11eb-9099-79ab6840a790.png)

Here is the commit which changed the `Fable.Browser.Event` to make `CustomEvent` generic https://github.com/fable-compiler/fable-browser/commit/53a4cbd4976bf9b795ed8b281540175b5e1c51c0 for me the code looks good because it didn't change the `[<Emit("new $0($1...)")>` instruction

So I suspect this is a problem in Fable itself because the problem is the generated JavaScript it should have generated `new CustomEvent("NavigatedEvent")`

**Comment by forki** [comment]
"Fable is generated invalid JavaScript" 

https://media.giphy.com/media/xT9IgvEOwRzUcZDRiU/giphy.gif

**Comment by MangelMaxime** [comment]
> 
> 
> "Fable is generated invalid JavaScript"
> 
> _screaming_

You can also see it as: Fable is generating JavaScript as good as the one human write 🤣

**Comment by forki** [comment]
javascript you can be proud of! ;-)

**Comment by chkn** [comment]
I just noticed on the link @MangelMaxime sent that `CustomEvent` inherits from `Event`, so it is possible that #2454 could have caused this.

That patch [changes the handling for the `(|CreateEvent|_|)` case](https://github.com/fable-compiler/Fable/pull/2454/files#diff-10431e89b8f55bac576b87b3cd8b318e8fca8270a27200cffb0bf0060fe2ecb1R499) to invoke through a proper call rather than just a simple `get`, to ensure that the proper mangling is applied. But I thought that codepath is only taken for events tagged `[<CLIEvent>]`

**Comment by chkn** [comment]
If someone has a test case I could build locally, I'd be happy to step through and see what's happening

**Comment by MangelMaxime** [comment]
@chkn The `Event` inherited by `CustomEvent` is not `Event` from `FSharp.Core` but a custom type used to bind to a JavaScript type.

It is defined at the top of [Browser.Event.fs](https://github.com/fable-compiler/fable-browser/blob/53a4cbd4976bf9b795ed8b281540175b5e1c51c0/src/Event/Browser.Event.fs)

Also, I am able to reproduce the error with Fable 3.1.4 which is way before your changes so I don't think it is related.

I don't have an isolated project but you can clone Thoth.Elmish.Toast from the PR I linked:

1. Clone from https://github.com/PaigeM89/Thoth.Elmish.Toast
2. `npm install`
3. In the `build.js` change the command `dotnet fable ...` to use a custom version of Fable
4. Run `./build.js demo watch`

**Comment by forki** [comment]
according to the REPL we can put a workaround in Fable.Browser (until it is fixed here)

![image](https://user-images.githubusercontent.com/57396/121667342-78827a00-caaa-11eb-8e37-b85bad98107c.png)

see https://github.com/fable-compiler/fable-browser/pull/69

**Comment by alfonsogarciacaro** [comment]
Sorry, I should have look into this more carefully. As you correctly noticed this was actually caused by the latest changes in Fable.Browser.Event package. I've made slight changes to @forki PR to fix the issue (and hopefully also the one in Thoth.Elmish.Toast). Can you please try with Fable.Browser.Event 1.4.5?

**Comment by forki** [comment]
works like a charme. thanks everyone
