### ISSUE TITLE
ReleaseNotes should be copied into nuget package

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2474]
Would be nice to see the release notes under https://www.nuget.org/packages/Fable/3.2.6

**Comment by alfonsogarciacaro** [comment]
Is there a standard/preferred way to do that automatically?

**Comment by forki** [comment]
If you are using dotnet pack then there is a switch. see https://github.com/fsprojects/Paket/blob/master/build.fsx#L455

**Comment by forki** [comment]
looks like you are already doing some xml grepping here:  https://github.com/fable-compiler/Fable/blob/main/build.fsx#L34

Similarly we could do something with the release notes:

    <PropertyGroup>
        <PackageReleaseNotes>PLACEHOLDER</PackageReleaseNotes>
     </PropertyGroup>

**Comment by MangelMaxime** [comment]
One thing to note is that when appending the Release Note via CLI `PackageReleaseNotes` args it should not contains a `,` otherwise dotnet crash / generate an error because it doesn't interpret the argument correctly...

At least, that was still the case a few months ago when I released a new version of Fulma.

I am unsure of the behaviour when using XML tags.

**Comment by alfonsogarciacaro** [comment]
As expected it took a couple of releases 😅 but the notes should be shown on the Nuget page now 👍

**Comment by forki** [comment]
Awesome news!

Alfonso Garcia-Caro ***@***.***> schrieb am Fr., 2. Juli
2021, 14:03:
