### ISSUE TITLE
Referencing Map.empty prevents tree shaking

### ISSUE THREAD

**Issue by bklop** [fable-compiler/Fable#2480]
### Description
Referencing Map.empty generates side-effecting code, preventing tree shaking by Webpack (and possibly other bundlers).

### Repro code
Consider the following Fable program:

```fsharp
module Simple
open Fable.Core

let foobar () =
    Array.empty

JS.console.log("Hi")
````

Note that `foobar` is not called and can be tree shaken out. After compiling with Fable 3 and bundling with Webpack 5 (using `mode: production` with everything else default), a bundle is generated that is `2.73KiB` in size.

What if we refer to Map.empty instead of Array.empty?

```fsharp
module Simple
open Fable.Core

let foobar () =
    Map.empty

JS.console.log("Hi")
````

For this program a bundle is generated that is `25.2KiB` in size! Looking at the bundle with ` webpack-bundle-analyzer` we can see that many modules are included that aren't used by the program directly, but that can't be tree shaken out.

Looking at the reason why (running `webpack --json` with `pathinfo: 'verbose'` in webpack's output config), we see the following optimizationBailout entry: `Statement (ExpressionStatement) with side effects in source code at 8:0-24`.

I think this is due to Map.empty being defined as `static let empty = ...` since commit 01984513b4f2a618160c1ea7d04c77f16cd5188c, which Fable compiles as side-effecting code and which in turn defeats tree shaking for that import path.

Would it be possible to change `empty` to be a static property (same as `static member Empty`)? That would imply an allocation per call, but that might be worth it. Or are there other solutions to prevent the generation of side effects?

I also found a (possibly related) issue where a simple integer range (list comprehension) leads to the inclusion of the BigInt module in the bundle, but I have to look into more detail there...

### Expected and actual results
I would expect the resulting bundle of both programs to be around the same size.

### Related information
* Fable version: 3.2.9
* Webpack version: 5.44.0
* OS: Win 10 x64

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for looking into this so thoroughly @bklop! As you say the static field seems to be the culprit because in JS an iife is used to initialize the static fields which is interpreted as a side-effect by the minifier:

```js
(() => {
    FSharpMap.empty = FSharpMap_$ctor(LanguagePrimitives_FastGenericComparer(), MapTreeModule_empty());
})();
```

As you suggest, I've converted it to a function. This removes the static constructor and the file can be tree shaken. The bundle is still big though because as soon as you pull `empty` and with the F# Map constructor, most of that file and other dependencies are needed as well. In my test I got a bundle of 18K.

More interesting is the case of integer ranges. As you noticed the Range module was pulling BigInt, which couldn't be tree shaken because of the side-effect when initializing the static fields. But in this case I thought it was better to keep this cached value: https://github.com/fable-compiler/Fable/blob/20a6d4555caceb9fa89718402c6d99d4787cc9ad/src/fable-library/BigInt/z.fs#L29

And then I realized that converting it into a module value was still triggering a side effect. So at the end following [Webpack's recommendation](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) I've added the following `package.json` to fable-library:

```json
{
  "name": "fable-library",
  "sideEffects": false
}
```

This seems to help and a bundle with integer ranges doesn't include the BigInt module if it doesn't use it, even with `static let`.

As a side note, I also considered using static class fields which are now supported in JS. Not sure if these help minification or not, but anyways it proved to be not trivial because F# uses a static constructor to initialize the fields as seen above, and we would need to identify and extract the field initializers from the constructor body to generate the JS static class fields.

**Comment by bklop** [comment]
Sorry for the late reply, I haven't been able to test this due to the summer holidays :). So how is the `package.json` supposed to work? I just upgrade a sample app to Fable 3.2.10 and there is no `package.json` file under `.fable\fable-library.3.2.10` after running `dotnet fable`. I think it needs to be there in order for Webpack to read the `sideEffects` flag? If I add the `package.json` file manually then the tree shaking seems to work (bundle size goes from ~ 30KiB to ~11KiB).

**Comment by alfonsogarciacaro** [comment]
Ups, you're right! I thought I was copying it to the .fable folder, but it seems I'm not doing it properly. I need to fix that, thanks for checking!

**Comment by alfonsogarciacaro** [comment]
Unfortunately, adding the package.json is breaking some projects #2549 so I've removed it again. Let's reopen this and try to think of a better solution... or just wait until all packages use ES modules :)

**Comment by alfonsogarciacaro** [comment]
Ok, CI is fixed now so we'll give it yet another try in the next release :)
