### ISSUE TITLE
Generated `.fable` folder gets ingored by Git

### ISSUE THREAD

**Issue by pkese** [fable-compiler/Fable#2481]
When Fable compiler renders javascript files it adds `.fable/fable-library.3.2.9/` with some libraries.

The problem is that if I add that generated code to some Git repository, any folders prefixed with dot (e.g. `.fable`) gets ignored by Git (default in .gitignore) and is rather painful keep track of.  
For example, when `.fable/fable-library.3.2.9/` switches to `.fable/fable-library.3.2.10/` git needs to be instructed to `add -f` that other ignored folder.

So this is a feature request for a compiler switch with an option to generate `fable` instead of `.fable`.

**Comment by MangelMaxime** [comment]
Hello @pkese, you should not track generated files.

If you want to track the files, you should change your Git config to track files under `.fable` folders by adding to your gitignore file `!.fable/`.

**Comment by pkese** [comment]
Yes, but then that requires all users of that library to also install fable, and dotnet on their developer and CI computers which is a no-go for my client.

Adding just `!.fable/` to `.gitignore` doesn't work either - it doesn't work that way.  
Every single subdirectory underneath `./fable` needs to be listed in `.gitignore` and even then Git won't automatically accept all files. In addition, if someone forgets to update `!.fable/fable-library.3.2.9/` in `.gitignore` to `!.fable/fable-library.3.2.10/` if an update comes, then we'll have a broken build.

For the moment, I'm checking for a workaround to put webpack into the pipeline just to copy files to another directory and fix import paths.

**Comment by alfonsogarciacaro** [comment]
In Fable 2 the `.fable` folder with the library sources was put in the root of the working repository, that's why it was usually ignored. In Fable 3 `.fable` is located either next to the .fsproj file or in the output directory if specified. In the second case usually the output directory is ignored by Git because as @MangelMaxime says generated files should normally not be tracked so it doesn't matter whether `.fable` is ignored too, but I assume you're deploying to a Git repository and that's why you cannot ignore the files? In that case it would make sense to add the option not to ignore `.fable` but maybe the easiest solution for your case is just to remove the `.fable/.gitignore` file in your build process, as this is what tells Git to ignore the folder.

**Comment by alfonsogarciacaro** [comment]
Ah, if you're writing a library for your colleagues who don't have Fable installed, I think it's a good idea to use webpack because then you only need to track one file and you won't have huge diffings every time you recompile the F# code. I think just a command like this should work (say your last file is called Lib.fs):

```
dotnet fable src --run webpack ./src/Lib.fs.js --mode production
```

This should generate a `dist/main.js` with the bundle, but you can pass [extra args](https://webpack.js.org/api/cli/) to change the target file or use a webpack.config.js to indicate [external JS libraries](https://webpack.js.org/configuration/externals/#root) that shouldn't be included in the bundle.

**Comment by pkese** [comment]
Thanks, @alfonsogarciacaro - that worked.
