### ISSUE TITLE
Unchecked.defaultof for a struct tuple generates null

### ISSUE THREAD

**Issue by sasmithjr** [fable-compiler/Fable#2491]
### Description

`let x: struct (int*int) = Unchecked.defaultof<_>` generates the JS `export const x = null;`

I saw #2206 exists but it appears to be an unrelated issue because it seems to be about passing around generic information. Additionally, I do not think this is a regression.

### Repro code

[REPL example](https://fable.io/repl/#?code=HYQwtgpgzgDiDGEAEBlALgJwK7zQFSxgBsIARCAMxCyLQCgBiYAewHcQNgkAiAFgCZudOsxgQuKAJ5Q0EMMLDMAJjWR5oaJAF46SPUhKaAHgC4kM7LiQAKAJbA0AKntoAlNqQBVYPAAWEeABrCCUAOiVKalpmCgAeAH0APl19Q3NMHE1rSQAaJAAvdy0kIxS9GAwXCi4AEm5snMKzawBvSQBfPJb89tduIA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwOAHpi98g&css=Q)

### Expected and actual results

Expected results: Generate `export const x = [0, 0];` and print "(y,z): (0, 0)"
Actual result: Generate `export const x = null;` and get "Uncaught TypeError: Cannot read property '1' of null" in Chrome console

### Related information

* Fable version: 3.2.9
* Dotnet version: 5.0.302
* Operating system: macOS 11.4

**Comment by alfonsogarciacaro** [comment]
This is tricky because currently the Fable AST doesn't contain information whether a tuple is a struct or not (AST for the next major version will), but let's assume the case when you want to the default of a struct tuple is more useful and default (pun unintended) to that for now. I hope this doesn't break anything 🙏

**Comment by sasmithjr** [comment]
Sorry I forgot to reply! This is working for me. Thanks for the help!
