### ISSUE TITLE
[Feature Request] Ability to emit JS classes from F# classes

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2504]
### Description

Right now, Fable compiles members of F# classes into standalone JS module functions. These functions take the the instance (`this`) as the first argument. If I remember correctly, it was this way because JS module functions can be removed during tree-shaking which improves the bundle size. 

That said, it would be great to have the ability to output standard JS classes from F# classes. 

### Reasoning

The main use case for this feature is to allow _mocking_ classes generated by [Snowflaqe](https://github.com/Zaid-Ajaj/Snowflaqe) and [Hawaii](https://github.com/Zaid-Ajaj/Hawaii)

This could be huge for properly unit testing or previewing React components in isolated environments that use these tools. It will require more tooling to provide an API that is easily mocks specific functions but it starts by generating the JS class of which the prototype can be overridden 

### Proposal

Using an attribute that tells Fable that a class should be generated

> I know you don't like these but I am not sure what else to do here

### Alternatives

Modifying Snowflaqe and Hawaii so that they don't generate classes anymore. This could work for Snowflaqe that for example it generates a record type which has functions (you can easily override function definitions here) but for Hawaii it won't work because method signatures with optional parameters don't map nicely to record functions

What do you think? cc @MangelMaxime @irium @kerams

**Comment by alfonsogarciacaro** [comment]
Just because it's you, I'll start working on this immediately.

[...Ready!](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQBA2gDwCCALhXAMYAWAsmALYJhYDOAfALoEUBPcLGDAAFADcAXFACWECgEooAXgJQNUZizZYoAfVQARYAGVg2inXkBzMcpVQQWeRQBm0ACQAic5esQNlAA3hIAvlAUstocAITe6poc1FE0WjrsUCZ+YFa2pimyNHBISAL2qk4uCh5Qvha5ATbxBAQoFJFgyRVq+JoiwMZmDXmBBXCpJWX2iRrtUG6VMKJiAKyKswtDOaN2G4T4FF0UMwdAA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADiaZs2sZprEwGbZrEMARAH03ACQDyAZT4eClA0AEbaCpooYmAAdMSabKhU0TScMRA0HDEAVtouMMAKVjZ2FsDFtvaOzu5efgFuQaHhkcjRpKhsEHEJSSlpGVm5+YUVpQhKKOgIIYkC4lDI2tquyMRkElzImYia+XBYWMCo9Bg0qK6IUBnaIKRrxC4LSysuVzd3DyMKJ3TwhbNUAJ-kpILAgA&css=Q)

**Comment by alfonsogarciacaro** [comment]
Yes, I know, this should be documented somewhere. I always forget that little part after implementing a feature 😅

**Comment by Zaid-Ajaj** [comment]
Oh wow how did I not know about this until now 😍 awesome! I will start experimenting with mocks soon

**Comment by MangelMaxime** [comment]
There is a small note about this features here: https://fable.io/docs/communicate/fable-from-js.html#Custom-behaviour

The catch is that overload will not be working according to the documentation.
