### ISSUE TITLE
Extremely slow compilation performance on large project

### ISSUE THREAD

**Issue by not-rusty** [fable-compiler/Fable#2508]
### Description

I got about 80s of compilation time while testing fable on an example large project, aswell as on making a small file change.

### Repro code

https://github.com/not-rusty/large-todo-app

### Expected and actual results

As fable was rewritten in fsharp, I expected the compilation times to be far better than typescript, as an example.

Maybe I should split the example project into multiple sub projects?

### Related information

* Fable version: 3.2.11
* Operating system: Ubuntu 20.04

**Comment by not-rusty** [comment]
I need to clarify that in small projects fable compilation times are really good! I just want to know if there's a way to make them stay reasonably low whenever my project scales.

**Comment by MangelMaxime** [comment]
I am not sure how representative this tests is.

I don't think we can do much on Fable side, this is the F# compiler which is a "slow" not the Fable part:

> F# compilation finished in 71734ms
> ...
> Fable compilation finished in 10114ms

This is "normal" that the F# compilation is slower, because it is doing more job like reading the source code, infering the types, checking the types, etc.

Here is a discussion about improving F# compilation time: https://github.com/dotnet/fsharp/discussions/11134

**Comment by not-rusty** [comment]
> I am not sure how representative this tests is.

Maybe too many types, I wanted to see the limit. I agree they are not really representative of real code.

Thanks for the link! I'll check that out
