### ISSUE TITLE
Feature suggestion: Record NPM dependencies made by Import('npm-package') when creating nuget PKG

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/Fable#2551]
Problem Statement: If you create a nuget package from Fable code that uses "Import( 'npm-package-name' )" then users of your package will face build errors.  This is because nuget does not know to fetch the required npm packages.

I believe `femto` can handle this. 

For those users who don't know about `femto`, it would be useful if Fable itself had the ability to perform this aspect on its own. 

Here's a poorly thought-out approach:

1. Fable knows when it has `import`ed a package from node_modules. 
2. Write that into a file named `npm-imports.json` alongside generated .fs.js files
3. Modify .fsproj to read 
```
<Content Include="*.fsproj; **\*.fs; npm-imports.json" PackagePath="fable\" />
```
4. The part of Fable that rebuilds the nuget package from its packed .FS files calls `npm add` for each dependency found in the packed `npm-imports.json`, first.

One issue with this approach is that it requires that fable has compiled the project since it was last cleaned up, before `dotnet pack` is called (which won't generate the npm-imports.json).

Even if the package maintainer has to write npm-imports.json by hand, this will still allow them to provide a works-out-of-the-box solution for their downstream package consumers.

**Comment by MangelMaxime** [comment]
Hello,

I know we had a discussion about it on another issue but to make easier I tried to sum up my thought in this issue so everyone can see it.

----------------

I can't find the issue but in the past we choose to not do that in Fable because this add a lot of complexity.

One of the main complexity is that not everyone use `npm` and so we would need to support other tools like yarn, pnpm, etc.

Another thing to consider is that it seems like new languages will be supported by Fable like Python, PHP, and so we would have to offer the same set of capabilities for these languages too increasing again the complexity.

There is also the watch mode to support, as people can add NuGet dependencies while Fable is running in watch mode.

For me the current position which is:

> You add your Fable packages via NuGet and add the required NPM packages via your favourite package manager.

is ok.

Since the beginning Fable choose to embrace the JavaScript ecosystem which gives it great interop and also make the gap between both world really slim almost for free. Especially with Fable 3, where now it  generates the files on the disk and so you can consume them as if you had written them manually. 

Pure JavaScript project:

1. User setup its NPM dependencies
2. User write JavaScript files
3. User setup its JavaScript toolchain (if needed) consuming the manually written files
4. Profit

With Fable 3:

1. User setup its NuGet and NPM dependencies 
2. User write F# files
3. User call Fable
4. User setup its JavaScript toolchain (if needed) consuming the generating files
5. Profit

-----------

It should be written in the library documentation how to install the library:

Libraries requiring both Npm and NuGet:

- https://zaid-ajaj.github.io/Feliz/#/Feliz/Installation
- https://elmish.github.io/react/

Libraries requiring both NuGet only:

- https://elmish.github.io/browser/
- https://thoth-org.gitbook.io/thoth-elmish-toast/how-to-use

------------

One way to advertise more femto could be to try see if femto is installed when starting Fable and if not have a small message saying:

```
Fable detected that you are not using femto.

Femto is a CLI tool that automatically resolves npm packages used by Fable bindings. Learn more at https://github.com/Zaid-Ajaj/Femto/.
```

This would advertise more femto and also keep the complexity outside of Fable as it just have to try spawn `dotnet femto --version` and see if it exists or not.

**Comment by davedawkins** [comment]
> One of the main complexity is that not everyone use npm and so we would need to support other tools like yarn, pnpm, etc.

That's a fair point.

> It should be written in the library documentation how to install the library

It should not require instructions to install a library. Once you know how to install a nuget package, that should be all you need to know.

> One way to advertise more femto could be to try see if femto is installed when starting Fable 

I was hoping you'd suggest something like this. Go further and install femto automatically alongside fable when it is installed, the same way that old c compilers relied on both cpp and ld to take the user from source code to executable.

**Comment by MangelMaxime** [comment]
> Once you know how to install a nuget package, that should be all you need to know.

If we wanted that then, we should have stay with publishing to NPM directly instead of using NuGet.

In the past we were using NPM but there was some decision made to change to NuGet. I don't remember exactly all the reason for that.

Actually, we made the switch back and forth depending on the version of Fable 😅 Now we try to keep things stable and this is also what should allows Fable to support new languages people publish Fable library to NuGet but set up the dependencies using the targetted runtime tool.

> I was hoping you'd suggest something like this. Go further and install femto automatically alongside fable when it is installed

There is things to explore here indeed we just need to take the whole picture into consideration as in the past we made the mistake to go a direction and ask the user to go to another direction and this cause a lot of conflict and frustration.

**Comment by alfonsogarciacaro** [comment]
Yes, this is a complex topic and because of the issues raised I'd prefer to keep package management outside of Fable's responsibilities 😸 As @MangelMaxime says, the current behavior is more or less the same as in JS (npm packages don't include code from their dependencies directly in the packages), the only difference is we cannot declare cross Nuget-npm dependencies, but this is the gap Femto tries to fill.

> One way to advertise more femto could be to try see if femto is installed when starting Fable and if not have a small message saying:

This is a great idea! Not sure if we can detect if Femto is being used or not (it can be installed globally or locally, and even if we detect it we don't know if it's been run before Fable). But I think when parsing .fsproj from Fable packages we can detect if they contain Femto metadata and in that case just display a non-invasive message:

```
Some of the Nuget packages contain Femto metadata, learn more about Femto at https://github.com/Zaid-Ajaj/Femto/
```

**Comment by davedawkins** [comment]
> the current behavior is more or less the same as in JS (npm packages don't include code from their dependencies directly in the packages)

My suggestion was to include the **name** of the dependency not the code.  Including the code would defeat the objective.

You mention femto metadata - it sounds like the same thing; however, I agree with the points raised (separation of concern). Let's focus on femto.

I find it hard to agree that a package I ship (Sutil) is allowed to create build errors when used.  Thankfully Alfonso fixed this by wrapping the dependency I had with a nuget package, but ironically that was achieved by copying the dependency code (the js polyfill) into package code.  This was a judgement call, since he (and I) probably both consider it to be stable. It would be good to add the femto metadata to this package though. I can make a PR once I've read about it.

As you say, it's complex and I'm looking for a solution that is frictionless for the end user.

A femto message would be helpful, but I think we can help the end user a little more.

Perhaps 'dotnet new fable' could use a template that includes femto in the .config

Then, this is all I need to set up a batteries- included new Fable project and it's what our package users would do too. Maxime's library installation instructions are (to a degree) wrapped up in the template. 

The template may already do this. If not I'll send a PR unless there is disagreement.

This has been a useful discussion for me, thanks both for engaging.

**Comment by alfonsogarciacaro** [comment]
> My suggestion was to include the name of the dependency not the code. Including the code would defeat the objective.

Ah, I misread the comment, sorry 😅
