### ISSUE TITLE
Support F# 6.0

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/Fable#2607]
### Description

Currently there is no way to use Fable 3 with F# 6.0 code

### Related information

This would be valuable because:

- It is not obvious how to downgrade F# to 5.0  in VS2022
- F# 6.0 has features (new syntax for indexing, better undenting rules) that will reduce friction for learners
- I am teaching F# in Spring Term.

So it would be great to change all my materials and remove the dots!

**Comment by kerams** [comment]
> It is not obvious how to downgrade F# to 5.0 in VS2022
What do you mean? Just don't use F# 6 features (enforcable with `LangVersion`). FSharp.Core 6 is not a problem.

**Comment by tomcl** [comment]
Ahh! thanks for that, I did not know about LangVersion enforcement. Thanks.

The other reason remains, but I guess it is lower priority. Personally I have got used to the . indexing but I do remember how painful it was initially.

**Comment by alfonsogarciacaro** [comment]
We just updated to latest FCS so F# 6 syntax should be supported in the upcoming 3.6 release 👍

**Comment by alfonsogarciacaro** [comment]
I've released v3.6.0-beta-001 with support for F# 6. Could you please give it a go and check if everything works fine for you? Besides F# 6 support it contains several improvements for the watch mode so I hope I didn't break anything :)

**Comment by tomcl** [comment]
Many Thanks!

I have upgraded to 3.6.0-beta-001.

My (20K line) application all works as before. I tried adding and changing some test types in an early compile order file and referencing them in another, all works as expected and I could not detect any _excess compilation_ nor _not-done needed compilation._ In fact excess compilation appeared reduced over 3.9 but that is not a scientific test. That is no guarantee it all works but at least it is initial sanity test. One caveat: ever since the original now fixed bugs I've been keeping everything in one project so am no longer a good test case for multiple fsproj issues. I guess I should maybe separate things out again: which would make dev a bit faster.

I'm getting the F# 6.0 warnings on .[ syntax so it is using F# 6.0. No changes needed to any of the setup.

I guess FABLE should have a flag like LangVersion to downgrade the compiler, maybe it has this? Or picks it up from .fsproj?

Also (irrelevant to me) worth noting that I don't myself use LangVersion or know about it in fsproj, but I suppose some might. In which case FABLE looking at it and doing the right thing might (for them) be desirable. Sorry I don't have much of a clue about LangVersion, but maybe over the 5 -> 6 transition a few people might need it.

**Comment by alfonsogarciacaro** [comment]
Great, thanks a lot for testing the release @tomcl! Good to hear it's working well for you, I detected a problem in watch mode when saving multiple files at the same time, but it's been fixed in 3.6.0-beta-002.

> In fact excess compilation appeared reduced

Yes, one of the improvements was to avoid recompiling unneeded files in watch compilations. This should help in big projects when touching files that are up in the list. We've also made it so changes done while Fable is recompiling are queued and not lost.

>  I've been keeping everything in one project so am no longer a good test case for multiple fsproj issues

Fable merges all sources in a single project under the hood, so for Fable it should be the same either you have one single or multiple project references. Multiple projects may help with the IDE and code organization though.

> I guess FABLE should have a flag like LangVersion to downgrade the compiler, maybe it has this? Or picks it up from .fsproj?

Yes, this is a bit tricky. In principle we can read `LangVersion` from the .fsproj and apply it but then we've issues: e.g. as seen above Fable merges everything in a single project so what happens if you use different LangVersion per project? Also, Fable now relies on a feature from F# 5 (witnesses) which means if you set LangVersion < 5 Fable will fail sometimes.

If the warning about the `[.` is too noisy, it's possible to suppress it with the `--nowarn:3370` flag: https://github.com/fable-compiler/Fable/blob/b4aaa0dfe90b70b4eb7774464112ccd39298b93f/tests/Main/Fable.Tests.fsproj#L2-L8

**Comment by nojaf** [comment]
Hi, you are probably aware of this but I just encountered that some new `FSharp.Core` functions are not yet ported.
I just ran against this when using [List,removeAt](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#removeAt) for example.
Is this tracked somewhere?

**Comment by MangelMaxime** [comment]
Hello @nojaf, 

I don't think it is tracked. Can you please open an issue per missing API you know of or with a list of Todos so we can keep track of it?

I am also closing this issue because F# 6 syntax support has been added to Fable. What you are speaking about is more related to how much .NET API we want to support in Fable.
