### ISSUE TITLE
[Beyond] Numeric types

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2781]
Right now, Fable only includes as "primitive" numeric types those representable in JS. Not sure how are you solving for Python and Rust but I'm realizing this is very limiting. We should likely at least include Int64/UInt64, if a target language doesn't have support for it they should deal with that in `Replacements.makeTypeConst` and then in the Fable2XXX step just fail with "no supported" if a numeric literal of this type remains in the AST (shouldn't happen).

> BTW, it looks that JS BigInt has [good support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility) so this is also good timing to support longs natively in JS.

I'm less sure about BigInt and decimal because they're classes in disguise. Though it seems JS BigInt is not only for longs and be arbitrarily large (except in TypedArrays where it's constrained to 64bits). Thoughts? @ncave @dbrattli

**Comment by ncave** [comment]
@alfonsogarciacaro Makes sense. For Rust I get around the lack of 64-bit ints in the Fable AST by serializing (encoding) them as [floats wrapped in an enum](https://github.com/fable-compiler/Fable/blob/beyond/src/Fable.Transforms/Rust/Replacements.fs#L56-L63). It works, but having proper 64-bit ints in the AST is of course much clearer.

**Comment by dbrattli** [comment]
Not really sure why things work, just focusing on getting the unit-tests to pass 😄  For Python I compile everything to Python `int` since they are variable in length. BigInt is also compiled to `int`. Long uses the low / high bits stuff. For Decimal I compile them to the Python Decimal type. But it would be really great if the AST would  have some proper value types (float / int) instead of "number".

**Comment by alfonsogarciacaro** [comment]
Fixed by #2789
