### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by samwightt** [fable-compiler/Fable#2814]
I think the website is down? Can anyone else verify?

**Comment by MangelMaxime** [comment]
It is down for me too.

Last time it happened, it was because of the domain name not being renew or something like that.

@alfonsogarciacaro Do you know if the person having the domain name renew it?

**Comment by arthurlomakin11** [comment]
For me too, from Ukraine)))

**Comment by arthurlomakin11** [comment]
@MangelMaxime Domain was updated yesterday. And it's now to 2023 expire date. But still don't work

**Comment by MangelMaxime** [comment]
This looks fixed for me.

@arthurlomakin11  @samwightt Can you please check on your side?

**Comment by alfonsogarciacaro** [comment]
Sorry, I didn't have good internet access last week and couldn't check this. The problem seems to be fixed so it was probably related to the renewal of the domain names.

@MangelMaxime I don't remember exactly but I think I already asked the owner of the domain name and he told he was ok with keeping it (and paying the renewal cost) and let us "borrow" it.

**Comment by alfonsogarciacaro** [comment]
I'll close it for now but please reopen if someone else still have issues.
