### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by emaborsa** [fable-compiler/Fable#2839]
I have an old fable project, every time I have to change something it is a fight. This time I am not able to compile it anymore. Last friday it started without errors, today when I run the project using _yarn start_, I get the following error:

```
ERROR in ./src/App/Main.fs
Module build failed (from ./node_modules/fable-loader/index.js):
Error: File C:/Source/MyProject/monthly-data/src/App/Main.fs doesn't belong to parsed project (C:/Source/MyProject/monthly-data/src/App/Main.fs)
    at C:\Source\MyProject\monthly-data\node_modules\fable-loader\index.js:78:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 @ ./src/monthly-data-gatherer.fsproj 1:0-30 1:0-30
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/monthly-data-gatherer.fsproj
```

The exact same code compiles and runs on an other machine, of a collegue.

These are the dependencies:
```
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/plugin-transform-runtime": "^7.3.4",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.3.4",
    "babel-loader": "^8.0.5",
    "copy-webpack-plugin": "^5.0.0",
    "fable-compiler": "^2.1.12",
    "fable-loader": "2.1.4",
    "fable-utils": "1.2.0",
    "html-webpack-plugin": "3.2.0",
    "remotedev": "^0.2.9",
    "webpack": "4.29.6",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "3.2.1"
  },
  "dependencies": {
    "@babel/runtime": "^7.3.4",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "whatwg-fetch": "^3.0.0"
  }`

Using yarn v1.22.10, doesn't compile also with last version.

**Comment by alfonsogarciacaro** [comment]
Hi @emaborsa, sorry to hear you're having issues updating an old Fable project. Sometimes there're small changes that can cause the different tools involved (Fable, Webpack, Yarn) to stop working together. It looks as if your project is using Fable 2, which unfortunately it's out of support now. Can you please try upgrading it to Fable 3 as there're many fixes included in the last version? Fable 3 is backwards-compatible with Fable 2 code, the main difference is Fable 3 is installed as a dotnet tool instead of a Webpack plugin. You can find here a guide and a PR example to upgrade a Fable 2 project: https://github.com/MangelMaxime/fulma-demo/pull/43

> I'd recommend not upgrading other tools (Webpack, Yarn) at the same time to avoid issues.
