### ISSUE TITLE
Force Fable to keep function curried

### ISSUE THREAD

**Issue by JaggerJo** [fable-compiler/Fable#2840]
### Description

We use a JS library that expects a **CURRIED** function as an argument. Fable does automatically **UNCURRY** the function in some cases. 

```fsharp
Fable.Core.JS.console.log (
    createObj [
        "key" ==> "hello"
        "get" ==> (fun a b -> 42)
    ]
)
```
With Fable 3.1.1 this worked as expected. After updating (> 3.1.8) this automatically curries functions. 

<img width="244" alt="image" src="https://user-images.githubusercontent.com/13090415/157535124-e318dcbb-c883-404e-9d52-613e8358b2e2.png">

Somehow passing the curried function through another function seems to prevent auto currying: 

```fsharp

let inline curry (func: 'a -> 'b -> 'c) =
    func

Fable.Core.JS.console.log (
    createObj [
        "key" ==> "hello"
        "get" ==> curry(fun a b -> 42)
    ]
)
```
<img width="244" alt="image" src="https://user-images.githubusercontent.com/13090415/157535644-e373b2be-b537-45df-b903-68c367acf888.png">

This seems really fragile and random to me. In the actual code we pass the curried function as an argument.

```fsharp
let inline curry (func: 'a -> 'b -> 'c) =
    func

type Binding () =

    // does not work / automatically curries the 'getter'
    static member selector<'a, 'b>(key: string, getter: 'a -> IGetter -> 'b) =
        createObj [
            "key" ==> key
            "get" ==> getter
        ]
        
     // works
    static member selector<'a, 'b>(key: string, getter: 'a -> IGetter -> 'b) =
        createObj [
            "key" ==> key
            "get" ==> curry getter
        ]
```

### Repro code

see examples above

### Expected and actual results

Not sure what I expect TBH. I'd like to have a stable way of knowing if a function will be compiled to a curried function or if it will be un-curried automatically. Currently this seems pretty fragile - I'd like to make this more explicit/clear. 

### Related information

* Fable version: `dotnet fable --version` 3.7.5
* Operating system MacOS 12.0.1

**Comment by alfonsogarciacaro** [comment]
Yes, the uncurrying rules are a bit complicated and we adjust them from time to time to try to make things more consistent as it happened recently, but this may have the unfortunate consequence that it can break existing projects as in your case.

Probably I should include this in the docs, there are three main points to consider:

- When you pass a lambda as argument, it's automatically uncurried. This is the "easiest" case because the signature of the argument tells us what arity to expect (e.g., this solves the ambiguity when passing `int -> int -> int` as argument with signature `'a -> 'b`). Passing a lambda to a union/record field works the same way.
- Uncurrying functions **returned** by other function doesn't work well so it's disabled, this is way in your case the function is kept in curried form when returned by another function.
- In patterns used for JS interop, like `Emit` or `createObj` as in your sample, we consider most of the time users expect the function not to be curried to interact with JS. This is more complicated because we don't have a signature so we don't know the expected arity so we just try to detect the nested lambdas and uncurry them.

> In your case, I'm assuming this was the originally intended behavior but didn't work well in 3.1.1 and it was "fixed" in 3.1.8.

In any case when you want to control explicitly the curry/uncurry behavior the recommended way is [to use System.Func<> delegate](https://fable.io/docs/communicate/fable-from-js.html#using-delegates-for-disambiguation), **BUT** I just checked and it looks this is not working well with `createObj` (or typed object expression for that matter) 😞 I need to fix this. For now you can use the "trick" to wrap the lambda with `curry`. This behavior is not going to change and I will add a test to the test suite to make sure there are no regressions. If you inline the function everything will be resolved at compile time:

```fsharp
let inline curry2(f): 'a -> 'b -> 'c =
    f

createObj [
    "key" ==> "hello"
    "get" ==> curry2(fun a b -> 42)
]

// Generates:
// {
//     key: "hello",
//     get: (a) => ((b) => 42),
// }

```

**Comment by JaggerJo** [comment]
Thanks for the fast response @alfonsogarciacaro!

Yeah, it "just worked" with fable 3.1.1 so we never really had to think about it. It's a 3rd party dependency that breaks with fable > 3.1.8 - so in order to update we needed to find out and fix what broke because of the update.

> In any case when you want to control explicitly the curry/uncurry behavior the recommended way is [to use System.Func<> delegate](https://fable.io/docs/communicate/fable-from-js.html#using-delegates-for-disambiguation), BUT I just checked and it looks this is not working well with createObj (or typed object expression for that matter)

Yeah - I tried this.

For now the 'passing it through a function' trick is fine for me as you said it will be stable. 

Thanks for the great work!

**Comment by alfonsogarciacaro** [comment]
@JaggerJo I think I've fixed the issues with delegates to preserve currying in this case. With Fable 3.7.7 you should be able to do something like:

```fsharp
type Curry<'T1, 'T2> = delegate of 'T1 -> 'T2

Fable.Core.JS.console.log (
    createObj [
        "key" ==> "hello"
        "get" ==> Curry(fun a -> Curry(fun b -> 42))
    ]
)
```
