### ISSUE TITLE
createObj not erased despite inlining

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2850]
Hello, I just want to check whether there's something that can be done about what's happening in [this snippet](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWouudAnuFNQPIh0CWwaAF4o-eowBmcAMZgokACYt2nHgDdGWfovmjxDLNLkKIy3AG0APAFEscSmAB8AXVYd5ADSjDcUf1CUdHACMlAAtmDhCIxiEEji8sCaWNq6lFAAFMlaOmCUAFyBYACOVkHaEADmUABUgXSVVU4AlEU8fIIiUACEPZkARDmpeZQDADRQMjghYNwIAFa9PcNp+S1+AUEh-GGR0bHiCRDyivyUxGCKWepwSACuYEUIwMBIbVy8AkI+y4NnF2QVwmUFuDzAG02-m2oQiURiWDix3k0zAsyyoG+EEKxTKHSxrV+qNm8yWFigQ06QjGk2JDFJy0xXQyblwKDoUAAHr9PKg6fILFCoLzVqMoOSBgALACMIKlACYBlA3Kz2VA2Dy+TMGOKhbyAZdro1HrhVWAOUzqUTtXNFuKKZbsSD+QzyX1MiKUmsMhKZXLJYrlS1lS4oGzzVBHZQAOTWtH0u0SqPOm2uv7686GqDGiHKvO4IA&html=DwCwLgtgNgfAUHUBTAhgE3gAk8CSwqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEt2QCoBPEkmaYAxlx7cWPAB5gA9OGgBuCSBQAnAM75G1MADMyADmZYcO8VtokwmHVvGMARMRI6AXIsXVOJADWAOYAdJIQigACAO5IAEYRJFy8YDqK4tQ6YOwQFFBIeNw6UQCMoQBMoQAMGVk5eUgFRWmhELScoQBWOq4wwIrWtvaWwEN2Dk4u7mCk3r7+QWER0XGJucmcqek6mmiCaLlloeUAzIN7B7ltHd29-YM2E-ADIKgYCMDx7PsSUCg6HRuFAkciSbgoDpILR9ODYbC4QRkeKGHKcTD-eJNNzsdh9AYQJEo2ZcF6Kb77eCIZSQWBwIA&css=Q). It does not cause any problems, but represents a potential optimization.

The purpose of the `X` class is to create a configuration object for interop with a JS library. Every method is defined inlined and called with values provided on the spot. It works well where the `createObj` is on a single level as seen with the value of `y`. However, when a method doing `createObj` is passed a value that is constructed in another method also calling `createObj`, one of the calls does not get erased and the result is no longer a simple Pojo - value `x`.

Now, when I manually inline the outer function (`create`), the result _is_ a Pojo - value `options` - and this is what I would expect `x` to turn into.

Any idea why this is? Thank you.

### Related information

* Fable version: 3.7.7 and REPL

**Comment by kerams** [comment]
Interestingly, when I change `create` into anonymous record, which should boil down to the same thing, I do get the [expected result](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWouudAnuFNQPIh0CWwaAF4o-eowBmcAMZgokACYt2nHgDdGWfovmjxDLNLkKIy3AG0APAFEscSmAB8AXVYd5ADSjDcUf1CUdHACMlAAtmDhCIxiEEji8sCaWNq6lFAAFMlaOmCUAFyBYACOVkHaEADmUABUgXSVVU4AlEU8fIIiUACEPZkARDmpeZQDADRQMjghYNwIAFa9PcNp+S1+AUEh-GGR0bHiCRDyivyUxGCKWepwSACuYEUIwMBIbVy8AkI+y4NnF2QVwmUFuDzAG02-m2oQiURiWDix3k0zAsyyoG+EEKxTKHSxrV+qNm8yWFigQ06QjGk2JDFJy0xXQyblwKDoUAAHr9PKg6fILFCoLzVqMoOSBgALACMIKlACYBlA3Kz2VA2Dy+TMGOKhbyAZdro1HrhVWAOUzqUTtXNFuKKZbsSD+QzyX1MiKUmsMhKZXLJYrlS1lS4oGzzVBHZQAOTWtH0u0SqPOm2uv7686GqDGiHKvO4IA&html=DwCwLgtgNgfAUHUBTAhgE3gAk8CSwqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEt2QCoBPEkmaYAxlx7cWPAB5gA9OGgBuCSBQAnAM75G1MADMyADmZYcO8VtokwmHVvGMARMRI6AXIsXVOJADWAOYAdJIQigACAO5IAEYRJFy8YDqK4tQ6YOwQFFBIeNw6UQCMoQBMoQAMGVk5eUgFRWmhELScoQBWOq4wwIrWtvaWwEN2Dk4u7mCk3r7+QWER0XGJucmcqek6mmiCaLlloeUAzIN7B7ltHd29-YM2E-ADIKgYCMDx7PsSUCg6HRuFAkciSbgoDpILR9ODYbC4QRkeKGHKcTD-eJNNzsdh9AYQJEo2ZcF6Kb77eCIZSQWBwIA&css=Q)

```fsharp
    static member inline create (options: seq<IOption>) = {| options = createObj !!options |}
```

I've been looking at this for an hour, and now when I have typed out this issue it occurs to me to try an anonymous record...

**Comment by MangelMaxime** [comment]
@kerams Yes, anonymous record are always (as far as I know) mapping to POJO.

About the problem, you reported about `createObj` I suspect that the reason is we can't always detect correctly the cases and sometimes it could result in bad/invalid JavaScript/behaviour. But on this point, I would wait for @alfonsogarciacaro has he definitely knows better than me.

**Comment by alfonsogarciacaro** [comment]
My guess looking at the generated code is Fable is not confident enough to move inlined `options` arguments and because of this the Pojo optimization cannot identify the expected pattern at the call site. To understand how Fable does inlining, it first creates some bindings for the arguments with the passed values, so:

```fsharp
let inline foo a b = a + b

let x = foo 2 2
```

Becomes:

```fsharp
let x = (fun () ->
    let a = 2
    let b = 2
    a + b)()
```

Then in beta reduction Fable will try to inline the bindings if conditions are fulfilled, like the variable only being referenced one and not being captured by a closure:

```fsharp
let x = 2 + 2
```

However there's another important condition: inlining bindings should not alter side-effect execution. Even though most F# code doesn't have side effects, to be on the safe side we assume that anything that's not a constant or an immutable identifier can have a side effect. We still try to inline bindings in this case, but we need to confirm the expression doesn't "jump" over any other side effect. This is the algorithm to detect this: https://github.com/fable-compiler/Fable/blob/0e6c975b6f7629d1858d84f7a79c62ba534beb46/src/Fable.Transforms/FableTransforms.fs#L136-L205

Looking at the code, I'd assume it's safe to inline the binding here so the Pojo optimization is activated. We may try to fix the algorithm to cover this case, although IIRC I had to make it more strict because it caused weird and difficult-to-reproduce errors in some projects if the optimization was too aggressive.

**Comment by kerams** [comment]
Thank you for the explanations.
