### ISSUE TITLE
[Proposal] Nestable union types?

### ISSUE THREAD

**Issue by cannorin** [fable-compiler/Fable#2858]
Since Fable only supports up to 8-union, `ts2fable` has to emit `obj` when it encounters 9-union or more.

I was experimenting around and got this [(live)](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQoksiKG2aAUgM4CSEALmFqAQQwJ7hQDaAPAFEscamAB8AXSgBVALIU+AcjgAaKIoRrFAYzFQAvASjGoAHyjoRYAIxRgAM3VwjJ85dEAmO440vjbq3kcb3VtPyhqBjgGAEttKABbMASEZjsQAH0hKwATdwYACgAPAC5lAEoDCytbIvDI6LjE5NSsdKzhUTyRQtKNSv1qzyg6-BMIqNj4pJS00A7c-OKy7UqSmSCwPgy1HdC9QfcwTZH6yaaZ1qgYiCQbsHbsrqW+hjWNhT29gD1pA6HjhQoAUAITfIrlNj4AD00IBJwA7tgANbUKAIgAWxAArhAIGBImAcgQUAwoHBbOs5Aobgw1JEsDcAOZqBDAYBIf5ghhYbF4fAEWHwoFIrCo9FY6D4wnE-Ck8leKmbPi0+k85lqak4PhsjlqexIYDRNS4mIMMRc74AFlQHihQqOiJRaMxxGlTByUC8sSS1BJYDJcAAzFAlTTGGrGRAWR9tQajXSoLqkJrlabE7SAGxW-WG6JBjwWy02jz2e1w3HuonC4I3agxHIPKuex0i53+wNW0OxraqiZRmNarbJ3MJk0QM0WqpggqQgUwuHaYAJEAxFBtHLAAlQCDAMlLldIOA3a6OBhYiJwJJQTjcAq0ypwEDgOBYNEMBFxfnyuAAVm7Q4qhG-Yaj2QGJgyoHxtEU6DGCVoeEAA&html=Q&css=Q):

```fsharp
open Fable.Core
open Fable.Core.JsInterop

type [<Erase>] UMore<'a, 'b, 'c> =
    | Case1 of 'a
    | Case2 of 'b
    | CaseMore of 'c
    static member op_ErasedCast(x:'a) = Case1 x
    static member op_ErasedCast(x:'b) = Case2 x
    static member op_ErasedCast(x:'c) : UMore<_, _, 'c> = CaseMore x
    static member inline op_ErasedCast(x:'t) : UMore<_, _, ^U> = CaseMore (!^x)

// CaseMore works when unnested
let a1 : UMore<int, string, bool> = !^true

// CaseMore works when nested
let a2 : UMore<int, string, UMore<bool, float, unit>> = !^4.2

// CaseMore works when nested 2 times
let a3 : UMore<int, string, UMore<float, bool, UMore<unit, int64, float32>>> = !^4.2f

// unnested CaseMore inside nested CaseMore works
let a4 : UMore<int, string, UMore<bool, float, unit>> = !^()

// compiler does not complain if the same type (int) appears twice
let a5 : UMore<int, string, UMore<int, string, float>> = !^42
```

So I found that nestable union types are possible even with Fable's limited support to trait (SRTP) calls.

Should we do this? (Modifying `U8` would break the existing codes, so I would add `U9` with nest support)

**Comment by alfonsogarciacaro** [comment]
Thanks @cannorin! This looks like a good solution so we don't need to set an arbitrary limit for TS unions. It's a bit more cumbersome but I guess that's ok if it's mainly intended for auto-generated code. What do you think @MangelMaxime @Booksbaum?

**Comment by Booksbaum** [comment]
Accessing a nested value is then quite laborious:
```fsharp
let a8 : UMore<int, unit, UMore<int, unit, UMore<int, string, unit>>> = !^ "foo"
match a8 with
| CaseMore (CaseMore (Case2 str)) ->
    printfn "got %s" str
| _ -> ()
```
-> must track how deep nested the Case is (and what actual Case in final nesting) instead of just what index it has.  
(-> better for creating union than consuming it)

But way better than `obj`.  
-> I think it's an ok solution for now


<br/>
<br/>


One consideration is probably how fast [RFC 1092](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1092-anonymous-type-tagged-unions.md) gets implemented -> solves problem without need for nested unions   
But considering how complex that is and how slowly implementation goes it'll likely take a long time

<br/>

----------------

<br/>


One issue I found: deeply nested unions:
```fsharp
let a9 : UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, UMore<int, unit, string>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> = !^ "foo"
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQoksiKG2aAUgM4CSEALmFqAQQwJ7hQDaAPAFEscamAB8AXSgBVALIU+AcjgAaKIoRrFAYzFQAvASjGoAHyjoRYAIxRgAM3VwjJ85dEAmO440vjbq3kcb3VtPyhqBjgGAEttKABbMASEZjsQAH0hKwATdwYACgAPAC5lAEoDCytbIvDI6LjE5NSsdKzhUTyRQtKNSv1qzyg6-BMIqNj4pJS00A7c-OKy7UqSmSCwPgy1HdC9QfcwTZH6yaaZ1qgYiCQbsHbsrqW+hjWNhT29gD1pA6HjhQoAUAITfIrlNj4AD00IBJwA7tgANbUKAIgAWxAArhAIGBImAcgQUAwoHBbOs5Aobgw1JEsDcAOZqBDAYBIf5ghhYbF4fAEWHwoFIrCo9FY6D4wnE-Ck8leKmbPi0+k85lqak4PhsjlqexIYDRNS4mIMMRc74AFlQHihQqOiJRaMxxGlTByUC8sSS1BJYDJcAAzFAlTTGGrGRAWR9tQajXSoLqkJrlabE7SAGxW-WG6JBjwWy02jz2e1w3HuonC4I3agxHIPKuex0i53+wNW0OxraqiZRmNarbJ3MJk0QM0WqpggqQgUwuHaYAJEAxFBtHLAAlQCDAMlLldIOA3a6OBhYiJwJJQTjcAq0ypwEDgOBYNEMBFxfnyuAAVm7Q4qhG-Yaj2QGJgyoHxtEU6DGCVp2vOP4AJwAcqfbpqm4aJphYEYROiaAfhZpYdqxGEehwG4URVEEaRva0SReGMRR2HjkxNE4XRzFcRxlG8axZEsfR4HsYJDECSJ5FScJPFiTJklyVA1H8fJSkqWxyncZxak6VpfGaRpQmKXpRkSbpqn6eJolWQpFmGdpllmTZuGQdGRYeZ5XneT5RbTt8UAAET2OygVAA&html=Q&css=Q))

-> Compilation takes forever (or cannot resolve at all?). I terminated comilation after a couple of minutes.
(same behaviour of course for tooling (like tooltips))

Unlikely to have such intense union (especially when you only nest after 8 prev values). But possible from a tool like ts2fable. That's going to be a funny debugging session of why the F# compiler doesn't come to an end....  
(Though ts2fable wouldn't instantiate the type, but just declare it -> compilation would only break when user accesses the type (like passing something into a function that expects that type))

**Comment by MangelMaxime** [comment]
Removing arbitrary limitation is always a good thing. 

Only thing is that the code to access the value is not really easy to read/understand. But like @Booksbaum said, it is probably better than `obj` and if need I suppose the user can always `box` or `unbox` the value to "simplify" the code.

```fs
let value = unbox<string> myComplexNestedUnionValue

// to avoid stuff like:
let value =
    match a8 with
    | CaseMore (CaseMore (Case2 str)) ->
        str
    | _ -> failwith "unexpected"
```

**Comment by cannorin** [comment]
Regarding the problem on creating `U9+`: 
- As @Booksbaum pointed out, `!^` takes forever to resolve if the target type is deeply nested and it involves a lot of recursive SRTP calls 
- I think on ts2fable we can set the limit to how deeply nested `U9` can become?
- I need to do some experiments to know the limit

Regarding the problem on consuming `U9+`: 
- Matching against `Un` types only works if they only contain basic types (`typeof`) and classes (`instanceof`), but there are only a handful of basic types and ts2fable almost never emits classes, so my guess is `match` would be useless for most 9-unions or more
- As @MangelMaxime said, people can always use `unbox` or `!!` (which they would have used for `obj`) so I think it's ok?
