### ISSUE TITLE
Add an isTruthy function?

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2871]
I was wondering is the standard library (`Fable.Core.JS`) should contain a test for JavaScript truthy-ness?

Something like:

```fsharp
module JS = 

    [<Emit("!!$0")>]
    let inline isTruthy x = jsNative
```

```fsharp
printfn "%b" <| JS.isTruthy 1 // true
printfn "%b" <| JS.isTruthy "a" // true
printfn "%b" <| JS.isTruthy null // false
printfn "%b" <| JS.isTruthy JS.undefined // false
```

This is useful when writing bindings for JS packages.

Happy to send a PR if so!

**Comment by MangelMaxime** [comment]
If this is added don't forget to add type anotation to the function otherwise it can return any type

```fs
[<Emit("!!$0")>]
let inline isTruthy (value : 'T) : bool = jsNative
```

**Comment by alfonsogarciacaro** [comment]
Thanks for the suggestion @njlr! TBH, I'm a bit reluctant to include such a function. Most of the helpers in Fable.Core are there for one of these two reasons:

1. They require compiler magic
2. They can be resolved with `Emit` but we put them in Fable.Core because they are common operations when interacting with JS and we want to make it easy for devs and/or standardize them.

This could enter in category 2, but I'm a bit wary of adding too many things to Fable.Core as I see it as lowest common denominator rather than a general purpose library. I personally try not to rely on "truthy" values when programming in JS/TS (although I do find useful sometimes the fact that empty strings eval to false) so I don't see the need to include this function in Fable.Core.

So as this is something that's very easy to define for custom projects, I'd prefer not to include it in Fable.Core but if many other devs would find it useful we could reconsider it.

**Comment by njlr** [comment]
OK thanks @alfonsogarciacaro !
