### ISSUE TITLE
Bindings with keywords

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2894]
Sometimes we need to write bindings that contain F# keywords (of, begin, end, then). One solution is to use quotations but the code doesn't look very nice:

```fsharp
    type Navigator =
        member _.pop(): unit = nativeOnly
        static member ``of``(context: BuildContext): Navigator = nativeOnly

Navigator.``of``(context).pop()
```

Sometimes we add a an underscore at the end. This makes the call-site looks nicer but requires using `Emit` in the binding:

```fsharp
    type Navigator =
        member _.pop(): unit = nativeOnly
        [<Emit("$0.of($1)")>]
        static member of_(context: BuildContext): Navigator = nativeOnly

Navigator.of_(context).pop()
```

Maybe we could add an automatic mechanism so whenever we're dealing with imported/global types we automatically remove the underscore at the end if any, so binding authors don't need to use `Emit` but they need to be aware of the convention.

What do you think? @ncave @dbrattli @MangelMaxime @Booksbaum

**Comment by MangelMaxime** [comment]
As always, I prefer writing explicit code so I prefer to have to write `Emit` or use the backticks

The reason is because it is really easy to forget about specific rules, and spend a lot of time trying to understand why the code doesn't do what is written.

So I am for not introducing the feature you are mentioning.
