### ISSUE TITLE
Enable precompiledLib for fable watch

### ISSUE THREAD

**Issue by Programmerino** [fable-compiler/Fable#2971]
### Description

When using ``fable watch``, large projects take a long time to compile on the initial build. I tried to get around this by using the new precompilation command, however it seems like it breaks the file watcher in my testing. I used:
```
fable precompile src/App.fsproj -o fable-cache
fable watch src -o js --sourceMaps --precompiledLib fable-cache --runFast yarn exec -- vite --cors
```

### Expected and actual results

I expect ```fable watch``` to avoid the initial compile with the precompiled build, and then to act normally

### Related information

* Fable version: 3.7.6
* Operating system: Arch Linux

**Comment by alfonsogarciacaro** [comment]
Hi @Programmerino, thanks a lot for the report! Maybe it's a bit confusing from the [blog post](https://fable.io/blog/2022/2022-01-09-Faster-compilation-Fable-3-7.html) but the `precompile` option is intended for libraries and/or files that are stable and not supposed to change. If I interpret your commands correctly, you're trying to precompile a project and then watch it. This won't work because Fable will just reference the generated .dll for the precompiled files and won't watch the sources. For a successful precompilation, your project should be split in a way similar to this:

1. `src/MyLib`: This will reference your Nuget packages and files from your project that are not expected to change often
2. `src/MyApp`: This will reference src/MyLib/MyLib.fsproj and contain the files you change normally

Now you can run Fable like this:

```
dotnet fable precompile src/MyLib -o fable-cache
dotnet fable watch src/MyApp -o js --sourceMaps --precompiledLib fable-cache --run yarn exec -- vite --cors
```

This will precompile your dependencies and stable files. You can run this command every time and Fable will automatically detect if the precompilation can be reused or if files have changed (don't do this if files are expected to change often because precompilation brings some overhead when generating the .dll). When the precompilation is done, the second command can bootstrap faster and Fable will watch normally the files in `src/MyApp`.

> **Warning**: Fable Nuget packages that contain different code for DEBUG and RELEASE compilations cannot be precompiled. The two examples I can think of are Elmish.HMR and Fable.Lit.

> **Note**: With Fable 3.7 you don't need to use `runFast` explicitly.

**Comment by Programmerino** [comment]
Alright, makes sense! Thanks for your detailed explanation!
