### ISSUE TITLE
[Python] Fable repl 4 imports not formatted correctly

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/Fable#2977]
### Description

In the Fable repl 4, the Python imports are not formatted correctly. Not sure what's wrong @ncave and what makes it different from the cli, but I would love to help out if you can point me in the right direction.

### Repro code

Default repl example

### Expected and actual results

Expected result:

```py
from __future__ import annotations
from abc import abstractmethod
from typing import (Protocol, Optional, Any)
from fable_library.string import (to_console, printf)
from fable_library.types import Array
```

Actual result:

```py
from __future__ import annotations
from abc import abstractmethod
from typing import (Protocol, Optional, Any)
from fable-library/string.py import (to_console, printf)
from fable-library/types.py import Array
```

**Comment by ncave** [comment]
@dbrattli

The problem seems to be that for Python the import path is [modified](https://github.com/fable-compiler/Fable/blob/snake_island/src/Fable.Cli/Pipeline.fs#L171-L196) in the CLI pipeline, but *not* in the [REPL Worker](https://github.com/fable-compiler/Fable/blob/snake_island/src/fable-standalone/src/Worker/Worker.fs#L51), which uses a simple `SourceWriter` that writes to a StringBuilder.

If you refactor that logic somewhere outside `Fable.Cli`, you should be able to use it in the `REPL` worker too, when `language = Python`. You will have to pass in the language to the `SourceWriter` [here](https://github.com/fable-compiler/Fable/blob/snake_island/src/fable-standalone/src/Worker/Worker.fs#L119) to branch on it.

**Comment by dbrattli** [comment]
@alfonsogarciacaro moved moved path resolution to MakeImportPath in the Printer in #2935. So a bit unsure what to do here. Any suggestions @alfonsogarciacaro ?

**Comment by alfonsogarciacaro** [comment]
Yes, as @ncave says, path resolution is done in 2 steps:

1. During Fable.Transforms we do simplistic resolution and basically we just try to get an absolute path for every import.
2. In Fable.Cli we convert the absolute path into relative paths taking into the account the target directory and also file deduplication. For some reason I put originally this in the `Printer.MakeImportPath` method, but it could a specific step between Fable2XXX and the printing.

Why do we split the path resolution? Because the final resolution uses some APIs from System.IO that are not available when compiling Fable.Transforms to JS, and also because the final resolution depends on things like the target directory, file extension or file deduplication that Fable.Transforms doesn't know about.

I did move the bulk of Python path resolution from Fable2Python to the pipeline 😅 I think it's important to make sure deduplication and target directory are resolved the same way as for other languages. It's true that this is not accessible to the REPL, but the only imports the REPL need to care about is fable-library. Currently the path is hard-coded in the Worker: https://github.com/fable-compiler/Fable/blob/17b8e8667144007f39d4e29a619b31a07fa792c7/src/fable-standalone/src/Worker/Worker.fs#L114-L117

Maybe the only thing we need to do is customize the path for each language and/or adapt this so it uses a `.` instead of the path separator for the REPL: https://github.com/fable-compiler/Fable/blob/17b8e8667144007f39d4e29a619b31a07fa792c7/src/Fable.Transforms/Transforms.Util.fs#L581-L589

**Comment by dbrattli** [comment]
Thanks for the great explanation @alfonsogarciacaro. Yes, that suggested change looks good. Then I can also get rid of that `".py"` as well. But I also have to refactor `MakeImportPath` in `Pipeline.fs` since it expects paths with `/` and not `.`. But thanks to you that code is so much smaller and simpler to work with 👍 I'll see if I can fix this.
