### ISSUE TITLE
Question: Implicit vs compiler generated constructors

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/Fable#3058]
I'm a bit confused about the naming of some functions, i.e `transformClassWithImplicitConstructor` vs `transformClassWithCompilerGeneratedConstructor`. It seems to me that `transformClassWithImplicitConstructor` has a very explicit `cons` argument since the type that is being translated contains one (or more) constructors. 

While `transformClassWithCompilerGeneratedConstructor` do not have any explicit constructor and will generate one for you. Thus the constructor is implicit here.

Shouldn't the names instead then be `transformClassWithExplicitConstructor` and `transformClassWithCompilerGeneratedConstructor`, or have I misunderstood something?

- Explicit: fully revealed or expressed without vagueness
- Implicit: capable of being understood from something else though unexpressed

**Comment by alfonsogarciacaro** [comment]
You're right @dbrattli. I think the name comes because for some reason I think of F# primary constructors as being _implicit_ in the type declaration (vs C# constructors that are declared separately). But it's true it can be confusing. I'm OK with the proposed change 👍

**Comment by ncave** [comment]
I've wondered about that constructor naming too in the past, so it's a good idea to change it to make sense.

**Comment by dbrattli** [comment]
Ok, thanks. I've fixed this for Python.

**Comment by ncave** [comment]
@dbrattli Actually I take that all back, hopefully I'm not entirely wrong again;)

It's better to stick to the F# terminology, and there (like in other languages) the primary constructor is called `implicit` probably because you don't technically declare it as a constructor (using the constructor syntax), but it is a constructor nonetheless.

If you look at its method definition, it will have `.IsImplicitConstructor = true`.
So calling it `implicit` in this context makes sense.

Sorry for going 180 on this, naming things is hard, so it's better to stick to existing nomenclature.

**Comment by dbrattli** [comment]
Ok, @ncave  that's fine. I can rename back. I just need to think "primary" every time I read "implicit" 😄

**Comment by ncave** [comment]
@dbrattli Yes, primary is another name for it, actually F# documentation doesn't really mention `implicit`, only `primary`, so that must be a .NET thing. We can switch to `transformClassWithPrimaryConstructor` then, if you prefer, I agree it's much clearer.

**Comment by dbrattli** [comment]
@ncave I'll give a +1 for that suggestion. Then it's self explanatory.

**Comment by ncave** [comment]
@alfonsogarciacaro @dbrattli Fixed in #3061, feel free to merge if you approve.
