### ISSUE TITLE
%O in interpolated strings doesn't work recursively

### ISSUE THREAD

**Issue by daz10000** [fable-compiler/Fable#3078]
### Description

When evaluation of interpolated strings includes the `%O` operator and that causes a recursive evaluation of `%O` with a ToString implementation,  Fable produces misformatted strings.

### Repro code

```
type B() =
    let a = 6
    with
        override x.ToString() = $"a=%O{a}"
end

let b = B()
printfn $"b=%O{b}"
```

### Expected and actual results

`dotnet fsi` on windows implementation produces the expected 
`B = a=6`

In the fable repl I get

`b=a=6b=undefined`

If either `%O` operator is omitted in the above example,  the Fable version works as expected.

### Related information

* Fable version: (current repl version) (also 3.7.3 on desktop)
* Operating system (windows and web)

**Comment by alfonsogarciacaro** [comment]
You're not going to believe but the problem happened because of JS and mutation 😱 ...well, also because I'm stupid, but maybe because of JS and mutation ;)

We're using a singleton regex to identify the format patterns in interpolation string, but in JS the `lastIndex` property of the regex is updated in every match so when resolving an interpolation gap also involved interpolation, the nested calls modified the `lastIndex` of the singleton regex.

Anyways, should be fixed now. I'll push a release with the fix 👍
