### ISSUE TITLE
importAll not finding exported symbol at run-time

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/Fable#3085]
### Description

Symbol `zip` is undefined at runtime when `importAll` anything other than `zip.js`

### Repro code

See attached zip file

Project is result of these steps
- dotnet new fable
- Follow simple instructions [here](https://github.com/kerams/Fable.ZipJs#usage)

These are reproduced here for convenience:

```
# npm install @zip.js/zip.js@2.4.7
```

- Add to App.fsproj
```
    <PackageReference Include="Fable.ZipJs" Version="1.0.1" />
```

```fs
open Fable.Core.JsInterop
open Fable.ZipJs

importAll "@zip.js/zip.js/dist/zip-no-worker.min.js"
Zip.configure (jsOptions<IConfiguration> (fun x -> x.useWebWorkers <- false))
```

### Expected and actual results

App should start up, with no errors logged to console

However,  this error appears in console
```
Uncaught ReferenceError: zip is not defined
    <anonymous> webpack:///./src/App.fs.js?:13
    js http://localhost:8080/bundle.js:592
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> webpack:///multi_(webpack)-dev-server/client?:2
    0 http://localhost:8080/bundle.js:603
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> http://localhost:8080/bundle.js:84
    <anonymous> http://localhost:8080/bundle.js:87
```

Following link to App.fs.js shows
<img width="198" alt="image" src="https://user-images.githubusercontent.com/285421/185100909-a6163e42-2ad2-4943-a6d0-d0ed76f8eba8.png">

Problem will go away if `importAll[".../zip.js"]` however this doesn't include the no-workers option (which causes other issues). Also: `zip-full.js` and `zip-full.min.js` do *not* work.

 I'm logging as a fable issue since I can't see what's wrong with the exports on any of these modules.

### Related information

* Fable version: 3.2.9
```
Darwin davebook.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
```

**Comment by davedawkins** [comment]
[x.zip](https://github.com/fable-compiler/Fable/files/9358972/x.zip)

**Comment by alfonsogarciacaro** [comment]
Hi @davedawkins! I guess that here you probably need `importSideEffects` instead. If you use `importAll` it will be translated to something like this:

```js
import * as zip_no_worker$002Emin from "@zip.js/zip.js/dist/zip-no-worker.min.js";
```

TBH, I'm not sure what are the semantics of JS in this case. It may also behave differently depending on the bundler you're using. I assume in your case, the import is just ignored because you're not using it directly. When using `importSideEffects` usually the bundlers understand that you're interested in the side effects when importing: applying some styles, declaring global variables, etc.

Probably it would be a good idea to raise a warning if you're not assigning `importAll` to anything. Unfortunately, F# doesn't raise a warning because `importAll` returns a generic so F# just assumes it's `unit` in this case. Maybe we could even detect if importAll is not being assigned to anything and compile it the same way as `importSideEffects` in that case, but I'm not sure how easy it is.

**Comment by gildas-lormeau** [comment]
@davedawkins, @alfonsogarciacaro Author of zip.js here, I stumbled upon this issue with the search engine of GitHub. I guess the problem is that the file you're importing is not an ES module. Import `@zip.js/zip.js/lib/zip-no-worker.js` instead. I added a note in the [README](https://github.com/gildas-lormeau/zip.js/blob/master/dist/README.md) from the `dist` folder regarding this issue.

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot for your help @gildas-lormeau!

@davedawkins Could you please try it? I can see the [Fable.ZipJs bindings](https://github.com/kerams/Fable.ZipJs/blob/b1a7144462cef7c1559886cbdbf774efc7d92955/Fable.ZipJs/Zip.fs#L320-L323) assume the library is in a `zip` variable in scope so you need to use that name for the import identifier:

```fsharp
open Fable.Core
open Fable.Core.JsInterop
open Fable.ZipJs

let zip: obj = importAll "@zip.js/zip.js/lib/zip-no-worker.js"

// Alternatively
// [<ImportAll("@zip.js/zip.js/lib/zip-no-worker.js")>]
// let zip: obj = jsNative

Zip.configure (jsOptions<IConfiguration> (fun x -> x.useWebWorkers <- false))
```

> I'll open an issue in Fable.ZipJs so the example is updated 👍

**Comment by gildas-lormeau** [comment]
@alfonsogarciacaro You're welcome, I'm glad to hear that I was able to help in fixing this problem :)

**Comment by davedawkins** [comment]
YES!! This worked. Thanks all.
