### ISSUE TITLE
Question: Where can users help with snake island?

### ISSUE THREAD

**Issue by bentok** [fable-compiler/Fable#3088]
I have a Flutter app I've been making that uses Flutter Redux. Rather than moving the whole app to F# (I plan to release the app next month), I converted the entire redux architecture to F# - it is a somewhat Elmish-ish setup - so I have a bit of interop between Dart and F#. The whole thing has gone very smoothly.

I imagine since I'll probably release this thing in the next month, I'll be a somewhat early user of Fable -> Dart compilation in a production app, and as such I'd like to do what I can to be a good, helpful early adopter. If I can contribute in some way, where would be most helpful? I don't have any experience contributing to the Fable compiler project.

**Comment by alfonsogarciacaro** [comment]
That's great to hear @bentok! And thanks a lot for your offer to help ❤️ I'm very happy to hear that the interaction between F# and Dart it's working well. I had high hopes about it thanks to the quality of the generated code, and also because Dart is a typed language and has some similarities with dotnet semantics (e.g. equality and comparison).

I think the best way to help is to let the world (and Fable maintainers) know about your work. I understand that probably your code cannot be made public but if you can tweet or post about your experience that will encourage others to try F# to Dart compilation (if you don't have a blog on your own you can post in Fable's blog, [example](https://github.com/fable-compiler/fable-compiler.github.io/pull/61)). Also, reporting about the problems you've encountered is very useful for us to know where to put the focus on, so please don't hesitate to open an issue for any suggestion or question you may have.

I guess the first step for me is to formalize the Flutter bindings and put them in a proper package 😅 I assume for now you've pasted them from the Fable Flutter sample, did you make any modifications? If you want, I can put the bindings in their own repo and give you access if you can help maintain/improve them 👍

**Comment by bentok** [comment]
Will do! I'll write about my experience as you suggested. I can't make the code public, but I can definitely share large snippets as well as the experience. I could probably also write up some material on using Fable with Flutter Redux in an Elmish-inspired way

Surprisingly, I was able to put a significant amount of code in F#  by _only_ using Dart bindings. I didn't use the Flutter bindings from the example repo at all (although I do want to migrate the rest at a future date). With the redux architecture I had a lot of the most important code in action creators, along with model classes and selector functions which would grab data from the store and manipulate it in different ways. All of that code was just plain Dart and it ported to F# elegantly. When the Flutter widgets which are still written in Dart interact with the Fable compiled code, the fable_modules utilities are really easy to use and do the job well. I'm just in love with how smooth the whole thing is and can't way to rewrite the actual Flutter widgets!

**Comment by bentok** [comment]
>  If you want, I can put the bindings in their own repo and give you access if you can help maintain/improve them 👍

I would love to help in this regard.
