### ISSUE TITLE
Object members are sometimes not uncurried

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3093]
Looks like sometimes object members are not uncurried (as opposed to module members).
It makes generating member types a bit unpredictable (i.e. are there any corner cases where we want to uncurry lambda types? Perhaps not).

```fs
let test f = (fun x y -> f x y)

type Test =
    static member test f = (fun x y -> f x y)
```
Generates this:
```js
export function test(f, x, y) {
    return f(x, y);                       // <-- uncurried as expected
}

export function Test_test_Z5BC4E4FB(f) {
    return (x) => ((y) => f(x, y));       // <-- not uncurried
}
```
Possibly related to #2436

**Comment by ncave** [comment]
Perhaps it's just a fact of life, feel free to close.

**Comment by alfonsogarciacaro** [comment]
I need to check, but on first sight I think this is unfortunately "by design". In fact, Fable is not doing any uncurrying here. Fable only uncurries functions passed as arguments, not declarations. FCS by default converts module functions into multi-argument methods both when the arguments are curried or tupled. So FCS generates the same AST for these three declarations:

```fsharp
let test2 f = (fun x y -> f x y)
let test2 f x y = f x y
let test3 (f, x, y) = f x y
```

FCS does something similar with class methods, but apparently not when we make the method return a function. So in the sample below the AST generated for Test.test1 and Test.test2 is not the same. I assume this is because from the C# point of view the signature of the two methods is different.

```fsharp
type Test =
    static member test1 f = (fun x y -> f x y)
    static member test2 f x y = f x y
    static member test3 (f, x, y) = f x y
```

**Comment by ncave** [comment]
Thanks @alfonsogarciacaro!
