### ISSUE TITLE
Some namespace confusing

### ISSUE THREAD

**Issue by napretep** [fable-compiler/Fable#3117]
## when imported Browser.Dom, cannot find style
![image](https://user-images.githubusercontent.com/7680792/187092017-8b2d8144-3005-4a53-831e-b74b73a06560.png)
## when imported Browser , cannot find Event
![image](https://user-images.githubusercontent.com/7680792/187092028-3f2122f8-25b2-41ef-8709-cf59bd77d1c1.png)
How to import them at the same time?

[code at fable.io](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpJQEIBOwA7gmAQHQAqc4CWO0AYgIYBGANmBQMLAFgG4aIRJkCQ3AFkAlgGMiCYADMkFJjAAWLAiF7AOXOUhnAI9TFyRQWALgASVKQBkAol1SRrAXigATYDkAV08INQUwFhR3NC8oACI-GQA3eKx0zAysKygEKF8WCmQ4LizM8pywX1dkrwAeZAIZCABzACpG5paAPgAKAEogA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZWYiFOOzq4eJKS6AFxKSjRcpADWAObxUhBKAAIA7kjhx6TcfGBRl9d9t1z3ugWnAEzxAAzxAGYlBIaLowH1KFAkPgeLpKLoAKzkdAoRxIbT5QrFUo1CpzXF1JbuFbrTbbPaHY5nJ43O6w4Gg8EQSHQ96nACM8R+vwZYIhSChMIeWRymImOPKYHg1UliwaJI2Wx2ByOfWpV1pb3pui0aCEvQgHPinKBOvQ+r6IrGWMmBPgCBKIFQGAd4RSQkkUBQul0HlRFCkPBQOXRRTgOFwECE5HCRnBXEwXvCAo8HA44qjMbj3GlSjdevtjsgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

**Comment by alfonsogarciacaro** [comment]
Sorry it's a bit confusing. We had some discussions about this but when publishing the API, we always try to find a balance between requiring less open statements and avoiding scope pollution, but there's rarely a single perfect solution. Unfortunately, because in F# we cannot qualify namespaces (only modules as in `module Dom = Browser.Dom`) it's easy to have conflicts when opening too many things. In the past we had problems with `Option` module and the type in Fable.Core.JS.

This is explained in [fable-browser README](https://github.com/fable-compiler/fable-browser#usage) but the solution we came up with was to open all APIs (Dom, WebSocket, etc) when using `open Browser`, and the types (like Event, HTMLElement, etc) when using `open Browser.Types`. Our hope at the beginning was users would only need `Browser` but most of the times you need both. So in general:

1. Reference the packages containing the APIs you need. For example, note that styles are in their own package because the API is very big, so:
```
dotnet add package Fable.Browser.Dom
dotnet add package Fable.Browser.Css
```
2. Open both Browser and Browser.Types:
```fsharp
open Browser
open Browser.Types
```
