### ISSUE TITLE
AttachMembers generates invalid Python for static fields

### ISSUE THREAD

**Issue by OneManEquipe** [fable-compiler/Fable#3255]
### Description

When adding a static field (`static member Foo = obj ()`) to a type marked with the `AttachMembers` attribute, compilation generates invalid python code: instead of emitting a `@property` it emits a simple field, which references the type before it exists.

### Repro code

repl: https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDaAPAIIAuZcAxgBYCyYAtgmFgM4B8AurmQJ7hYwYFAAUASigBeXFDlRGTFligAPVACE4WCdKggsASwhkAZtABENYEjgBCC-nlQ2lMoaoKlrKAGVgijDCekHAEvihqP6BwpraEkA&html=Q&css=Q

For convenience, here is the code:

```fs
open Fable.Core

[<AttachMembers>]
type Foo () =
    member x.Bar() = printf "hello!"

    static member SomeFoo = Foo()

Foo.SomeFoo.Bar()
```

### Expected and actual results

I am providing the full expected and actual results, and marking a comment on the problematic line, but please see "Explanation" below for a more readable explanation.

#### Expected result

```py
from __future__ import annotations
from typing import Literal
from fable_library.reflection import (TypeInfo, class_type)
from fable_library.string import (to_console, printf)

def _expr17() -> TypeInfo:
    return class_type("Test.Foo", None, Foo)


class Foo:
    def __init__(self, __unit: Literal[None]=None) -> None:
        pass

    def Bar(self, __unit: Literal[None]=None) -> None:
        to_console(printf("hola!"))

    # I would expect a property, so that the reference to Foo happens after the class is initialized
    @property
    def SomeFoo() -> Foo:
        return Foo()

Foo_reflection = _expr17

def Foo__ctor(__unit: Literal[None]=None) -> Foo:
    return Foo(__unit)


Foo.SomeFoo.Bar()

__all__ = ["Foo_reflection"]
```

#### Actual Result

```py
from __future__ import annotations
from typing import Literal
from fable_library.reflection import (TypeInfo, class_type)
from fable_library.string import (to_console, printf)

def _expr18() -> TypeInfo:
    return class_type("Test.Foo", None, Foo)


class Foo:
    def __init__(self, __unit: Literal[None]=None) -> None:
        pass

    def Bar(self, __unit: Literal[None]=None) -> None:
        to_console(printf("hola!"))

    # this causes an early reference to Foo (on the right-hand side of the assignment, the type is correctly handled thanks to the `from __future__ import annotations` 
    SomeFoo: Foo = Foo()

Foo_reflection = _expr18

def Foo__ctor(__unit: Literal[None]=None) -> Foo:
    return Foo(__unit)


Foo.SomeFoo.Bar()

__all__ = ["Foo_reflection"]
```

#### Explanation

Static member `SomeFoo` in Javascript is compiled (correctly) as follows:

```js
static get SomeFoo() {
    return new Foo();
}
```

In Python, instead, it compiles to:

```py
SomeFoo: Foo = Foo()
```

This causes an early invocation to `Foo`, which is not defined yet as we are inside its definition.

The correct code to be generated (also aligned to the behaviour in Javascript)  would be:

```py
@property
def SomeFoo() -> Foo:
    return Foo()
```

### Related information

Aside from the Fable tool version I don't think other versions matter at all in this specific case, but here is all I could find:

- Fable tool: 4.0.0-theta-015
- Fable.Core: 4.0.0-theta-006
- Python: 3.10.7
- dotnet: 6.0.402
- operating system: MacOS 12.6 (Monterey)

**Comment by dbrattli** [comment]
@OneManEquipe Thanks for the detailed error report. I don't think static properties is a thing in Python (did you btw try to run your suggested code?). We could somehow make it work by making it into a classmethod instead:

```py
    @classmethod
    @property
    def SomeFoo(cls): 
        return Foo()
```

But even this will stop working from Python 3.11 https://docs.python.org/3.11/library/functions.html#classmethod.

To make this work you would have to remove the `[<AttachMembers>]` attribute. Is that not an option? Why?

**Comment by dbrattli** [comment]
I see some use e.g a custom `classproperty`. I will need to investigate if this could be a solution?

```py
class classproperty(property):
    def __get__(self, owner_self, owner_cls):
        return self.fget(owner_cls)
```

**Comment by OneManEquipe** [comment]
@dbrattli well this is embarassing... yes I did try the code, but then I rewrote it a few times trying to simplify the example, and thought "there's no way I messed it up".

I can't remove `[<AttachMembers>]` because I'm working on a cross-language library, and detached members would make the API very weird (I'm still going to write more idiomatic wrappers for each target, but I'd like to keep them as thin as possible).

I like your proposed solution, though it does need some investigation; I'll try it in my specific use case just to be sure.

Thanks!

On a side note: why is python 3.11 removing class properties? They were just introduced :(

**Comment by dbrattli** [comment]
Found some info here: https://github.com/python/cpython/issues/89519

**Comment by OneManEquipe** [comment]
mmm then I think it's just a matter of: is Fable aiming at writing libraries as well? If so, I think it would be useful to support this (especially since in JS it is already supported), otherwise it might be superfluous.

What do you think?

(in my specific case I can work around it by changing `static member SomeFoo = Foo()` to `static member SomeFoo () = Foo()`, with little-to-no impact on my code)

**Comment by dbrattli** [comment]
Yes, I think you would need to work around it. Fable generates working code in the normal case and `[<AttachMembers>]` is a special case which do not work for any F# code (or I would already have used it by default). Python do not support static properties so you would need to work around the problem. 

Fable aims at writing libraries, and we have quite a few libraries as well. But libraries can be made for either F# Fable apps, Python apps or both. This is the same for F# itself. Not all F# libraries are easily consumable from C#, and if you want your libraries to be usable from C#, then you need to follow the guidelines https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines. Those guidelines should work well for targeting Python also, i.e use .NET types instead of F# types since that would target Python native types etc. I will add info about this at our own guidelines at: https://fable.io/Fable.Python/communicate/fable-from-py.html

**Comment by dbrattli** [comment]
Any thoughts about this issue? @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Not sure, I added `AttachMembers` because some patterns required it (like implementing a Web Component). It's true some devs want it to be default because it generates more idiomatic code, but I prefer to restrict it to only where it is necessary because it has problems, like overloads not working.

In principle `AttachMembers` only attaches the member reference to the class declaration in the AST (and also deals with the calls) but the actual implementation is responsibility of the target language (including binding the `this` argument). Not sure how you can deal with static properties in Python, maybe converting them to methods?

**Comment by dbrattli** [comment]
Converting them to static methods is a great suggestion @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
@dbrattli For that, I think you can deal with the declaration in Fable2Python. The calls to attached properties are resolved here, so maybe you can check if the language is Python and the property is static and in that case call it as a method: https://github.com/fable-compiler/Fable/blob/f7412403ef53ffa29dcf60d5806dac7a1bb04e01/src/Fable.Transforms/FSharp2Fable.Util.fs#L2049-L2057
