### ISSUE TITLE
Wrong behavior if --outDir is a prefix of project dir

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#3274]
### Description

A simple project layout like so:

```
./fable_src
├── fable.fsproj
└── Program.fs
```

When compiling like this:

```bash
dotnet fable fable_src/fable.fsproj --verbose --outDir fable --extension .fs.js --noRestore --noCache
```

The transpiled file `Program.fs.js` appears in `fable_src` instead of `fable`. 

### Repro code

Please see this repo: https://github.com/njlr/fable-out-dir-repro

The GitHub Action demonstrates the issue.

### Expected and actual results

I would expect the transpiled file to be in the `--outDir`, so `fable/Program.fs.js`

Instead it appears under the source directory at `fable_src/Program.fs.js`

The `_` in `fable_src` may be a significant factor.

### Related information

* Fable version: `3.7.20`
* Operating system: Ubuntu 22.04

**Comment by alfonsogarciacaro** [comment]
Oh, thanks a lot for providing the code, I can indeed reproduce. Still unsure why, but it seems the problem is using `fable` exactly as `--outDir`. If you pass something like `fable_build` or `build/fable` instead it will work.

I will try to find what's causing the problem exactly. I remember we had a similar issue in the past and had to "ban" some outDirs like "bin", maybe we need to add "fable" to the list 😅

**Comment by njlr** [comment]
I think it might be when the output directory is a prefix of the source directory - in this case "fable"

**Comment by alfonsogarciacaro** [comment]
You're right! 👀 The problem also happens when using `fable_s` as outDir. Probably this means we need to fix the algorithm to find the common base dir 👍
