### ISSUE TITLE
Fable issues with reflection in Fable-compatible library

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3394]
### Description

Hey everyone, i am working on a library ([FsSpreadsheet](https://github.com/Freymaurer/FsSpreadsheet/tree/fable) and want to make one project fable compatible. I followed the official [guide lines](https://fable.io/docs/your-fable-project/author-a-fable-library.html) and started testing around with local nuget packages (`./build.cmd pack` to create nuget packages). I then created a fresh SAFE stack to test the whole thing ([here](https://github.com/Freymaurer/Fable-reflection-library-issue)). I used a `nuget.config` to add a local feed for my nuget packages and tested around. Now to my issue. [This](https://github.com/Freymaurer/FsSpreadsheet/blob/635f3d707ab7df959669264a28123a3fd9b3c4e4/src/FsSpreadsheet/Cells/FsCell.fs#L231) member function errors in fable with:

![image](https://user-images.githubusercontent.com/39732517/229076231-c8b09b7b-5657-4557-a9a1-6158ec2b69dd.png)

I then removed this function for fable using the `#if FABLE_COMPILER` logic you can see in the current version of the repo.
I added the package again and it works with the function removed. I then added the code to the test SAFE stack directly [here](https://github.com/Freymaurer/Fable-reflection-library-issue/blob/e2be2ba60b700aa687843d10d39b5e33d4e6851c/src/Client/Test.fs#L9) and it works. 

So to summarize, the same function returns an error in a Fable library, but runs if written directly into the Fable compiled project.

### Repro code

**Fable library**: https://github.com/Freymaurer/FsSpreadsheet/tree/fable
**Test SAFE stack**: https://github.com/Freymaurer/Fable-reflection-library-issue

The test SAFE stack contains to local nuget packages in `lib`. 
Version 1.1.9 has the relevant code in the library removed (therefore it works in the SAFE stack),
version 1.2.0 contains the relevant code (therefore it does not work in the SAFE stack).
Can switch between these versions [here](https://github.com/Freymaurer/Fable-reflection-library-issue/blob/e2be2ba60b700aa687843d10d39b5e33d4e6851c/src/Client/Client.fsproj#L15).

### Expected and actual results

It should work in both versions or not work in both versions.

### Related information

* Fable version: `dotnet fable --version`:  **3.7.5**
* Operating system: Windows **10**

Please let me know if you need further information 👍

**Comment by MangelMaxime** [comment]
Hello @Freymaurer can you please try with the latest version of Fable?

If you can't use Fable 4, can you try with Fable 3.7.20?

**Comment by alfonsogarciacaro** [comment]
I assume the problem is not actually caused by `GetValueAs` because that function is inlined (that's why it works with the SAFE stack) but the [helper below](https://github.com/Freymaurer/FsSpreadsheet/blob/635f3d707ab7df959669264a28123a3fd9b3c4e4/src/FsSpreadsheet/Cells/FsCell.fs#L260-L261) which is not inlined.

**Comment by Freymaurer** [comment]
I will test both and answer asap 👍

**Comment by alfonsogarciacaro** [comment]
@Freymaurer BTW, inlining big functions must be done with care because you can end up emitting too much code. I'm trying [to improve this](https://github.com/fable-compiler/Fable/pull/3396/commits/6987bc34aefdb0a38ca2e68f89c32fc2276a0309) by doing the equality at compile time and eliminating the false branches. But anyways a common pattern for these situations is to inline only a small helper that extracts the type info from the generic and then calls the big method:

```fsharp
let getValue(t: Type) =
    // Big function
    
let inline getValueAs<'T>() = getValue typeof<'T>
```
