### ISSUE TITLE
How to get started with Fable 4?

### ISSUE THREAD

**Issue by marcelocra** [fable-compiler/Fable#3426]
Hey there!

Instructions from fable.io point to a couple of blog posts, but I couldn't get Fable 4 running from those.

Do you have anything more up to date?

_(I can help updating the docs if that'd be useful.)_

**Comment by OnurGumus** [comment]
I have a very lengthy video for  getting started Fable.Lit

https://www.youtube.com/watch?v=u4H8dOg_Z3w

**Comment by MangelMaxime** [comment]
@marcelocra In theory, all the documentation about Fable 3 should still be relevant to Fable 4 because it is consumed the same way.

If you want just something to test it, today I am releasing a new Gitpod template for Fable 4 + Vite + React. Found here: https://github.com/MangelMaxime/template-gitpod-fable-4-vite-react

If you want a more guided step by step, it is something like:

**Install Fable tool locally to your project**

1. `dotnet new tool-manifest`
2. `dotnet tool install fable`

**Create an F# project and add Fable.Core dependency to it**

4. `dotnet new classlib -lang f#` 
5. `dotnet package add Fable.Core`

**Change the code**

6. Replace `Library.fs` content with

```fs
module App

open Fable.Core

printfn "Hello from Fable!"
```

**Compile F# to JavaScript files**

7. `dotnet fable -e mjs` *I am using mjs extension here otherwise, node is going to complain that we are not in a `module` project. (Nothing to do with F#)*

**Use node to execute the compiled file**

8. `node Library.mjs` 

The things to understand with Fable is really just instead of doing `Manually edit JS file > Execute JS` you do `Manually edit F# file > Generates JS files > Execute JS`.

**Comment by MangelMaxime** [comment]
> 4\. I ended up with a project configured to use Fable 3, requiring .NET 6. At this point my guess is that `Fable.Template` is still using Fable 3?

Templates are indeed using Fable 3. However, the templates are configured with a `global.json` file meaning if you have .NET7 and .NET6 installed you will be fine as the template will choose the correct version.

That's the reason why it worked after you installed both .NET 6 too.

> Again, sorry for the confusion and thanks for the quick and helpful answers! The F# community seems very welcoming and Fable too!

Thank you :), I would say to that we are welcoming just need as always to work on the documentation but this is a never ending task ahah.

> **Last question here**: do we have a good hot module replacement (stateful reload) story with Fable? From my initial tests it seems like state is always reset, but I remember seeing a demo that worked differently.

It does support HMR, but it depends on the tooling/library you are using:

- If you are using Elmish, then it is provided by Elmish.HMR package
- If you are using React, then you need to refer to your JavaScript bundler documentation (Vite, Webpack, Parcel, etc.)
- If you use any other JavaScript library, you need to refer to their documentation too.

What is tricky, is that depending on the choice made HMR can have requirements or not. For example, Elmish.HMR doesn't need anything special to be done beside installing it and using it's API.

But if you use React, then you files need to only expose React component, so you have to mark your types, non React component function as private, etc.

**Comment by marcelocra** [comment]
> Templates are indeed using Fable 3. However, the templates are configured with a global.json file meaning if you have .NET7 and .NET6 installed you will be fine as the template will choose the correct version.

Yeah, I noticed that. Before installing .NET 6 I tried to change the required .NET version mentioned there. I knew that it was a bad idea and that it would probably not work (and it didn't haha), but it was very easy to try, so I did.

> That's the reason why it worked after you installed both .NET 6 too.

Sure, makes sense.

> Thank you :), I would say to that we are welcoming just need as always to work on the documentation but this is a never ending task ahah.

Yes, and I plan on helping with the docs, as I have a beginner's vision right now. Do you know if we have a "Fable for .NET beginners" doc or something like that? Perhaps even in the F# main docs?

If not, I can open a new issue to discuss/track that.

> It does support HMR, but it depends on the tooling/library you are using

Cool, I'll try Elmish then. Have played with Elm in the past and it will be interesting to see how they compare.

---

Closing the issue, as I'm sure your suggestions will work for me. If I have any problem, I'll report here. Thanks!

**Comment by MangelMaxime** [comment]
> Yes, and I plan on helping with the docs, as I have a beginner's vision right now. Do you know if we have a "Fable for .NET beginners" doc or something like that? Perhaps even in the F# main docs?

There is just this section https://fable.io/docs/introduction/dotnet-users-read-this.html 

We don't have a big section because in reality, once you know what is on that page the rest of the knowledge to learn falls in 2 categories:

- Fable specifics which any user of Fable needs to learn independently of their .NET or JavaScript background
- JavaScript specifics because well you are running code on a JavaScript runtime

If you feel like improvements can be made, please send PRs or open issues on the docs repository. Of if you feel like a blog post is better you can send one to the repo or on medium or the new hot tool at the moment 🙂

Happy coding and if you need have others problems feel free to ask on Github, Gitter or Slack.
