### ISSUE TITLE
Decorators Support

### ISSUE THREAD

**Issue by danfma** [fable-compiler/Fable#347]
### Description

Most of the libraries today, like Angular 2, Aurelia, Mobx and others, use decorators as a source of metadata or to extend the existent functionality of some object.

https://www.typescriptlang.org/docs/handbook/decorators.html

I am not a F# pro so I will need help with this, but it will be nice if the fable provides some synthetic way to do that. By now, we only can apply decorator to classes, affecting the objects, in JS. I will let the definition of decorators in the link.
### Propose

To apply this kind of decorator in a more .NET way and keep the compatibility with JS, we could do use synthetic Attributes, like:

``` F#
[<ClassDecorator(myDecorator)>]
type MyClass =
  ...
```

The compiler then can translate this to something like:

``` javascript
function MyClass() {
}

...

MyClass = __decorate([
        myDecorator, 
        __metadata('design:paramtypes', [])
    ], MyClass);
```

borrowing the function __metadata from the generated js from typescript.

This would allow us to define and use any type of decorator and this can be extended to any decorator type (class, property, method). The decorator syntax in F# could be just the method receiving a function, but that I leave for others to define better.
### Another approuch to create decorators

``` F#
type MyDecorator (... parameters) =
  inherits CustomClassDecorator<T>
  override this.apply(constructor: Constructor<T>) =
    ... do something
    ()
```

``` javascript
function myDecorator(target) {
   var fsharpDecorator = new MyDecorator(); // defined before in some place
   return fsharpDecorator.apply(target);
}
```

**Comment by alfonsogarciacaro** [comment]
It'd be nice to have this feature. Some comments:

- As there're currently competing proposals for JS decorators (the so called decorators vs annotations) I would just compile them using ES7 syntax and then let the user decide the appropriate Babel plugin to compile them to ES5. For example: https://github.com/shuhei/babel-plugin-angular2-annotations

- F# attributes have some restrictions, for example you cannot pass a method reference or a lambda as an argument. Because of this and because many attributes are just used for the compilation process, maybe a nice and simple way to start would be to add imported decorators, as in most cases this feature will be used with decorators from frameworks like Angular 2. For example:

```fsharp
open Fable.Core

[<ImportedDecorator(
    "Component", "@angular/core",
    "<h1>My First Angular 2 App</h1>")>]
type AppComponent() =
    class end
```

...would translate to:

```js
import { Component } from '@angular/core';

@Component('<h1>My First Angular 2 App</h1>')
export class AppComponent { }
```

> It would still be possible to create your own decorators, but you'll have to do it in another file.

I still need to solve how to pass non primitive values to the attribute constructor arguments though.

**Comment by danfma** [comment]
This could solve the problem with the use of decorators as annotations but when you need to create some, it won't. We need to find a better way to do that.

**Comment by alfonsogarciacaro** [comment]
Then I'm afraid we'll probably won't be able to use F# attributes, we'll have to use a helper function after the type definition. Something like:

```fsharp
open Fable.Core.JsInterop

let Component = importMember "@angular/core"

type AppComponent() =
    class end

attachDecorator<AppComponent> Component
    (createObj [ "selector" ==> "my-app"
                 "template" ==> "<h1>My First Angular 2 App</h1>" ])
```

**Comment by danfma** [comment]
I used this approuch when working with Kotlin (yes, I'm trying a lot of transpilers by these days), but it is not natural (at least, from a js perspective). I still think that the attribute inheritance should be the best option to do that. I will investigate too.

**Comment by alfonsogarciacaro** [comment]
Closing the issue for now as it's not planned to add decorator support for now, at least until decorators specs become final in JS.
