### ISSUE TITLE
"Cannot find replacement for System.Int32.Parse"

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#348]
When converting old code I get 

```
Cannot find replacement for System.Int32.Parse
```

An easy fix is to use `int` convert function instead.

We should stil consider to add these "replacements"

**Comment by alfonsogarciacaro** [comment]
It's difficult where to draw the line to support BCL methods, In general I prefer to focus on FSharp.Core and avoid implementing specific methods of some classes from the BCL because it may be confusing for users to see some methods of the class are implemented and other aren't.

Of course, we can still discuss if it's better to add this method or not. In any case, remember that for translating old code or other specific cases, you can always use custom plugins to add the specific replacements you need without having to wait for a Fable update.

**Comment by jptarqu** [comment]
When I use the recommended FSharp.Core.int.Parse and/or FSharp.Core.int.TryParse instead of the BCL, I am still getting the following error by the Fable compiler:

> ERROR: Cannot find replacement for System.Int32.Parse (L8,35-L8,56)

Should I be using something different from FSharp.Core.int.Parse and/or FSharp.Core.int.TryParse?

Thanks!

**Comment by markek** [comment]
Try
~~~~
int "4"
~~~~

Note that
~~~~
int "x"
~~~~
produces an exception in f#, but a javascript number of NaN (no exception) in fable. For more insight, be aware that `int` is actually a function `int<'T>: 'T -> int`
