### ISSUE TITLE
curriing limit to 10 is low

### ISSUE THREAD

**Issue by slyshykO** [fable-compiler/Fable#3514]
### Description

I've tried to create a form with 11 fields with Fable.Form .
When compiling to JavaScript Fable generates the wrong function call & export

```js

import { createObj, curry11 } from "./fable_modules/fable-library.4.1.4/Util.js";
...
return append(extra0Field, append(extra0Field, append(extra0Field, append(extra0Field, append(extra0Field, append(extra0Field, append(extra1Field, append(extra0Field, append(rememberMe, append(passwordField, append(emailField, succeed(curry11(onSubmit)))))))))))));
...
```

Fable 4.0.1 generate the working code.

### Repro code

https://github.com/slyshykO/big-form

### Expected and actual results

Fable compile working code.

### Related information

* Fable version: 4.1.4
* Operating system: win11 x64

**Comment by MangelMaxime** [comment]
When running fable in non watch mode (`dotnet fable src`) the generated is correct and support infinite curry as requested in https://github.com/fable-compiler/Fable/issues/2525

However, if running it in watch mode (`dotnet fable watch src`) then it tries to use `curry11` which is invalid.

Fable `4.0.2` is the version which introduced this regression.

If you revert to Fable `4.0.1` then your application should works, you will have a few bug fixes missing but most of the changes are related to the others Fable target like TypeScript, Rust, Python, etc. So I hope for now it can be a workaround for your project.

**Comment by MangelMaxime** [comment]
@ncave I am looking into fixing this issue because having infinite currying/uncurrying is really important for libraries like Thoth.Json and Fable.Form.

I found the previous implementation of the `curry` function:

**fable-library/Util.ts**

```ts
const CURRIED = Symbol("curried");

function _curry(args: any[],  arity: number, f: Function): (x: any) => any {
  return (arg: any) => arity === 1
    ? f(...args.concat([arg]))
    // Note it's important to generate a new args array every time
    // because a partially applied function can be run multiple times
    : _curry(args.concat([arg]), arity - 1, f);
}

export function curry(arity: number, f: Function): Function | undefined {
  if (f == null || f.length === 1) {
    return f;
  }
  else if (CURRIED in f) {
    return (f as any)[CURRIED];
  } else {
    return _curry([], arity, f);
  }
}
```

But when I try to apply it in place of this code https://github.com/fable-compiler/Fable/blob/7b51c595072a7bee2d9827d8bf0466da183b8e7f/src/Fable.Transforms/Replacements.Util.fs#L379-L389, it looks like the arity number is wrong (offset by 1).

When trying different approach I also had issues with mangling signature changing, etc. Probably because the code changed too much between Fable 4 and Fable 3, so I can naïvely patch it...

While reading through the code I found out that the new curry/uncurry implementation is using some kind of global storage. https://github.com/fable-compiler/Fable/blob/7b51c595072a7bee2d9827d8bf0466da183b8e7f/src/fable-library/Util.ts#L656

Can't this global storage be out of sync depending on the code order? I mean it seams like it store the last function called with `uncurryX` but what garantee that the next `curryX` is the one related to the correct function?

I suppose that storage is to work around "partial application and side effets" as if I replace it with an older implementation like:

```ts
export function curry2<T1, T2, TResult>(f: (a1: T1, a2: T2) => TResult) {
  return ((a1: T1) => (a2: T2) => f(a1, a2));
}
```

then 2 tests are failings.

Do you have any guidance to give me ?

**Comment by ncave** [comment]
@MangelMaxime If you need more than 10 levels, perhaps just add extra curry/uncurry to `fable-library/Utils.ts`.

Here is when the first 10 curry/uncurry were [introduced](https://github.com/fable-compiler/Fable/pull/3378/commits/0d278a2447d90d2f6cacc9a8aed8f6de97f59333#diff-97d4c66f7f5fe15831f5f2a798f3237f87a6d9520d873a0bab30b51580876baa).

Here is a description of [why those tests are failing](https://github.com/fable-compiler/Fable/pull/3378#issuecomment-1477240299).

**Comment by slyshykO** [comment]
I've heard that typescript have variadic tuples. Maybe it helps.

https://instil.co/blog/crazy-powerful-typescript-tuple-types/

**Comment by ncave** [comment]
@MangelMaxime 
> Do you know why we need to store uncurried function inside of a WeekMap

Yes, it's described in #3378:

> to resolve the problem of side effects running multiple times when partial applying a function that has been previously uncurried. The way this is currently solved for JS and Python is to add a property with a reference to the curried function (kept in a WeakMap) so when partial applying we can [check if the curried version is already available](https://github.com/fable-compiler/Fable/blob/746c9d98f14becc13b382aca315bddfa4a1fb616/src/fable-library/Util.ts#L741-L745).

**Comment by MangelMaxime** [comment]
I will need to re-read the code because I don't understand how that WeakMap stuff works.

I don't understand how it know which functions to retrieve. To me it looks like if `uncurry2` is called twice, then the last call override the previous stored value in the WeakMap.

Meaning that when `curry2` is called, there is no guarantee that you get the function you wanted to have. 

Unless, curry2 and uncurry2 are always right after one another which I don't think is possible to guarantee with `async` code.

**Comment by ncave** [comment]
@MangelMaxime
> I don't understand how it know which functions to retrieve
 If I'm not mistaken, the WeakMap is just a storage, the key s stored in each function object as property.
 I

**Comment by MangelMaxime** [comment]
@ncave 

Ohhh, I think you are right. A new function is created each time, and that function is what is used as a key. So each time, there is a new instance so it doesn't override the previous `uncurryX`.

**Comment by ncave** [comment]
@MangelMaxime Right, I haven't implemented that for Rust yet, so in Rust curry/uncurry with side effects can run the side effects twice.
