### ISSUE TITLE
Create JSON schema for fableconfig.json

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#364]
This is basically a self-reminder for this: https://github.com/ionide/ionide-vscode-fsharp/issues/138

**Comment by michaelsg** [comment]
I wanted to contribute something and (don't laugh) I like creating XML schemas and have been meaning to learn JSON schemas. This is what I learned in about 8 hours.

https://github.com/michaelsg/fable-config-schema/blob/master/fable-config-schema.json

I made a guess at the representation for some things - msbuild, ... - key/value stuff mostly.

Visual Studio 2015 was very helpful (don't faint) in learning JSON schema. Intellisense wasn't bad.
* If you change the schema (dropdown or $schema), close and re-open fableconfig.json.
* Once the schema _is_ loaded, updates are automatic when using local schema file (/fable-config-schema.json#)

Should I continue? 
Changes?

**Comment by alfonsogarciacaro** [comment]
Wow, that's really cool, thanks a lot! :clap: I haven't read anything about JSON schemas yet so I cannot comment much on your fantastic work. Just a couple of things:

- I see there is an `additionalProperties: false` option. It'd be ideal if the schema covers all compiler options, but I guess there'll be moments when the schema is not updated with the latest compiler options (for example, a `--noTypedArrays` flag has been added recently). Would it be better to set this to true so the user doesn't get an error when writing new options? (I actually don't know how `additionalProperties` works so I may be understanding it wrong.)
- It seems the [scripts](http://fable.io/docs/compiling.html#fableconfig-json) option is missing, probably because it's not included in the compiler argument list as it's only available in `fableconfig.json`. Could it be added as an object with the three current possible keys: `prebuild`, `postbuild` and `postbuild-once`?

Also, the PR for this should go to https://github.com/ionide/ionide-vscode-fsharp. Not sure where in the repo though, @Krzysztof-Cieslak can help with that :+1:

Again, thanks a ton for this!

**Comment by michaelsg** [comment]
I added scripts.

I would opt to keep additionProperties: false.
Reasons (verified in VS2015 and VSCode, at least):
* The indications of incorrect property names are informational only - not even warnings. There is nothing to prevent using a JSON file just because the schema doesn't match.
* Without the additionProperties: false, it's pretty much a free-for-all. You do get suggestions from the schema, and type checking, but anything misspelled, or incorrectly cased will show no signs of being wrong, unless you bother to hover and get the popup intellisense which will say something generic like *FieldName* - like it knows what it's talking about. The clue is there is no description or type info.

I'll look into passing it along.

**Comment by alfonsogarciacaro** [comment]
I understand and I totally agree, thanks a lot for the explanation!

**Comment by MangelMaxime** [comment]
We can probably close this issue now that the merge has been made into Ionide ?

**Comment by alfonsogarciacaro** [comment]
Indeed! Thanks 😸 

As some options are changing a bit before v0.7 a couple of adjustments need to be made. I'll do it later :+1:
