### ISSUE TITLE
Setup Prerequisites Docs .NET Version Needs Updating

### ISSUE THREAD

**Issue by han-tyumi** [fable-compiler/Fable#3669]
### Description

It seems the Prerequisites section needs updating?
I'm pretty new to everything .NET, F#, and Fable,
but based on the README and my playing around, it seems .NET 6+ works with Fable.

![image](https://github.com/fable-compiler/Fable/assets/13040345/b65de77f-f085-4f5a-b8bd-2a6f5c13f928)

**Comment by smoothdeveloper** [comment]
@han-tyumi good point, I think things are smoother since v4.0 and stuff working out of the box, the note must be here so that older projects (on fable 3) still have this relevant piece of info displayed.

If you need overall help with picking up on fsharp and dotnet ecosystem to use fable:
* [fsharp.org](https://fsharp.org/guides/slack/) (and mail to info@fsharp.org to get your account registration working to join)
* [discord server](https://discord.com/servers/fsharp-196693847965696000)

Welcome on board, and if you want to make contribution to the doc or fable itself, it is pretty straightforward through PR here.

**Comment by MangelMaxime** [comment]
Yes, I think we can remove this note now that Fable 4 has been around for quite a while.

Also, Fable 3 had a maintenance release which will generates a similar help message if the user tries to use an unsupported version of .NET with it.

**Comment by han-tyumi** [comment]
Ahh I made the assumption that the note pertained to the latest version of Fable which I thought was 3.

It makes sense, but I agree it'd be better off removed as I'd guess most people setting up Fable at this point will not be using version 3.

Thanks!
Appreciate the community links as well!
