### ISSUE TITLE
 IndexOutOfRangeException for bad index?

### ISSUE THREAD

**Issue by goswinr** [fable-compiler/Fable#3729]
I am expecting an `IndexOutOfRangeException` here, but it just returns `undefined`
```fsharp
let xs: string[] = [||]

printfn $"{xs[0]}"
```
See [REPL](https://fable.io/repl/#?code=DYUwLgBAHgzgXBGYBOBLAdgcwNoF0IC8E2APibgFAUAOa6YAZuhACQBEA3rNgAy4C+bIA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)
I know this is the default JS behavior. Should Fable stick to .NET semantics? 
Or could it offer a debug mode where indices are checked?

**Comment by ncave** [comment]
@MangelMaxime I agree it's a tricky one cause that's ho it as implemented from the start, and `Array.item` is also implemented without bounds checking. But IMO it should have bounds checking because that's what's [documented](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-arraymodule.html#item). There might be some existing code that wasn't breaking before, that can start breaking if we start throwing exceptions on invalid index, and obviously the performance can suffer a bit, but IMO it's more important to have the documented F# .NET behavior.
