### ISSUE TITLE
printf produces an implict new line

### ISSUE THREAD

**Issue by markek** [fable-compiler/Fable#375]
**(Unleated to issue #369, although `console.log` plays a similar role there. Issue #369 has been updated regarding `console.log`)**

@alfonsogarciacaro, currently we have:
~~~~
for i in 1 .. 10 do
    printfn "%d" i

for (var i = 1; i <= 10; i++) {
  _fableCore.String.fsFormat("%d")(function (x) {
    console.log(x);
  })(i);
}
~~~~
The js might better be produced as
~~~~
process.stdout.write(x);
process.stdout.write("\n");
~~~~
(or something similar) instead of
~~~~
console.log(x);
~~~~

`printf` incorrectly produces console.log and thus produces an unprogrammed new line. I think it should simply produce `process.stdout.write(x);`

I spent a little time trying to figure out how to do this and decided I need help. This also directly affects the appearance of the js and I don't want to be inconsistent with your goals there.

Just realized that the node and browser solutions ought to be unified and I doubt the browser has `process.stdout`

**Comment by alfonsogarciacaro** [comment]
Yes, `printfn` should work both in the browser and node (actually the former is more important) and I don't know if there's an alternative for printing to the console in that environment. In any case, the problem with `console.log` only happens with node on Windows 7, right? Can't it be solved by updating node?

**Comment by alfonsogarciacaro** [comment]
Can we close this after merging #376?

**Comment by markek** [comment]
#369 addresses compile-time, this one (#375) is run-time. A common use for printf looks something like:
~~~~
printf "working "
for i in 10 do
    printf " ."
printfn ""
~~~~
I'm ok with:
~~~~
* node/browser printfn -> console.log
* browser printf -> compiler warning
* node printf -> process.stdout.write
~~~~

If you could list a few key files in the compiler, I can figure it out.

**Comment by alfonsogarciacaro** [comment]
Ups, again I didn't read well the issue, sorry! 😅 There are a few methods that are translated with somewhat different semantics as a _lesser evil_ (instead of not being supported at all):

- printf
- System.Console.Write
- Async.Start (has the same semantics as StartImmediate)

We could remove support completely or add a warning when any of these are used. About making distinctions depending on the runtime environment, at the moment there's no way for Fable to know if the code will be run on node or the browser and I'm not sure it'll be a good idea to add an option for that (so far Fable is being designed to be _isomorphic_ and changing that can be problematic).

**Comment by alfonsogarciacaro** [comment]
I've added the warnings for now, please feel free to reopen the issue if you think there's a better way to fix this.
