### ISSUE TITLE
TimeSpan gets poisoned when created from high-precision TimeSpan.FromMilliseconds(float) 

### ISSUE THREAD

**Issue by DunetsNM** [fable-compiler/Fable#3815]
### Description

if a float with many decimals passed to `TimeSpan.FromMilliseconds(fload)` it will later crash when I try to read `Ticks` of this 

It's a problem only in Fable 4, worked fine in Fable 3 but broke after migration.

I think that there are other `TimeSpan.From*` members affected too.

### Repro code

```fs
open System

let highPrecisionFloat: float = 1. / 3.
let timeSpanWithABomb = TimeSpan.FromMilliseconds highPrecisionFloat

try
    let crashingTicks = timeSpanWithABomb.Ticks
    printf $"Ticks are: {crashingTicks}"
with
| ex ->
    printf $"Exception is: {ex}"
```

(btw while I'm here, https://fable.io/repl/ doesn't print out unhandled exception details, unless caught and printed explicitly like in the sample above)

### Expected and actual results

Expected output:

> Ticks are: 3333

Actual output:

> Exception is: RangeError: The number 0.3333333333333333 cannot be converted to a BigInt because it is not an integer

### Related information

* Fable version: 4.17.0 
* Operating system: Windows 11

**Comment by MangelMaxime** [comment]
Hello @DunetsNM 

> (btw while I'm here, [fable.io/repl](https://fable.io/repl/) doesn't print out unhandled exception details, unless caught and printed explicitly like in the sample above)

This is to be expected, currently we only report back `console.log`, `console.warn` and `console.error` which are of type `string`. I am not sure how we could report others type of "log" as we need to serialise them / print them ourself.

Regarding the BigInt conversion error I suspected this is because in the past we used a custom library as BigInt was not available yet on JavaScript and now we are using the native BigInt API. So it is possible that something is different in the behaviour.

@ncave Am I remembering correctly when saying that we move to native BigInt with Fable 4?
