### ISSUE TITLE
[TypeScript] Async type signature always returns any

### ISSUE THREAD

**Issue by leononame** [fable-compiler/Fable#3864]
### Description

Async does not generate correct type signature.

### Repro code

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoAqALATmAQwBMBLCAcywIQGsEAoegGzCSiOAEEE4IBjKAF4o9KGKjVeAgN6jx8-EgCuuaACJsJNXLEBfIA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwMLSQEMwCUVgYBLGbJXAUQA8olsUBmAGwBWFAwB2KChLQQArgCdgAekbNW+WsExIYFdDBgIAtEgCOshgDcAvAHIAwhDEwkzowBVESWyihOXznYuHDBKxNgA3L5oFPIAzjrWsjAAZkYAHLY0dNq6KGIU2tYARJYMSADuCBDyMMW+-q4wJRUMYDBo1mBIZdxGre1oADSiYkwMFNhGcVCTSNYAjMXZwDPyDAgwKHHyUCUYhnEAXEpKUGBiAHQAVnHd2Fbyl2I6SmIImEpltbKTRpCYAACACZLgswUowAw4qFvjBflMATc4vUoPIIHE4jUGABzcS4ZRrDYwFYwuAsbK0ABGEDAcBQAG8NLQWQgqFCxDijighAAGBAcCLMlkoFL+IwpQoMbBwblxKRxaZIdYpIUigC++GFKF0VJYjO11Jq3Xk0zZUHEXJQ-MFhpQNPkJqMNIMEEw3IWAu2EAeYBQAGIkLyg0G1SL7cblUZ1jiMB6vVjfQGQ8HeWHaJrtTAwEMs2gDeGUAMOty+QL0yyHU6WCkYPGON6k4HU6G7VWozAIAh6422smW2m7WywByrUJy3aIJZlSlsBAKty0G1umIK7RgjAjFOZ3OFygeA8EHFoRXMyLs5cEixYEg-UzC8PR9ybaetee-eIEMkC+Hi2hubM2BQAAFAsvK8gApCgRg8gKACUa7oEguJxigwLAhOhaYLEeJiM+mEspqmhKGSFKEGElDUFqwA0nSKxQpYohgCU2HiMsygMQQyi0XApDKOEBBAA&css=Q)

### Expected and actual results

It should have some type signature like `export const doAsync: Async<string>` instead of `any`, and ideally should be awaitable as well from typescript without giving errors.

### Related information

* Fable version: `dotnet fable --version`
* Operating system

**Comment by MangelMaxime** [comment]
> and ideally should be awaitable as well from typescript without giving errors.

I am not sure if this will be possible because in Fable when you use `async` we generate a custom async type which have the same behaviour as in .NET.

If you want asynchronous code to be await-able from TypeScrip you should use `promise` (coming from [Fable.Promise](https://fable.io/fable-promise/)) because in this case you will have a real promise.

Regarding the we could indeed type it to:

https://github.com/fable-compiler/Fable/blob/b93f2484e07acc2eb0ce94c3d67c78decb0080ed/src/fable-library-ts/Async.ts#L12-L13
