### ISSUE TITLE
[JS]  casting a .NET Dictionary to ICollection JS should not use .push

### ISSUE THREAD

**Issue by goswinr** [fable-compiler/Fable#3914]
Casting a .NET `Dictionary` to an `ICollection` emits `.push` for `.Add`, but a JS Map has no `.push` member.

```fsharp
open System.Collections.Generic

let dic = Dictionary<int,string>()  

let coll = dic :> ICollection<KeyValuePair<_,_>>    

let kv = KeyValuePair(1,"a")

coll.Add(kv) // emits .push on a JS Map, but Map has no .push member
```

[REPL](https://fable.io/repl/#?code=LAKA9gDgpgdgBAZQJ4GcAuUC2A6AwmAGwKgGM0BLMGFbAcVigCdyTRRi04ATFuAXjgARFhSoBDRkgA85GGgA06ZjADmAPgAUASjhw2IDnBKEC-brwBcauAEl8RUqJhSA0lCQA1MQQCuUAApi5IxSAPryoWrWunog7FCcANYAbmZunt5+gcEaAIzyAERiBVr6xkTYAIJcXBopOgD0DXBY5GgocNgQPigAFnBUcGJwAFIIcACyYhDycABGPpxTEHC9Yh0wYJ3dfXCYWHNM+qAxoEA&html=Q&css=Q)

![image](https://github.com/user-attachments/assets/cf7bbd5c-d809-46d8-bb62-28fa4f1921b6)

fable 4.21

**Comment by MangelMaxime** [comment]
It seems like this is not has easy to fix as I though.

JS Map doesn't seem to have a `Add` equivalent, it only have a  [`set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set) prototype for adding / updating an element.

I think the issue comes from the fact that `Dictionary<int, string>()` is represented using `JS.Map` instead of a class / wrap we control.

Because of that, when calling:

```fs
open System.Collections.Generic

let dic = Dictionary<int,string>()  

dic.Add(2, "b")
```

Then Fable is able to replace the `Add` call with `addToDict`

```js
import { addToDict } from "fable-library-js/MapUtil.js";

export const dic = new Map([]);

addToDict(dic, 2, "b");
```

But when doing the cast to `ICollection` Fable can't do the replacement, because the concrete type of `ICollection` can be anything. I think the path to fix this issue is to rework how `Dictionary<'Key, 'Value>` works and instead of using `JS.Map` directly, we should extends it:

```js
 class ExtendedMap extends Map {
    constructor() {
        super();
    }
    
   add(key, value) { // This will replace the call to `addToDict`
	// ...
   }
 }
```

In theory, it means that the new Map class will keep fulfilling the following statement from Fable

![CleanShot 2024-10-02 at 09 10 09](https://github.com/user-attachments/assets/642de6d6-2df3-432e-8914-97bcd603eac3)

If people compare the constructor there will be issues, but the existing API should keep working.

**Comment by goswinr** [comment]
@MangelMaxime  I am confused about how Interfaces are used in Fable.
I have a type that implements `IDictionary<K,V>` see [REPL](https://fable.io/repl/#?code=LAKA9gDgpgdgBAZQJ4GcAuUC2pK0ajTAOgGEwAbcqAYzQEswYUiBxWKAJzutFDSWhwAskgAi3NAB4A5AGkANNIBqcAO4ALPHIBcUAI4BXAIbk6-OAD44ACgCUcALy8QcV3Cpo4AE26O442gYYIw4kGQVlCztnUDc4AHp4gFoU1LT0jMys1LoYDA4AMyNqKBRtbIrKzOc43PyikrgASQBRGANMTiMAIypJWSgkJRMDKAAFIzoOcLhFJQsrVTN1WLi3TsxuzjgAfVYoNDaOrrQwDjs-IrpyJbR1ArgAIkw6FBRcgHNHmrc6zgaoHAyJQaPRGMxWu1OhwelQ1MsEvE4AA5RhwD7sLjUOAwKBQLz4uCnMBwAD8qzWcA2Ww4uz2bEOUJOZwuDjgVxuywez1e7xgXx+rj+hWKgOBVEC4KITXFoKC8LuiJRaIxuKxOLxBK8RLAJPJLkpVKwNN2pDABjyl0mnLu3Jeb0+3xAFLW1O2ezIECQABUwNYQhx5HA6PY2Rzbvcnva+QLnQbKW7aXsmihkDBqOoOIw6AAvfFh60Ru28x2C13G91ENPUABKurQBeuRajJf5TpdwoBzVlkpg-UGw3IowmU3CcwWCpW8fLm0rAEEvF5rAAPUNwF2GuAQLh5ArwR5GRdwIxwWRKJ2buI+ahEBdL5dEAZIIMPwejeyJdfTzeJazX7QWDKFASmCfZPm+4yTNMcjjhYti3ouK4fkiWBmCgW4GCg6hwNocDqGgaAQGUiQfMsBjdEQ1BgJg8RFL0UBJFRmAQNcnDxAAYrCUDxLyowoPEADMACcACMAAsZZxImpokFQISsuyhZci2DptpJ6wVkmRA1lgYAAG6AgA1npEBWk2yk8qpsYbhps5aWQeSTEwcDGaZbKKeZtoqTG7bfrZJoepAPp+gGQYhmZNqRpZPnqa40nJigOmHgA8jA5BIBFzbRaWcabvFZoWp4jaRcWVm+bUeT-KKzQBKBIRhDBkSTjZcWaaaTSEC1awRuiBwuW4bLXgA2oZAC6XVxEYMDanAKB9YZcB6X4w1jXAkhJItX5dflT7ocVWXRjl21tXsEF7R5JXeUdfmtXZpp3tYhlBnpa4TW4251HuTyHtqTS1UE9UXperjXghS5PYttixUad2BY5uQoE+-X7RZh1qblhr5d6oQMhBj2DNocizHAQ2SDWhV0J00qVVmEAIJwencKURDJQYaAWKNcAcFABQQThcDdEg3MFDI8z2Lh3S6uQmWo621k3TDAXabpBn40ga7hrLZXOB4At+CItWSOgO4fGFeRRFDIC665fjgSMkFTNYjxzo8QYiZbut0OKfjWN0OFWEBIK9v2Qz2yO0zG58Zvs3BoBe8BYOPSZHt9XQog+37AE1RIAOhEbaAm9HscgGniePAAQq7ABMltAA&html=Q&css=Q)
it seems to correctly generate the `ICollection` interface:
![image](https://github.com/user-attachments/assets/e05b4bb0-e574-4e98-9ce8-9e422209159a)
But then just calls `push `when used: 
![image](https://github.com/user-attachments/assets/8d7c25a9-6108-4931-9314-33b9de5c9393)
js:
![image](https://github.com/user-attachments/assets/5f10394d-21bf-4b02-be8d-7e9e8fffff30)
Also, the `IDictionary.Add` interface works as expected, but the `toConsole` side effect in the implementation is missing:
![image](https://github.com/user-attachments/assets/e6470ef5-428a-4c47-b045-e2a37b1ac539)
becomes:
![image](https://github.com/user-attachments/assets/05ab97e1-e558-45da-931d-bb923fe2bf2f)

**Comment by MangelMaxime** [comment]
My theory, is when doing:

```fs
let iD = (b :> IDictionary<string, int>)
iD.Add("B",2)
```

Fable only see the type of `iD` as `IDictionary` and because of that the code hit Fable replacement code. And doesn't use your custom Type implementation.

This can be visible when doing:

```fs
type MyDict<'K,'V when 'K:equality > () =
	// ..
    interface IDictionary<'K,'V> with

        member _.Add(k, v) = 
            printfn "add IDictionary"
            failwith "dwdwdw" // I am on purpose not using `dic.Add(k, v)`
	// ..

let iD = (b :> IDictionary<string, int>)
iD.Add("B",2)
```

generates

```js

export class MyDict$2 {
	// ..
    "System.Collections.Generic.IDictionary`2.Add5BDDA1"(k, v) {
        toConsole(printf("add IDictionary"));
        throw new Error("dwdwdw");
    }
	// ..
}
export const iD = b;

addToDict(iD, "B", 2);
```

I don't think there is a way to implements to implements your own `MyDict` like you are trying to do. Where you trying to do that for working around the issue reported here ?

**Comment by goswinr** [comment]
Yes, I was trying to work around the original issue. Do you know why correct code is generated for the interface but not used?

**Comment by MangelMaxime** [comment]
This is because `IDictionary` hit Fable replacement.

Fable replacement is the mechanism that's allow Fable to support native API, you cannot say I don't want replacement to happen.

To work around the issue, you can use [dynamic typing temporary](https://fable.io/docs/javascript/features.html#dynamic-typing-proceed-with-caution) to create a helper function.

**Comment by MangelMaxime** [comment]
I am looking at how to fix `ICollection` and I don't know how to do it.

The problem is that `ICollection` can be a lot of different types in reality with different APIs supported.

```fs
let dic = Dictionary<int,string>()
let dicCollection = dic :> ICollection<_>    
let kv = KeyValuePair(1,"a")
printfn "Dic collection count: %d" dicCollection.Count

let intArray : int array = [|1;2;3|]
let intCollection = intArray :> ICollection<int>
intCollection.Add(4)
printfn "Int collection count: %d" intCollection.Count

let stringArray : string array = [|"a";"b";"c"|]
let stringCollection = stringArray :> ICollection<string>
stringCollection.Add("d")
printfn "String collection count: %d" stringCollection.Count
```

With the example above, we already have 3 different types at runtime (with different APIs)

- `JS.Map` for `Dictionary` (don't have `add` only `set`)
- `Int32Array` for `int array` (cannot be mutated directly)
- Standard JS array (aka `[]`) for `string array` (works fine because there is `push`)

@ncave Do you have any ideas? I can implement it with some guidance, I just don't know how we can ensure that `ICollection` works for any possible type.

**Comment by ncave** [comment]
@MangelMaxime In theory we need different wrappers for each internal type that is supposed to implement ICollection, and return those on casting.

**Comment by MangelMaxime** [comment]
That was my supposition.

So the idea is for:

```fs
open System.Collections.Generic

let stringArray : string array = [|"a";"b";"c"|]
let stringCollection = stringArray :> ICollection<string>
stringCollection.Add("d")
```

```js
export const stringArray = ["a", "b", "c"];
export const stringCollection = stringArray;
void (stringCollection.push("d"));
```

to becomes something like that?

```js
export const stringArray = ["a", "b", "c"];
export const stringCollection = castArrayToIColletion(stringArray);
void (stringCollection.push("d"));
```

I suppose this also means we will need to support the other direction too going from `ICollection` to `string array`?

**Comment by ncave** [comment]
@MangelMaxime We could, technically the wrapper can just return the wrapped collection.

**Comment by goswinr** [comment]
Thanks for looking into this. 
For the `.Remove` member of `ICollection` it is even more tricky.
It doesn't throw an error, but actually never removes the KeyValue Pair.
see [REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoDCwA2OwDGSAlsBAugOKRgBOxBAUI-klACZQC8UAIgyTIBDWnAA8xCEgA0kpAD4AFAEoWYNgW4coALnlQAktjyFBEMQGkwcAGpCcAVzAAFIcVoSp0qHPnzG7OgA2gCMALpQYgC0UAAMzKxQANYAblpWtvZOru6KId6xqom0aMApYOwWNloE6ABKpeWKqaog9FIAZtAAJABEGXaOLm60UADuQghQJahlFTpQAN4zc5U2AL69amwr5ey8WoENs00hre1IXVB9GVAIABbADjicAEZgUADmZGDerw5sYhTAhCaDvaaNCpQCDAMYLZaQ-abIA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)

**Comment by ncave** [comment]
To clarify, although this PR fixes the current issue using runtime checks, arguably a better way would be to eventually provide proper F# wrappers for all native JS collections, so that all their other interfaces can be easily implemented.

Something like [this](https://github.com/fable-compiler/Fable/commit/c0c71300477f60e7b27e80534a252bf330be73fb) which does it for JS Map/Set, but we probably also want to wrap ResizeArray (JS Array).

**Comment by goswinr** [comment]
Thank you for fixing this @ncave ! Is there an overview of which Interfaces of .NET Collections are supported in Fable ? Maybe documenting and failing at compile time  it is good enough?  For Resizearray there are these three issues (or more? ): https://github.com/fable-compiler/Fable/issues/3812 https://github.com/fable-compiler/Fable/issues/3718 https://github.com/fable-compiler/Fable/issues/2506

**Comment by ncave** [comment]
@goswinr I'm not sure, each new version of .NET adds quite a few new interfaces.
For interfaces that match replacement types one to one, it's easy to add support.
For interfaces implemented on multiple native types (without wrappers), we need runtime checks.

For now I've also added the mappings and tests for `IReadOnlyCollection` (see #3953).
