### ISSUE TITLE
fable-compiler question

### ISSUE THREAD

**Issue by askucher** [fable-compiler/Fable#404]
Can I do something like

```javascript
var fable = require("fable-compiler")
var js = fable.compile("Code here")
console.log(js)
```

**Comment by alfonsogarciacaro** [comment]
`fable-compiler` is a Node console app (though it doesn't offer an API to be used with `require` yet) but it still contains .NET bytecode so you also need to have .NET/Mono or .NETCore (`fable-compiler-netcore`) installed on your machine.

If you ask this to write a Webpack loader, this has already been discussed (e.g. #128). The main challenge is Webpack loaders work on a per-file basis, while Fable works per-project and it outputs multiple files. Webpack loaders should accept multiple files in order to work with Fable.

**Comment by alfonsogarciacaro** [comment]
It still needs some work but v0.7 exposes a JS API. Will you be interested in collaborating to improve it? If so, could you explain your use case for the API? Cheers!
