### ISSUE TITLE
Adding generic info to runtime?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#455]
For the new _major-before-1.0_ version we're aiming to make easier JSON serialization and usage of Fable libraries, and it's become clear we need some kind of generic info available at runtime for that. So far we managed to solve this problem by **inlining** functions and resolving generics at **compile time**. However, inlining is not possible with assembly references (because Fable has no access to the F# source code), so this may be the time to add generics at runtime.

Funscript achieved that by compiling different versions of types and methods with their generic implementations. I don't think this is a possibility because it makes code size explode and exposing interfaces to JS almost impossible. The only other way I can think of at the moment is passing generic info to generic types and functions. Unfortunately, while considering this idea at least two potential issues came to mind:
- **Overhead**: I don't have numbers, but obviously passing an extra argument to every generic function will increase code size and complexity. This is particularly worrisome for types, as we would have to extend them every time to create truly generic types. It would work something like this (in TypeScript pseudo-code):

``` typescript
function makeGenericType(typeDefinition: FunctionConstructor, genArgs: any) {
  return class extends typeDefinition { static get $generics() { return genArgs } }
}

class A<U> {
  constructor (public value: U) { }
}

// Instantiate a type with generic info
let x = new makeGenericType(A, { U: "number" })(5);  

class B<U> {}

function f<T>($genArgs: any): T {
  return new $genArgs["T"]();
}

f({ T: new makeGenericType(B, {U: "string"}) });
```
- **Compatibility with JS**: Because now many functions will expect the generic info, it won't be so easy to call code compiled with Fable from JS. Another issue that came to my mind is many times JS functions have different behavior depending on the number of arguments you passed to them, so if Fable sneaks the generic info every time this could create issues with functions declared generic in TypeScript bindings (see [this](https://github.com/fable-compiler/Fable/issues/231#issuecomment-231826253) for example).

So the question is, would having generic info available at runtime worth it in spite of potential issues? Or, can someone think of an alternative way of implementing generic arguments?

There could also be the possibility of extending the inline trick to assemblies instead. Maybe by making the F# source available somehow alongside the assembly?

**Comment by michaelsg** [comment]
I don't suppose the `[<ReflectedDefinition>]` would help in being able to inline across assemblies?

On generics at runtime:
I have 1 must-inline method because of a generic type check `:? 'a`. I quickly discovered that this doesn't work when I tried to use it from another Fable project. My solution was to snip the method from the interface and extend that interface (`type whatever with ...`) to add the desired inline method back. It means I have to drop a tiny source file in each project that uses the other project. It was a small price to pay.
I personally think the stuff I'm doing right now is about as nasty with the type-checking as anyone sane would want to do in a web browser application. Perhaps those writing Node might find more of a use in elaborate frameworks.
I think there are better things to work on that would have a more immediate impact:
* Pristine .d.ts generation. There is nothing that F# can say that TypeScript can't model in declaration syntax. It can model the JavaScript world - where there are no rules, so this has to be achievable.
* .d.ts consumption: I know people want this so bad, but it's so tough. I gave up and went the other way: for what little my Fable code must interact with JS code, I write a small TypeScript bridge with a small and sensible interface that is easily described and used in Fable. 

I'm on my 2nd layer of Fable projects. The newest layer is used by the C# Web project - from TypeScript. Using one Fable project from another was a no-op - just like normal, but they are both in the same solution. I had to add a ref - seems you should be able to find that in the project assembly references(?). 
To use them from the web, since there were several modules, I decided to treat the directory like a CommonJS setup with an index.js, a package.json (points to hand-made .d.ts, too).
package.json:
```json
{
  "name": "fakka",
  "version": "1.0.0",
  "main": "index.js",
  "typings": "index.d.ts",
  "dependencies": {
    "fable-core": "^0.6.3"
  }
}
```
index.js:
```js
```

**Comment by davidtme** [comment]
Fable feels real solid without this feature.

I’ve had a few running’s with inlining not working correctly but so far I haven’t had to abandon any ideas, just a bit of a rethink (and the occasional PR) has got around the problem (The improved Fable warning/error message have really help).

My pet-project at the moment is a game using webgl so my feelings about increased overhead are a big no-no (unless it was cleaver enough to only add this when needed or a flag?). 

“extending the inline trick to assemblies” would feel like more of a win.  Currently I’m having to include external common files in my project but this would make referencing common code really easy.

**Comment by dsyme** [comment]
Some other options

- Extend F# with "this type parameter may be required at runtime" inference, basically inferring when the type info may be needed.  The F# compiler actually does some of this inference anyway. 

- Extend F# to give a warning when type parameters are used in type tests etc. at runtime.

Both are in the category of "extending F# for the needs of Javascript".  I think neither fall in the category of "bifurcating the F# language" though we must be constantly alert to that possibility.

cheers
don

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your comments!

@michaelsg I'm happy to hear the lack of runtime generics is not a drawback for you, and I agree that there're other things that also need improvement. But generics are also important because they're usually needed for creating reusable packages.

`[<ReflectedDefinition>]` could indeed be a solution for making accessible the AST of compiled `.dll` assemblies. I didn't mention it because unfortunately the AST of code quotations and the one provided by the F# Compiler Services are different, so supporting also the first will require a lot of new code 😕 

@davidtme Yeah, I got a bit excited about adding generics to the runtime, but probably the price for them is too high and would make it impossible to use Fable for _low-level_ JS.

Thanks a lot for your insights, @dsyme! Fable's already doing some tricks for JS compilation, but I totally agree that general F# semantics should be kept as much as possible to reduce the cognitive load and for tool sharing. I didn't think of extending F# for this (actually, if we can make requests mine number 1 is a simpler project file :wink:) but if this is an option, maybe we could make some compilation trick to automatically pass type info when needed (similar to what `[<ReflectedDefinition>]` does for arguments). Something like:

```fsharp
type MyLib =
    static member Foo(x: 'T, [<Implicit>]?T: Type) =
        printfn "Value: %A - Type: %s" x T.Value.Name 

    static member Bar<'T>([<Implicit>]?T: Type) =
        printfn "%s" typ.Value.Name 

// Consumer
MyLib.Foo(5)
MyLib.Bar<string>()
```

This way lib authors could mark when they actually need the type info so Fable builds it in compile time when necessary, but the function signature will be cleaner and easier to use for consumers. If you agree, I can try to submit an RFC for that.

> EDIT: Actually, I just realised this could be directly implemented in Fable without extending F#. Would that be a better option?

**Comment by michaelsg** [comment]
+1 for special `[<Implicit>]` parameter - supplied by Fable - no change to F# language.

**Comment by tpetricek** [comment]
To better understand this, what are the scenarios when the generic type info would be needed? I can think of:

 - Equality test on values of generic types - in principle, I think this needs type info (?), but Fable gets away mostly fine without that - using runtime representation?
 - When you create a value of generic type with a `new` constraint - it needs to know the type when generating the object
 - Reflection - but I think Fable does not really need to emulate .NET reflection

Am I missing some important obvious cases?

**Comment by alfonsogarciacaro** [comment]
Sorry, @tpetricek, I forgot to add the link which motivated this issue. As mentioned above, currently Fable resolves generics by inlining functions but this forces you to add direct references to F# library files (like the React helpers) which is cumbersome. I thought of this when trying to move the Fetch helper, [this function](https://github.com/fable-compiler/Fable/blob/39144066bc61e3a5ef34f1f9de97b56cfbc19220/import/fetch/Fable.Helpers.Fetch.fs#L94-L98) requires the generic argument to pass it to `ofJson` but the code cannot be inlined if put in a `.dll` reference.

About the other issues you comment:

- Equality: this is not actually an issue, as Fable defaults to [this method](https://github.com/fable-compiler/Fable/blob/39144066bc61e3a5ef34f1f9de97b56cfbc19220/src/fable/Fable.Core/npm/fable-core.ts#L103) for structural equality when cannot resolve the type and it's been working so far.
- `new 'T()` or `typeof<'T>`: this is important, as it's used by the [React helper](https://github.com/fable-compiler/fable-react/blob/master/react/Fable.Helpers.React.fs#L580).
- Reflection: some reflection may be needed some types. For example, there're requests to perform validation on types received by JSON (like checking that it contains all the expected properties).

**Comment by 7sharp9** [comment]
If we have access to the dll then we have access to some type info via reflection, is that not enough, or is it F# specific info thats needed in opt/sig data?

**Comment by 7sharp9** [comment]
https://twitter.com/7sharp9_exhumed/status/741073122439397376
You can get some F# type into like this ^

**Comment by alfonsogarciacaro** [comment]
@7sharp9 True, you can get type info from dll references and Fable indeed relies on that. However, to properly inline functions you need access to the method body AST and unfortunately this is not available (afaik).

**Comment by michaelsg** [comment]
I've been trying to replace my inline method with one that accepts a `<GenericParam>` parameter. It will work for non-native types, but not for built-in types because of the value passed as the generic param. A string "type" is passed for native types, the type's constructor is passed for other types. If the constructors of the native types were passed instead, it looks like it would work.

```fsharp
```

**Comment by michaelsg** [comment]
I've been trying to replace my inline method with one that accepts a `<GenericParam>` parameter. It will work for non-native types, but not for built-in types because of the value passed as the generic type param. A string "type" is passed for native types, the type's constructor is passed for other types. These are those new TypeCodes (?) that I saw in the TypeScript. Is there a way to get the runtime type code of an object that I should be using instead of .GetType(), which returns the constructor of the type?

```f#
type ThingX = ThingX of string
type StaticX =
    static member OnlyAccept<'a>(msg:obj, [<GenericParam "a">]?genarg:Type) =
        let gentype = genarg.Value
        let mtype = msg.GetType()
        if gentype = typeof<obj> || gentype = mtype then
            do()
module TestX =
    StaticX.OnlyAccept<float>(43)
    StaticX.OnlyAccept<string>("hi")
    StaticX.OnlyAccept<ThingX>(ThingX "bye")
    StaticX.OnlyAccept<obj>("I'll accept anything")
```

```javascript
...
      StaticX.OnlyAccept = function OnlyAccept(msg, genarg) {
            var gentype = genarg;
            var mtype = Object.getPrototypeOf(msg).constructor;

            if (_fableCore.Util.equals(gentype, [1]) ? true : _fableCore.Util.equals(gentype, mtype)) {}
...
        StaticX.OnlyAccept(43, "number");
        StaticX.OnlyAccept("hi", "string");
        StaticX.OnlyAccept(new ThingX("ThingX", ["bye"]), ThingX);
        StaticX.OnlyAccept("I'll accept anything", [1]);
```

**Comment by alfonsogarciacaro** [comment]
@michaelsg Thanks for pointing that out! I've modified the behaviour of `.GetType()` in latest fable-compiler and fable-core 0.7 alpha (install them like `npm i fable-compiler@next`) so:

- If type is known at compile time works as `typeof<>`.
- Otherwise, for JS primitive types (boolean, number, string and function) return a string and call the prototype constructor (as before) otherwise.

Now [your code is working](https://github.com/fable-compiler/Fable/blob/c2ceb8ef316e4f6aafa746ba55e2de349affde66/src/tests/TypeTests.fs#L401-L406) but please note it will still have problems with generic types (options, tuples and arrays included).

**Comment by michaelsg** [comment]
So fast!
That's working well.
Thank you.
