### ISSUE TITLE
Relative JS imports should not be relative to the outDir

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#472]
Consider these two files:

```
// src/Foo.fs
module Foo

open Fable.Core
open Fable.Import

[<Import("foo", "./Foo.js")>]
let foo: string = jsNative

do
    Browser.console.log foo
```

```
// src/Foo.js
export const foo = "Hi!";
```

When I use an `outDir` of `build`, it is compiled to the following code:

```
// build/Foo.js
import { foo } from "./Foo.js";
console.log(foo);
```

But this is wrong: it should refer to `src/Foo.js` rather than `build/Foo.js`:

```
// build/Foo.js
import { foo } from "../src/Foo.js";
console.log(foo);
```

I'm honestly not sure whether relative imports should be relative to the importing file (`Foo.fs`), or relative to the project directory (`Foo.fsproj`). I can see pros and cons to either one.

But because `Fable.Core.Import` is for JS interop, and ES6 imports are always relative to the importing file, it probably makes more sense for it to be relative to `Foo.fs`

**Comment by alfonsogarciacaro** [comment]
I agree it's better to keep the ES6 import semantics. So I guess the operation should be as follows:

1. Take path in `Import`attribute: `./Foo.js` and combine it with the directory of current file, say `/src/Foo.js`.
2. Resolve the relative path from `outDir` (`/build/`) to `/src/Foo.js`: `../src/Foo.js`.

I'm already doing something similar for project references so it shouldn't be difficult :+1:

**Comment by alfonsogarciacaro** [comment]
Ok, this should be working in latest fable-compiler and fable-core 0.7 alpha (install them like `npm i fable-compiler@next`). It was a bit more complicated than expected because import attributes are actually compiled not in the file where they're declared but where they're used (this is because import attributes are normally declared in binding files which are erased), so in those cases I have to make the path first [relative to the current file](https://github.com/fable-compiler/Fable/blob/c2ceb8ef316e4f6aafa746ba55e2de349affde66/src/fable/Fable.Core/AST/AST.Fable.Util.fs#L98-L108) and then [resolve it with `outDir` later](https://github.com/fable-compiler/Fable/blob/c2ceb8ef316e4f6aafa746ba55e2de349affde66/src/fable/Fable.Compiler/Fable2Babel.fs#L978-L984). Also files that go into subfolders within `outDir` need to be taken into account.

In any case it seems to work now ([tests](https://github.com/fable-compiler/Fable/blob/c2ceb8ef316e4f6aafa746ba55e2de349affde66/src/tests/MiscTests.fs#L755-L769)). Could you please give it a try and confirm if it does? Cheers!

**Comment by Pauan** [comment]
@alfonsogarciacaro Yup, seems to work, thanks!

The only thing I noticed is that it gets resolved as `"./../src/Foo.js"` rather than `"../src/Foo.js"`, but that doesn't matter: they're both functionally identical.

Also, just to clarify: it will *always* resolve relative to the file which contains the `Import`, never the file where the import is used?

**Comment by alfonsogarciacaro** [comment]
Glad to hear it works! 😄 

About `"./../src/Foo.js"` that's because the value returned by `getRelativePath` doesn't always start with `./` so I'm adding it by default. We can just check if there's already a period before adding it.

As we talked in Gitter, the behaviour of `ImportAttribute` and import expressions (`let foo = importMember "./foo.js"`) work differently. The former are resolved in the file where the import is used (this is because `ImportAttribute` was designed for bindings which are often erased) while the latter are resolved on the file where they're declared.

However, you shouldn't normally need to worry about that, because Fable will automatically [edit relative paths in `ImportAttribute` so they can be used from the current file](https://github.com/fable-compiler/Fable/blob/1b3d30d4acab5448427941a7edaa712427129d71/src/fable/Fable.Core/AST/AST.Fable.Util.fs#L98-L108) :+1:

**Comment by alfonsogarciacaro** [comment]
Pasting what we talked in Gitter here for illustration purposes. In this example it can be seen that `ImportAttribute` is resolved in the JS consumer file:

```fsharp
module MyLib
open Fable.Core
open Fable.Core.JsInterop

[<Import("foo", "../js/foo.js")>]
let importAttribute: string = failwith "JS only"

let importExpression: string = importMember "../js/foo.js"
```

```fsharp
#r "../src/fable/Fable.Core/npm/Fable.Core.dll"
#load "MyLib.fs"

open System

Console.WriteLine(MyLib.importAttribute)
Console.WriteLine(MyLib.importExpression)
```

JS

```js
"use strict";

exports.__esModule = true;
exports.importExpression = undefined;

var _foo = require("./../js/foo.js");

var importExpression = exports.importExpression = _foo.importExpression;
```

```js
"use strict";

var _foo = require("./../js/foo.js");

var _MyLib = require("./MyLib");

console.log(_foo.foo);
console.log(_MyLib.importExpression);
```
