### ISSUE TITLE
0.7.x: "Invalid method name type MemberExpression"

### ISSUE THREAD

**Issue by fdcastel** [fable-compiler/Fable#492]
### Description

The following program outputs several `Invalid method name type MemberExpression` messages to the console when compiled with `--declaration`.

The problem doesn't happen if the namespace declaration (first line) is removed.
### Repro steps

Command line: `fable --projFile ./Gamma.fsx --declaration --verbose`

``` fsharp
// Gamma.fsx
namespace Alpha    // Remove this and the problem doesn't happen

module Beta =

    type Gamma = {
        Data: byte array
    }
```
### Fable versions

The problem occurs with **Fable 0.7.5-alpha.11**
The problem DOES NOT occurs with **Fable 0.6.15**

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the report. I'll try to have a look when I have time but I'm gonna give low priority to this because at the moment our efforts are more targeted to make it easier to produce libraries that can be consumed from other Fable projects, rather than TS ones. We also need to balance if the `--declaration` feature is worth the maintenance effort 😕

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit
