### ISSUE TITLE
Dictionary and KeyValuePair features

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#509]
Feature request (very low priority, more of a placeholder):

in src/tests/DictionaryTests.fs 

```
// TODO: implement ICollection<_>.Add(pair)
[<Test>]
let ``Dictionary KeyValuePair works``() =
    let dic = Dictionary<_,_>()
    for i in 1. .. 9. do dic.Add(i, i*i)
    let pair = KeyValuePair(10., 100.)
    (dic :> ICollection<_>).Add(pair)
    dic.Count |> equal 10
    Seq.sum dic.Values |> equal 385.


// TODO: implement KeyValuePattern
[<Test>]
let ``Dictionary KeyValuePattern works``() =
    let dic = Dictionary<_,_>()
    for i in 1. .. 10. do dic.Add(i, i*i)
    let i = ref 0.
    for KeyValue(x,y) in dic do
       i := y + !i
    equal 385. !i

```

**Comment by alfonsogarciacaro** [comment]
I added the `KeyValuePattern` (which is just an identity function as `KeyValue` is also represented with a tuple by Fable) but `ICollection<_>.Add(pair)` with dictionaries is going to be difficult, because in the runtime I cannot know if `ICollection` corresponds to a dictionary or a `KeyValue` resize array 😕

**Comment by ncave** [comment]
Great, thanks!
