### ISSUE TITLE
Testing 0.7 alpha - round 2

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#516]
First of all, thanks everybody who's been testing 0.7.0 alpha. Your PRs, bug reports and suggestions are helping 0.7.0 become much closer to a stable release :+1: I just uploaded a new version with so many changes that it deserves a new post, here we go!

> Remember you can download latest fable-compiler and fable-core alpha versions with the `next` tag, as in `npm install fable-compiler@next`.
### Use Forge to read .fsproj files (PR #500)

Now Fable uses latest FCS and Forge to read .fsproj which means it's not needed to have MSBuild installed on the system anymore :tada: The downside is Forge cannot read (yet) complicated .fsproj, so please try to keep a simple structure (no `When` tags or `Condition` attributes, file links, etc). Also, the `refs` argument has been removed (as well as `EntryModuleAttribute`). The way to make references now is:
- **Project References**: When you have a multi-project solution, you can now pass [an array of project files](https://github.com/fable-compiler/Fable/blob/0.7.0/src/tests/fableconfig.json#L2-L6) in fableconfig.json. Attention: the projects must be in compilation order, like files.
- **Dll references**: When referencing a dll, Fable will look in the dll directory for a file with the same name and `.fablemap` extension that maps the source files in the dll with compiled JS files. Fear not! This file is automatically generated when you compile a project with the `--dll` option.
### Generic info (PR #510)

See the PR explanation for details ☝️
### Bundling

The `--bundle` option has been replaced with `--rollup` to make it clearer this is the tool used. Also, you can pass a configuration object to Rollup in fableconfig. The config options correspond to [Rollup JS API](https://github.com/rollup/rollup/wiki/JavaScript-API#rolluprollup-options-). The only difference is plugins, which must be passed differently as fableconfig cannot contain code. The same format as with Babel plugins is used (See "Plugin/Presets Options" in the [link](https://babeljs.io/docs/plugins/)). These settings are equivalent:

``` js
import commonjs from 'rollup-plugin-commonjs';

rollup({
  plugins: [
    commonjs({ namedExports: {
        "virtual-dom": [ "h", "create", "diff", "patch" ]
      } })
  ]
});
```

``` json
"rollup": {
  "plugins": [
    ["commonjs", {
      "namedExports": {
        "virtual-dom": [ "h", "create", "diff", "patch" ]
      }
    }]
  ]
}
```

> Note you can omit the `rollup-plugin-` prefix in fableconfig, same as with Babel plugins.

The default Rollup configuration in Fable is as follows (any option in fableconfig will override them, including plugins):

``` js
{
    // entry: <Last F# source file>
    dest: fableOptions.outDir + "/bundle.js",
    format: fableOptions.module || "iife",
    sourceMap: fableOptions.sourceMaps,
    moduleName: normalizeProjectName(fableOptions),
    plugins: {
        require('rollup-plugin-node-resolve')({ ignoreGlobal: true }),
        require('rollup-plugin-commonjs')({ jsnext: true, main: true, browser: true })
    }
}
```

> Now the default `module` option is `es2015` to promote this module system as the standard when distributing Fable libraries. This will greatly improve dead-code removal.

**Comment by michaelsg** [comment]
Where is fable-core.js? and fable-core.min.js.
I just installed "next". I got compiler: 0.7.5-alpha.17 and core: 0.7.5-alpha.8.
There is no fable-core.js nor a fable-core.min.js.
The package.json says main is "Main.js" but that doesn't exist either.

**Comment by alfonsogarciacaro** [comment]
Now fable-core is completely modular. If you are developing a web app, you should bundle your code together with the necessary code from fable-core. The biggest advantage of this approach is you'll only get the pieces of code you actually need. Check the explanation above to learn how to bundle (I need to write more detailed docs on this), you can also see [this example](https://github.com/alfonsogarciacaro/fable-pixi-sample1/blob/master/fableconfig.json) and check Rollup wiki for more info.

**Comment by michaelsg** [comment]
It's an interesting alternative to the approach I've already taken, but ...

I elected to bundle all of fable-core in a Vendor bundle with other stuff (like Aurelia's millions of modules and other stuff like jquery).
I can't see how to bundle fable-core that way now unless I list each module explicitly.
This is very prone to breaking when you add/remove modules.
Also, if I produce multiple app bundles to partition the features, each would have to be bundled with its own minimal Fable-Core modules. 
My intent was that all my fable code would share one fable-core, pre-loaded into my app with all the other Vendor packages.

**Comment by alfonsogarciacaro** [comment]
We already had a similar discussion (#490) but unfortunately because the way ES6 exports works it's difficult to provide a common index.js files if we want to maximize the benefits of tree shaking.

However, this doesn't mean you cannot keep using the bundle tool of your choice, using the embedded Rollup is just a convenience and it's not mandatory at all. fable-core is distributed in commonjs format which is understandable by most JS build/bundle tools. You can just delay bundling until the final packaging of your app. You don't need to list each modules separately, Fable will create the necessary `require` calls for you (remember to use `module: commonjs` in fableconfig).

If you have any specific structure I could look at, I can guide you through the process of updating to the new modular fable-core.

**Comment by michaelsg** [comment]
You won't consider providing both loose and concatenated (fable-core.js)? 
It would provide the option of bundling through dependency tracing (if bundling with fable-compiled files or rolling up) and including fable-core as a whole in a bundle separate from the Fable-compiled code, as I'm doing.

I also think there are deployment situations that might require Fable-Core to be included apart from the Fable bundles. What if I have a modular application with multiple bundles containing Fable code? I might choose to do this because entire bundles of features can be demand-loaded or not loaded at all. Each of these app bundles would contain a part of Fable-Core. This will lead to duplicate module definitions if a Fable-Core module is included in more than one bundle. In a situation like this, included the whole Fable-Core separately from bundles including Fable code is the only way to ensure 1 and only 1 version of a Fable-Core module across the entire application.

**Comment by alfonsogarciacaro** [comment]
JS modules can be a bit complicated, but what you need is actually possible. You can compile Fable imports to a non-static module format like AMD or System.js. You just put fable-core JS files in a folder and let your Fable compiled code load them as needed (loaders like Require.js have caching systems, so all parts of your application will load the same fable-core). Please also note you can use the `--coreLib` compiler argument to tell Fable where to load fable-core modules from. It can be a CDN server, a specific folder in your server... I'll modify the samples in Fable's website so they load fable-core modules this way, and you'll probably see it clearer.

In any case, I'm not against distributing fable-core also as a bundle in a single file. But as commented above, I already tried and had some difficulties. If you have a look and find a viable solution we can implement it :+1:

**Comment by michaelsg** [comment]
What was the issue with a single fable-core.js file? I saw you said you couldn't make an "index.js" and I undetrstand that, but I don't know how a file - fable-core.js, perhaps in a sub-folder, would interfere with the rollup/loose modules in any way. I could see having to compile the TypeScript twice, but that's really not that big a deal, is it?

**Comment by alfonsogarciacaro** [comment]
You can read #490 for details. I guess it's solvable but I wasn't sure how to expose the module members. Also the way Fable creates the imports should be changed too...

Another problem about the single fable-core.js file is from now on we've more freedom to add new classes to fable-core (as users will only pay what they get), so distributed as single file could potentially become very big.

My recommendation is to adapt to the new modular system. I understand your doubts so I'll try to create a sample where files are loaded dynamically with require.js. We're still in alpha so there's still some room for experimentation 😄

**Comment by michaelsg** [comment]
I have 3 Fable projects and with the newest compiler 2 of them claim the project file has errors. They don't have errors. They aren't complicated  and they used to work. This project I'm working on is not a toy - it's for work - encouraged by your pleas for people to use Fable for production projects. I"m at a loss. This isn't something I can just change my code of fableconfig for. Help!

**Comment by michaelsg** [comment]
2 of my 3 Fable project are now un-compilable because Fable says the .fsproj have errors. They _don't_ have errors. They are simple projects without folders, and with just a few extra non-fs files. 
I don't know how to work around this. This isn't a toy project I can throw away - it's for my job - and I'm panicking. Ideas? :-(

**Comment by michaelsg** [comment]
I'm having issues with the new ways to reference other Fable projects.

* Alternative 1) List all Fable projects in projFile.
Issue: Only compiles first project then stops. 1st project has some warnings that are erroneous - about generics missing at runtime. Could this prevent it moving on to compile the next project in the list? 

* Alternative 2) Compile with "dll" option and reference Fable-created DLL.
This method is the least usable for me. My Fable projects (2 of the 3) produce both Fable-compiled and .NET-compiled code. The .NET DLL contains metadata for Fable + shared types + .NET code to be executed on the server. This has worked well since the beginning of the project. 
If I manually reference the Fable-created DLL from the primary Fable project, the code compiles under Fable, but not under .NET. If I use a project reference (like I have been until now), the .NET code compiles and the Fable codes does not. 
I think alternative 1 would still work for me - allowing me to have a project reference for the .NET compilation and a list of projFile projects for Fable compilation,... but only if it will compile all the files in the list ;-).

**Comment by michaelsg** [comment]
Fable-Core. 
The .js files directly under the node_modules/fable-core are in ES2015 format with import statements. For bundling and loose use, I can tell RequireJS to use node_modules/fable-core/umd as the alias for 'fable-core'.
However, I have one Node project - a unit test project - that produces a Node executable program. Now, when I execute it under Node, it complains immediately about about the import statements in the .js files under fable-core. How can I make Node use node_modules/fable-core/umd instead of node_modules/fable-core?

**Comment by alfonsogarciacaro** [comment]
@michaelsg Thanks for your comments 😄 

> Issue: Only compiles first project then stops. 1st project has some warnings that are erroneous

This looks like proper behaviour for me (Fable should compile only if there's no error in any file). Which are these erroneous warnings? Can you post Fable's output with `--verbose`? About compiling with `--dll`, this is mainly intended for distributing Fable libraries, you shouldn't need to use it for your internal projects.

I'm glad to see you solved the issue with Require.js 😸 Actually I just updated the [pacman sample](https://github.com/fable-compiler/Fable/blob/3fb2a76a3bdced91e4d94f2aadb22ffcf6703cad/samples/browser/pacman/index.html#L20) to show how to do so (I'm using System.js here because it allows folder mapping, I'm not sure if that's possible with Require.js). For a Node project, you can pass the `--coreLib fable-core/umd` option to Fable and should have the same effect :+1:

**Comment by michaelsg** [comment]
But they are compiler WARNINGS.
They are (or have been, I want to test under the new compiler) erroneous warnings for me. I'm only concerned about the type of an object - nothing about whatever generics it might contain - because I'm making sure not to do that! :-) I understand the limitations of what I'm doing and wish I could suppress the warnings.
This code works or worked - the `<PassGenerics>` is new, but it worked when it was `<GenericParam>`.
```fsharp
    let [<PassGenerics>] forType (body:'a -> _) =
        Receive <| fun msg ->
            if typeof<'a> = msg.GetType() || typeof<'a> = typeof<obj> then
                let a = msg :?> 'a
                true, body a
            else
                false, Ops.ZERO

    type ActorBuilder with
        [<PassGenerics>]
        member x.For(_:IMessageSource, body:'a -> _) = forType body
```

**Comment by alfonsogarciacaro** [comment]
I've tried to reproduce the situation: prepare two projects and  make the first throw a warning, but Fable managed to compile both. In any case, if possible, can you please access `fable-compiler` in `node_modules` and modify [this line](https://github.com/fable-compiler/Fable/blob/3fb2a76a3bdced91e4d94f2aadb22ffcf6703cad/src/fable/Fable.Client.Node/js/fable.js#L54) in `fable.js` so it reads:

```js
                fableLib.stdoutLog(babelAst.message);
```

...and try running Fable again?

**Comment by michaelsg** [comment]
I must appologize. Multiple fsproj in projFile works for me now. I don't know what I was doing wrong before.

Using the coreLib setting is perfect. I didn't equate that with simply forcing a path change on the imports.

Thanks for all your help.
