### ISSUE TITLE
0.7 script referenced entity replacements

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#535]
Just so it does not fall through the cracks:

### Description

If there is a Fable replacement for an entity referenced in a .fsx script, the replacement does not work.

### Repro steps

#r "System.Text.RegularExpressions.dll"
let r = System.Text.RegularExpressions.Regex("[a-z]")

### Expected behavior

Replaced with RegExp.

### Actual behavior

Not replaced.

### Known workarounds

Use .fsproj instead of .fsx

### Related information 

* Fable Version 0.7

**Comment by alfonsogarciacaro** [comment]
It may have some relation to [this](https://github.com/fable-compiler/Fable/blob/046efc4cd4ced808840decd051e563acfcedcaa7/src/fable/Fable.Compiler/FSharp2Fable.fs#L937-L941). That's a piece of code I included at the very beginning because I had some trouble with dll references in scripts. But it may be that that was an FCS bug that already got solved. I'll check if it can be removed :+1:

**Comment by alfonsogarciacaro** [comment]
Interesting, I cannot reproduce this because in Mono when trying to reference `#r "System.Text.RegularExpressions.dll"` I get an error:

```
Assembly reference 'System.Text.RegularExpressions.dll' was not found or is invalid
```

This is probably because of the new reference resolutions in latest FCS. In any case, the problem was indeed related to the code linked above. Precisely because it was _removed_ in one of 0.7.0 refactorings. After investigating about the problem I'm still puzzle but I'm trying [a different approach](https://github.com/fable-compiler/Fable/blob/fb1df53d723cbe3e70e8168581bb743cc8d2ba19/src/fable/Fable.Compiler/FSharp2Fable.fs#L1023-L1028) that seems to work. Could you please check?

Cheers!

**Comment by ncave** [comment]
@alfonsogarciacaro Tests are passing now, I've [uncommented](https://github.com/fable-compiler/Fable/pull/539) them. Thanks!
