### ISSUE TITLE
0.7.0 replacement issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#545]
This used to work in 0.6.x, but no longer compiles in 0.7.0:
```
namespace Microsoft.FSharp
module Test =
    let isTrue x = x
    let check x = isTrue x

```
Here is the error:
```
Cannot find replacement for Microsoft.FSharp.Test.isTrue
```
Work-around:
```
If I change the namespace it works.
```

**Comment by alfonsogarciacaro** [comment]
This is because a [short-circuit](https://github.com/fable-compiler/Fable/blob/88baf019ed21048dec3c85204f4ff2d9f747586d/src/fable/Fable.Compiler/Replacements.fs#L1674-L1689) I just added this weekend. Basically, the rule before was the replacements acted only on calls to external libraries, an failed if no replacement was found. However, in some cases is needed to replace (with plugins actually) calls to internal interfaces/types so now Fable tries to replace any call. However it still needs to fail if no replacement is found for a call to the BCL or FSharp.Core, so the user knows that's not compatible with Fable.

Maybe we could treat [replacement plugins and core replacements](https://github.com/fable-compiler/Fable/blob/88baf019ed21048dec3c85204f4ff2d9f747586d/src/fable/Fable.Compiler/FSharp2Fable.Util.fs#L927-L928) differently. Why do you need to use the `Microsoft.FSharp` namespace? For a polyfill?

**Comment by ncave** [comment]
Yes, I think it's a bit too restrictive, maybe they do need to be treated differently. I don't quite get it why there is such a restriction on the namespaces, we should be able to use any namespace, if it gets replaced, it gets replaced, right? Or maybe just convert replacement errors to warnings?

**Comment by alfonsogarciacaro** [comment]
Ok, I've published a new version that checks the assembly to see if the type belongs to an known source or not. Hopefully I got it right this time :) Please give it a try and tell me how it goes.

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, if you don't mind can you bump the version to 36, cause I already burned up 35? Thank you.

**Comment by alfonsogarciacaro** [comment]
Here you go!

**Comment by ncave** [comment]
@alfonsogarciacaro This works now, thanks for fixing it!
