### ISSUE TITLE
0.7.0 Entity issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#547]
Reporting as [requested](https://github.com/fable-compiler/Fable/blob/0.7.0/src/fable/Fable.Compiler/FSharp2Fable.fs#L1131), the following fails to compile:

```
namespace Test
type MyString = System.String
module M =
    let a = 0
```
`[ERROR] Multiple namespaces in same file are not supported`

**Comment by alfonsogarciacaro** [comment]
Supporting multiple namespaces is going to be difficult by how Fable works (it [conflates the namespace](http://fable.io/docs/compiling.html#Modules) in the file). But that sample should actually, I need to check the problem. Maybe the type alias confuses the [algorithm](https://github.com/fable-compiler/Fable/blob/b7a36c6406f592587c54a6975fd1aed6325f1c5b/src/fable/Fable.Compiler/FSharp2Fable.fs#L1126-L1141)?

**Comment by ncave** [comment]
Yes, I'm not sure what type of a (valid) construct are you guarding against [here](https://github.com/fable-compiler/Fable/blob/0.7.0/src/fable/Fable.Compiler/FSharp2Fable.fs#L1130), is it nested namespaces? Is there a way to target it directly instead of white-listing what is acceptable at top level?

**Comment by ncave** [comment]
@alfonsogarciacaro Fixed with #548.

**Comment by alfonsogarciacaro** [comment]
The algorithm is a bit confusing because it also depends on the [calculation of the root namespace](https://github.com/fable-compiler/Fable/blob/561cdb53f7842c89d6c4a842b220c4369d54c090/src/fable/Fable.Compiler/FSharp2Fable.fs#L999-L1009) for each file. Probably these two parts should be cleaned up and merged some how (now one relies in a string operation while the other uses the object hierarchy). For now I've added a fix in the commit above that discards ignored entities (like type aliases) when calculating the root namespace.

I'd have to check but I'm not sure #548 won't conflict in some situations, because Fable relies on certain heuristics to make the [proper imports](https://github.com/fable-compiler/Fable/blob/561cdb53f7842c89d6c4a842b220c4369d54c090/src/fable/Fable.Compiler/Fable2Babel.fs#L166-L187) when referencing types across or within the same file. In any case, Fable tries to have one single root module when possible as this has many benefits with tree shaking (right now I'm thinking how to avoid an inner with the common pattern of having a type and a module with the same name in the same file).

BTW, are you using a custom script to visualize the F# AST? Would it be possible to share it?

**Comment by ncave** [comment]
@alfonsogarciacaro Sure, see #549.
