### ISSUE TITLE
Fable-core/umd emitter

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#551]
Can we switch to using the typescript emitter for the fable-core/umd distribution?
For some reason some of the Babel-generated umd fails to work properly with node (getting runtime errors), but if emitted with typescript works fine.

**Comment by alfonsogarciacaro** [comment]
I guess that should be no problem (I actually don't even remember why are we using Babel just to translate the module system) though it's weird and it would be nice to know the problem... mainly because Fable does use Babel to compile to JS. Maybe we should upload the version.

In any case, could you please send a PR to modify the target? Thanks!

**Comment by ncave** [comment]
@alfonsogarciacaro I can't transpile fable-core to ES5 with typescript, is it ok to target ES6 for UMD?

**Comment by alfonsogarciacaro** [comment]
Ah, ok. That's why we're using Babel :) As the UMD distribution is meant for compatibility, I don't think it's a good idea to target ES6. What kind of runtime errors are you getting in node with the current Babel-compiled code?

**Comment by ncave** [comment]
@alfonsogarciacaro All kinds of errors, missing interfaces, etc.
Is it ok then to add another folder to the distro with ES6 commonjs or umd? I mean, why do we need to use ES5 in node, the whole point of producing beautiful javascript and all?

**Comment by alfonsogarciacaro** [comment]
It's not only node, the umd distribution can be used to load fable-core files in a browser with requirejs. I'd rather keep the number of distros to a minimum to prevent incompatibilities among tutorials, libraries, etc.

I'm really puzzled about these runtime errors. Babel is a very reliable tool used by thousands of developers and all Fable tests pass using fable-core/umd compiled with TS+Babel, so I think this must be a problem in our build process. It may be because the double compilation (first to ES5 with ES6 modules, and then just to UMD modules) or because the `loose` option.

**Comment by ncave** [comment]
@alfonsogarciacaro I meant adding another folder, say /umd-es2015, and maybe also /umd-es2016, for the advanced people out there :) The fable-core size is tiny, so it's not going to inflate the distro that much, but it will allow people to use what they want.

**Comment by alfonsogarciacaro** [comment]
I'm not completely against that. Actually you made me realize we need a better way to change the referenced distro, not only for fable-core but also for other libs. But I still think it's not the way to solve the problem (among other things, because I'm not sure yet what the problem is :wink:). As commented above, if Babel is not working properly, it's very worrisome, because Fable uses Babel to compile to ES5. I'll upload a new version with fable-core/umd compiled without the `loose` option to see if it fixes something.

**Comment by ncave** [comment]
@alfonsogarciacaro Hopefully it will help. Here is what's crashing with the current one (0.7.5-alpha.17):

```
let doTest1 =
    let s = [ for i in 1..20 -> i ]
    printfn "%A" s
```

compiles to:

```
const doTest1 = exports.doTest1 = (() => {
    const s = (0, _Seq.toList)((0, _Seq.delay)(() => (0, _Seq.map)(i => i, (0, _Seq.range)(1, 20))));
    return (0, _String.fsFormat)("%A")(x => {
        console.log(x);
    })(s);
})();
```

runtime error is in _Seq.toList:

```
[ERROR] ...\node_modules\fable-core\umd\Seq.js:126
        }, xs, new _List2.default());
               ^
```

Again, works fine when targeting ES6.

**Comment by alfonsogarciacaro** [comment]
Interesting, this works perfectly fine for me. Which node version are you using? Have you tried to upgrade?

**Comment by ncave** [comment]
@alfonsogarciacaro Tested with node v7.0.0 and v7.1.0, no go :(

**Comment by ncave** [comment]
@alfonsogarciacaro Sorry, the example above was incomplete, I've updated it with the correct code that fails with fable-core 0.7.5-alpha.17 (umd-ES5) but works fine if you target umd/commonjs-ES6.

**Comment by ncave** [comment]
@alfonsogarciacaro Tested with fable-core 0.7.5-alpha.18, still getting the same error (see example above).

**Comment by alfonsogarciacaro** [comment]
@ncave Can you put your generated JS code in a gist? It would be also useful to have the complete stack trace of the error and the versions of node & npm installed in your machine.

**Comment by ncave** [comment]
Source: [project.fsx.txt](https://github.com/fable-compiler/Fable/files/604361/project.fsx.txt)

Generated: [project.js.txt](https://github.com/fable-compiler/Fable/files/604342/project.js.txt)

node: v7.1.0
npm: v3.10.9

```
[ERROR] C:\Projects\fable-test\src\test\node_modules\fable-core\umd\Seq.js:179
        }, xs, new _List2.default());
               ^

TypeError: _List2.default is not a constructor
    at toList (C:\Projects\fable-test\src\test\node_modules\fable-core\umd\Seq.js:179:16)
    at main (C:\Projects\fable-test\src\test\out\project.js:46:29)
    at Object.<anonymous> (C:\Projects\fable-test\src\test\out\project.js:51:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)

```

**Comment by alfonsogarciacaro** [comment]
Thanks! I was finally able to reproduce the error :) I think it has to do with cyclic dependencies but I need to investigate more. I wonder why it didn't happen before and also why it doesn't happen whe compiling to ES6.

**Comment by alfonsogarciacaro** [comment]
I fixed the cyclic dependencies issue. Could you please try with latest fable-core alpha?

**Comment by ncave** [comment]
@alfonsogarciacaro It works now, thanks for fixing it!
