### ISSUE TITLE
Internal "inline" methods used to work in 0.7.5-alphas

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#556]
### Description

Internal inline methods used to work. Now with the release of 0.7.6 (and 0.7.7) it says the `inline` must be removed.

```fsharp

type Statement = Zero | ChangeState of Statement | Read

module internal Ops =
    let inline zero () = Zero
    let inline delay f = f
open Ops

type Builder () =
    member x.Zero () = zero ()
    member x.Delay f = delay f
```

**Comment by alfonsogarciacaro** [comment]
Sorry for that. This is actually not because of `internal` but because of an optimization I tried to introduce that was reordering declarations a bit. For now I've disabled the optimization (can you please try with 0.7.8?) but I'm gonna have to fix it anyway (probably with a first pass to cache the body inlined methods) because with F# 4.1 recursive modules it will be possible to call a function before it has been declared.

**Comment by michaelsg** [comment]
0.7.8 works. Thank you!
