### ISSUE TITLE
Pojo with static members

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#558]
After migrating to `fable 0.7.8`, I realized that `toPlainJsObj` is now obsolete. The approach I gathered was to use `PojoAttribute`. This is also required when using `react'. After updating all react component props and state records with this attribute, project compiles but breaks in some areas. Still investigating.

This discussion is on the limitation of the `PojoAttribute`. It cannot contain members. For my use case, records only have static members. One static member that most records have is `empty`. A less frequently used one is `create`. This is a way of providing reasonable defaults when creating the record. Example below

    //before
    type Settings =
      { ``type`` : CalendarType
        onChange : System.DateTime -> bool } with
      static member empty =
        { ``type`` = DateTime
          onChange = fun date -> true }

    //now
    [<Pojo>]
    type Settings =
      { ``type`` : CalendarType
        onChange : System.DateTime -> bool }
    let emptySettings =
      { ``type`` = DateTime
        onChange = fun date -> true }

    //usage
    let settings = { Settings.empty with ``type`` = type' } //before
    let settings = { emptySettings with ``type`` = type' } //now

The current approach I'm adopting is using the `PojoAtttribute` only when needed. Also if the record in a module, I move the static functions to the module. If not, I create a new module and move the functions there. 

I looked at the output when `PojoAttribute` is used and frankly, it would be lovely if it can be used in most places but for the current limitation.

Is the scenario below reasonable and possible?

- Records with `PojoAttribute` can only have static members.
- If there are static members, the record is compiled to something similar to a static class with the static members. Those with no static members are either erased or become empty classes.
- All references to the record become the Pojo equivalent while references to members are called on the static class for that record.
- I'm assuming instance members may be tricky but if they can be compiled to their static equivalent, it might just work.

### Related information 

* Fable Version: 0.7.8
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
> I looked at the output when `PojoAttribute` is used and frankly, it would be lovely if it can be used in most places but for the current limitation.

Hehe, this is precisely what I was afraid of and the reason I didn't introduce this attribute before. I know it looks nice to see simple JS objects in the compiled code, and then people would like to use it for everything. But I know how this scales: issues come requesting more and more features until they have the same semantics as _normal_ records :wink:

Static members would indeed be possible and I was already considering some of your points. My reasons to omit static members (at least for now) were:

- Time limitations to implement and test the feature
- Consistence with the other erased types
- Encourage devs to put functions in a root module, which work better with tree-shaking
- Discourage devs to use `PojoAttribute` in more places than strictly necessary

About instance members, as you say it'd be possible to compile them as static ones (this is what the F# compiler does actually), but I'd be more reluctant to include this. Because the `PojoAttribute` is meant to interact with JS APIs like React, and devs would expect that the instance members are travelling with the object.

**Comment by rkosafo** [comment]
Indeed. A problem however does arise when you have a type with static functions that you need to use with a function that expect `PojoAttribute`. Even though no code was generated for the type, it did not even occur to me that it is an erased type :) . Your explanation has put me on the fence now. I think it is ok either way. I'm using the record below to get around this issue for now for react components.


    [<Pojo>]
    type PojoRef<'t> = { content: 't }

**Comment by alfonsogarciacaro** [comment]
Thank you for your understanding. Yes, that's a good way to solve the problem, and it's more or less what the React helpers like fable-elmish or fable-arch are doing. Unfortunately React wasn't playing well with Fable types even when using `toPlainJsObject` so this was necessary :/

I know it's tempting to stretch the users of the erased types because they're supposedly more performant, but this brings a big maintenance burden because Fable needs to take different semantics into account in several places, so I need to find a way to restrict the usage.
