### ISSUE TITLE
toPlainJsObj is deprecated without a good option for Discriminated Unions

### ISSUE THREAD

**Issue by wastaz** [fable-compiler/Fable#572]
In Fable 0.7 `toPlainJsObj` is deprecated and replaced with the `[<Pojo>]` attribute. While this works nicely with records, it doesn't really work as well with discriminated unions.

In my project `fable-import-redux` I provide a small middleware for using discriminated unions as the message type for redux. This works quite well and makes working with redux in fable quite nice. However, this also relies on `toPlainJsObj`. 

This is how this middleware looks right now (I'll do some changes to this pretty soon since Im still upgrading the package to 0.7, so inline and such will be removed in the next version)
```
let inline unionMiddleware (_ : Redux.IUntypedStore) (next : obj -> unit) (action : obj) =
    if action.GetType().Name <> "Function" then
        let o = toPlainJsObj action
        if o?hasOwnProperty$("Case") |> unbox<bool> then 
            let o = toPlainJsObj action
            o?``type`` <- o?Case
            o |> next
        else
            action |> next
```

This of course causes deprecation warnings since I'm using `toPlainJsObj`.

Putting `[<Pojo>]` on the DU seems like a bad idea, plus the fact that Im providing a library here so I'm not actually declaring the type of the action itself which means that I have no real way of "forcing" the user to remember to put `[<Pojo>]` on the type. 

Some suggested solutions
- De-deprecate `toPlainJsObj`
- Make `[<Pojo>]` work nicely for DU's (though this doesn't solve the problem of how to help the users of my library to remember to decorate their action type with this attribute)
- ?

**Comment by alfonsogarciacaro** [comment]
I think we have two possibilities here:

- Allow `Pojo` on DUs and make them compile with the same body as other DUs, so for example, `type U = SingleCase of foo: int * bar: string` becomes:

```js
{ Case: "SingleCase", Fields: [5, "hi"] }
```

- Go crazy and compile them to something closer to what Redux expects:

```js
{ type: "SingleCase", foo: 5, bar: "hi" }
```

This last option requires a bit more editting of Fable than the first one, but it should be doable. The disadvantages of this approach is that it may tie Pojo DUs a bit too much to Redux (using `type` for the case name) and I'm afraid this may make developers overuse the attribute, but on the other hand it would play much better with Redux dev tools and it may allow interesting interactions with other JS libs.

What do you think? Would taking the second approach be beneficial for the Redux bindings, or would it suffice with the first solution?

About using it with libraries, you don't need to worry. It's possible to add the `Pojo` attribute to generic arguments and then Fable will make sure the type used to fill the hole is decorated with `Pojo`, as in the [React helper](https://github.com/fable-compiler/fable-react/blob/8090ac96c4063b50975d107796b4e4ff5f718a44/src/react/Fable.Helpers.React.fs#L586).

**Comment by wastaz** [comment]
@alfonsogarciacaro I think that this fix should be more of a generic fix and not a Redux-specific one. I can easily imagine that there are more JS libraries out there that would be really nice to interact with together with DU's that does not have the same requirements as Redux, so I dont think that we should tie this functionality to Redux specifically.

So I'd say that option 1 is quite ok for my usage (and how `toPlainJsObj` works right now if I'm not mistaken?)

Also, thanks for the tip about `[<Pojo>]` attributes on generic arguments! That's a great feature :)

**Comment by alfonsogarciacaro** [comment]
Hehe, a bit late. I already implemented Pojos DUs using the second approach above :wink: I did some texts with the Redux Devtools extension and this kind of DUs are more informative so I thought it was worth a shot. Also, Typescript has implemented [tagged unions](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#tagged-union-types) in a similar way, so this pattern may become popular in the future and be useful when interacting with JS libs. TS tagged unions give free choice for the property name to represent the tag, but this is not possible with Fable (at least for now) so I just picked `type` because: a) is compatible with Redux and b) is a keyword in F# so chances of it being used for another field name are very low.

I cloned your Redux bindings and tried to update them but it was a bit difficult for me to follow the code. You can check the updated [Redux sample](https://github.com/fable-compiler/Fable/blob/5989e16954b9f1c8312bd901e9c6abac153b1ec4/samples/browser/redux-todomvc/redux-todomvc.fsx#L42-L57) to see how the new Pojo DUs and dynamic programming capabilities make the code to interact with non-typed JS nicer.

**Comment by wastaz** [comment]
@alfonsogarciacaro Alright :) I don't mind version 2, it does allow me to remove some unnecessary code which is always nice.

I am currently trying to update my Redux bindings to 0.7, it's on a local branch here on my computer. I think I have pretty much figured it out. I'm just kinda waiting for a 0.7 compatible version of `fable-import-react` to be released so I can test everything properly and update my other bindings as well.

**Comment by alfonsogarciacaro** [comment]
Nice! :clap: Just ping me if you need any help :+1:

**Comment by alfonsogarciacaro** [comment]
I'm closing the issue for now, please feel free to reopen it if you've any other comment.
