### ISSUE TITLE
Newbie: sample interaction with JS Code

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#587]
Hi!
I'm currently struggling to communicate with this kind of JS code:

```js
var myPrototype = myPrototype || {};
(function () {
    "use strict";
    myPrototype.foo = function () {
        return "bar";
    };
}());
```

I know **I lack some JS  knowledge** here (and my questions may seem redundant).

But let's say that:
- the JS code is inside a myProto.js file. 
- this file is loaded from index.html

1. **fableconfig.json**: what do I need to configure? rollup section? None? 
2.  F# code: what must I do in order to call the foo function?
3. Do I need to trandform this code?

 Thanks in advance!

**Comment by alfonsogarciacaro** [comment]
Hi @whitetigle! As per your description, this code is exposed globally, so there are two options to make it accessible from F#:

- If the you use the same variable name in F# you can just use the `GlobalAttribute`:

```fsharp
type IMyPrototype =
    abstract foo: unit->string

[<Global>]
let myPrototype: IMyPrototype = jsNative // This is the same as `failwith "JS only"`
```

- For more flexibility you can use `EmitAttribute`, for example:

```fsharp
[<Emit("myPrototype.foo()")>
let foo(): string = jsNative
```

As these will be translated to calls to global values, my guess is you don't need to add anything to Rollup config. This is only needed if you're _importing_ the function but then it's exposed globally. For example, if you do:

```fsharp
[<Import("foo", from="myPrototype")>]
let foo(): string = jsNative
```

Then you would need to add the following to your rollup config:

```js
{
    // Tell Rollup not to try to bundle this code
    "external": ["myPrototype"],
    "globals": {
        // Tell Rollup the actual name of the global variable
        // (the same in this case)
        "myPrototype":  "myPrototype"
    }
}
```

This is not needed for your case but it's useful for example if you're using the React or Pixi bindings (which use `Import`) but then expose the library code globally through a script tag instead of bundling it.

I hope this is useful, please give it a try and tell me if you still have problems :)

**Comment by alfonsogarciacaro** [comment]
If you prefer to import the JS code so it can be bundled (instead of loading it with a script tag), I think you just need to modify the first line of the .js file:

```js
export default var myPrototype = myPrototype || {};
```

Then in F#:

```fsharp
type IMyPrototype =
    abstract foo: unit->string

let myPrototype: IMyPrototype = importDefault "./myPrototype.js"

/// This is equivalent to the previous line
// [<Import("default", from="./myPrototype.js")>]
// let myPrototype: IMyPrototype = jsNative
```

This way Rollup will automatically bundle the JS code into your app (no extra config needed). I did something similar for the [Three.js sample](https://github.com/fable-compiler/Fable/blob/259d71caaa5cfb23c76423d7bd4edc427f8bd0c6/samples/browser/webGLTerrain/js/FirstPersonControls.js#L7).

**Comment by whitetigle** [comment]
Excellent @alfonsogarciacaro! 👏 
I'm going to try this right away!
Thanks

**Comment by whitetigle** [comment]
Ok it works. I have access to my global object. 👍 

Now I have another problem.
Let's say that I have an inner prototype inside my global object that I have instantiate this way:

```js
var mySubProto = new myPrototype.MySubProto(configObj);
```
How can I retrieve/get an instance of this sub object from F#?
Again thanks for your patience!

**Comment by whitetigle** [comment]
ok I found: 

```f#
[<Emit("new myPrototype.MySubProto($0)")>]
let bar(config:obj): MySubProto = jsNative
```

**Comment by alfonsogarciacaro** [comment]
There are several ways to do this. You can create an add-hoc function as you did above or you could use `EmitAttribute` in the `IMyPrototype` interface:

```fsharp
type IMySubProto =
    // Define your methods here
    interface end

type IMyPrototype =
    abstract foo: unit->string
    [<Emit("new $0.MySubProto($1)")>]
    abstract MySubProto: obj->IMySubProto

[<Global>]
let myPrototype: IMyPrototype = jsNative // This is the same as `failwith "JS only"`

myPrototype.MySubProto(obj())
```

In the very latest Fable version (released yesterday), you have `JsConstructor` which implements the constructor method automatically for you:

```fsharp
type IMyPrototype =
    abstract foo: unit->string
    abstract MySubProto: JsConstructor<obj,IMySubProto>

myPrototype.MySubProto.Create(null)
// In JS becomes: new myPrototype.MySubProto(null)
```

**Comment by whitetigle** [comment]
Thanks again. I will try this.
