### ISSUE TITLE
fable-providers-regex broken for fable 0.7.18

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#589]
When trying to use Fable.Providers.Regex I got this error:

```
[0] [ERROR] Cannot find replacement for Fable.Providers.Regex.Internal.Helper.CreateRegex (L68,4-L68,47) (L:\Squiibz\src\Browser\Pages/Prestation/Prestation_Create.fs)
```

Code for reproduction:

```fs
open Fable.Providers.Regex

let regexTime =
  SafeRegex.Create<"^\d$", ignoreCase=true>()
```

**Comment by MangelMaxime** [comment]
I still have this error with fable 0.7.22.

**Comment by alfonsogarciacaro** [comment]
I don't believe you ;) Hehe, just kidding. Would it be possible to create a repo to reproduce (.fsx, fableconfig, package.json)?

**Comment by MangelMaxime** [comment]
Yes sure 😊

**Comment by MangelMaxime** [comment]
Here is a project to reproduce the error :)

[RegexReproduction.zip](https://github.com/fable-compiler/Fable/files/672975/RegexReproduction.zip)

Usage:

```bash
➜ npm i
➜ node build.js
```

**Comment by MangelMaxime** [comment]
Working with the new version of fable-providers-regex

**Comment by CliveWongTohSoon** [comment]
Hi is it possible to let this also works on .fs format?

**Comment by MangelMaxime** [comment]
@CliveWongTohSoon Not sure to undetstand your point here. Could you please explain a bit more ?

**Comment by CliveWongTohSoon** [comment]
I am working on a project using Fable + Electron using fable-loader, and in the code System.Text.RegularExpressions are needed (specifically, Regex(s).match is needed). However, when I tried to compile it, it gives error saying "error FABLE: Cannot find replacement for System.Text.RegularExpressions.GroupCollection::GetEnumerator". 

I tried to resort to using fable-provider-regex, only to realise it can't be used in my project as they need to be in .fs format, but fable-provider-regex only works in .fsx (script file). I wonder is there anything I can do to make it work on my .fs codes.

**Comment by alfonsogarciacaro** [comment]
Hi @CliveWongTohSoon. Type providers are not working at the moment for Fable 1.x but we expect this to be fixed soon. For what you describe, in you case probably the easiest solution is to implement the replacement for "System.Text.RegularExpressions.GroupCollection::GetEnumerator". Do you have a sample of the code that's failing so we can add it as a test? Cheers!

**Comment by CliveWongTohSoon** [comment]
Here is the snipper of the code. I believe the error is thrown from regexMatch, where it returns m.Groups which fable-loader doesn't support yet. 

    let regexMatch (regex:string) (str:string) =
        let m = System.Text.RegularExpressions.Regex(regex).Match(str)
        if m.Success
        then
        let mLst = [ for x in m.Groups -> x.Value ]
        Some (List.head mLst, List.tail mLst)
        else None

    let (|LexMatchD|_|) debug regex (lexData: LexData) = 
        match regexMatch regex (lexData.Txt) with
        | None -> 
            if debug 
            then printfn "Match of '%s' with '%s' failed." lexData.Txt regex
            None
        | Some (mStr, rst) -> 
            let mChars = String.length mStr
            if mChars = 0 then
                failwithf "Unexpected 0 character match '%s' " regex
            if debug then
                printfn "Match of '%s' with '%s' OK: match is '%s'" lexData.Txt regex mStr
            let lexData' = {lexData with Txt = lexData.Txt.[mChars..]}
            Some (mStr, lexData')

    let (|LexMatch|_|) = (|LexMatchD|_|) false

    let nextToken ld = 
        let incr ld = {ld with Num = ld.Num + 1}
        match ld with
        | LexMatch @"^\," (_, ld') -> None, ld'
        | LexMatch @"^[ ]" (_, ld') -> None, ld'
        | LexMatch @"^#.*" (exp, ld') -> Some (Exp (exp)), ld'
        | LexMatch @"^[rR][0-9]+" (reg, ld') -> Some (R (reg, ld'.Num)), incr ld'
        | LexMatch @"^[lL][sS][lL]" (opr, ld') -> Some (Opr (opr)), ld'
        | LexMatch @"^[lL][sS][rR]" (opr, ld') -> Some(Opr(opr)), ld'
        | LexMatch @"^[aA][sS][rR]" (opr, ld') -> Some(Opr(opr)), ld'
        | LexMatch @"^[rR][rR][xX]" (opr, ld') -> Some(Opr(opr)), ld'
        | LexMatch @"^[rR][oO][rR]" (opr, ld') -> Some(Opr(opr)), ld'
        | _ -> failwithf "Matching failed in lexer"

**Comment by alfonsogarciacaro** [comment]
Hmm, `Regex.Groups` should be supported. The code below is working for me [in the REPL](http://fable.io/repl/#?code=let%20regexMatch%20(regex%3Astring)%20(str%3Astring)%20%3D%0D%0A%20%20%20%20let%20m%20%3D%20System.Text.RegularExpressions.Regex(regex).Match(str)%0D%0A%20%20%20%20if%20m.Success%20then%0D%0A%20%20%20%20%20%20%20%20let%20mLst%20%3D%20%5B%20for%20x%20in%20m.Groups%20-%3E%20x.Value%20%5D%0D%0A%20%20%20%20%20%20%20%20Some%20(List.head%20mLst%2C%20List.tail%20mLst)%0D%0A%20%20%20%20else%20None%0D%0A%0D%0Alet%20(%7CLexMatchD%7C_%7C)%20debug%20regex%20(lexData%3A%20string)%20%3D%20%0D%0A%20%20%20%20match%20regexMatch%20regex%20lexData%20with%0D%0A%20%20%20%20%7C%20None%20-%3E%20%0D%0A%20%20%20%20%20%20%20%20if%20debug%20%0D%0A%20%20%20%20%20%20%20%20then%20printfn%20%22Match%20of%20'%25s'%20with%20'%25s'%20failed.%22%20lexData%20regex%0D%0A%20%20%20%20%20%20%20%20None%0D%0A%20%20%20%20%7C%20Some%20(mStr%2C%20rst)%20-%3E%20%0D%0A%20%20%20%20%20%20%20%20let%20mChars%20%3D%20String.length%20mStr%0D%0A%20%20%20%20%20%20%20%20if%20mChars%20%3D%200%20then%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20failwithf%20%22Unexpected%200%20character%20match%20'%25s'%20%22%20regex%0D%0A%20%20%20%20%20%20%20%20if%20debug%20then%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20printfn%20%22Match%20of%20'%25s'%20with%20'%25s'%20OK%3A%20match%20is%20'%25s'%22%20lexData%20regex%20mStr%0D%0A%20%20%20%20%20%20%20%20let%20lexData'%20%3D%20lexData.%5BmChars..%5D%0D%0A%20%20%20%20%20%20%20%20Some%20(mStr%2C%20lexData')%0D%0A%0D%0Alet%20(%7CLexMatch%7C_%7C)%20%3D%20(%7CLexMatchD%7C_%7C)%20false%0D%0A%0D%0A%2F%2F%20let%20nextToken%20ld%20%3D%20%0D%0A%2F%2F%20%20%20%20%20let%20incr%20ld%20%3D%20%7Bld%20with%20Num%20%3D%20ld.Num%20%2B%201%7D%0D%0A%2F%2F%20%20%20%20%20match%20ld%20with%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5C%2C%22%20(_%2C%20ld')%20-%3E%20None%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5B%20%5D%22%20(_%2C%20ld')%20-%3E%20None%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%23.*%22%20(exp%2C%20ld')%20-%3E%20Some%20(Exp%20(exp))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BrR%5D%5B0-9%5D%2B%22%20(reg%2C%20ld')%20-%3E%20Some%20(R%20(reg%2C%20ld'.Num))%2C%20incr%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BlL%5D%5BsS%5D%5BlL%5D%22%20(opr%2C%20ld')%20-%3E%20Some%20(Opr%20(opr))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BlL%5D%5BsS%5D%5BrR%5D%22%20(opr%2C%20ld')%20-%3E%20Some(Opr(opr))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BaA%5D%5BsS%5D%5BrR%5D%22%20(opr%2C%20ld')%20-%3E%20Some(Opr(opr))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BrR%5D%5BrR%5D%5BxX%5D%22%20(opr%2C%20ld')%20-%3E%20Some(Opr(opr))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20LexMatch%20%40%22%5E%5BrR%5D%5BoO%5D%5BrR%5D%22%20(opr%2C%20ld')%20-%3E%20Some(Opr(opr))%2C%20ld'%0D%0A%2F%2F%20%20%20%20%20%7C%20_%20-%3E%20failwithf%20%22Matching%20failed%20in%20lexer%22%20&html=%3Chtml%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E). I just set `lexData` to be string because I didn't have the `LexData` type. What version of Fable are you using (`dotnet fable --version`)?

```fsharp
let regexMatch (regex:string) (str:string) =
    let m = System.Text.RegularExpressions.Regex(regex).Match(str)
    if m.Success then
        let mLst = [ for x in m.Groups -> x.Value ]
        Some (List.head mLst, List.tail mLst)
    else None

let (|LexMatchD|_|) debug regex (lexData: string) = 
    match regexMatch regex lexData with
    | None -> 
        if debug 
        then printfn "Match of '%s' with '%s' failed." lexData regex
        None
    | Some (mStr, rst) -> 
        let mChars = String.length mStr
        if mChars = 0 then
            failwithf "Unexpected 0 character match '%s' " regex
        if debug then
            printfn "Match of '%s' with '%s' OK: match is '%s'" lexData regex mStr
        let lexData' = lexData.[mChars..]
        Some (mStr, lexData')

let (|LexMatch|_|) = (|LexMatchD|_|) false
```
