### ISSUE TITLE
ReactDom is not defined

### ISSUE THREAD

**Issue by sslotsky** [fable-compiler/Fable#607]
Sorry if this has been asked or if I'm missing something obvious. I'm trying to follow the react samples, and I can't figure out how you're able to reference `ReactDom` without importing it in some way. I've copied and modified the `fableconfig.json`:

```json
{
    "projFile": "./main.fsx",
    "rollup": {
        "dest": "../public/js/bundle.js",
        "external": ["react", "react-dom"],
        "globals": {
            "react": "React",
            "react-dom": "ReactDOM"
        }
    }
}
```

And I'm attempting to render a simple `<h1>Hello World</h1>` but I get the error shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/374078/21291065/00d182b6-c498-11e6-8211-f64450bbcf61.png)

Advice appreciated!

**Comment by sslotsky** [comment]
This makes the error go away in the editor:

```fsharp
module R = Fable.Helpers.React
module ReactDom = Fable.Import.ReactDom
module Browser = Fable.Import.Browser

ReactDom.render(R.h1 [] [ R.str "Hello World!"], Browser.document.getElementById("app"))
```

but when I attempt to rollup I get the error below

```
sam@sam-Alienware-13-R2:~/react-electron$ npm run rollup

> react-webpack-client@1.0.0 rollup /home/sam/react-electron
> fable --rollup

fable-compiler 0.7.22: Start compilation...
Compiled main.js at 8:59:37 PM
Bundling...
[BUNDLE ERROR] 'render' is not exported by node_modules/react-dom/index.js (imported by app/main.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/sam/.nvm/versions/node/v7.0.0/bin/node" "/home/sam/.nvm/versions/node/v7.0.0/bin/npm" "run" "rollup"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-client@1.0.0 rollup: `fable --rollup`
npm ERR! Exit status 1
```

**Comment by alfonsogarciacaro** [comment]
Hi @sslotsky! Sorry for the late reply. Unfortunately, Rollup doesn't work well with React. There are some configurations out there to make it work but personally I prefer to declare `react` and `react-dom` as external (as you did in fableconfig.json above) which means they won't be included in the bundle. Then you can just [load the libraries with `<script>` tags](https://github.com/fable-compiler/Fable/blob/0fea84c80627dc1203963b77c4eec01fb5a39352/samples/browser/react-todomvc/index.html#L12-L13).

Another option is to use Webpack instead of Rollup. [Webpack 2](https://webpack.js.org/get-started/) can finally read ES2015 modules so it's a good alternative.

> As Webpack is not embedded, to best way to use it together with Fable is adding a `webpack.config.js` file and then calling it in a `postbuild` script like:

```json
"scripts": {
    "postbuild": "node node_modules/.bin/webpack"
}
```

**Comment by sslotsky** [comment]
Ah excellent, thanks so much for the tip! I normally do use webpack with React, but inferred that it was advised to use the new bundling tools.

**Comment by alfonsogarciacaro** [comment]
Yeah, that was mainly for convenience of people who don't know well how to use Webpack, and also because when Fable 0.7 came out, Webpack 2 was still very alpha, but I guess it's fine to use it now :)

One last tip: if you use webpack `--watch` mode, make sure to use `postbuild-once` instead. Usually, the config is like:

```json
"targets": {
    "debug": {
         "watch": true,
         "scripts": {
             "postbuild": "", // cancel the default option
             "postbuild-once": "node node_modules/.bin/webpack --watch"
         }
    }
}
```
