### ISSUE TITLE
Meteorjs methods table

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#630]
Hi, I'm trying to write Fable bindings for Meteor js.
I've to use ts2fable and use it's output for simple apps and it works. But for some complex things, ts2fable's output is too poor.

For example [Methods](http://docs.meteor.com/api/methods.html#Meteor-methods).
regular use:
```js
Meteor.methods({
  foo: function (arg1, arg2) {
    // .. do stuff ..
   console.log(this.userId);
   return "some return value";
  },
  bar: function () {
    // .. do other stuff ..
    return "baz";
  }
});
```
ts2fable outout
```fs
type Globals =
   static member methods(methods: obj): unit = jsNative
```
I can create objs like
```fs
let methods = createObj [foo ==> fun arg1 arg2 -> "some return value"]
```
but I can't use `this` keyword here.
**Maybe you can give me hint about `this` problem?**

Some thoughts about it:
1. Create type Method
```fs 
[<KeyValueList>]
type Methods = 
    |[<Erase>] Method of methodname:string * MeteorMethod

and MeteorMethod() =
    member this.userId :string = jsNative
    abstract Function:[<ParamArray>] args: obj[] -> unit
///and use it like this
Meteor.methods [
   Method ("name", {new MeteorMethod() with Function([<ParamArray>] args: obj[]) = this.userId}
 ] ///too long and how to render MeteorMethod to function?
```
2. Wrap function and pass `this` as parameter
```fs 
let mehodWrapper (func:thisContext -> obj list -> 'a) = jsNative
```
and it render like 
```js
function(params) {
  return func(this,params)
}
```
How should I write fable binding here? And how anybody should use it?

```fs
type Globals =
   static member methods(methods: #seq<string * (thisContext -> obj list -> 'a)>): unit = 
        createObj <| (methods |> Seq.map (fun (f,s) -> f ==> mehodWrapper s)) 
///will it work?
```

**Comment by alfonsogarciacaro** [comment]
ts2fable needs a big update. Unfortunately at the moment, it cannot read objects without an interface declaration and whose shape is defined on the method signature itself 😕 

About JS `this`, I couldn't document it yet but the latest Fable versions include `jsThis` in the `Fable.Core.JsInterop` module, that will translate to `this` in JS. Please note it can only be used within a delegate (you'll get a compiler error otherwise). Example:

```fsharp
open System
open Fable.Core.JsInterop

let methods = createObj [foo ==> Func<_,_,_>(fun x y -> jsThis?add(x, y))]
```

It's a bit annoying to type the `Func` generics placeholders, even if they're inferred. So `Fable.Core` also includes the JsFuncX aliases, where X is the number of arguments:

```fsharp
open Fable.Core
open Fable.Core.JsInterop

let methods = createObj [foo ==> JsFunc2(fun x y -> jsThis?add(x, y))]
```

**Comment by Neftedollar** [comment]
@alfonsogarciacaro thanks, I've found jsThis. But it doesn't compile. I'll create new issue.
