### ISSUE TITLE
gl.bindFramebuffer and nulls

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#640]
### Description

Can't pass null into gl.bindFramebuffer

### Repro code
```
let gl = canvas.``getContext_experimental-webgl``()
let rttFramebuffer = gl.createFramebuffer()
gl.bindFramebuffer(gl.FRAMEBUFFER, rttFramebuffer)
gl.bindFramebuffer(gl.FRAMEBUFFER, null)
```
### Expected and actual results
Expected:
```
var gl = canvas.getContext("webgl");
var rttFramebuffer = gl.createFramebuffer();
gl.bindFramebuffer(context.FRAMEBUFFER, rttFramebuffer);
gl.bindFramebuffer(context.FRAMEBUFFER, null);
```

Actual:
```
var gl = canvas.getContext("webgl");
var rttFramebuffer = gl.createFramebuffer();
gl.bindFramebuffer(context.FRAMEBUFFER, rttFramebuffer);
gl.bindFramebuffer(context.FRAMEBUFFER);
```

Workaround:
```
let x = null
gl.bindFramebuffer(context.FRAMEBUFFER, x);
```

**Comment by alfonsogarciacaro** [comment]
This is tricky, it's necessary to remove the tail `null` arguments because in F# optional arguments have the `option` type (which Fable translates to nullable) and other APIs precisely fail when you pass null while they expect nothing (see #231).

However the `null` argument removal is being done with a Babel plugin, maybe it could be possible on the Fable side where we can still distinguish between _intended_ nulls and omitted optional arguments.
