### ISSUE TITLE
Zero fill shift right (>>>) is wrong for uint32...

### ISSUE THREAD

**Issue by GordonBGood** [fable-compiler/Fable#646]
### Description

There is just one shift right operator in F# is (>>>) which is fine as when passed an integer (signed) argument as the first argument it shoes an arithmetic shift right and with an uint32 argument it **should** do a zero fill shift right (logical shift right).  Currently, Fable does not do the later for uint32's, but rather continues to do a regular arithmetic shift right (>> in JavaScript).

The compiler should keep track of the type of the first argument so it knows which kind of shift to apply.  Using a uint32 conversion before shift takes place applies the JavaScript hack (>>> 0) to produce a uint32 value, but then the application of the wrong shift operator still does the arithmetic shift right on the argument converted back to integer form.

### Repro code

printfn "%A" (0x80000000u >>> 1) // or (Note that the MSB is set)

printfn "%A" (uint32 0x80000000 >>> 1)

### Expected and actual results

Expected:  1073741824 // is same as ox40000000

Actual: -1073741824 // is same as 0xC0000000 with MSB set incorrectly and typed as int32 in JavaScript

### Related information 

* fable-compiler version: 0.7.24
* fable-core version: 0.7.20
* Operating system: Windows 10 64-bit

**Comment by alfonsogarciacaro** [comment]
Thanks for catching this! Does this affect to other unsigned integers? Also, do you know what would be the most efficient way to simulate the expected behaviour in JS?

**Comment by GordonBGood** [comment]
You're welcome.

Unsigned bytes (uy) and shorts (us) don't have a problem even though the wrong shift is used as they are less than the 32 range of a JavaScript bit operation, thus zero fill in any case.

64-bit unsigned numbers (UL) aren't a problem because they are an artificial library object in JavaScript, and are handled correctly by the library shift method dependent on whether they are flagged as signed or not (although the output prints as a string (with quotes) rather than as a value - understandable I suppose as it isn't a primitive JavaScript type).

So the problem manifests itself only with 32-bit uint32's.

What you want in JS is just "(n >>> 1)", which is the zero fill shift right or logical shift right instead of the "(n >> 1)" arithmetic shift right it currently emits.  You also should really terminate all 32 bit expressions with " | 0" for signed results and " >>> 0" for unsigned 32-bit (or less) results for friendliness with asm.js and not use these internally to an expression where in most cases they are cancelled by other later operations in the sequence.  Especially, "((n >>> 0) >>> 1)" is redundant in the first shift, and if anything should be the other say around if this is the end of the expression as in ((n >>> 1) >>>0) to ensure that the result of the expression is unsigned.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the info! This will be fixed in the next release :+1:

About asm.js, it'd be very interesting to support it (maybe as an opt-in with a compiler flag). I actually had a look at the beginning, but the spec looked a bit confusing to me and also browser vendors seem to be focusing on WebAssembly now so I didn't put too much work on it. However, if you'd like to help (with a PR or just by enumerating the necessary additions to emit asm.js compliant code) and we've an easy way to measure the performance improvement, we could add the feature 😄

**Comment by GordonBGood** [comment]
Alfonso, most JavaScript compilers/transpilers seem to consider that just supporting a small set of asm.js features adequate, which is usually limited to just adding " | 0" at the end of expressions that produce integers of 32 bits or less, and " >>> 0" at the end of expressions that produce unsigned integers of 32 bits or less.

As you say, in the future a back end to support wasm is likely going to be more important, but that is likely several years in the future.

Issues that more affect Fable now are the following:

1. That currently Fable can't be controlled as to whether it uses "call-by-currying" or not,, using currying for non-exported functions and nested functions but not for interface method implementations or for exported functions.

1. That the output code memory model over uses JS string-tagged JS objects, which are slow.

The first is probably reasonably easily fixed with all functions being curried unless a NotCurriedAttribute is used.

To fix the second would require some major work:  support for Dynamic types is fine as tagged objects as one expects those to be slow but all other types should be implemented as (untyped when necessary) JS Array's with numeric tags for tagged unions much as BuckleScript does; this can make a difference in speed of up to about six or seven times for tight loop code using tuples, records, lists, unions, etc.

I don't recall how classes are implemented, but they should likely just tap into the way that JS classes are normally implemented:  with functions and function prototypes.

Generally in JS one gets much better performance by using a simple subset of overall JS capabilities, which is really what asm.js is all about.  To this end, one of the simplest data structures in JS which generally well optimized in JS engines is first the TypedArray, and second (when those can't be used) untyped Arrays.  Your lazy implementation is accordingly very slow and should use a function returning a function as the lazy constructor, with the Force function/Value property getter being the inner function.  Closures should be implemented with this same pattern - an outer function to capture the free variables as arguments and the inner function being the actual closure code.

Of course, Fable code is barely functional without tail call optimization at least for recursion within the same function, and this is made a little more complex when there are closures inside the recursion as is typical for the "worker/wrapper" pattern:  the closure needs to be "lifted", then arguments need to be recognized and flagged as being immutable if they don't change over the course of the closure call so that the closure can also be inlined.  And so on.  Without this, tight functional loops are always going to be extremely slow as compared to imperative code, and F# isn't the best language for imperative code due to limitations on loops - one has to write around not having break and continue at an execution speed cost.

For these reasons I have temporarily suspended using Fable and have gone back to improving the code generation of Elm, which is easier because it is a simpler language.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for all your suggestions! Yeah, there're still many optimisation opportunities for Fable but it's difficult for me to catch them all due to my limited capacity. Also, designing a compiler involves a lot of tradeoffs, and for the moment we're favouring JS code readability and compatibility with other libraries over raw performance.

There're advantages and disadvantages of using a general-purpose over and ad hoc language when compiling to JS, but the second makes things definitely much simpler. I hope you can make good contributions to Elm's code generation!

**Comment by GordonBGood** [comment]
@alfonso, although I note that you fixed the issue (I've tried version 0.7.40), your use of the extra `>>> 0' is not quite right as noted in my first response above to your enquiry.

When given code such as `int (uint32 v >>> 1)' in order to cause a zero fill right shift of an integer where v is of type int, Fable emits `~~(v >>> 0) >>> 1', where the first shift is redundant as noted in a previous post: it may as well emit `(v >>> 1) | 0' with the `| 0' to convert back to int more conventional for asm.js, and as the first `>>> 0' does nothing that the second will not do anyway (`>>>' always produces an unsigned result).

One does not require expression internal applications of `>>> 0' and `| 0` to produce uint and int, respectively, for every operator application, but it is adequate to just put them at the end of any given expression that is not bitwise:  the results of all bitwise operators are automatically int other than `>>>' which is uint, the result of all non-bitwise operator application is automatically of type number (double) unless terminated by a bitwise ooperation.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your comments as usual @GordonBGood.

At the moment, the replacements of F# operators (such as `int`, `uint32` or `>>>`) is done one by one so I guess there's room for optimizations as the one you propose by checking the AST a bit deeper: e.g., when replacing `>>>` check if the left operand is a `uint32` cast and omit it. TBH, @ncave has done most of the job with bitwise operators, so I don't know that part that well. PRs (with tests please) are very welcome! 😄 [This is the code that catches the right shifting](https://github.com/fable-compiler/Fable/blob/8e486eb43199a3ad7a20f6f0f73bf02ca9f712e4/src/fable/Fable.Compiler/Replacements.fs#L315-L318), I can also provide you more guidance through Fable source if needed.

Remember also that's possible to extend the compiler to better fit your needs using [plugins](http://fable.io/docs/plugins.html#Creating-call-replacement-plugin) if necessary. For example, a user created the [BitwiseWrap plugin](https://github.com/fable-compiler/Fable/blob/8e486eb43199a3ad7a20f6f0f73bf02ca9f712e4/src/plugins/bitwise-wrap/Fable.Plugins.BitwiseWrap.fsx) to make sure all number operations respected byte boundaries.

About asm.js, I've reading a little about this and it seems that in order to get the benefits of it you need to comply with the [full spec](http://asmjs.org/spec/latest/) which is rather restrictive. But I might be wrong, do you have any reference that JS VMs can give partial optimization by using some (but not all) of asm.js conventions=

**Comment by GordonBGood** [comment]
Hi @alfonsogarciacaro,

Part of choosing a mostly "one-man-show" new language is choosing a Benevolent Dictator For Life (BDFL) who is responsive, helpful, and accepts constructive criticism; If that were the only criteria, Fable would definitely be at the top of ones list!

In response to your repeated invitations to get involved as an active contributor to Fable, if Elm did not exist then I would likely be there, but I find I am spending most of my time trying to further the Elm cause as I mentioned previously.  I only have time to contribute to Fable with an occasional issue or issue post as these.

Yes, I am aware of and admire the Fable compiler plug-in system.  I was going to try to activate the old plug-in that does Tail Call Optimization (TCO), but see that you are working on that with version 0.7.41 so there may be no need :)

I don't think you need to worry too much about asm.js support and I don't know that much about it either; my suggestions are just based on the code that I see other JS transpilers emit that are attempting to be asm.js friendly, comments about this on other transpiler forums, and also that I hate to see double operators as in `~~` to enforce an `int` when this can be accomplished by other means ;)

As I think I implied before, my main problems with current Fable that I would have to work on if I were to get involved are as follows:
1. The compiler seems quite slow, which is understandable I suppose, as it has to go through three phases of F# -> F# AST, F# AST -> Babel AST, and Babel AST -> JS code, with at least the Babel phase commonly known to be quite slow.  Yes, I know that there are ways to trigger incremental compilation  and pre-production builds which will help, but I generally find it very slow even as compared to the current Elm compiler which isn't regarded to be particularly fast.
1. As I said before, the emitted JS code isn't very performant; I believe that this is primarily due to the compiler chain emitting many nested functions in implementing closures, currying, and so on.  Turning some of this into simple loops with advanced TCO will help, but any function construction within loops that isn't optimized away will be hard to get rid of without major compilation target changes, at least as I see it. 
Elm actually emits quite fast JS code other than for the bottleneck of requiring a call to equality/comparison checker library functions even for primitive types; as I believe that Fable preserves static type information into the code generation phase which Elm does not currently do, it may be easier to make the compiler changes required to emit the direct JS operators for primitive types in Fable than it is currently in Elm.  Or maybe Fable already does this and I missed it by leaving a function type too generic ;)

As I think I said before, I have always loved F# as a language, but in this case the full F# language may be overkill for my intended use as just a Web Application Framework and Elm is likely the more appropriate choice.
