### ISSUE TITLE
Option code generation issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#660]
Not urgent at all as there is a work-around, but here it is:
```
[<NoEquality; NoComparison>]
type Test = 
| A of Test option
| B of int

let rec f test acc =
  // these are functionally equivalent
  //let f2 (opt:Test option) acc = if (Option.isSome opt) then (f opt.Value acc) else acc // <== this works!!!
  //let f2 (opt:Test option) acc = Option.fold (fun a b -> f b a) acc opt // <== this does not generate proper code
  let f2 (opt:Test option) acc = Option.foldBack f opt acc // <== this does not generate proper code either

  match test with
  | A d -> f2 d acc
  | B i -> i::acc

[<EntryPoint>]
let main argv =
    let a = f (A (Some (B 1))) []
    printfn "%A" a
    0
```

**Comment by alfonsogarciacaro** [comment]
The `Option` module replacements were a bit flaky. I improved them, can you please try the latest version?

**Comment by ncave** [comment]
Still looks like an issue, the correct result is `[1]`, the version with foldBack gives you `[]` as result, the version with fold gives you a runtime error: `xs[Symbol.iterator] is not a function`.

**Comment by alfonsogarciacaro** [comment]
It should work, Fable's code doesn't need to do anything besides **not** passing the `babelrc: false` parameter to let Babel read options from .babelrc (unless this behaviour has changed in recent Babel versions). I guess [this comment](https://github.com/fable-compiler/Fable/blob/cb2b065faae0a8e556279fada24c50456134a110/src/fable/Fable.Client.Node/ts/options.ts#L185) is confusing, it should read "If opts.babelrc is true, **let** Babel read plugins and presets from .babelrc". The actual `babelrc` option is passed to Babel [here](https://github.com/fable-compiler/Fable/blob/cb2b065faae0a8e556279fada24c50456134a110/src/fable/Fable.Client.Node/ts/lib.ts#L220).

It's been a while since I haven't tested it but I think Babel can read the .babelrc file even if it's in a parent folder. Is it not working for you?

**Comment by ncave** [comment]
Yes, it works with most presets, thanks. Unfortunately Babili preset is crashing on FCS, too bad.
