### ISSUE TITLE
Pattern matching codegen regression

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#673]
This works as expected with the last released compiler (0.7.37), but something in the latest commits is causing a regression:
```
type ITraits = 
    abstract S : string option

type Test(s) =
  interface ITraits with
    member x.S = Some s

let mkOption (t : ITraits) =
  let o = 
    match t.S with
    | Some s -> Some s
    | None -> None
  o

[<EntryPoint>]
let main argv =
    let a = mkOption (Test "a")
    printfn "%A" a
    0
```

Previously mkOption (correctly) compiled to:
```
function mkOption(t) {
  const o = (() => {
    const matchValue = t.S;

    if (matchValue == null) {
      return null;
    } else {
      return matchValue;
    }
  })();

  return o;
}
```

Now mkOption compiles to:
```
function mkOption(t) {
  {
    let o;
    {
      const matchValue = t.S;

      if (matchValue == null) {
        o = null;
      } else {
        o = matchValue;
      }
    }
  }
  return o; // <== runtime error here as o is out of scope
}
```

**Comment by alfonsogarciacaro** [comment]
Weird, in the last commit I'm using _redundant_ blocks which should be removed by a custom Babel plugin. This is because `Fable2Babel` flow relies in some functions returning a single statement and it was a bit complicated to change it.

I wonder why the custom Babel plugin is not working for you. Are you using `.babelrc`? But even like that the custom plugins should be executed. I probably should get rid of the hack and make it possible to return multiple statements in `transformExprAndResolve`, but anyway other custom plugins are needed, like the emit macro transformer.

**Comment by ncave** [comment]
@alfonsogarciacaro So the example above works for you?

**Comment by alfonsogarciacaro** [comment]
Yes. I think maybe if you're using babili there's a problem with the order of the plugins. Anyway, I just remove the redundant blocks, can you please check with latest master?

**Comment by ncave** [comment]
@alfonsogarciacaro No, I was not using any presets.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, seems to be working now, thanks a lot!
