### ISSUE TITLE
Discussion: a better runtime representation for union types?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#682]
Currently F# union types (as other typed structures) are represented in runtime with a ES2015 class with two fields: `Case`, a string with the case name, and `Fields`, a JS array containing the data for that particular case (if any).

The `Case` and `Fields` tags were chosen for compatibility with Json.NET, but now we have the Fable.JsonConverter so this is not important any more. Also, while records and classes have more or less JS equivalents, union types have no _standard_ equivalent in JS so we can use a more optimized runtime representation without fear to break compatibility with other JS libs.

Union types will probably still be implemented as ES2015 classes as this is the easiest way to implement other methods and do type testing, but we may have some room for improvements in the way the case and other data are stored in the class. For example:

- Use an integer instead of a string to represent the case (the case name would still be accessible through reflection).
- Put the case in the same array as the other data.

A union type would then be implemented more or less like this (simplified version):

```fsharp
type MyUnion = A | B of int * string

let a = A
let b = B(5, "foo")
```

```js
class MyUnion {
    constructor(data) {
        this.data = data;
    }
}

var a = new MyUnion([0])
var b = new MyUnion([1, 5, "foo"])
```

The advantage of the current approach (using a string for the case name) is the JS code is more readable and we can more easily identify the cases when debugging. The advantage of using an integer would probably be saving some bytes in the generated JS code and letting the VM optimize better the memory storage of union types (I'm not an expert of JS VM optimization, so I may be wrong about this).

It'd be great if you could vote for this proposal with :+1: or :-1:, or leave your comments if you've another suggestion.

Thanks a lot for your collaboration in advance!

**Comment by davidtme** [comment]
It would be interesting to see the speed difference between the current unions vs new class style. Either way I like the strings for debugging.

**Comment by panesofglass** [comment]
I am generating string literals for unions with no fields in any case and interfaces with a tag field with the case name in https://github.com/Tachyus/gluon. This works for TypeScript's tagged unions. We had classes previously, but the new approach is much simpler for us.

**Comment by Pauan** [comment]
I would like to point out that JS VMs optimize arrays differently from objects. I haven't tested it, but it's possible that using an array will be slower, because the elements of the array are different types.

Instead, I think it might be better if this:

```fsharp
type MyUnion = A | B of int * string

let a = A
let b = B(5, "foo")
```

Was compiled into this:

```js
class MyUnion {
    constructor(a, b, c) {
        this.a = a | 0;
        this.b = b;
        this.c = c;
    }
}

var a = new MyUnion(0, null, null)
var b = new MyUnion(1, 5, "foo")
```

This might optimize better, because it can take advantage of hidden classes, and because the `| 0` causes the VMs to treat the case as an integer rather than a floating point.

Of course I might be wrong, and there might be an even more efficient way of compiling it, so I'm open to alternatives.

I think we should run extensive benchmarks on big real applications (not microbenchmarks!) to determine which compilation strategy is the best.

**Comment by Pauan** [comment]
I would also like to point out that Chrome has a special API you can use to [provide custom printing in the developer console](https://github.com/andrewdavey/immutable-devtools).

We can use this so that `new MyUnion(0, null, null)` would get printed as `A` and `new MyUnion(1, 5, "foo")` would get printed as `B(5, "foo")`

This only works in Chrome, but it's still really useful.

**Comment by ncave** [comment]
String labels are convenient for debugging, but a recent change in the generation for pattern matching is bunching them at the beginning in a single statement converting them to integers and then switching on those, which makes them less useful.

A simple micro-bench for both representations should be able to answer which one is faster and how much.

Hopefully whatever the new representation is should retain the ability to be properly [deserialized](https://github.com/fable-compiler/Fable/blob/narumi/src/netcore/Fable.Client.Browser/demo/repl.js#L330-L331) in JS.

**Comment by Pauan** [comment]
@ncave Unfortunately, [microbenchmarks aren't reliable for predicting JS VM performance](https://www.youtube.com/watch?v=g0ek4vV7nEA).

Because modern JS VMs are very good, and because they use complex heuristics to determine optimizations, you can get **very** different results in a microbenchmark compared to a real app.

It's very hard to write good microbenchmarks. Running benchmarks on big real applications is much more reliable.

**Comment by ncave** [comment]
Sure, we do have a large code base with lots of unions over [here ](https://github.com/ncave/FSharp.Compiler.Service/tree/fable/src/fsharp/Fable.FCS) that can be benchmarked.

**Comment by Pauan** [comment]
@ncave Great, I think that's a good place to start.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your insightful comments, @Pauan! I think you're right and the way to go is implementing one JS field per data field in the union (using the case in the union with maximum number of data fields as reference) plus the case tag (turned into an integer). I looks like we have a winner here 😄 

@ncave: The case names can be accessed using the `Symbol.reflection` method in the object prototype, so it will still be possible to deserialize the object in runtime.

Following your also very useful comments in the Gitter channel about how other projects compile union types to JS:

- Purescript: Using a specific class for each union case is a interesting idea and it probably helps the optimization, but I'd rather keep a single JS class for unions as in F# they can have methods/properties/interfaces as a normal class, and these would have to be duplicated in each case definition. 

- Bucklescript: erasing empty union constructors to an integer is also a very interesting idea, but probably it's difficult to do it in Fable as we're providing some reflection support in runtime, so instances of a union type must be proper instances of the type in JS as well..

**Comment by valery-vitko** [comment]
So, I guess interop code with Fable from plain JavaScript would change from ``du.Case === 'CaseName'`` to something like ``du.Case === 0``?

**Comment by alfonsogarciacaro** [comment]
@valery-vitko Yeah, it will actually be `du.tag === 0`. You will still be able to get the case name in runtime doing something like: `du[FableSymbol.reflection]().cases[du.tag][0]`.

**Comment by Pauan** [comment]
@alfonsogarciacaro I don't really like the idea of accessing the fields (like `tag`, `a`, `b`, `c`, etc.) directly from JavaScript, since it prevents us from changing the implementation later.

Is there any way we can keep the JS reflection, but without requiring us to hardcode field names and integers in JS?

**Comment by alfonsogarciacaro** [comment]
@Pauan At the moment I'm doing something like [this](https://github.com/fable-compiler/Fable/blob/4579c52c499eb6d545c333fb3e63b29af539aa69/src/fable/Fable.Core/ts/Util.ts#L256-L273), but I agree with you. That should be abstracted to a reflection method so it's easy to change the implementation later if necessary without breaking client code.

**Comment by Pauan** [comment]
@alfonsogarciacaro I'm glad to hear that you've considered it. :+1:

I don't mind hard-coding implementation details in `fable-core`, I meant in ordinary user code.

Also, that function's performance can potentially be improved if each tagged union contains a `size` property which is the number of fields which are being used, something like this:

```
class MyUnion {
    constructor(tag, size, a, b) {
        this.tag = tag | 0;
        this.size = size | 0;
        this.a = a;
        this.b = b;
    }
}

var a = new MyUnion(0, 0, null, null)
var b = new MyUnion(1, 2, 5, "foo")
```

This does increase the memory usage, but it may be worth it. We should benchmark to be sure.
