### ISSUE TITLE
Adding byref parameter support

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#694]
Adding byref parameter support will enable some performance optimizations where needed.
Feature request, contributions welcome.

**Comment by alfonsogarciacaro** [comment]
That's tricky because afaik you cannot pass byref parameters in JS. I guess the way to support it would be to wrap the function so it returns the the parameter values, but this wouldn't provide extra performance.

**Comment by ncave** [comment]
I agree, probably not much of a performance gain, if any. Struct tuples FTW instead.

**Comment by alfonsogarciacaro** [comment]
I've thought about this a couple of times, but I'm still unsure about what's the best way to emulate passing value types by reference in JS :

I'm closing it for now, will revisit.

**Comment by ncave** [comment]
@alfonsogarciacaro

Since this is tagged with "Revisit", what is your opinion on these two options for supporting `byref/inref/outref` parameters :
- Convert all `mutable` variables and `byref/inref/outref` to `FSharpRef`. A bit heavy-handed, but simple to implement and reason about. Should be able to properly handle harder cases like mutable fields etc. Run-time backwards compatibility with older generated code might be an issue (but that probably already is an issue with Fable 2 vs 3), so perhaps enable behind a flag.
- Analyse usage of `mutable` variables and only declare as `FSharpRef` the ones that are later passed by reference (`AddressOf`), and also all `byref/inref/outref`. A bit more involving to handle harder cases, and creates two types of mutable variables, so could be either more compatible, or could be even less compatible with existing generated code. Perhaps enable behind a flag too.

Personally I like option 1 for its simplicity, but I may be missing some context, or oversimplifying things, feel free to shoot it down.
Definitely the performance impact on large real life projects needs to be evaluated so people can make an informed decision about enabling that compiler flag.

**Comment by ncave** [comment]
@alfonsogarciacaro I see mutable vars are already implemented as closures (createAtom), so is it just a matter of extending that to `byref/inref/outref` and mutable fields, and implementing `AddressOf/AddressSet` to properly handle the closure function?

**Comment by alfonsogarciacaro** [comment]
Hi @ncave! Sorry I don't remember well but I think I gave this a try at some point by converting variables to `FSharpRef` when passed as byref arguments and gave up (probably too quickly) because it was difficult to identify in the AST when we were accessing such refs (don't remember if it was difficult to just check for `byref` type in BasicPatterns.Value for some reason). It'd be great if you could give it another try, probably you'll come up with a better solution.

About changing all mutable values to refs, I'm not very convinced. I use mutable values quite often and I like the simplicity of the generated code. Also by fields you mean record or interface fields? Many fields in JS bindings are marked as mutable, so there will be interop issues if Fable assumes the underlying field is a record. 

No special reason about the way `createAtom` is implemented, it'd be nice to replace it with the current `FSharpRef` for consistency. The nice thing about `FSharpRef` vs something like one-tuple arrays is we can use the getter/setter to either access a value either internally stored in the ref or declared externally. As in the code generated to translate `MutableMap.TryFindIndex`:

```js
function Dictionary__TryFindIndex_2B595(this$, k) {
    const h = this$.comparer.GetHashCode(k) | 0;
    let matchValue;
    let outArg = null;
    matchValue = [tryGetValue(this$.hashMap, h, new FSharpRef(() => outArg, (v) => {
        outArg = v;
    })), outArg];
    if (matchValue[0]) {
        return [true, h, matchValue[1].findIndex((pair) => this$.comparer.Equals(k, pair[0]))];
    }
    else {
        return [false, h, -1];
    }
}
```

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, I'll give it a shot.
