### ISSUE TITLE
Async.RunSynchronously issue (narumi)

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#712]
This compiles:
```
async { return 42 }
|> Async.RunSynchronously
```
but throws this:
```
C:\Projects\fable-test\src\fable-test\out\project.js:8
  return (0, _Async.runSynchronously)(arg00);
                                     ^
TypeError: (0 , _Async.runSynchronously) is not a function
```

**Comment by alfonsogarciacaro** [comment]
Yeah, this is because the Replacements module makes two passes, in the first one it matches per method individually but in the second one it matches the whole module, and for some of them (Async, Seq...) it just assumes the method can be found in fable-core. At one point I kept a list of the implemented functions in fable-core to avoid cases like the one you point out. But even if the list was automatically generated it was a bit cumbersome to keep it up-to-date with the contributions and I removed it.

I'm not sure what's the best way to fix this. Maybe we should back to the list improving the automatic generation? Or do you have any other suggestion?

**Comment by ncave** [comment]
@alfonsogarciacaro How are the tests that use Async.RunSynchronously passing?

**Comment by alfonsogarciacaro** [comment]
That's a dirty trick done by the NUnit plugin ;) It's explained at the end of [the tutorial](http://fable.io/samples/nunit/index.html) and you can also see in [the code](https://github.com/fable-compiler/Fable/blob/eb6d573664bfb6e4acf89a503d8059a95d2c307e/src/plugins/nunit/Fable.Plugins.NUnit.fs#L48-L56). Although I'd like to deprecate the plugin in the next release and use shared APIs instead for testing (Expecto and Mocha).

**Comment by ncave** [comment]
@alfonsogarciacaro Can this dirty transformation be moved from the NUnit plugin into the main?

**Comment by alfonsogarciacaro** [comment]
@ncave I'm afraid that wouldn't be possible. This relies in the possibility of adding a `done` argument to mocha test functions that you can call to signal the end of an async test. The trick is just to wrap the test with `Async.StartWithContinuations` and pass it the `done` continuation, but the test is not run synchronously. I just chose that pattern so it could be reproduced with NUnit/XUnit in .NET.

The funny thing is that `Async` in JS actually starts synchronously (because you cannot spawn thread in JS... yet), but as soon as an async API is called (timeout, a promise...) you need to put the continuation code in a callback.

**Comment by ncave** [comment]
@alfonsogarciacaro What about just implementing it as ES2017 await on a promise?

**Comment by ncave** [comment]
Closing this as it's already documented as unsupported, as you pointed out.
