### ISSUE TITLE
COSMETICS: Reuse same variable if they don't clash in scope

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#714]
I'm compiling the Sudokusolver https://gist.github.com/alfonsogarciacaro/e9cfd5fbf18937cd132b4781ffc85ece with Fable v1.0.0-narumi, FCS v10.0.1, Babel v6.22.1 in the browser

![image](https://cloud.githubusercontent.com/assets/57396/22983107/6042baa2-f3a1-11e6-8c0d-f5dcd4f90054.png)

I think `a_1` should be named `a`, right?

**Comment by alfonsogarciacaro** [comment]
Until very recently Fable was only creating unique names when a variable created a new scope in F#. However due to the recent changes to avoid generating too many closures, it's possible that variables in different scopes in F# get into the same scope in JS (e.g., when pattern matching cases become switch cases). This creates a cryptic error in Babel (#483 #700) so the safest way is generating a unique name for every identifier within the same method.
