### ISSUE TITLE
COSMETICS: Don't introduce lambda if it's not needed

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#715]
I'm compiling the Sudokusolver https://gist.github.com/alfonsogarciacaro/e9cfd5fbf18937cd132b4781ffc85ece with Fable v1.0.0-narumi, FCS v10.0.1, Babel v6.22.1 in the browser

![image](https://cloud.githubusercontent.com/assets/57396/22983242/d1197a22-f3a1-11e6-93d7-58936ccbb935.png)

I think it could be 

    return map(Int32Array.from, list);

**Comment by alfonsogarciacaro** [comment]
The F# compiler always wraps in a lambda method calls used as values. In theory, these are not needed in JS but I decided to keep them because sometimes they're actually needed. For example:

- If you pass an object method this way, JS doesn't capture the `this` context. That's the reason, for example, why they have to use `bind` [here](https://github.com/tastejs/todomvc/blob/feb8465b4e7f2631195c64ded82f45aa7a6cb982/examples/react/js/app.jsx#L29-L33). It works if you use an ES2015 arrow function which does capture `this`.
- Some JS APIs don't work like this. Actually that very sample above won't work. You can try the following code in Chrome's console:

```js
var ar = [[1,2],[3,4],[5,6]]
ar.map(Int32Array.from) // This throws an exception
ar.map(x => Int32Array.from(x)) // This works
```
