### ISSUE TITLE
Missing Exception when casting bad int

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#725]
## Explanations 
When casting a malformated string into an integer we don't get an exception. [REPL](https://goo.gl/lM8m2c)

When executing the same code in Fsharp interactive I got System.FormatException: Le format de la chaîne d'entrée est incorrect.

## Code to reproduce

```fsharp
printfn "%i" (int "5")
printfn "%i" (int "maxime")
```

@alfonsogarciacaro anwser on gitter:

> @MangelMaxime Yeah, we're just using JS native Number.parseInt, but we do make a isNan check when using System.Int32.TryCheck. It makes sense to follow F# semantics and throw an error if the parsing is not sucessful, can you please open an issue?

**Comment by Zaid-Ajaj** [comment]
it seems that supporting correct parsing and correct formatting for int, double, decimal, DateTime, etc. that there should also be support for `System.Globalization` specifically for `CultureInfo`. As CultureInfo holds data that contain [NumberFormatInfo](https://msdn.microsoft.com/en-us/library/system.globalization.numberformatinfo(v=vs.110).aspx) and [DateTimeFormatInfo](https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo(v=vs.110).aspx)

I was thinking on how to support this in fable, because this is a lot of data to be included in a bundle for every possible culture info. Maybe we can start with pre-define a "most commonly used" data in json files and have a fable option to tell fable which CultureInfo the user wants to be supported (to be included in the bundle) in his/her app? Maybe support [InvariantCulture](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.invariantculture(v=vs.110).aspx) as the bare minimum for parsing and formatting?

Related to #693

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj Supporting CultureInfo would be nice, but I think it requires quite an amount of work and other considerations like, as you say, how to decide what goes in the bundle. Right now, Fable doesn't include any parser it relies on native JS functions to parse numbers and dates.

I don't think I could do this myself as I already have many other tasks pending, if there's interest for this feature it should be added by a contributor.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Could you please check if #831 has fixed this after a new Fable 1.0 version is published (I'll do it today)? Thx in advance!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro  Sure :)
Just ping me on gitter when ready :)

**Comment by Pauan** [comment]
I just tested it with `1.0.0-narumi-910` and it doesn't throw an exception:

```js
String.fsFormat("%i")(x => {
    console.log(x);
})(Number.parseInt("5"));

String.fsFormat("%i")(x => {
    console.log(x);
})(Number.parseInt("maxime"));
```

It seems that it [still calls `parseInt` and `parseFloat`](https://github.com/fable-compiler/Fable/blob/c67178c044e8049492844483e91ef1d1c3be7a85/src/dotnet/Fable.Compiler/Replacements.fs#L295) at some spots.

There are some [other spots](https://github.com/fable-compiler/Fable/blob/c67178c044e8049492844483e91ef1d1c3be7a85/src/typescript/fable-core/Long.ts#L948) that might also need changing.

**Comment by alfonsogarciacaro** [comment]
You're right @Pauan, we need to make the `toInt` and `toFloat` functions in Replacements call the new parser method. Actually I just touched them today, I should have done it 😅 

The code for Long.ts was taken from another project (I don't remember which one at the moment) so we were refraining from modifying it in case we had to update it from the source. But there is a good reason to touch it now ;)

**Comment by alfonsogarciacaro** [comment]
@Pauan Do you want to make a follow-up PR to fix the remaining parseInt/parseFloat calls?

**Comment by Pauan** [comment]
@alfonsogarciacaro Sure, I'll do that.

In `Replacements.fs`, how do I make it call an F# method? For example, I want `int "foo"` to get translated into the F# code `System.Int32.Parse("foo")` (which then gets translated further into JavaScript), so that way it can reuse the existing parsing code.

**Comment by alfonsogarciacaro** [comment]
Awesome @Pauan, thank you! Unfortunately, there's no way at the moment for the Replacements module to call itself recursively 😕 In these cases, it's necessary to refactor the code you want to reuse ([here it is for `System.Int32.Parse("foo")`](https://github.com/fable-compiler/Fable/blob/84fc0361d0d5c0b9b9eacba3915b86c711b26ccd/src/dotnet/Fable.Compiler/Replacements.fs#L1036-L1038)) into a separate function and then call it from the new site.
