### ISSUE TITLE
Comments in the generated JavaScript

### ISSUE THREAD

**Issue by davidpodhola** [fable-compiler/Fable#752]
How to deal with comments? In our workflow one team of developers writes in F#, the JavaScript produced by Fable is then integrated into a bigger solution.

The JavaScript team would benefit from comments in the code produced by Fable. At least at a function description level. Right I am about to follow how the docs is produced e.g. in [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold).

Any ideas? Thanks!

**Comment by alfonsogarciacaro** [comment]
Hmm, I haven't looked much into this but it should be possible. FCS is providing access to XmlDocs either in memory or as a signature to look them up in an XML file. Comments are not included in [Babel AST specs](https://github.com/babel/babylon/blob/master/ast/spec.md) but they do appear in [the AST explorer](http://astexplorer.net/) so they should be available. To add a comments in function declarations at least I guess you would have to:

1. Add a comments field to the `MemberDeclaration` in [Fable AST](https://github.com/fable-compiler/Fable/blob/a9653e272848063383a48a16634b1039962f05aa/src/fable/Fable.Core/AST/AST.Fable.fs#L116) (probably it should be an option type).
2. Add the `CommentBlock` and/or `CommentLine` nodes to [Babel AST](https://github.com/fable-compiler/Fable/blob/a9653e272848063383a48a16634b1039962f05aa/src/fable/Fable.Core/AST/AST.Babel.fs) and a `leadingComments` field to [FunctionDeclaration](https://github.com/fable-compiler/Fable/blob/a9653e272848063383a48a16634b1039962f05aa/src/fable/Fable.Core/AST/AST.Babel.fs#L280) as can be seen in the AST explorer.
3. Get the `XmlDoc` field from `meth` and add them to the declaration when it's [parsed by Fable](https://github.com/fable-compiler/Fable/blob/a9653e272848063383a48a16634b1039962f05aa/src/fable/Fable.Compiler/FSharp2Fable.fs#L990).
4. Add the comments when Fable [emits a Babel FunctionDeclaration](https://github.com/fable-compiler/Fable/blob/a9653e272848063383a48a16634b1039962f05aa/src/fable/Fable.Compiler/Fable2Babel.fs#L969) (this may a bit tricky because Fable first creates a function expression and then upcasts it to a function declaration).
5. Probably also add a compiler option to make outputting comments optional.

**Comment by davidpodhola** [comment]
On a second thought this is probably not what one would want or need.

We sometimes use comments in our F# code (I think the code should not need too much comments, but sometimes it helps to understand WHY it is done the way it is), but those are completely different from comments we would want the JavaScript developers to read; those are probably more or less information about interface (WHAT this function can be used for) and documentation should work here.

**Comment by davidpodhola** [comment]
So far we are here.

![fable_js_comments](https://cloud.githubusercontent.com/assets/436605/26079788/4f727dde-39c4-11e7-8518-8398cb9213c5.png)
