### ISSUE TITLE
[discussion] Idea of VSCode pugin to run scripts in Chrome

### ISSUE THREAD

**Issue by maestrow** [fable-compiler/Fable#783]
I suggest in this topic to discuss the idea of ​​a VSCode plugin, which allows you to run scripts in Chrome. From a users's perspective this should look like working with fsharp interactive in VSCode. So you can select a code snippet and press the key combination. Next, the selected fragment will be compiled into javascript and executed in an open browser window. Hereby we can get a convenient F#-scratchpad for frontend development.

I suggest here to discuss the concept, tools and other issues on the development of this plug-in.

My theses and questions:
1. To interact with Chrome, I suggest using [Chrome Debugging Protocol](https://developer.chrome.com/devtools/docs/debugger-protocol) and launching the browser window using the key combination from VSCode: `chrome.exe --remote-Debugging-port=9222`
2. How to get javascript from fs-snippet, that is only a part of the program? Suppose we have a program:
```
Let add a b = a + b
console.log (add 1 2)
```
And first we decide to use and send to chrome the first line, and then the second. It is impossible to compile separately only the second line, but we must somehow get a javascript representation of only second line. How?

3. There is a fable-server solution that allows you to reload browser after saving F# source (https://github.com/fable-compiler/Fable/tree/narumi/src/templates/simple/Content). The only difference of this solution is that it does not allow you to execute separate pieces of code, but compiles whole program and reload whole page in browser. But I felt that it is worth mentioning here this solution

**Comment by Pauan** [comment]
Can we use something like PhantomJS for this rather than having a running instance of Chrome?

**Comment by maestrow** [comment]
The idea is go get _visible_ results in browser window. I.e. to add some DOM elements, or to transform existing and immediately see changes. PhantomJS doesn't have an interface, instread.

**Comment by alfonsogarciacaro** [comment]
Related #727 

I think this is a very interesting idea. However as you comment @maestrow we already a similar workflow with webpack dev server and hot reloading, the only difference being that you send the whole program instead of pieces of code, but thanks to the watch mode, this shouldn't be very noticeable to users.

Although it's a bit stopped now as we're focusing in polishing Fable 1.0, the idea is to improve the Fable REPL so it has some IDE features (like autocompletion), can interact with DOM elements and works more like F# interactive (so it can send lines of code incrementally as you suggest). Maybe we can focus on that, as it would work in any browser with zero installation, instead of putting work on something that would only work with a specific editor and browser. What do you think?

**Comment by maestrow** [comment]
@alfonsogarciacaro, thanks for pointing to [Fable REPL](http://fable.io/repl). The idea of Fable REPL as an incremental compiling service is very nice. This will allow to build any GUI-Repl tool (either in browser, or in the form of IDE-plugins). Can you give a link to Fable REPL repository?

**Comment by alfonsogarciacaro** [comment]
Fable REPL it's here in this repo, although the current way of building it is a bit hacky (it depends on a special fork of FCS being installed locally), we need to clean it up. If you want, you can check [this folder](https://github.com/fable-compiler/Fable/tree/87d4177cf90c4ff2a08673662fad2acd5d502123/src/dotnet/Fable.Client.Browser/demo) and https://github.com/fsharp/FSharp.Compiler.Service/pull/688. And also all PRs by @ncave ;)
