### ISSUE TITLE
Prevent stack overflows

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#787]
Related to https://github.com/Microsoft/visualfsharp/issues/2682#issuecomment-290769571

The `transformExpr` functions in FSharp2Fable and Fable2Babel are called recursively many times, we should prevent to have deep stacks with these. Two measures we can take: 

- Make those functions are slim as possible, refactoring most of the code to helpers.
- Trick from Paket:

```
Create a data type that contains all parameters of the recursive call
Create a System.Collections.Generic.stack
Put your first call into that stack
Use a while not stack.isempty do
Pop from stack
Execute that bit of work
For every original recursive call put on element on the stack
```

**Comment by alfonsogarciacaro** [comment]
Summoning @cloudRoutine to continue here the discussion in https://github.com/Microsoft/visualfsharp/issues/2682#issuecomment-290769571

I'm not sure if that function can be made tail recursive, there are many places where the function calls itself in a non-tail position. For example, in a let binding, I have to transform the bound value and then attach it to the context that's passed to the binding body. Similar with application arguments, etc.

As written above, probably the first step is to refactor the function to make it slimmer. I can do that because it's a bit tedious work. But if for some reason you like you can go ahead, of course ;)

After that I'm curious if we can apply @forki's trick :)

**Comment by alfonsogarciacaro** [comment]
FYI, I just merged narumi into master to prevent confusions.

**Comment by cloudRoutine** [comment]
We had a similar problem in Paket in the past where [evaluating the versions to use during package resolution](https://github.com/fsprojects/Paket/blob/0974e2c9a12ebbd64b2480160b7166742aa2098c/src/Paket.Core/PackageResolver.fs#L260-L552) was causing stack overflows due to the [two inner while loops that made recursive calls](https://github.com/fsprojects/Paket/blob/0974e2c9a12ebbd64b2480160b7166742aa2098c/src/Paket.Core/PackageResolver.fs#L504-L552), which worked fine for the amount of packages people were checking before netcore, but once netcore levels of packages needed to be checked all the time paket was dying with stack overflow exceptions constantly.

The way I fixed it was to [break out all of the mutable bools that were being used to keep track of the status and define the branch of execution the tail-rec function needed to go down with a DU that stored the data the function needed to keep processing the package restrictions](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageResolver.fs#L601-L625). Refactoring out a lot of the internal functions helped so that it was easy to see what the minimal amount of logic that needed be addressed in a tail-rec conversion.  In the end we had a [tail recursive resolution function](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageResolver.fs#L652-L810) and the stack overflows were gone.

I think a similar approach will work here.

**Comment by cloudRoutine** [comment]
I'll do the refactoring myself, I don't love doing it but it'll help me get a better understanding of the code I'm working with. I'll get started on it tonight, but it'll probably take a while for me to finish it. Fixing the resolution function for paket was a huge pain in the ass.

**Comment by alfonsogarciacaro** [comment]
That's very nice @cloudRoutine, thanks! Please check with me if you have any question. Don't worry about the timing, at the moment this is only affecting a few rare cases: actually, when compiling the `transformExpr` function itself to JS with Fable and with a specific stack configuration. So fortunately it's not very urgent.

**Comment by alfonsogarciacaro** [comment]
Sorry @cloudRoutine, just a quick note to say that the code itself must be compilable by Fable (in order to support the amazing REPL created by @ncave) so you need to be careful not to add extra dependencies or use classes from the BCL not yet supported by Fable.

**Comment by cloudRoutine** [comment]
Anything additional I need will be defined in that file, besides that FSharp.Core has everything I need.

**Comment by realvictorprm** [comment]
@cloudroutine how is it going :smiley: ?

**Comment by alfonsogarciacaro** [comment]
@realvictorprm Are you having problems with this? At the moment it's a bit stopped because we have to streamline the REPL build so this can be better tested, but I'm currently busy with other issues so I haven't finished it yet.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your help! Let's continue the discussion in the open PR #795

**Comment by realvictorprm** [comment]
@alfonsogarciacaro Now I'm having problem with this hahaha :smile:
Maybe I got things wrong but so far I understood doing the same approach as in the [mario example ](https://github.com/fable-compiler/Fable/blob/master/samples/browser/mario/src/Main.fs#L25-L31) should work.

**Comment by alfonsogarciacaro** [comment]
What's the problem you're having, @realvictorprm? Are you getting a Stack Overflow exception? If so, when compiling with Fable or in the JS runtime?
