### ISSUE TITLE
REPL issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#807]
- The REPL seems to be broken in master.
- FCS-fable parsing works, as you can see from running the [testapp](https://github.com/fable-compiler/Fable/tree/master/src/dotnet/Fable.Client.Browser/testapp).
- The REPL was actually working fine [fairly recently](https://github.com/fable-compiler/Fable/pull/782).

**Comment by ncave** [comment]
@alfonsogarciacaro This is [fixed](https://github.com/ncave/FSharp.Compiler.Service/commit/a35a4fd7b613aff9cf341592b27c33d5f553edba), please get latest FCS-Fable.
Both REPL and testapp work on all samples.

**Comment by ncave** [comment]
@alfonsogarciacaro How do I build a fable-core version that can be referenced correctly from the REPL compiled JS, currently first reference is to import from, say, "fable-core/String" but within it the import is from say "./Util" which does not resolve properly.

**Comment by alfonsogarciacaro** [comment]
@ncave I didn't create any special build of fable-core for the REPL but I actually had to do some require.js trickery [here](https://github.com/fable-compiler/Fable/blob/7287cd7d053dc5a08299cdd5290248ced5c02b33/src/dotnet/Fable.Client.Browser/demo/repl.js#L217-L219) and [here](https://github.com/fable-compiler/Fable/blob/7287cd7d053dc5a08299cdd5290248ced5c02b33/src/dotnet/Fable.Client.Browser/demo/repl.html#L64-L68) to load the files correctly.

Another solution I've been thinking of recently is distribute fable-core also as a bundle. We'll just have to create an entry file for that like:

```js
import * as String from "./String"
import * as Seq from "./Seq"
...

export { String, Seq, ... }
```

Then we should add a compiler option to make fable-core references using a global variable (e.g. `fableCore.String.fsFormat(...)`) instead of JS imports. That should be checked [here](https://github.com/fable-compiler/Fable/blob/7287cd7d053dc5a08299cdd5290248ced5c02b33/src/dotnet/Fable.Compiler/Fable2Babel.fs#L1142-L1147). That would make it much easier to reference fable-core methods from code compiled in the REPL, and also make it easier to share the core lib between the code generated by the REPL and the F# compiler itself.

**Comment by Pauan** [comment]
@alfonsogarciacaro Just as an FYI, [Rollup can correctly remove dead code if you are using that coding pattern](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGJhciUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGZm9vJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhiYXIuYSklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGJhciUyMGZyb20lMjAlNUMlMjIuJTJGYmFyJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBiYXIlMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMHZhciUyMGElMjAlM0QlMjAxJTNCJTVDbmV4cG9ydCUyMHZhciUyMGIlMjAlM0QlMjAyJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) but Webpack probably can't. Then again, Webpack's dead code elimination is pretty bad in general.

**Comment by ncave** [comment]
@alfonsogarciacaro Sorry, I was just being too slow in figuring out obvious stuff, I could have just looked in the build.fsx, you know. The fable-core just needed to be compiled with amd modules and put in the server root to be referenced by the REPL for the samples to work properly. The REPL is fully functional as is, let me know if I can help with the publishing.

**Comment by alfonsogarciacaro** [comment]
@ncave Ah, sorry! I forgot to tell you that 😅 The previous times I did the publishing manually, just copy&pasting the REPL files into the fable-compiler.github.io repo and committing. We should probably automate that, but if you want to publish I just gave you write rights to the fable-compiler.github.io repo :+1:

```
repl/
repl_samples/
repl.html
repl.js
```

It'd be also be very nice if your fork could be added as a Github dependency so other contributors can run the REPL build target without needed anything else (for that we also need to add the metadata binaries to this repo).
