### ISSUE TITLE
Add debugger fn to Fable.Import.JS?

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable#814]
Trying to setup debug points with chrome is often flaky for me when doing it from the fs files (breakpoints being set on wrong lines, not being able to set breakpoints on lines I'm expecting) and doing it in the JS is cumbersome so I'll often find myself using a fn like below to force the debugger to hit where I want it to reliably.

```fs
[<Emit("debugger;")>]
let debugger () : unit = jsNative
```

Thoughts on adding this in `Fable.Import.JS`?

**Comment by alfonsogarciacaro** [comment]
Yeah, of course. I guess it was not in the Typescript declaration because `debugger` is a JS keyword. Could you please send a PR?

Pro-tip: Fable is compatible with the F# `assert` keyword, so I often use `assert false` with the same effect. Just remember you must pass the `DEBUG` define constant to Fable compilation to prevent `assert` statements from being ignored. This is also a benefit over using JS debugger directly, as `assert` will be automatically removed in production mode ([`debugger` prevents optimizations by JS compilers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax)).
