### ISSUE TITLE
Extend BCL support

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#826]
The current Replacements module is good to have more control over the more used classes from the BCL/FSharp.Core and inline code when possible to improve performance. However, this model probably won't escalate very well if we want to extend BCL support.

There are other projects that try to port the BCL to JS so we could ~~steal~~take inspiration from them and bridge the code so it can be used by Fable. Something similar as what was done with the `int64` type. We should still keep the module approach so users only need to bundle what they actually use in their apps.

Any ideas? cc @ncave @7sharp9

**Comment by 7sharp9** [comment]
Making fable projects use a subset like pcl 259 or similar would make it
clear what parts of the bcl do exist.  My main gripe is I don't know what
is missing up front.  Reducing scope like that might be a good start too.

On 18 Apr 2017 8:45 am, "Alfonso Garcia-Caro" <notifications@github.com>
wrote:

The current Replacements module is good to have more control over the more
used classes from the BCL/FSharp.Core and inline code when possible to
improve performance. However, this model probably won't escalate very well
if we want to extend BCL support.

There are other projects that try to port the BCL to JS so we could stealtake
inspiration from them and bridge the code so it can be used by Fable.
Something similar as what was done with the int64 type. We should still
keep the module approach so users only need to bundle what they actually
use in their apps.

Any ideas? cc @ncave <https://github.com/ncave> @7sharp9
<https://github.com/7sharp9>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/Fable/issues/826>, or mute the thread

**Comment by alfonsogarciacaro** [comment]
I guess at this point it would make more sense to target .NET Standard, but I think we're still far from the lowest profile. It was discussed whether we should use a custom mscorlib.dll and FSharp.Core.dll but at the end we decided it was better to aim for more BCL support rather than limiting ourselves (see https://github.com/fsharp/FSharp.Compiler.Service/pull/688#issuecomment-279754493).

I've been also thinking to add F# code to fable-core and compile it in the build process the same way as we're doing with Typescript.

About giving the user a better hint of what's supported by Fable, hopefully this will help: https://github.com/ionide/ionide-vscode-fsharp/issues/412

**Comment by 7sharp9** [comment]
Some of the pain comes from acclimatising to the fact your not really on
.net anymore.  File access would be via node bits.  Maybe some analysis and
warnings on opening certain parts would be good.

On 18 Apr 2017 11:11 am, "Alfonso Garcia-Caro" <notifications@github.com>
wrote:

I guess at this point it would make more sense to target .NET Standard, but
I think we're still far from the lowest profile. It was discussed whether
we should use a custom mscorlib.dll and FSharp.Core.dll but at the end we
decided it was better to aim for more BCL support rather than limiting
ourselves (see fsharp/FSharp.Compiler.Service#688 (comment)
<https://github.com/fsharp/FSharp.Compiler.Service/pull/688#issuecomment-279754493>
).

I've been also thinking to add F# code to fable-core and compile it in the
build process the same way as we're doing with Typescript.

About giving the user a better hint of what's supported by Fable, hopefully
this will help: ionide/ionide-vscode-fsharp#412
<https://github.com/ionide/ionide-vscode-fsharp/issues/412>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/Fable/issues/826#issuecomment-294763082>,
or mute the thread

**Comment by ncave** [comment]
@alfonsogarciacaro IMO basic functionality should be build in, and additional big BCL functionality can be added through plugins. Yes, bootstrapping some of fable-core to F# makes sense, as it is so much easier to add [adapters](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/fcs-fable/adapters.fs) for stuff.
