### ISSUE TITLE
Multiple namespace declarations gives an error

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#869]
### Description

Multiple namespace declarations gives an error: `error FABLE: Public types, modules or functions with same name at same level are not supported: SMC`

### Repro code

http://fable.io/repl.html#?astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=namespace%20Test.A.B%0Atype%20Test%20%3D%20%7B%0A%20%20Int%3A%20int%0A%7D%0Anamespace%20Test.A.B%0Atype%20Test2%20%3D%20%7B%0A%20%20String%3A%20string%0A%7D

### Expected and actual results

This is valid F# so it should compile

### Related information 

* fable-compiler version: 
* fable-core version: 1.0.0-narumi-910
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
The error message seems to be wrong, it should say explicitly that multiple namespaces are not supported.

This is tricky, in theory it should be possible to support multiple namespaces, but it's a pattern Fable apps shouldn't follow as it prevents the compiler from removing the namespace (see [the docs](http://fable.io/docs/compiling.html#Modules)) and, in order to avoid name clashes, it must nest modules multiple levels which prevents all the benefits of ES2015 modules, like tree shaking, exposing the public methods to external JS code, etc.

**Comment by alfonsogarciacaro** [comment]
As you already found a workaround, I'm closing this. Please feel free to reopen if you still need support for multiple namespaces in the same file.
