### ISSUE TITLE
[ERROR] This expression was expected to have type 'obj' but here has type 'obj -> obj'

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#895]
### Repro code

```fsharp
module Main

open Fable.Core
open Fable.Core.JsInterop

let foo: obj = jsNative?bar
```

### Description

I get this error:

```
ERROR in ./Main.fsproj
/Main.fs(6,15,6,27) : error FSHARP: This expression was expected to have type
    'obj'    
but here has type
    'obj -> obj'    
 @ multi babel-polyfill ./Main.fsproj
```

Is this expected behavior? I thought that the `?` syntax can be used for both property lookups and method calls, but it seems not.

### Related information 

* fable-compiler version: `fable-loader@1.0.0-narumi-912`
* fable-core version: `fable-core@1.0.0-narumi-914`
* Operating system: Debian GNU/Linux Testing 64-bit

**Comment by alfonsogarciacaro** [comment]
This is a trick I had to do to make dynamic properties directly applicable. So you can do `foo?bar(1,2)` instead of using an intermediate operator like before `foo?bar$(1,2)`. I've filled an [F# language suggestion](https://github.com/fsharp/fslang-suggestions/issues/543) to avoid the need of having the result of `?` be of `obj->obj` type.

For now, you can just use they dynamic cast in these cases: `let foo: obj = !!myObj?bar`

> BTW, `jsNative` will throw an exception. I guess you want something else there.

**Comment by Pauan** [comment]
The `jsNative` was just to create the smallest possible repro code, in a real app it would use proper JS interop.

Thanks for filing an issue! :heart:
