### ISSUE TITLE
Running `dotnet fable npm-run` without `start` or `build` causes an exception

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#926]
### Description

Running `dotnet fable npm-run` without `start` or `build` causes an exception

`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array. at Fable.Tools.Main.main(String[] argv)`

### Repro code

`dotnet fable npm-run`

### Expected and actual results

Provide a helpful recommendation on what to run.

### Related information 

* fable-compiler version: Latest
* fable-core version: Latest
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
You're right, we should add an array length check for [the npm-run command](https://github.com/fable-compiler/Fable/blob/7ac95ae2adf4236073f9e62790f995a3032c4114/src/dotnet/Fable.Tools/Main.fs#L166) (and also for node-run and shell-run) and print a more helpful error message.

Could you please PR it?

**Comment by jeremyabbott** [comment]
@alfonsogarciacaro if it can wait until this weekend I'd be interested in giving it a try.

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro Would it be possible to replace npm-run with just build and start to simplify things?  npm-run is not only extra characters, but I believe it is a bit misleading since there is extra magic that happens prior to npm run.

**Comment by MangelMaxime** [comment]
@mizzle-mo `npm-run` allow you to the commands from `package.json`

It's an alias to `npm run start`. Only when using `dotnet fable` to run, this will automatically start the fable compilation server.

You could archieve the same result using two consoles with this commands: `dotnet fable start` && `npm run start`.

**Comment by mizzle-mo** [comment]
@MangelMaxime Could we not get the same result with ```dotnet fable start``` and ```dotnet fable build```  The npm-run seems redundant and misleading.  I initially thought it just ran ```npm run``` since that is the name of the command.  I figured I could do that with less typing by just using ```yarn start``` which obviously didn't work as expected.  Just wondering why we have extra sugar on the command if not necessary.  Why is the npm-run command required in the cli?

**Comment by MangelMaxime** [comment]
Because fable isn't dedicated to be used with npm only.

You could start the Fable compilation server and pass it the files you want to compiler via FAKE, bash etc.

`dotnet fable npm-run` is an helper which start for you the compilation server before executing the command from `package.json`

Perhaps the help can give you more info:

```fs
C:\Users\mange\Workspace\Github\fable-elmish\fable-elmish.github.io>dotnet fable --help
Fable F# to JS compiler (1.0.4)
Usage: dotnet fable [command] [script] [fable arguments] [-- [script arguments]]

Commands:
  -h|--help           Show help
  --version           Print version
  start               Start Fable server
  npm-run             Run Fable while an npm script is running
  node-run            Run Fable while a node script is running
  shell-run           Run Fable while a shell script is running
  webpack             Start Fable server, invoke Webpack and shut it down
  webpack-dev-server  Run Fable while Webpack development server is running

Fable arguments:
  --timeout           Stop the server if timeout (ms) is reached
  --port              Port number (default 61225) or "free" to choose a free port

To pass arguments to the script, write them after `--`
Example: `dotnet fable npm-run build --port free -- -p --config webpack.production.js`
```

**Comment by Pauan** [comment]
@mizzle-mo Just use this in `package.json`:

```json
{
  "scripts": {
    "postinstall": "dotnet restore Main.fsproj",
    "build": "dotnet fable webpack",
    "watch": "dotnet fable webpack-dev-server"
  }
}
```

Then you can use `yarn build` and `yarn watch`

----

The reason why `fable npm-run` is needed is because Fable has a [daemon](https://en.wikipedia.org/wiki/Daemon_(computing)) which runs in the background and does the actual compilation.

When you use `fable npm-run`, Fable will start up the daemon, run the npm command, then kill the daemon. So it's pretty much the same as `npm run`, but with the addition of the Fable daemon.

Why does Fable use a daemon? By using a daemon, `watch` mode is super fast, because the daemon can store the old compilation results in memory, so it only needs to recompile the files that actually changed.

**Comment by mizzle-mo** [comment]
@MangelMaxime Thanks for showing me the help.  I think I tried --help a while back and it didn't display any help.  Seeing it in that context, it makes a lot more sense.  Thank you.

@Pauan I knew it used a daemon, I just didn't know about some of the other commands, so I thought that npm-run was pretty much the main command and it just seemed redundant.  It makes more sense now, please disregard my previous comment requesting a change.
