### ISSUE TITLE
Make server support different commands

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#943]
As far as I've seen (from looking at the source), the current server only supports requests for compiled sources. This should be improved to a more "command"-centric RPC server instead. This would likely also help with enabling non-bundling compiles.

Sample first commands:
* `['load', 'myProj.fsproj']` - Load the project into memory (like what happens today when you request compiling a project), but don't emit any code/produce any sourcetrees.
* `['compile', {path:'myFile.fs'}]` - Same as what the server does today.
* `['list', 'myProj.fsproj']` - List all fs files loaded for project.

**Comment by alfonsogarciacaro** [comment]
This is a very interesting idea, especially the `list` command which I've already been considering. I'm not so sure about `load` because right now you can just send the project path and ignore the result (the AST for .fsproj files is just an `export * from` command redirecting to the last file of the project).

What would be your use case for this? Would you be interested in sending a PR to add the `list` command? (Please note it shouldn't break interaction with current Fable JS counterparts: loader, rollup plugin...)

**Comment by Alxandr** [comment]
My suggestion sends commands as json arrays which can be distinguished from first character. This was in order to keep back-compat. The reason for `load` is just to not need a compile that you're just going to ignore anyways. Also, the result from `list` needs to include relative file-paths (relative to the project root) and whether or not the file is part of the project being compiled.

I could probably PR this, but not till next month at least. My master thesis is due in 3 weeks and then I'm moving, and I'm already doing too much OSS work those things considered :)

**Comment by alfonsogarciacaro** [comment]
Closing this for now, we can revisit later when there's a WIP PR or more details about the use cases for the new commands are provided. About loading a project without any output please note a similar request #1116 was resolved with a slightly different feature.
