### ISSUE TITLE
[Feature] Quotation based jsEmit

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#970]
Currently, the way to control "emit" from F# is with the `Emit` attribute. The problem with this is that `Emit` is string-based, and based on JS, which is likely to be error prone. As an alternative to the `Emit` attribute (in conjunction with `jsNative`), I propose a `jsEmit` function so that you could write code such as this:

```
[<Sealed; Erase>]
type MyJsType private () =
  member x.DoStuff (str: string) (num: int) = jsEmit <@@ (%%arg0)?plan?(%%arg1) @@>
```

It's not as pretty, nor is it typesafe (not that strings in `Emit` is typesafe either), but we don't have to parse JS, nor do we have to do replacement on strings. Oh, and if anyone can think of a better way to deal with arguments than `%%arg0` please do chime in.

**Comment by alfonsogarciacaro** [comment]
I've been also considering this, but please note it's not trivial so it will likely not be implemented in this cycle. There are also some notes to consider:

- The content of `Emit` is actually [parsed by Babel](https://github.com/fable-compiler/Fable/blob/8b4c54b2b0467e9c7b95574c13ee29af68f6a621/src/typescript/fable-utils/babel-plugins.js#L36) so you do get an error at compile time if the syntax is wrong.
- For quotations, when you have access to the source, the FSharp.Compiler.Service gives you the same AST as for normal F# expressions. But you still have to deal with quotation specific issues (splicing, referencing to external code, etc) and this is also not a very interesting use case, as you can do the same with a normal F# expression. Take Fable's [`nameof` operator](https://github.com/fable-compiler/Fable/blob/8b4c54b2b0467e9c7b95574c13ee29af68f6a621/src/tests/Main/JsInteropTests.fs#L180-L194) as an example, which doesn't need to use a quotation to [take the name of the expression from the AST](https://github.com/fable-compiler/Fable/blob/8b4c54b2b0467e9c7b95574c13ee29af68f6a621/src/dotnet/Fable.Compiler/Replacements.fs#L103-L107).
- More interesting would be to emit code from quotations embedded in a .dll, mainly so they can be used with type providers or libraries embedding their own plugins in the .dll (as fable-react did with Fable 0.7). However in this case, you have to inspect the quotation normally which means a whole reimplementation of `FSharp2Fable` because: a) patterns are different and b) quotations use .NET reflection while FCS provides its own code introspection classes.
- An alternative solution would be to improve emission of Fable AST, as it's done in [the Fable Regex provider](https://github.com/fable-compiler/Fable/blob/8b4c54b2b0467e9c7b95574c13ee29af68f6a621/src/providers/regex/src/Fable.Providers.Regex.fsx#L15-L27) (please note type providers doesn't work yet with netcore and thus neither with Fable 1.0). I've been building the Fable AST and helpers on the go, an I acknowledge the design is not great and it's not easy to use unless you have a good knowledge of the code base. Wiriting a better DSL to emit Fable AST will make it easier for library authors to tweak the AST when needed.

**Comment by Alxandr** [comment]
There has to be someone who has written a `F# quotation -> F# AST` library somewhere? If not, that's probably what we should do if we wanted a feature like this, so we could reuse the old babel ast generation.

**Comment by tpetricek** [comment]
I'm not sure what can the quotation-based library do that is not otherwise possible without quotations?

For example:

```
jsEmit <@@ (%%arg0)?plan?(%%arg1) @@>
``` 

Can probably be written as (given appropriate definition of `?`):

```
(fun arg0 arg1 -> arg0?plan?(arg1) )
```

**Comment by Alxandr** [comment]
Hmm. You're right. The point thought is to modify the JS output. But it could probably be simplified to something like this:

```fsharp
[<Sealed; Erase>]
type MyJsType private () =
  member x.DoStuff (str: string) (num: int) = jsEmit (arg0?plan?(arg1))
```

After all, it's just supposed to be a hint to the compiler of what it should generate. The constant "placeholders" `arg0` to `arg<somethingbigenough>` should probably exist inside some `jsInterop` namespace, just like `jsThis`.

**Comment by alfonsogarciacaro** [comment]
Closing for now as this is not a priority and we probably should rather focus effort on improving the API to emit Fable AST.
