### ISSUE TITLE
printfn codegen

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#997]
Previously the `printfn "%d" 5` was compiled as:
```
fsFormat("%d")(x => {
  console.log(x);
})(5);
```
Now it compiles as:
```
  ({
    formatFn: fsFormat("%d"),
    input: "%d"
  }).formatFn(x => {
    console.log(x);
  })(5);
```
Is the wrapping in object necessary?

**Comment by Zaid-Ajaj** [comment]
Yes, it makes retrieving the `input` possible at a later time in the program. See [this issue](https://github.com/fable-compiler/Fable/issues/536) with the [fix here](https://github.com/fable-compiler/Fable/pull/990).

**Comment by alfonsogarciacaro** [comment]
I guess this is not too much an overhead. But we could try to optimize the cases where the result is printed/returned immediately (and also cases where there's no format like `printfn "Hello!"`), though it's a bit tricky because we'd have to check a bigger portion of the AST than it's currently possible in the Replacements module. We would need a custom active pattern in FSharp2Fable.

**Comment by ncave** [comment]
Thanks, hopefully it can be optimized away. Closing.
